steps:
- template: /tech_products/loja-online/tasks/bash/welcome.yml
  parameters:
    message: $(DB_DEPLOY_WELCOME_MSG)
    
- template: /tech_products/loja-online/tasks/artifacts/download_db.yml

- template: /tasks/azure_key_vault/get_akv_credentials.yml
  parameters:
    secretsFilter: 'NEXUS-DEPS-USR, NEXUS-DEPS-PSW'

- template: /tech_products/loja-online/tasks/docker/docker_image_build.yml.yml
  parameters:
    workingDirectory: '$(System.ArtifactsDirectory)/extracted_tars/db'

- template: /tasks/liquibase/run_liquibase_maven_goal.yml
  parameters:
    goal: 'tag'
    taskName: 't_pre_deploy_tag'
    displayName: 'Pre-Deploy Tag pre-$(Build.BuildNumber)'
    workingDirectory: '$(System.ArtifactsDirectory)/extracted_tars/db'
    extraAttributes: '-Dliquibase.tag=pre-$(Build.BuildNumber)'

- template: /tasks/liquibase/run_liquibase_maven_goal.yml
  parameters:
    goal: 'update'
    taskName: 't_deploy_changesets_to_database'
    displayName: 'Deploy Changesets to Database'
    workingDirectory: '$(System.ArtifactsDirectory)/extracted_tars/db'
    extraAttributes: '-Dliquibase.contexts=$(environment) -Dliquibase.labels=$(LIQUIBASE_LABELS)'

- template: /tasks/liquibase/run_liquibase_maven_goal.yml
  parameters:
    goal: 'tag'
    taskName: 't_post_deploy_tag'
    displayName: 'Post-Deploy Tag post-$(Build.BuildNumber)'
    workingDirectory: '$(System.ArtifactsDirectory)/extracted_tars/db'
    extraAttributes: '-Dliquibase.tag=post-$(Build.BuildNumber)'

- template: /tasks/liquibase/run_liquibase_maven_goal.yml
  parameters:
    goal: 'listUndeployedChangesets'
    taskName: 't_list_undeployed_changesets'
    displayName: 'List Undeployed Changesets'
    workingDirectory: '$(System.ArtifactsDirectory)/extracted_tars/db'
    condition: succeededOrFailed()
    continueOnError: 'true'

- template: /tasks/liquibase/run_liquibase_maven_goal.yml
  parameters:
    goal: 'diff'
    taskName: 't_compare_database_state'
    displayName: 'Compare Database Objects'
    workingDirectory: '$(System.ArtifactsDirectory)/extracted_tars/db'
    condition: and(succeededOrFailed(), eq(variables.ENABLE_SNAPSHOT_COMPARE, true) )
    continueOnError: 'true'
    extraAttributes: '-Dliquibase.referenceUrl=offline:$db_type?snapshot=snapshot_db_$(environment).json -Dliquibase.includeSchema=true'
