parameters:
- name: dsmSecretName
- name: dsmSecretKey
- name: variableToBeSet

steps:
- task: PythonScript@0
  displayName: '[DSM] Get secret ${{ parameters.dsmSecretKey }}'
  inputs:
    scriptSource: inline
    script: |
      import requests
      import os
            
      base_url = os.getenv('SENHA_SEGURA_BASE_URL')
      access_token = os.getenv('ACCESS_TOKEN')
      dsm_secret_name = os.getenv('DSM_SECRET_NAME')
      dsm_secret_key = os.getenv('DSM_SECRET_KEY')
      variable_to_be_set = os.getenv('VARIABLE_TO_BE_SET')

      print('##[debug] DSM_SECRET_NAME..........: ', dsm_secret_name)
      print('##[debug] DSM_SECRET_KEY...........: ', dsm_secret_key)
      print('##[debug] VARIABLE_TO_BE_SET.......: ', variable_to_be_set)

      def get_secret_value():
        url = base_url + '/iso/sctm/secret'
        print('##[command] GET {} - Get Secret'.format(url))
        response = requests.get(
          url,
          headers = {
            'Authorization': 'Bearer ' + access_token,
            'Content-Type': 'application/json'
          },
          verify = False
        )
        response_json = response.json()
        secret = [item for item in response_json['secrets'] if item['secret_name'] == dsm_secret_name]
        secret_value = secret[0]['data'][0][dsm_secret_key]

        print('##vso[task.setvariable variable={};]{}'.format(variable_to_be_set, secret_value))

      get_secret_value()
  env:
    SENHA_SEGURA_BASE_URL: $(SENHA_SEGURA_BASE_URL)
    ACCESS_TOKEN: $(SENHA_SEGURA_ACCESS_TOKEN)
    DSM_SECRET_NAME: ${{ parameters.dsmSecretName }}
    DSM_SECRET_KEY: ${{ parameters.dsmSecretKey }}
    VARIABLE_TO_BE_SET: ${{ parameters.variableToBeSet }}