parameters:
- name: senhaId
- name: usernameVariable
- name: passwordVariable

steps:
- task: PythonScript@0
  displayName: '[COE] Get senha ${{ parameters.senhaId }}'
  inputs:
    scriptSource: inline
    script: |
      import requests
      import os
            
      base_url = os.getenv('SENHA_SEGURA_BASE_URL')
      access_token = os.getenv('ACCESS_TOKEN')
      senha_id = os.getenv('SENHA_ID')
      username_variable = os.getenv('USERNAME_VARIABLE')
      password_variable = os.getenv('PASSWORD_VARIABLE')

      print('##[debug] SENHA_ID....................: ', senha_id)
      print('##[debug] USERNAME_VARIABLE...........: ', username_variable)
      print('##[debug] PASSWORD_VARIABLE...........: ', password_variable)

      def get_senha():
        url = base_url + '/iso/coe/senha/' + senha_id
        print('##[command] GET {} - Get Senha'.format(url))
        response = requests.get(
          url,
          headers = {
            'Authorization': 'Bearer ' + access_token,
            'Content-Type': 'application/json'
          },
          verify = False
        )
        response_json = response.json()
        username = response_json['senha']['username']
        password = response_json['senha']['senha']

        print('##vso[task.setvariable variable={};]{}'.format(username_variable, username))
        print('##vso[task.setvariable variable={};]{}'.format(password_variable, password))

      get_senha()
  env:
    SENHA_SEGURA_BASE_URL: $(SENHA_SEGURA_BASE_URL)
    ACCESS_TOKEN: $(SENHA_SEGURA_ACCESS_TOKEN)
    SENHA_ID: ${{ parameters.senhaId }}
    USERNAME_VARIABLE: ${{ parameters.usernameVariable }}
    PASSWORD_VARIABLE: ${{ parameters.passwordVariable }}