parameters:
- name: environment
  type: string
- name: environmentType
  type: string
- name: action
  type: string
- name: workDir
  type: string
  default: all
- name: runFoundation
  type: boolean
- name: runStorage
  type: boolean
- name: runDatabricks
  type: boolean

stages:
- ${{ if and(eq(parameters.runFoundation, true), eq(parameters.workDir, 'all')) }}:
  - template: ./iac-databricks-component-template.yml
    parameters:
      environment: ${{ parameters.environment }}
      environmentType: ${{ parameters.environmentType }}
      action: ${{ parameters.action }}
      workDir: foundation
      componentName: Foundation
      previousWorkDir: ''
      ${{ if eq(parameters.runStorage, true) }}:
        nextWorkDir: storage
      ${{ elseif eq(parameters.runDatabricks, true) }}:
        nextWorkDir: databricks
      ${{ else }}:
        nextWorkDir: ''

- ${{ if and(eq(parameters.runStorage, true), eq(parameters.workDir, 'all')) }}:
  - template: ./iac-databricks-component-template.yml
    parameters:
      environment: ${{ parameters.environment }}
      environmentType: ${{ parameters.environmentType }}
      action: ${{ parameters.action }}
      workDir: storage
      componentName: Storage
      ${{ if and(eq(parameters.runFoundation, true), eq(parameters.runDatabricks, true)) }}:
        previousWorkDir: foundation
        nextWorkDir: databricks
      ${{ elseif eq(parameters.runFoundation, true) }}:
        previousWorkDir: foundation
        nextWorkDir: ''
      ${{ elseif eq(parameters.runDatabricks, true) }}:
        previousWorkDir: ''
        nextWorkDir: databricks
      ${{ else }}:
        previousWorkDir: ''
        nextWorkDir: ''

- ${{ if and(eq(parameters.runDatabricks, true), eq(parameters.workDir, 'all')) }}:
  - template: ./iac-databricks-component-template.yml
    parameters:
      environment: ${{ parameters.environment }}
      environmentType: ${{ parameters.environmentType }}
      action: ${{ parameters.action }}
      workDir: databricks
      componentName: Databricks
      ${{ if eq(parameters.runStorage, true) }}:
        previousWorkDir: storage
      ${{ elseif eq(parameters.runFoundation, true) }}:
        previousWorkDir: foundation
      ${{ else }}:
        previousWorkDir: ''
      nextWorkDir: ''

- ${{ if and(eq(parameters.runFoundation, true), eq(parameters.workDir, 'foundation')) }}:
  - template: ./iac-databricks-component-template.yml
    parameters:
      environment: ${{ parameters.environment }}
      environmentType: ${{ parameters.environmentType }}
      action: ${{ parameters.action }}
      workDir: foundation
      componentName: Foundation
      previousWorkDir: ''

- ${{ if and(eq(parameters.runStorage, true), eq(parameters.workDir, 'storage')) }}:
  - template: ./iac-databricks-component-template.yml
    parameters:
      environment: ${{ parameters.environment }}
      environmentType: ${{ parameters.environmentType }}
      action: ${{ parameters.action }}
      workDir: storage
      componentName: Storage
      previousWorkDir: ''

- ${{ if and(eq(parameters.runDatabricks, true), eq(parameters.workDir, 'databricks')) }}:
  - template: ./iac-databricks-component-template.yml
    parameters:
      environment: ${{ parameters.environment }}
      environmentType: ${{ parameters.environmentType }}
      action: ${{ parameters.action }}
      workDir: databricks
      componentName: Databricks
      previousWorkDir: ''
