parameters:
  - name: qa_environment
  - name: service_connection
  - name: deploy_app_folder

steps:
  - task: SSH@0
    displayName: "Start Karaf"
    inputs:
      sshEndpoint: ${{ parameters.service_connection }}
      runOptions: inline
      failOnStdErr: false
      inline: |
        $(deploy_app_folder)/prisma_azuredevops_start_karaf.sh
        sleep 90