parameters:
  - name: artifactDir
    type: string
    default: "$(DEFAULT_WORKDIR_ARTIFACTS)"

steps:
- bash: |
    echo "##[debug]Publishing to npm registry..."
    
    export NPM_CONFIG_USERCONFIG=$(Agent.TempDirectory)/.npmrc

    npm publish --verbose --access=restricted
  displayName: "Publish to npm registry"
  workingDirectory: "${{ parameters.artifactDir }}"
