parameters:
- name: newVersion
  type: string
- name: incrementLevel
  default: patch  
- name: condition
  type: object
- name: createGitTag
  type: boolean
  default: true

steps:
- template: /tech_products/loja-online/tasks/versioning/update_repo_version.yml
  parameters:
    condition: ${{ parameters.condition }}
    componentNewVersion: ${{ parameters.newVersion }}
    createGitTag: ${{ parameters.createGitTag }}
    bashScript: 
      content: |
      
        echo "##[debug]Update Repository Version:"
        
        #A versão utilizada do NPM é a versão default do Node.js nos agentes
        #Caso seja necessário uma versão diferente, é necessário adicionar o .tool-versions (ASDF)na pasta do projeto 
        npm --no-git-tag-version version ${{ parameters.incrementLevel }}

        cd bff/
        npm --no-git-tag-version version ${{ parameters.incrementLevel }}

        cd ../client/
        npm --no-git-tag-version version ${{ parameters.incrementLevel }}