parameters:
- name: environment
- name: remoteHostAlias
  default: ' '

steps:
- script: |
    set -e

    echo "##[debug] WORKING_DIRECTORY...........: $(pwd)"
    echo "##[debug] DIRECTORY...................: ${DIRECTORY}"
    echo "##[debug] REMOTE_HOST_ALIAS...........: ${REMOTE_HOST_ALIAS}"
    echo "##[debug] API_MANAGER_URL.............: ${HOST}"
    echo "##[debug] AXWAY_CLI_API_BASEPATH......: ${AXWAY_CLI_API_BASEPATH}"

    if [ ! -d "${DIRECTORY}" ]; then
      echo "##vso[task.logissue type=warning;] Directory ${DIRECTORY} does not exists."
      echo "##vso[task.complete result=SucceededWithIssues;]"
      exit
    fi

    if [ ! -z "${REMOTE_HOST_ALIAS}" ]; then
      if [ ! -f "${DIRECTORY}/${REMOTE_HOST_ALIAS}.json" ]; then
        echo "##vso[task.logissue type=error;] Remote host file '${DIRECTORY}/${REMOTE_HOST_ALIAS}.json' was not found."
        echo "##vso[task.complete result=Failed;]"
        exit
      fi

      echo "##[debug] Import remote host file"
      ${AGENT_TEMPDIRECTORY}/apim-cli-${AXWAY_CLI_VERSION}/scripts/apim.sh settings import -c "${DIRECTORY}/${REMOTE_HOST_ALIAS}.json" -apimanagerUrl "${HOST}" -u "${USERNAME}" -p "${PASSWORD}" -apiBasepath "${AXWAY_CLI_API_BASEPATH}" -ignoreCache
      exit
    fi

    echo "##vso[task.logissue type=warning;] Remote host file was not definied. Importing all remote hosts for environment '${ENVIRONMENT}'."
    for file in "${DIRECTORY}"/*.json; do
      filename=$(basename "$file")

      echo "##[group] Import remote host file '${DIRECTORY}/${filename}'"
      ${AGENT_TEMPDIRECTORY}/apim-cli-${AXWAY_CLI_VERSION}/scripts/apim.sh settings import -c "${DIRECTORY}/${filename}" -apimanagerUrl "${HOST}" -u "${USERNAME}" -p "${PASSWORD}" -apiBasepath "${AXWAY_CLI_API_BASEPATH}" -ignoreCache
      echo ""
      echo "##[endgroup]"
    done
  displayName: 'Import Remote Hosts into API-Manager'
  workingDirectory: $(Build.SourcesDirectory)
  env:
    AXWAY_CLI_VERSION: $(AXWAY_CLI_VERSION)
    AXWAY_CLI_API_BASEPATH: $(AXWAY_CLI_API_BASEPATH)
    ENVIRONMENT: ${{ parameters.environment }}
    REMOTE_HOST_ALIAS: ${{ parameters.remoteHostAlias }}
    DIRECTORY: '${{ parameters.environment }}/remote_hosts'
    HOST: $(API_MANAGER_URL)
    USERNAME: $(ADMIN_USERNAME)
    PASSWORD: $(ADMIN_PASSWORD)
    LOG_LEVEL: $(AXWAY_CLI_LOG_LEVEL)