parameters:
- name: fortifyExclusionRepository

stages:
- stage: security
  displayName: "Security"
  dependsOn: build_test
  isSkippable: false
  pool: $(PRIVATE_AGENT_DEFAULT)
  jobs:
  - job: app_config_keys
    displayName: "Get AppSec Config Keys"
    steps:
    - template: /tasks/bash/welcome.yml@CorePipelines
    - template: /security/get_appconfig_keys.yml

  - job: sast_scan
    dependsOn: app_config_keys
    variables:
      USE_FORTIFY: $[ dependencies.app_config_keys.outputs['evaluate_flags.USE_FORTIFY'] ]
      USE_CONVISO: $[ dependencies.app_config_keys.outputs['evaluate_flags.USE_CONVISO'] ]
      SKIP_SECURITY_GATE: $[ dependencies.app_config_keys.outputs['evaluate_flags.SKIP_SECURITY_GATE'] ]
    condition: and(
                    succeeded(),
                    and(
                      eq(variables.USE_FORTIFY, 'true'),
                      not(startsWith(variables['Build.SourceBranch'], 'refs/tags/'))
                    )
                  )
    displayName: "SAST Scan"
    steps:
    - template: /security/run_fortify_scan.yml
      parameters:
        fortifyExclusionRepository: ${{ parameters.fortifyExclusionRepository }}

    - template: /tasks/telemetry/telemetry.yml@CorePipelines
