parameters:
  - name: environment
  - name: helm_chart_version
  - name: k8s_service_connection
  - name: k8s_resource_group 
  - name: app_name
  - name: namespace
  - name: helm_chart_name
  - name: app_version  

variables:
- name: PRIVATE_AGENT_SHARED
  value: GeneralPurposeLinuxAgentsCD
- name: APP_VERSION
  value: ${{ parameters.app_version }}
- name: AZURE_SUBSCRIPTION
  value: ${{ parameters.k8s_service_connection }}-${{ parameters.environment }}
- name: K8S_RESOURCE_GROUP
  value: ${{ parameters.k8s_resource_group }}-${{ parameters.environment }}
- name: NAMESPACE
  value: ${{ parameters.namespace }}-${{ parameters.environment }}
- name: HELM_REGISTRY
  value: acrsharedservices01.azurecr.io
- name: IMAGE_REGISTRY
  value: acrsharedservices01.azurecr.io
- name: IMAGE_PATH
  value: 'dvps/monitoria'
- name: IMAGE_NAME
  value: ${{ parameters.app_name }}
- name: HELM_CHART_NAME
  value: ${{ parameters.chart_name }}
- name: HELM_CHART_VERSION
  value: ${{ parameters.helm_chart_version }}


