stages:
- stage: build_test
  displayName: "Build & Test & Coverage"
  dependsOn:
    - pipeline_init
  pool: $(PRIVATE_AGENT_DEFAULT)
  jobs:
  - job: build_app
    displayName: Build & Test
    dependsOn: []
    steps:
    - template: /tasks/bash/welcome.yml
    - template: /task_groups/build/extension_build_test.yml