stages:
- stage: publish
  displayName: "Publish Market Place"
  dependsOn: package
  pool: "GeneralPurposeLinuxAgentsCD"
  jobs:
    - job: publish_extension
      displayName: Publish Extension
      variables:
        EXTENSION_VERSION: $[ stageDependencies.package.package.outputs['QueryVersion.Extension.Version'] ]
      steps:
      - template: /task_groups/publish/extension_publish.yml