# This YAML file contains a pipeline task for updating flags in a Helm chart.

parameters:
# The name of the Helm chart to update.
- name: helmChart
# The execution mode for the ECE (Execution Control Engine).
- name: eceExecutionMode

steps: 
- task: CmdLine@2
  displayName: "Update pricingLoadFromPersistence flags"
  inputs:
    script: |
      # Print debug information
      echo "##[debug] HELM_CHART.............: ${HELM_CHART}"
      echo "##[debug] ECE_EXECUTION_MODE.....: ${ECE_EXECUTION_MODE}"
      echo "##[debug] HELM_CHART_PATH........: ${HELM_CHART_PATH}"

      # Update pricingLoadFromPersistence flag based on the execution mode
      echo ">>>> Updating pricingLoadFromPersistence in ${HELM_CHART}/override-values.yaml"

      if [ ${ECE_EXECUTION_MODE} == RESTART ]; then
        echo "##[command]yq -i '.charging.cachePersistenceConfigurations.cachePersistenceConfigurationList[0].pricingLoadFromPersistence = "true"' $HELM_CHART_PATH"

        yq -i '.charging.cachePersistenceConfigurations.cachePersistenceConfigurationList[0].pricingLoadFromPersistence = "true"' $HELM_CHART_PATH
      elif [ ${ECE_EXECUTION_MODE} == DEPLOY ]; then                  
        echo "##[command]yq -i '.charging.cachePersistenceConfigurations.cachePersistenceConfigurationList[0].pricingLoadFromPersistence = "false"' $HELM_CHART_PATH"
        
        yq -i '.charging.cachePersistenceConfigurations.cachePersistenceConfigurationList[0].pricingLoadFromPersistence = "false"' $HELM_CHART_PATH
      else
        # Log an error and fail the task if the execution mode is invalid
        echo "##vso[task.logissue type=error;]Error when updating the pricingLoadFromPersistence flags"
        echo "##vso[task.complete result=Failed;]"

        exit 1
      fi

      # Print the updated flag value
      echo =========== RETURN ===========
      echo "##[command]yq e '.charging.cachePersistenceConfigurations.cachePersistenceConfigurationList[0]' $HELM_CHART_PATH"

      yq e '.charging.cachePersistenceConfigurations.cachePersistenceConfigurationList[0]' $HELM_CHART_PATH
      echo ==============================
  env:
    HELM_CHART: ${{ parameters.helmChart }}
    ECE_EXECUTION_MODE: ${{ parameters.eceExecutionMode }}
    HELM_CHART_PATH: $(Pipeline.Workspace)/${{ parameters.helmChart }}/override-values.yaml
