parameters:
- name: environment 
  type: string

variables:
- template: variables/load.yml
  parameters:
    environment: ${{parameters.environment}}

stages:

- template: stages/default/prepare.yml

- template: stages/default/import.yml
  parameters:
    environment: ${{parameters.environment}}

- template: stages/default/build.yml
  parameters:
    environment: ${{parameters.environment}}

- template: stages/default/upload.yml

- template: stages/default/restart.yml
  parameters:
    environment: ${{parameters.environment}}

- template: stages/default/adm.yml
  parameters:
    environment: ${{parameters.environment}}

- template: stages/default/active.yml
  parameters:
    host: $(host)

- template: stages/default/security.yml
  parameters:
    fortifyExclusionRepository: FortifyExclusion

- template: stages/default/quality_gates.yml