parameters:
  - name: pythonVersion
    type: string

stages:
- stage: build_test
  displayName: "Build & Test"
  dependsOn: extract_version
  pool: $(PRIVATE_AGENT_DEFAULT)
  jobs:
  - job: build_app
    displayName: Build & Test & Coverage
    steps:
    - template: /tech_products/srus/tasks/bash/welcome.yml
    - template: /tech_products/srus/task_groups/build/python_build_test.yml
      parameters:
        pythonVersion: ${{ parameters.pythonVersion }}
    - template: /tech_products/srus/task_groups/tests/publish_tests_reports.yml
      parameters:
        testResultsFilesPattern: "**/test-*.xml"
        codeCoverageTool: "Cobertura"
        publishCoverTaskVersion: 1