parameters:
- name: environment
- name: pythonVersion
  type: string
- name: gitTag

stages:
- stage: deploy
  dependsOn:
  - validation
  pool: $(PRIVATE_AGENT_DEFAULT)
  displayName: "Deploy ${{ parameters.environment }}"
  jobs:
  - deployment: ${{ parameters.environment }}
    condition: eq(variables.flowIsMain, true)
    workspace:
      clean: all
    displayName: Deploy
    environment: "deploy-${{ parameters.environment }}"
    strategy:
      runOnce:
        deploy:
          steps:
          - download: none

          - template: /tech_products/srus/task_groups/deploy/databricks_run_deploy.yml
            parameters:
              pythonVersion: "${{ parameters.pythonVersion }}"