parameters:
- name: qa_environment
  type: string
- name: run_component_test
  type: boolean
- name: skip_deploy
  type: boolean
  default: False
- name: useExternalEnv
  type: boolean
  default: False
- name: deploystrategy
  type: string
  default: "different"
- name: run_e2e_tests
  type: boolean
  default: False  

variables:
- template: /provisioners/app/trunkbased/java/api_default/variables/load.yml@CorePipelines
  parameters:
    environment: ${{ parameters.qa_environment }}
    deploystrategy: ${{ parameters.deploystrategy }}
    useArgoRolloutsDeploys: ${{ variables.useArgoRolloutsDeploys }}
resources:
  repositories:
    - repository: FortifyExclusion
      name: DevOps/Vivo.Fortify.Exclusions
      type: git
      ref: refs/heads/master
      endpoint: CorePipelines

    - repository: CorePipelines
      name: DevOps/Vivo.Core.Pipelines
      type: git       
      ref: refs/tags/v1
      endpoint: CorePipelines

stages: 
## INIT
- template: /tech_products/dip/dip_stages/init.yml

- template: /provisioners/app/trunkbased/java/api_default/stages/init.yml@CorePipelines

## BUILD & TEST
- template: /provisioners/app/trunkbased/java/api_default/stages/build_test.yml@CorePipelines

## GATES
- template: /provisioners/app/trunkbased/java/api_default/stages/gates.yml@CorePipelines

## SECURITY
- template: /provisioners/app/trunkbased/java/api_default/stages/security_sast_sca.yml@CorePipelines
  parameters:
    fortifyExclusionRepository: FortifyExclusion

## COMPONENT TEST
- template: /provisioners/app/trunkbased/java/api_default/stages/component_test.yml@CorePipelines
  parameters:
    run_component_test: "${{parameters.run_component_test}}"