stages:
- stage: pipeline_init
  displayName: "Pipeline initialization"
  dependsOn: feature_flag
  pool: $(GENERAL_PURPOSE_CI_AGENT)
  jobs:
  - job: prepare_pipeline
    displayName: "Prepare"
    steps:
    - template: /tech_products/sap-hybris/tasks/artifacts/publish_catalog_info.yml
      parameters:
        breakWhenNotFound: true