stages:
- stage: feature_flag
  displayName: "Flag to run feature branch"
  condition: |
    or(
      and(
        startsWith(variables['Build.SourceBranch'], 'refs/heads/feature/'),
        contains(variables['Build.SourceVersionMessage'], '[Start Pipeline]')
      ),
      ne(startsWith(variables['Build.SourceBranch'], 'refs/heads/feature/'), true),
      eq(variables['Build.Reason'], 'Manual'),
      or(
        contains(variables['Build.SourceVersionMessage'], '[DeployD1]'),
        contains(variables['Build.SourceVersionMessage'], '[DeployD2]'),
        contains(variables['Build.SourceVersionMessage'], '[DeployD3]'),
        contains(variables['Build.SourceVersionMessage'], '[DeployS1]'),
        contains(variables['Build.SourceVersionMessage'], '[DeployS2]'),
        contains(variables['Build.SourceVersionMessage'], '[DeployS3]'),
        contains(variables['Build.SourceVersionMessage'], '[DeployP1]')
      )      
    )
  jobs:
    - job: 
      steps:
      - checkout: none
      - bash: |
          YELLOW='\033[1;33m'
          BLUE='\033[0;34m'

          printf "
          ${YELLOW}=================================================================================================================================
          ${YELLOW}                                                  STARTING PIPELINE
          ${YELLOW}=================================================================================================================================
          O pipeline está sendo iniciado. Todas as etapas serão executadas conforme planejado para garantir a entrega correta da aplicação.

          Para mais informações sobre as fases do pipeline, consulte a documentação: 
          ${BLUE}https://wikicorp.telefonica.com.br/display/DEVELOP/Stages+do+pipeline+para+Deploy+na+SAP
          ${YELLOW}=================================================================================================================================

          "
        displayName: "Starting pipeline"
