parameters:
- name: pythonVersion
  type: string

stages:
- stage: build_test
  displayName: "Build & Test"
  ${{ if eq(variables.flowIsPullRequest, false) }}:
    dependsOn: bump_version
  ${{ else }}:
    dependsOn: pipeline_init
  pool: $(PRIVATE_AGENT_DEFAULT)
  jobs:
  - job: build_app
    displayName: Build & Test & Coverage
    steps:
    - template: /tasks/bash/welcome.yml

    - template: /tasks/databricks/lint_with_docker.yml
      parameters:
        pythonVersion: ${{ parameters.pythonVersion }}
        excludePaths: $(LINT_EXCLUDE_PATHS)
    
    - template: /tasks/artifacts/publish_app.yml
      parameters:
        contents: |
          **/*
          !.git/**/*
          !?/**/*
          !**/*.log
          !.venv/**/*

    - template: /tasks/telemetry/telemetry.yml
