parameters:
  - name: pythonVersion
    type: string

stages:
- stage: gate
  displayName: "Quality Gates"
  dependsOn: 
  - build_test
  pool: $(PRIVATE_AGENT_DEFAULT)
  jobs:
  - job: sonarqube
    condition: and(
                  eq(variables.flowIsToReview, true),
                  ne(variables.skip_sonarqube, true)
                )
    displayName: Code Analysis
    steps:
    - template: /tasks/bash/welcome.yml
    - ${{ if eq(variables.flowIsMain, true) }}:
      - template: /tasks/catalog_info/extract_variables.yml
        parameters:
          workingDirectory: $(Build.SourcesDirectory)
          skipDownload: true
      - template: /task_groups/gates/run_sonarqube_scan.yml
        parameters:
          stack: "PYTHON"
          pythonVersion: "${{parameters.pythonVersion}}"
          projectKey: "$(SONAR_PROJECT_KEY)"
      - template: /tasks/telemetry/telemetry.yml