stages:
- stage: validation
  displayName: "Validation"
  dependsOn:
  - security 
  - package
  - gate
  pool: $(PRIVATE_AGENT_DEFAULT)
  jobs:
  - job: validation
    condition: eq(variables.flowIsMain, true)
    displayName: "Gates Validation"
    steps:
    - template: /tasks/bash/welcome.yml
