parameters:
- name: artifactGroup
  type: string
- name: artifactId
  type: string
- name: artifactVersion
  type: string

steps:
- bash: |
    RESPONSE=$(curl -s "$AZURE_ARTIFACTS_MAVEN_REST_API/groups/${GROUP_ID}/artifacts/${ARTIFACT_ID}/versions/${VERSION}" \
                -H "Authorization: Basic $(echo -n :$SYSTEM_ACCESSTOKEN | base64 | tr '\n' ' ')" \
                -o /dev/null -s \
                -w "%{http_code}" \
                --proxy "$HTTPS_PROXY" \
              )

    if [[ "$RESPONSE" == "200" ]]; then
      echo "##vso[task.logissue type=error] The artifact $GROUP_ID:$ARTIFACT_ID:$VERSION already exists on Azure Artifacts."
      exit 1
    fi
  env:
    SYSTEM_ACCESSTOKEN: $(System.AccessToken)
    HTTPS_PROXY: $(PROXY_AGENT_HTTPS)
    GROUP_ID: ${{ parameters.artifactGroup }}
    ARTIFACT_ID: ${{ parameters.artifactId }}
    VERSION: ${{ parameters.artifactVersion }}