stages:
- stage: quality_gates
  displayName: "Quality Gates"
  dependsOn: pipeline_init
  variables:
    NEW_VERSION: $[ stageDependencies.pipeline_init.get_new_version.outputs['versioning.NEW_VERSION'] ]
  pool:
    name: $(PRIVATE_AGENT_DEFAULT)
  jobs:
  - job: run_sonar_scanner
    displayName: "Running Sonar Scanner"
    variables: 
      - name: SONARQUBE_PROJECT_NAME
        value: "$(System.TeamProject)-$(Build.Repository.Name)"
    steps:
    - template: /tech_products/mule-fenix/steps/catalog_info/extract_variables.yml

    # - task: SonarQubePrepare@7
    #   displayName: 'Prepare analysis on SonarQube'
    #   inputs:
    #     SonarQube: '$(SONARQUBE_SERVICE_CONNECTION_NAME)'
    #     scannerMode: CLI
    #     cliVersion: '$(SONARQUBE_CLI_VERSION)'
    #     configFile: '$(Build.SourcesDirectory)/.azuredevops/sonar-project.properties'
    #     extraProperties: |
    #       sonar.scm.disabled=True
    #       sonar.projectBaseDir=$(Build.SourcesDirectory)
    #       sonar.projectKey=$(SONAR_PROJECT_KEY)
    #       sonar.projectName=$(System.TeamProject)-$(Build.Repository.Name)
    #       sonar.projectVersion=$(NEW_VERSION)
    #       sonar.analysis.repositoryName=$(Build.Repository.Name)
    #       sonar.analysis.buildId=$(Build.BuildId)
    #       sonar.analysis.repositoryId=$(Build.Repository.ID)
    #       sonar.analysis.projectName=$(System.TeamProject)
    #       sonar.analysis.projectId=$(System.TeamProjectId)
    #       sonar.links.homepage=$(System.TeamFoundationCollectionUri)$(System.TeamProject)
    #       sonar.links.ci=$(System.TeamFoundationCollectionUri)$(System.TeamProject)/_build/results?buildId=$(Build.BuildId)&_a=summary
    #       sonar.links.issue=$(System.TeamFoundationCollectionUri)$(System.TeamProject)/_workitems
    #       sonar.links.scm=$(System.TeamFoundationCollectionUri)$(System.TeamProject)/_git/$(Build.Repository.Name)
    #       sonar.scanner.metadataFilePath=$(Agent.TempDirectory)/sonar/$(Build.BuildId)/report-task.txt
    #       sonar.qualitygate.wait=true
    #       sonar.qualitygate.timeout=300
    #       sonar.lang.patterns.xml=$(SONAR_LANG_PATTERNS_XML)
    #       sonar.lang.patterns.mule=$(SONAR_LANG_PATTERNS_MULE)
    #       sonar.mule.file.suffixes=$(SONAR_MULE_FILE_SUFFIXES)
    #       sonar.exclusion=$(SONAR_MULE_EXCLUSIONS)
    #   env:
    #     NODE_EXTRA_CA_CERTS: $(CACORP_LOCATION)
 
    - task: XmlParseFromVivo@4
      displayName: 'Get pom.xml info'
      inputs:
        type: 'file'
        origin: $(Build.SourcesDirectory)/pom.xml
        jpaths: |
          var POM_XML_VERSION = .project.version._text

    - task: YamlParseFromVivo@4
      displayName: 'Get Metadata Info'
      inputs:
        type: 'file'
        origin: $(Build.SourcesDirectory)/catalog-info.yaml
        jpaths: |
          var CATALOG_YAML_ACRONYM = .metadata.annotations['techarch.governance-app.acronym']
          var CATALOG_YAML_MODULE = .metadata.annotations['techarch.governance-app.module']
          var CATALOG_YAML_SONAR_PROJECT_KEY = .metadata.annotations['sonarqube.org/project-key']
          var CATALOG_YAML_JAVA_LANGUAGE_VERSION = .metadata.annotations['arqtech.telefonica.com.br/language-version']

    - task: ListFilesAndFolders@4
      displayName: 'Fetch "sonar.java.binaries"'
      inputs:
        scriptSource: 'text'
        separator: ','
        script: 
          var://BINARIES_DIRECTORIES = $(Build.SourcesDirectory)/**/target/classes

    - task: SonarQubePrepare@5
      displayName: 'Config Sonar'
      inputs:
        SonarQube: VIVO_SONARQUBE
        scannerMode: "CLI"
        # configFile Não funciona no scannerMode Other, apenas CLI (https://learn.microsoft.com/pt-br/azure/devops/pipelines/tasks/reference/sonar-qube-prepare-v5?view=azure-pipelines)
        configFile: $(Build.SourcesDirectory)/.azuredevops/sonar-project.properties
        extraProperties: |
          sonar.scm.disabled=True
          sonar.projectBaseDir=$(Build.SourcesDirectory)
          sonar.projectKey=$(SONAR_PROJECT_KEY)
          sonar.projectName=$(SONARQUBE_PROJECT_NAME)
          sonar.projectVersion=$(NEW_VERSION)
          sonar.analysis.repositoryName=$(Build.Repository.Name)
          sonar.analysis.buildId=$(Build.BuildId)
          sonar.analysis.repositoryId=$(Build.Repository.ID)
          sonar.analysis.projectName=$(System.TeamProject)
          sonar.analysis.projectId=$(System.TeamProjectId)
          sonar.links.homepage=$(System.TeamFoundationCollectionUri)$(System.TeamProject)
          sonar.links.ci=$(System.TeamFoundationCollectionUri)$(System.TeamProject)/_build/results?buildId=$(Build.BuildId)&_a=summary
          sonar.links.issue=$(System.TeamFoundationCollectionUri)$(System.TeamProject)/_workitems
          sonar.links.scm=$(System.TeamFoundationCollectionUri)$(System.TeamProject)/_git/$(Build.Repository.Name)
          sonar.scanner.metadataFilePath=$(Agent.TempDirectory)/sonar/$(Build.BuildId)/report-task.txt
          sonar.qualitygate.wait=true
          sonar.qualitygate.timeout=300
          sonar.lang.patterns.xml=$(SONAR_LANG_PATTERNS_XML)
          sonar.lang.patterns.mule=$(SONAR_LANG_PATTERNS_MULE)
          sonar.mule.file.suffixes=$(SONAR_MULE_FILE_SUFFIXES)
          sonar.exclusion=$(SONAR_MULE_EXCLUSIONS)
          sonar.sources=.
          sonar.inclusions=**/src/main/java/**/*
          sonar.java.binaries=$(BINARIES_DIRECTORIES

    - task: SonarQubeAnalyze@7
      displayName: 'Run Code Analysis'
      continueOnError: true
      env:
        ASDF_JAVA_VERSION: 'openjdk-11.0.2'

    - task: SonarQubePublish@7
      displayName: 'Publish Quality Gate Result'
      continueOnError: true
      env:
        NODE_EXTRA_CA_CERTS: $(CACORP_LOCATION)