parameters:
- name: environment
- name: workDir
  default: $(Build.SourcesDirectory)

steps:

- task: qetza.replacetokens.replacetokens-task.replacetokens@5
  displayName: "Replace Secrets"
  inputs:
    targetFiles: "${{parameters.workDir}}/$(DEFAULT_APPLICATION_HELM_CONFIG)/${{parameters.environment}}/$(DEFAULT_APPLICATION_HELM_SECRET_FILENAME)"
    tokenPattern: custom
    tokenPrefix: '$('
    tokenSuffix: ')'
    verbosity: detailed
    keepToken: true
    actionOnNoFiles: warn