# This YAML file defines a build task that creates a file with build information.

parameters:
  - name: filePath # The parameter 'filePath' specifies the path where the file will be created.

steps:
  - task: CmdLine@2
    displayName: "Create file with build information"
    inputs:
      script: |
        # The script section contains the commands to be executed.

        # Get the current date and time
        DATE=$(date +"%d-%m-%Y-%H:%M:%S")

        # Define the file name
        FILE=last-pipeline-run

        # Print debug information      
        echo "##[debug] FILE............................: $FILE"
        echo "##[debug] APPLICATION_NAME................: $(APPLICATION_NAME)"
        echo "##[debug] PIPELINE_URL....................: $(System.CollectionUri)$(System.TeamProject)/_build/results?buildId=$(Build.BuildId)"
        echo "##[debug] BUILD_NUMBER....................: $(Build.BuildNumber)"
        echo "##[debug] PIPELINE_QUEUE_BY...............: $(Build.QueuedBy)"
        echo "##[debug] PIPELINE_REASON.................: $(Build.Reason)"
        echo "##[debug] ENVIRONMENT.....................: $(OPERATION_HOST_ENVIRONMENT)"
        echo "##[debug] LAST_UPDATE.....................: $DATE"

        # Create the file and write build information to it
        echo "##[group]Create $FILE File"
        cat > ${{ parameters.filePath }}/$FILE <<- "EOF"
        Application: $(APPLICATION_NAME)
        Pipeline URL: $(System.CollectionUri)$(System.TeamProject)/_build/results?buildId=$(Build.BuildId)
        Build Number: $(Build.BuildNumber)
        Pipeline Queue By: $(Build.QueuedBy)
        Pipeline Reason: $(Build.Reason)
        Environment: $(OPERATION_HOST_ENVIRONMENT)
        EOF

        # Append the last update date to the file
        echo "Last Update: $DATE" >> $FILE

        # Print the contents of the file
        cat ${{ parameters.filePath }}/$FILE
        echo "##[endgroup]"
