parameters:
  - name: directory
  - name: disableCleanDirectory
    default: false
  - name: condition
    default: succeeded()

steps:
  - task: CmdLine@2
    displayName: "Clean ${{ parameters.directory }} Directory"
    condition: |
      or(
        ne('${{ parameters.disableCleanDirectory }}', 'false'), 
        ${{ parameters.condition }}
      )
    inputs:
      script: |
        DIRECTORY=${{ parameters.directory }}

        echo "##[debug] DIRECTORY........................................: $DIRECTORY"

        echo "##[command]rm -rfv $DIRECTORY"
        rm -rfv $DIRECTORY
