steps:
  - task: CmdLine@2
    displayName: "Get All Variables Groups"
    name: get_all_variables_groups
    inputs:
      script: |
        echo ">>>>> Listing all variable groups:"

        echo "##[command]az pipelines variable-group list --org $(System.CollectionUri) --project $(System.TeamProjectId) --output table 2>&1 | grep -v 'WARNING: Could not retrieve credential from local cache for service principal' 2>/dev/null || 2>/dev/null"
        az pipelines variable-group list --org $(System.CollectionUri) --project $(System.TeamProjectId) --output table 2>&1 | grep -v 'WARNING: Could not retrieve credential from local cache for service principal' 2>/dev/null || 2>/dev/null

    env:
      AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)
