steps: 
# This YAML file defines a task called "Get Job Agent" that runs a command line script.

- task: CmdLine@2
  displayName: "Get Job Agent"
  name: get_job_agent
  retryCountOnTaskFailure: 3
  inputs:
    workingDirectory: $(Agent.BuildDirectory)/${{ parameters.workingDirectory }}
    script: |
      # This script outputs the value of the environment variable AGENT_NAME using the "echo" command.
      echo "##[debug] JOB_AGENT_NAME.............: $AGENT_NAME"
    
      # This script sets the value of the variable JOB_AGENT_NAME as an output variable using the "echo" command.
      echo "##vso[task.setvariable variable=JOB_AGENT_NAME;isOutput=true]$AGENT_NAME"