parameters:
  - name: pipelineName
  - name: teamProjectId
    default: $(System.TeamProjectId)
  - name: accessToken
    default: $(System.AccessToken)

steps:
  - task: CmdLine@2
    displayName: "Get Pipeline ${{ parameters.pipelineName }} Id"
    name: get_pipeline_id
    retryCountOnTaskFailure: 3
    inputs:
      script: |
        echo "##[debug] PIPELINE_NAME.................................: ${PIPELINE_NAME}"
        echo "##[debug] TEAM_PROJECT_ID...............................: ${TEAM_PROJECT_ID}"
        echo "##[debug] ACCESS_TOKEN..................................: ***"
        echo ""

        echo "##[command]curl -s -H "Content-Type: application/json" -u :$AZURE_DEVOPS_EXT_PAT -X GET $(System.CollectionUri)${TEAM_PROJECT_ID}/_apis/pipelines?api-version=7.1-preview.1 | jq -r --arg name "$PIPELINE_NAME" '.value[] | select(.name==$name) | .id'"
        PIPELINE_ID=$(curl -s -H "Content-Type: application/json" -u :$AZURE_DEVOPS_EXT_PAT -X GET $(System.CollectionUri)${TEAM_PROJECT_ID}/_apis/pipelines?api-version=7.1-preview.1 | jq -r --arg name "$PIPELINE_NAME" '.value[] | select(.name==$name) | .id')

        if [[ -z "$PIPELINE_ID" ]]; then
          echo "##vso[task.logissue type=error;]Pipeline '${PIPELINE_NAME}' not found"
          echo "##vso[task.complete result=Failed;]"
          exit 1
        fi

        echo ""
        echo ">>>>> Pipeline ID found: $PIPELINE_ID <<<<<"

        echo "##vso[task.setvariable variable=PIPELINE_ID;]$PIPELINE_ID"
    env:
      AZURE_DEVOPS_EXT_PAT: ${{ parameters.accessToken }}
      PIPELINE_NAME: ${{ parameters.pipelineName }}
      TEAM_PROJECT_ID: ${{ parameters.teamProjectId }}