steps: 
- script: |
    echo "##[debug] Start Time ..............................................: $(date +%H:%M:%S) [$(date +%s)]"

    echo "##vso[task.setvariable variable=START_TIME;isoutput=true]$(date +%s)"
    echo "##vso[task.setvariable variable=START_TIME_FORMATTED;isoutput=true]$(date +%H:%M:%S)"
  name: setStartTime
  displayName: "Set Start Time"