parameters:
  - name: stoppedNodes

steps:
  - task: CmdLine@2
    displayName: "Set Stopped Nodes Variable"
    name: stopped_nodes_variable
    inputs:
      script: |
        echo "##[debug] STOPPED NODES ...................................: ${{ parameters.stoppedNodes }}"
        echo ""

        echo "##### Updating the STOPPED_NODES variable in the BRM IAC Variables Library ..."

        echo "##[command]az pipelines variable-group variable update --group-id $(BRM_IAC_VARIABLES_LIBRARY_ID) --name STOPPED_NODES --value \"${{ parameters.stoppedNodes }}\" --org $(System.CollectionUri) --project $(System.TeamProjectId) --secret false --output none"
        az pipelines variable-group variable update \
          --group-id $(BRM_IAC_VARIABLES_LIBRARY_ID) \
          --name STOPPED_NODES \
          --value "${{ parameters.stoppedNodes }}" \
          --org $(System.CollectionUri) \
          --project $(System.TeamProjectId) \
          --secret false \
          --output none 2>&1 \
          | grep -v 'WARNING: Could not retrieve credential from local cache for service principal' 2>/dev/null || 2>/dev/null

        echo ""
        echo "✅ STOPPED_NODES variable updated successfully."
    env:
      AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)
