parameters:
- name: incrementLevel
  default: patch
- name: enableDevflowValidations
  type: boolean
  default: False

stages:
- stage: build_test
  displayName: "Build & Test"
  dependsOn:
    - pipeline_init
    - ${{ if eq(parameters.enableDevflowValidations, True) }}:
      - repo_validations
  pool: $(GENERAL_PURPOSE_CI_AGENT)
  jobs:
    - job: bump_version
      displayName: Bumping Version
      steps:
      - template: /tech_products/loja-online/tasks/git/checkout_last_commit.yml
        parameters:
          branchName: "$(Build.SourceBranchName)"
      - template: /tech_products/loja-online/tasks/nodejs/npm_extract_version.yml
        parameters:
          currentVersionVariableOut: CURRENT_VERSION
      - template: /tech_products/loja-online/tasks/versioning/bump_version.yml
        parameters:
          currentVersion: $(export_current_version.CURRENT_VERSION)
          newVersionVariableOut: NEW_VERSION
          incrementLevel: ${{ parameters.incrementLevel }}
          
    - job: build_test
      displayName: Build & Test & Coverage
      dependsOn:
          - bump_version
      variables:
      - name: NEW_VERSION 
        value: $[ dependencies.bump_version.outputs['component_bump_version.NEW_VERSION'] ]
      steps:
      - template: /tech_products/loja-online/tasks/bash/welcome.yml
      - template: /tech_products/loja-online/task_groups/build/nodejs_build_test.yml
        parameters:
          newVersion: "$(NEW_VERSION)"
      - template: /tech_products/loja-online/task_groups/tests/publish_tests_reports.yml
        parameters:
          testResultsFilesPattern: "**/junit.xml"
          coverageFilePattern: "**/cobertura-coverage.xml"
          codeCoverageTool: "Cobertura"