parameters:
- name: deviceIp
- name: deviceHostname

steps:
- task: PythonScript@0
  displayName: '[PAM] Delete Device'
  inputs:
    scriptSource: inline
    script: |
      import requests
      import os
            
      base_url = os.getenv('SENHA_SEGURA_BASE_URL')
      access_token = os.getenv('ACCESS_TOKEN')
      device_hostname = os.getenv('DEVICE_HOSTNAME')
      device_ip = os.getenv('DEVICE_IP')

      def get_device_id():
        url = base_url + '/iso/pam/device'
        params = {
          'ip': device_ip,
          'hostname': device_hostname
        }

        print('##[command] GET {} - Get Device'.format(url))
        print('##[debug] request_params...................: ', params)
        response = requests.get(
            url,
            headers = {
              'Authorization': 'Bearer ' + access_token
            },
            params = params,
            verify = False
        )
        response_json = response.json()
        print('##[debug] response_json....................: ', response_json)
        device_id = response_json['devices'][0]['id']
        print('##[debug] device_id........................: ', device_id)
        return device_id

      def delete_device(device_id):
        url = base_url + '/iso/pam/device/' + device_id 
        print('##[command] DELETE {} - Delete Device'.format(url))
        response = requests.delete(
            url,
            headers = {
              'Authorization': 'Bearer ' + access_token
            },
            verify = False
        )
        response_json = response.json()
        print('##[debug] response_json....................: ', response_json)

      device_id = get_device_id()
      delete_device(device_id)
  env:
    SENHA_SEGURA_BASE_URL: $(SENHA_SEGURA_BASE_URL)
    ACCESS_TOKEN: $(SENHA_SEGURA_ACCESS_TOKEN)
    DEVICE_IP: ${{ parameters.deviceIp }}
    DEVICE_HOSTNAME: ${{ parameters.deviceHostname }}