parameters:
- name: environment
- name: packageVersion
- name: artifact
- name: appName

variables:
- group: lib-weblogic

stages:
- stage: cd_deploy
  displayName: "CD - Deploy ${{ parameters.environment }}"
  pool: GeneralPurposeLinuxAgentsCD
  jobs:

  - deployment: deploy
    displayName: 'Deploy'
    environment:
      name: deploy-${{ parameters.environment }}
    continueOnError: true
    strategy:
      runOnce:
        deploy:
          steps:

          - download: none

          - checkout: self
            fetchDepth: 1

          - task: XmlParseFromVivo@4
            displayName: 'Get pom.xml info'
            inputs:
              type: 'file'
              origin: $(Build.SourcesDirectory)/pom.xml
              jpaths: |
                var GROUP_ID = .project.groupId._text
                var ARTIFACT_ID = .project.artifactId._text

          - task: DownloadPackage@1
            displayName: 'Download Maven Artifact from Azure Artifacts'
            inputs:
              packageType: 'maven'
              feed: 'DevOps'
              definition: '$(GROUP_ID):$(ARTIFACT_ID)-${{ parameters.artifact }}'
              version: '${{ parameters.packageVersion }}'
              downloadPath: '$(Build.ArtifactStagingDirectory)/downloaded-artifact'

          - task: CmdLine@2
            displayName: list packages and remove unwanted files
            condition: succeeded()
            continueOnError: false
            inputs:
              workingDirectory: $(Build.ArtifactStagingDirectory)/downloaded-artifact
              targetType: inline
              script: |
                echo "##[group] Antes da exclusão:"
                ls -l $(Build.ArtifactStagingDirectory)/downloaded-artifact
                echo "##[endgroup]"
                echo "Removendo arquivos que não terminam com .ear, .jar, .ejb ou web"
                find $(Build.ArtifactStagingDirectory)/downloaded-artifact -type f ! \( \
                  -name "*.ear" -o \
                  -name "*.jar" -o \
                  -name "*.ejb" -o \
                  -name "*web" \
                \) -exec rm -f {} +

                echo "##[group] Depois da exclusão:"
                ls -l $(Build.ArtifactStagingDirectory)/downloaded-artifact
                echo "##[endgroup]"

          - task: Bash@3
            displayName: 'Define ARTIFACT_FILE variable'
            inputs:
              targetType: 'inline'
              workingDirectory: $(Build.ArtifactStagingDirectory)/downloaded-artifact
              script: |
                ARTIFACT_FILE=$(ls | grep -E '\.ear$|\.jar$|\.ejb$|web$' | head -n 1)
                echo "Arquivo encontrado: $ARTIFACT_FILE"
                echo "##vso[task.setvariable variable=ARTIFACT_FILE]$ARTIFACT_FILE"

          - task: UniversalPackages@0
            displayName: Get Weblogic Scripts
            inputs:
              command: download
              vstsFeed: "3d53bc62-8749-4931-ae46-a443b73bc87a"
              vstsFeedPackage: "codeplay-weblogic-scripts"
              vstsPackageVersion: "0.0.5"
              downloadDirectory: "$(Pipeline.Workspace)"

          - task: CmdLine@2
            displayName: Unzip tar file
            condition: succeeded()
            continueOnError: false
            inputs:
              workingDirectory: $(Pipeline.Workspace)
              targetType: inline
              script: |
                tar -xvf codeplay-weblogic-scripts-0.0.5.tar

          - task: YamlParseFromVivo@4
            displayName: 'Set Weblogic Environment'
            inputs:
              type: 'file'
              origin: $(Build.SourcesDirectory)/.azuredevops/config/${{ parameters.environment }}/weblogic.yml
              jpaths: |
                var WEBLOGIC_ADMIN_SERVER_URL = .weblogic['WEBLOGIC_ADMIN_SERVER_URL']
                var WEBLOGIC_USER = .weblogic['WEBLOGIC_USER']
                var WEBLOGIC_PASS = .weblogic['WEBLOGIC_PASS']
                var WEBLOGIC_CLUSTER = .weblogic['WEBLOGIC_CLUSTER']
                var WEBLOGIC_APPLICATIONS_SERVER_PATH = .weblogic['WEBLOGIC_APPLICATIONS_SERVER_PATH']
                var WEBLOGIC_SCRIPTS_SERVER_PATH = .weblogic['WEBLOGIC_SCRIPTS_SERVER_PATH']
                var WEBLOGIC_PROPERTIES_SERVER_PATH = .weblogic['WEBLOGIC_PROPERTIES_SERVER_PATH']
                var WEBLOGIC_PROPERTIES_SERVER_FILE = .weblogic['WEBLOGIC_PROPERTIES_SERVER_FILE']
                var WEBLOGIC_TIMEOUT = .weblogic['WEBLOGIC_TIMEOUT']
          
          - script: |
              echo "WEBLOGIC_ADMIN_SERVER_URL: $(WEBLOGIC_ADMIN_SERVER_URL)"
              echo "WEBLOGIC_USER: $(WEBLOGIC_USER)"
              echo "WEBLOGIC_PASS: $(WEBLOGIC_PASS)"
              echo "WEBLOGIC_CLUSTER: $(WEBLOGIC_CLUSTER)"
              echo "WEBLOGIC_APPLICATIONS_SERVER_PATH: $(WEBLOGIC_APPLICATIONS_SERVER_PATH)$(ARTIFACT_ID)/codeplay_deployment_${{ parameters.packageVersion }}"
              echo "WEBLOGIC_SCRIPTS_SERVER_PATH: $(WEBLOGIC_SCRIPTS_SERVER_PATH)$(ARTIFACT_ID)/codeplay_scripts_${{ parameters.packageVersion }}"
              echo "WEBLOGIC_PROPERTIES_SERVER_PATH: $(WEBLOGIC_PROPERTIES_SERVER_PATH)"
              echo "WEBLOGIC_PROPERTIES_SERVER_FILE: $(WEBLOGIC_PROPERTIES_SERVER_FILE)"
              echo "WEBLOGIC_TIMEOUT: $(WEBLOGIC_TIMEOUT)"
            displayName: "Get variables"

          - task: LegacySSH@0
            displayName: Set SSH Environment
            condition: succeeded()
            inputs:
              sshEndpoint: weblogic_${{ parameters.environment }}
              runOptions: 'inline'
              readyTimeout: '60000'
              inline: |

                echo "##[debug] SSH is connected! IP: $(hostname -i)..."
                echo "##vso[task.setvariable variable=WEBLOGIC_ADMIN_SERVER_IP;isOutput=true]$(hostname -i | awk '{print $1}')"

                echo "##[debug] Setting up folders..."
                mkdir -p "$(WEBLOGIC_APPLICATIONS_SERVER_PATH)$(ARTIFACT_ID)/codeplay_deployment_${{ parameters.packageVersion }}"
                chmod 775 "$(WEBLOGIC_APPLICATIONS_SERVER_PATH)$(ARTIFACT_ID)/codeplay_deployment_${{ parameters.packageVersion }}"
                echo "##[debug] Folder $(WEBLOGIC_APPLICATIONS_SERVER_PATH)$(ARTIFACT_ID)/codeplay_deployment_${{ parameters.packageVersion }} created!"

                mkdir -p "$(WEBLOGIC_SCRIPTS_SERVER_PATH)$(ARTIFACT_ID)/codeplay_scripts_${{ parameters.packageVersion }}"
                chmod 775 "$(WEBLOGIC_SCRIPTS_SERVER_PATH)$(ARTIFACT_ID)/codeplay_scripts_${{ parameters.packageVersion }}"
                echo "##[debug] Folder $(WEBLOGIC_SCRIPTS_SERVER_PATH)$(ARTIFACT_ID)/codeplay_scripts_${{ parameters.packageVersion }} created!"

                echo "##[debug] Create an empty file to add server addresses ... "
                touch "$(WEBLOGIC_SCRIPTS_SERVER_PATH)$(ARTIFACT_ID)/codeplay_scripts_${{ parameters.packageVersion }}/weblogic_machines_info.txt"
                chmod 777 "$(WEBLOGIC_SCRIPTS_SERVER_PATH)$(ARTIFACT_ID)/codeplay_scripts_${{ parameters.packageVersion }}/weblogic_machines_info.txt"
                echo "##[debug] File $(WEBLOGIC_SCRIPTS_SERVER_PATH)$(ARTIFACT_ID)/codeplay_scripts_${{ parameters.packageVersion }}/weblogic_machines_info.txt created!"

          - task: LegacyCopyFilesOverSSH@0
            displayName: Transfering Package - SSH
            condition: succeeded()
            inputs:
              sshEndpoint: weblogic_${{ parameters.environment }}
              sourceFolder: '$(Build.ArtifactStagingDirectory)/downloaded-artifact'
              contents: '**'
              overwrite: true
              targetFolder: '$(WEBLOGIC_APPLICATIONS_SERVER_PATH)$(ARTIFACT_ID)/codeplay_deployment_${{ parameters.packageVersion }}'
              readyTimeout: '60000'

          - task: LegacyCopyFilesOverSSH@0
            displayName: Transfering Scripts - SSH
            condition: succeeded()
            inputs:
              sshEndpoint: weblogic_${{ parameters.environment }}
              sourceFolder: '$(Pipeline.Workspace)/scripts/'
              contents: '**'
              overwrite: true
              targetFolder: '$(WEBLOGIC_SCRIPTS_SERVER_PATH)$(ARTIFACT_ID)/codeplay_scripts_${{ parameters.packageVersion }}'
              readyTimeout: '60000'

          - task: LegacySSH@0
            displayName: Set Directory Permissions to 775
            condition: succeeded()
            inputs:
              sshEndpoint: weblogic_${{ parameters.environment }}
              runOptions: 'commands'
              commands: |
                chmod -R 775 $(WEBLOGIC_APPLICATIONS_SERVER_PATH)$(ARTIFACT_ID)/codeplay_deployment_${{ parameters.packageVersion }}
                chmod -R 775 $(WEBLOGIC_SCRIPTS_SERVER_PATH)$(ARTIFACT_ID)/codeplay_scripts_${{ parameters.packageVersion }}

          - task: LegacySSH@0
            displayName: Verify Package on Target Server
            condition: succeeded()
            inputs:
              sshEndpoint: weblogic_${{ parameters.environment }}
              runOptions: inline
              failOnStdErr: true
              inline: |

                echo "##[debug] Starting verification process on machine: $(hostname)"

                ## -> Variables
                PACKAGE_DIR=$(WEBLOGIC_APPLICATIONS_SERVER_PATH)$(ARTIFACT_ID)/codeplay_deployment_${{ parameters.packageVersion }}
                SCRIPTS_DIR=$(WEBLOGIC_SCRIPTS_SERVER_PATH)$(ARTIFACT_ID)/codeplay_scripts_${{ parameters.packageVersion }}
                PACKAGE_FILE=$(ARTIFACT_FILE)

                echo "##[debug] Checking machine name and environment..."
                MACHINE_NAME=$(hostname)
                echo "##[debug] Machine Name: $MACHINE_NAME"
                echo "##[debug] Environment: ${{ parameters.environment }}"

                ## -> Check Scripts Archive
                echo "##[debug] Verifying package file in $PACKAGE_DIR..."
                if [ -f "$PACKAGE_DIR/$PACKAGE_FILE" ]; then
                  echo "##[debug] Package $PACKAGE_FILE found in $PACKAGE_DIR"
                  echo "##[debug] File details:"
                  ls -lh "$PACKAGE_DIR/$PACKAGE_FILE"
                  echo "##[debug] Permissions for $PACKAGE_FILE:"
                  stat -c "%A %U %G" "$PACKAGE_DIR/$PACKAGE_FILE"
                else
                  echo "##[debug] ERROR: Package $PACKAGE_FILE not found in $PACKAGE_DIR"
                  exit 1
                fi

          - task: LegacySSH@0
            displayName: List Scripts
            inputs:
              sshEndpoint: weblogic_${{ parameters.environment }}
              runOptions: 'inline'
              inline: |
                ls -la $(WEBLOGIC_SCRIPTS_SERVER_PATH)$(ARTIFACT_ID)/codeplay_scripts_${{ parameters.packageVersion }}/python

          - task: LegacySSH@0
            displayName: Start Servers - Readiness Assurance
            condition: succeeded()
            inputs:
              sshEndpoint: weblogic_${{ parameters.environment }}
              runOptions: 'commands'
              commands: >
                /opt/web/applications/oracle_common/common/bin/wlst.sh
                $(WEBLOGIC_SCRIPTS_SERVER_PATH)$(ARTIFACT_ID)/codeplay_scripts_${{ parameters.packageVersion }}/python/StartServers.py
                $(WEBLOGIC_USER)
                $(WEBLOGIC_PASS)
                $(WEBLOGIC_ADMIN_SERVER_URL)
                $(WEBLOGIC_TIMEOUT)
              readyTimeout: '60000'
              failOnStdErr: false

          - task: LegacySSH@0
            displayName: Undeploy/Retiring package
            condition: succeeded()
            inputs:
              sshEndpoint: weblogic_${{ parameters.environment }}
              runOptions: 'commands'
              commands: >
                /opt/web/applications/oracle_common/common/bin/wlst.sh
                $(WEBLOGIC_SCRIPTS_SERVER_PATH)$(ARTIFACT_ID)/codeplay_scripts_${{ parameters.packageVersion }}/python/UndeployAppRetired.py
                $(WEBLOGIC_USER)
                $(WEBLOGIC_PASS)
                $(WEBLOGIC_ADMIN_SERVER_URL)
                ${{ parameters.appName }}
              readyTimeout: '60000'
              failOnStdErr: false

          - task: LegacySSH@0
            displayName: Update package
            condition: succeeded()
            inputs:
              sshEndpoint: weblogic_${{ parameters.environment }}
              runOptions: 'commands'
              commands: >
                /opt/web/applications/oracle_common/common/bin/wlst.sh
                $(WEBLOGIC_SCRIPTS_SERVER_PATH)$(ARTIFACT_ID)/codeplay_scripts_${{ parameters.packageVersion }}/python/HotDeployApp.py
                $(WEBLOGIC_USER)
                $(WEBLOGIC_PASS)
                $(WEBLOGIC_ADMIN_SERVER_URL)
                ${{ parameters.appName }}_${{ parameters.packageVersion }}
                $(WEBLOGIC_APPLICATIONS_SERVER_PATH)$(ARTIFACT_ID)/codeplay_deployment_${{ parameters.packageVersion }}/$(ARTIFACT_FILE)
                $(WEBLOGIC_CLUSTER)
                $(WEBLOGIC_TIMEOUT)
              readyTimeout: '60000'
              failOnStdErr: false

  - job: post_weblogic_deploy
    displayName: "Post Weblogic Deploy"
    dependsOn:
    - deploy
    condition: always()
    steps:

    - checkout: self
      fetchDepth: 1

    - task: YamlParseFromVivo@4
      displayName: 'Get WebLogic Scripts Path'
      inputs:
        type: 'file'
        origin: $(Build.SourcesDirectory)/.azuredevops/config/${{ parameters.environment }}/weblogic.yml
        jpaths: |
          var WEBLOGIC_SCRIPTS_SERVER_PATH = .weblogic['WEBLOGIC_SCRIPTS_SERVER_PATH']

    - task: XmlParseFromVivo@4
      displayName: 'Get pom.xml info'
      inputs:
        type: 'file'
        origin: $(Build.SourcesDirectory)/pom.xml
        jpaths: |
          var GROUP_ID = .project.groupId._text
          var ARTIFACT_ID = .project.artifactId._text

    - task: LegacySSH@0
      displayName: Remove Folders
      inputs:
        sshEndpoint: weblogic_${{ parameters.environment }}
        runOptions: 'inline'
        readyTimeout: '60000'
        inline: |

          validate_and_remove() {
            local path=$1
            if [[ "$path" == /opt/web/applications/* && "$path" != /opt/web/applications/ && "$path" == *codeplay_* ]]; then
              rm -r "$path"
            else
              echo "##[error] Path $path is not valid. It must start with /opt/web/applications/"
              echo "##[error] Folder path must have additional subdirectories, and contain 'codeplay_' in some folder name."
              exit 1
            fi
          }

          validate_and_remove "$(WEBLOGIC_SCRIPTS_SERVER_PATH)$(ARTIFACT_ID)/codeplay_scripts_${{ parameters.packageVersion }}"