
steps:
- task: PipAuthenticate@1
  displayName: 'Pip Authenticate'
  inputs:
    artifactFeeds: $(AZURE_ARTIFACTS_FEED)
  env:
    http_proxy: $(PROXY_NSKP_HTTP)
    https_proxy: $(PROXY_NSKP_HTTPS)
    no_proxy: $(PROXY_NSKP_NO_PROXY)

- bash: |
    set -uo pipefail
    cd $(Build.SourcesDirectory)
    CONFIG_FILE_PATH=".tool-versions"
    CUSTOM_PYTHON_VERSION=$(awk '/^python[[:space:]]/{print $2; exit}' "${CONFIG_FILE_PATH}")
    asdf local python "${CUSTOM_PYTHON_VERSION}"
    PYTHON_DIR=$(asdf where python "${CUSTOM_PYTHON_VERSION}")
    echo "##vso[task.prependpath]${PYTHON_DIR}/bin"
  displayName: "Config Python version"

- bash: |
    echo "[command]Using python version $(python --version)"
    set -uo pipefail
    if ! command -v uv &> /dev/null; then
      python -m pip install --upgrade pip
      echo "[command] uv not found, installing..."
      echo "[command] Installing uv==$(UV_VERSION)"
      pip install uv==$(UV_VERSION)
    fi
    uv venv
    source .venv/bin/activate
  displayName: "Install uv and create virtual env (using uv)"
  workingDirectory: "$(Build.SourcesDirectory)"
  condition: and(succeeded(), eq(variables['VERSION_MANAGER_TYPE'], 'uv'))
  env:
    UV_VERSION: $(UV_VERSION)
    http_proxy: $(PROXY_NSKP_HTTP)
    https_proxy: $(PROXY_NSKP_HTTPS)
    no_proxy: $(PROXY_NSKP_NO_PROXY)

- bash: |
    echo "[command]Using python version $(python --version)"
    set -uo pipefail
    python -m pip install --upgrade pip

    echo "[section]Creating virtual environment"
    python -m venv .venv

    source .venv/bin/activate
  displayName: "Install venv and create virtual env"
  workingDirectory: "$(Build.SourcesDirectory)"
  condition: and(succeeded(), eq(variables['VERSION_MANAGER_TYPE'], 'version_file'))
  env:
    http_proxy: $(PROXY_NSKP_HTTP)
    https_proxy: $(PROXY_NSKP_HTTPS)
    no_proxy: $(PROXY_NSKP_NO_PROXY)

- bash: |
    echo "[command]Using python version $(python --version)"
    set -uo pipefail
    bash -c "${UV_CMD_SYNC}"
  displayName: "Install dependencies (with uv)"
  workingDirectory: "$(Build.SourcesDirectory)"
  condition: and(succeeded(), eq(variables['VERSION_MANAGER_TYPE'], 'uv'))
  env:
    UV_CMD_SYNC: $(UV_CMD_SYNC)

- bash: |
    set -uo pipefail
    echo "[command]Using python version $(python --version)"
    python -m pip install -r requirements.txt
  displayName: "Install dependencies (with requirements.txt)"
  workingDirectory: "$(Build.SourcesDirectory)"
  condition: and(succeeded(), eq(variables['VERSION_MANAGER_TYPE'], 'version_file'))
  env:
    http_proxy: $(PROXY_NSKP_HTTP)
    https_proxy: $(PROXY_NSKP_HTTPS)
    no_proxy: $(PROXY_NSKP_NO_PROXY)
