steps:
- bash: |
    echo "[command]Using python version $(python --version)"
    export PYTHONPATH=./;
    if [ "${VERSION_MANAGER_TYPE}" == "uv" ]; then
      CMD_LINT="${UV_CMD_LINT}"
    else
      CMD_LINT="${DEFAULT_CMD_LINT}"
    fi

    echo "[command]Executando ${CMD_LINT}"
    bash -c "${CMD_LINT}"

    if [ $? -ne 0 ]; then
      MESSAGE="Erros de lint encontrados!"
      echo "[command]A variável BREAK_LINT_FAILED está com o valor: ${BREAK_LINT_FAILED}"
      if [ "${BREAK_LINT_FAILED}" = true ]; then
        echo "[error]${MESSAGE}"
        exit 1
      else
        echo "[warning]${MESSAGE}"
        echo "[warning]Lint falhou, mas build não será quebrada."
      fi
    fi
  displayName: "Run Lint"
  workingDirectory: "$(Build.SourcesDirectory)"
  condition: and(succeeded(), eq(variables['LINT_ENABLED'], 'true'), in(variables['VERSION_MANAGER_TYPE'], 'version_file', 'uv'))
  env:
    BREAK_LINT_FAILED: $(BREAK_LINT_FAILED)
    UV_CMD_LINT: $(UV_CMD_LINT)
    DEFAULT_CMD_LINT: $(DEFAULT_CMD_LINT)
    VERSION_MANAGER_TYPE: $(VERSION_MANAGER_TYPE)


