steps:
- bash: |
    export PYTHONPATH=./;
    echo "[command]Using python version $(python --version)"
    if [ "${VERSION_MANAGER_TYPE}" == "uv" ]; then
      CMD_RUN_TESTS="${UV_CMD_RUN_TESTS}"
    else
      CMD_RUN_TESTS="${DEFAULT_CMD_RUN_TESTS}"
    fi

    echo "[command]Running tests ........: Running ${CMD_RUN_TESTS}"

    bash -c "${CMD_RUN_TESTS}"
    if [ $? -ne 0 ] && [ "${BREAK_TEST_FAILED}" == "true" ]; then
      echo "[error]Erro ao executar os testes"
      echo "[error]Comando executado: ${CMD_RUN_TESTS}"
      exit 1
    fi
  displayName: "Run tests"
  condition: and(succeeded(), eq(variables['Build.Reason'], 'PullRequest'))
  env:
    DEFAULT_CMD_RUN_TESTS: $(DEFAULT_CMD_RUN_TESTS)
    UV_CMD_RUN_TESTS: $(UV_CMD_RUN_TESTS)
    BREAK_TEST_FAILED: $(BREAK_TEST_FAILED)
    VERSION_MANAGER_TYPE: $(VERSION_MANAGER_TYPE)

- template: /tech_products/ecmc/core-pipelines/task_groups/tests/publish_tests_reports.yml
  parameters:
    testResultsFilesPattern: "**/junit.xml"
    coverageFilePattern: "**/coverage.xml"
    codeCoverageTool: "Cobertura"

