parameters:
- name: frontendApiID
- name: componentName
- name: componentVersion

steps:
- script: |
    DAT_FILE_NAME="${COMPONENT_NAME}-${COMPONENT_VERSION}.dat"
    EXPORTED_DAT_FILE_LOCATION="${AGENT_TEMPDIRECTORY}/${DAT_FILE_NAME}"

    echo "##[debug] API_MANAGER_BASE_HOST_URL_DEV....: ${API_MANAGER_BASE_HOST_URL_DEV}"
    echo "##[debug] BUILD_REPOSITORY_NAME............: ${BUILD_REPOSITORY_NAME}"
    echo "##[debug] FRONTEND_API_ID..................: ${FRONTEND_API_ID}"
    echo "##[debug] DAT_FILE_NAME....................: ${DAT_FILE_NAME}"

    echo "##[command] POST /proxies/export"
    EXPORT_RESPONSE=$(curl -v --location -k -X POST \
    --user "${ADMIN_USERNAME}:${ADMIN_PASSWORD}" \
    --data-urlencode "id=${FRONTEND_API_ID}" \
    --data-urlencode "password=${DAT_FILE_PASSWORD}" \
    --data-urlencode "filename=${DAT_FILE_NAME}" \
    -H "Content-Type: application/x-www-form-urlencoded" \
    "${API_MANAGER_BASE_URL}/proxies/export" 2>&1)

    EXPORT_LOCATION=$(echo "${EXPORT_RESPONSE}" | grep -i "location:" | awk '{print $3}' | tr -d '\r')
    echo "##[debug] EXPORT_LOCATION..................: ${EXPORT_LOCATION}"

    echo "##[command] GET ${EXPORT_LOCATION}"
    RESPONSE_DAT=$(curl -v -k -X GET \
    --user "${ADMIN_USERNAME}:${ADMIN_PASSWORD}" \
    -H "Content-Type: application/x-www-form-urlencoded" \
    "${API_MANAGER_BASE_HOST_URL_DEV}${EXPORT_LOCATION}" --output ${EXPORTED_DAT_FILE_LOCATION})
    echo "##[debug] EXPORTED_DAT_FILE_LOCATION.......: ${EXPORTED_DAT_FILE_LOCATION}"
  displayName: Export API (.dat)
  env:
    ADMIN_USERNAME: $(ADMIN_USERNAME)
    ADMIN_PASSWORD: $(ADMIN_PASSWORD)
    API_MANAGER_BASE_HOST_URL_DEV: $(API_MANAGER_BASE_HOST_URL_DEV)
    COMPONENT_NAME: ${{ parameters.componentName }}
    COMPONENT_VERSION: ${{ parameters.componentVersion }}
    DAT_FILE_PASSWORD: $(DAT_FILE_PASSWORD)
    FRONTEND_API_ID: ${{ parameters.frontendApiID }}