parameters:
- name: framework
  type: string
- name: cenario
  type: string
- name: optionals
  type: string
  default: ""
- name: docker_image
  type: string
- name: test_environment
  type: string
- name: maven_settings
  type: string
- name: fail_pipeline
  type: boolean
- name: project_id
  type: string
  default: null
- name: enable_collect_metric
  type: boolean
  default: true

## Initialize global variables
variables:
  - template: /tech_products/qa/execution/initialize/init.yml

#resources:
#  repositories:
#    - repository: Metrics
#      name: MIGR-Framework-Qa-Automacao/testes.metrics-framework
#      type: git
#      ref: refs/heads/Metrics_AssertComplexityAzure
#      endpoint: CodePlay

stages:
  # Environment prep
  - template:  /tech_products/qa/execution/templates/ci/ci_environment.yml
    parameters:
      framework: "${{ parameters.framework }}"
  
  # Test Execution
  - template:  /tech_products/rbqa/test-execution-pipeline/individual/templates/ci_test_execution.yml
    parameters:
      framework: "${{ parameters.framework }}"
      cenario: "${{ parameters.cenario }}"
      optionals: "${{ parameters.optionals }}"
      docker_image: "${{ parameters.docker_image }}"
      test_environment: "${{ parameters.test_environment }}"
      fail_pipeline: "${{ parameters.fail_pipeline }}"
      project_id: "${{ parameters.project_id }}"
      enable_collect_metric: false #"${{ parameters.enable_collect_metric }}"

  
  # Clean up
  - template:  /tech_products/qa/execution/templates/ci/ci_clean.yml