stages:
- stage: stage_helm_lint
  displayName: Lint
  pool: $(PRIVATE_AGENT_DEFAULT)
  jobs:
  - job: job_helm_lint
    displayName: Lint validation
    steps:
    - template: /tech_products/ecmc/core-pipelines/tasks/bash/welcome.yml
    - template: /tech_products/ecmc/core-pipelines/tasks/helm/installer.yml
    - template: /tech_products/ecmc/core-pipelines/tasks/helm/lint.yml
    - template: /tech_products/ecmc/core-pipelines/tasks/telemetry/telemetry.yml