steps:
- script: |
    echo "##[debug] HTTP_PROXY.............: ${HTTP_PROXY}"
    echo "##[debug] AXWAY_CLI_VERSION......: ${AXWAY_CLI_VERSION}"
    echo "##[debug] WORK_DIR:..............: $(pwd)"
    
    cat <<EOF >>.wgetrc
    use_proxy = on
    http_proxy = ${PROXY_AGENT_HTTP}
    https_proxy = ${PROXY_AGENT_HTTPS}
    EOF

    echo "##[command] cat ./.wgetrc"
    cat ./.wgetrc

    echo "##[group] Download Axway CLI ${AXWAY_CLI_VERSION}"
    wget --config ./.wgetrc https://github.com/Axway-API-Management-Plus/apim-cli/releases/download/${AXWAY_CLI_VERSION}/axway-apimcli-${AXWAY_CLI_VERSION}.tar.gz
    echo "##[endgroup]"

    echo "##[command] tar -vzxf axway-apimcli-${AXWAY_CLI_VERSION}.tar.gz"
    tar -vzxf axway-apimcli-${AXWAY_CLI_VERSION}.tar.gz
    
    echo "##[command] apim-cli-${AXWAY_CLI_VERSION}/scripts"
    ls -la apim-cli-${AXWAY_CLI_VERSION}/scripts
  displayName: 'Download axway-apimcli $(AXWAY_CLI_VERSION)'
  workingDirectory: $(Agent.TempDirectory)
  env:
    AXWAY_CLI_VERSION: $(AXWAY_CLI_VERSION)
    ADMIN_USERNAME: $(ADMIN_USERNAME)
    ADMIN_PASSWORD: $(ADMIN_PASSWORD)
    PROXY_AGENT_HTTP: $(PROXY_AGENT_HTTP)
    PROXY_AGENT_HTTPS: $(PROXY_AGENT_HTTPS)