parameters:
- name: 'envs'
  type: object
  default: {}


variables:
- ${{ if eq(parameters.envs.HML_GCP_CRED_FILE_B64, 'POC_GCP_CRED_FILE_B64') }}:
  - name: HML_GCP_CRED_FILE_B64
    value:  $(POC_GCP_CRED_FILE_B64)
- name: GCP_CRED_FILE_B64
  value: $(HML_GCP_CRED_FILE_B64)
- name: IMAGE_REGISTRY
  value: ${{ coalesce(parameters.envs.HML_IMAGE_REGISTRY, variables['HML_IMAGE_REGISTRY']) }}
- name: GCP_PROJECT_NAME
  value: ${{ coalesce(parameters.envs.HML_GCP_PROJECT_NAME, variables['HML_GCP_PROJECT_NAME']) }}
- name: ENVIRONMENT
  value: hml
- name: IMAGE_NAME
  value: ${{ coalesce(parameters.envs.HML_IMAGE_NAME, variables['Build.Repository.Name']) }}
- name: DEPLOY_AND_EXECUTE_JOB
  value: ${{ coalesce( parameters.envs.DEPLOY_AND_EXECUTE_JOB, 'false') }}
- name: DEFAULT_CLOUDRUN_JOB_FILE_PATH
  value: gcp/$(ENVIRONMENT)-job.yaml
- name: CLOUDRUN_JOB_FILE_PATH
  value:  ${{ coalesce( parameters.envs.HML_CLOUDRUN_JOB_FILE_PATH, variables['DEFAULT_CLOUDRUN_JOB_FILE_PATH']) }}
- name: DEFAULT_CLOUDRUN_CLI_FILE_PATH
  value: gcp/$(ENVIRONMENT)-cli.yaml
- name: CLOUDRUN_CLI_FILE_PATH
  value:  ${{ coalesce( parameters.envs.HML_CLOUDRUN_CLI_FILE_PATH, variables['DEFAULT_CLOUDRUN_CLI_FILE_PATH']) }}
- name: DEPLOY_SERVICE
  value: ${{ coalesce( parameters.envs.DEPLOY_SERVICE, 'true') }}
- name: DEFAULT_CLOUDRUN_FILE_PATH
  value: gcp/$(ENVIRONMENT).yaml
- name: CLOUDRUN_FILE_PATH
  value:  ${{ coalesce( parameters.envs.HML_CLOUDRUN_FILE_PATH, variables['DEFAULT_CLOUDRUN_FILE_PATH']) }}
# - name: USE_YAML_TO_DEPLOY
#   value: $(USE_YAML_TO_DEPLOY)
# - name: DEPLOY_AND_EXECUTE_JOB
#   value: $(DEPLOY_AND_EXECUTE_JOB)
# - name: CLOUD_RUN_JOB_NAME
#   value: $(HML_CLOUD_RUN_JOB_NAME)
# - name: DEPLOY_CLI_SERVICE
#   value: $(DEPLOY_CLI_SERVICE)
