## -> Parameters:
parameters:
  - name: environment
  - name: skipDeploy
  - name: proxy
  - name: packageVersion
  - name: buildConfiguration
  - name: dotnetVersion
  - name: entrypoint
  - name: kubernetesServiceConnectionEnabled
    default: false

## -> CI
stages:
  ## -> Initialize Enviroment
  - template: /tech_products/hrcl/templates/common/stages/initialize/environment.yml
    parameters:
      packageVersion: ${{ parameters.packageVersion }}

  - stage: prepare
    dependsOn:
    - environment_init
    displayName: "Prepare"
    jobs:
      - job: extract
        displayName: "Preparing Pipeline"
        pool:
          name: GeneralPurposeLinuxAgentsCI
        steps:
        - checkout: self
          persistCredentials: true
          fetchTags: true
          clean: true
        - template: /tech_products/hrcl/templates/dotnet/ci/ci_prepare.yml
          parameters:
            proxy: ${{ parameters.proxy }}

  ## BUILD & TEST WITH SONAR
  - stage: build_package
    displayName: "Build & Test & SQ & Package"
    dependsOn:
      - environment_init
      - prepare
    variables:
    # -> Catalog Info Variables
    - name: CURRENT_VERSION
      value: $[ stageDependencies.prepare.extract.outputs['extract_version_and_sha.CURRENT_VERSION'] ]
    - name: NEXT_VERSION
      value: $[ stageDependencies.prepare.extract.outputs['extract_version_and_sha.NEXT_VERSION'] ]     
    - name: TAG_VERSION
      value: $[ stageDependencies.prepare.extract.outputs['extract_version_and_sha.TAG_VERSION'] ]     
    - name: COMMIT_SHA
      value: $[ stageDependencies.prepare.extract.outputs['extract_version_and_sha.COMMIT_SHA'] ]
    - template: /tech_products/hrcl/templates/common/initialize/variables_catalog_info.yml
    jobs:
      - job: build_and_test
        displayName: "Build & Test & SQ & Package"
        pool:
          name: GeneralPurposeLinuxAgentsCI
        steps:
          - checkout: self
            persistCredentials: true
            fetchTags: true
            clean: true
          - template: /tech_products/hrcl/templates/dotnet/ci/ci_build_test_sonarqube.yml
            parameters:
              nextVersion: $(NEXT_VERSION)
              proxy: ${{ parameters.proxy }}
              buildConfiguration: ${{ parameters.buildConfiguration }}
              entrypoint: ${{ parameters.entrypoint }}
              dotnetVersion: ${{ parameters.dotnetVersion }}
          - template: /tech_products/hrcl/templates/dotnet/ci/ci_package.yml
            parameters:
              nextVersion: $(NEXT_VERSION)
              proxy: ${{ parameters.proxy }}
              buildConfiguration: ${{ parameters.buildConfiguration }}
              entrypoint: ${{ parameters.entrypoint }}
              dotnetVersion: ${{ parameters.dotnetVersion }}
        
  - stage: gov_app_quality_gate
    displayName: "Gov App Gate"
    pool:
      name: GeneralPurposeLinuxAgentsCI
    dependsOn:
      - environment_init
      - prepare
      - build_package
    condition: succeeded()
    ## -> Loads variables from other stages.
    variables:
    - name: NEXT_VERSION
      value: $[ stageDependencies.prepare.extract.outputs['extract_version_and_sha.NEXT_VERSION'] ]
    - template: /tech_products/hrcl/templates/common/initialize/variables_catalog_info.yml
    jobs:
    - job: governance
      displayName: Governance Policies Check
      condition: succeeded()
      steps:
      ## -> Validate the application on Governance App
      - template: /tech_products/hrcl/templates/common/gates/gov_app/gov_app.yml
        parameters:
          environment: "${{ parameters.environment }}"
          operation: "validate"
          version: "$(NEXT_VERSION)"

#QUALITY GATE - SECURITY
  - template: /tech_products/hrcl/templates/common/stages/security/security.yml
    parameters:
      fortifyExclusionRepository: FortifyExclusion

  - stage: bump
    dependsOn:
      - prepare
      - security_quality_gate
      - gov_app_quality_gate
    displayName: "Bumping Version"
    variables:
      # -> Catalog Info Variables
      - template: /tech_products/hrcl/templates/common/initialize/variables_catalog_info.yml
      # -> variables are automatically exported as environment variables so this will override pip's default cache dir
      - name: pip_cache_dir
        value: $(Pipeline.Workspace)/.pip
    jobs:
      - job: PushTag
        displayName: "Bump & Push Tag Version"
        pool:
          name: GeneralPurposeLinuxAgentsCI
        steps:
          - checkout: self
            persistCredentials: true
            fetchTags: true
          - template: /tech_products/hrcl/templates/dotnet/ci/ci_bump.yml

    ## -> CD
  - ${{ if ne(parameters.skipDeploy, True) }}:
    - stage: Deploy
      dependsOn:
        - prepare
        - environment_init
        - bump
      pool:
        name: GeneralPurposeLinuxAgentsCD
      variables:
      - template: /tech_products/hrcl/templates/common/initialize/variables_catalog_info.yml
      - template: /tech_products/hrcl/templates/common/initialize/variables_helm.yml
      - name: NEXT_VERSION
        value: $[ stageDependencies.prepare.extract.outputs['extract_version_and_sha.NEXT_VERSION'] ]     
      jobs:
      - deployment: deploy_${{ parameters.environment }}
        displayName: 'Deploy'
        environment: deploy-${{ parameters.environment }}
        strategy:
          runOnce:
            deploy:
              steps:
              - template: /tech_products/hrcl/templates/common/initialize/deploy_environment.yml
                parameters:
                  environment: "${{ parameters.environment }}"
              ## -> Use HELM to deploy
              - template: /tech_products/hrcl/templates/common/cd/cd_deploy.yml
                parameters:
                  environment: "${{ parameters.environment }}"
                  packageVersion: $(NEXT_VERSION)
                  kubernetesServiceConnectionEnabled: ${{ parameters.kubernetesServiceConnectionEnabled }}

            on:
              success:
                steps:
                  ## -> Notifies 'Success on Deploy' on Governance App
                  - task: Bash@3
                    displayName: 'Get Namespace'
                    name: get_namespace
                    condition: succeeded()
                    continueOnError: false
                    inputs:
                      targetType: inline
                      script: |
                        selected_var=$(echo "K8S_NAMESPACE_${{ parameters.environment }}" |  tr 'a-z' 'A-Z')
                        NAMESPACE=${!selected_var}

                        if [ -z "$NAMESPACE" ] && [ ! -z "$(K8S_NAMESPACE)" ]; then
                          NAMESPACE=$(K8S_NAMESPACE)
                        fi
                        echo "##[debug] K8S_NAMESPACE: $NAMESPACE"
                        echo "##vso[task.setvariable variable=K8S_NAMESPACE]$NAMESPACE"

                  - script: |
                      set -e
                  
                      echo "##[debug] APP_NAME....................: ${APP_NAME}"
                      echo "##[debug] VERSION.....................: ${VERSION}"
                      echo "##[debug] ENVIRONMENT.................: ${ENVIRONMENT}"
                      echo "##[debug] CLUSTER.....................: ${CLUSTER}"
                      echo "##[debug] K8S_NAMESPACE...............: ${K8S_NAMESPACE}"
                      echo "##[debug] CATALOG_INFO_FILE_CONTENT...: ${CATALOG_INFO_FILE_CONTENT}"
                    displayName: Governance Data
                    env:
                      APP_NAME: $(APP_NAME)
                      VERSION: $(NEXT_VERSION)
                      ENVIRONMENT: ${{ parameters.environment }}
                      CLUSTER: $(GOV_APP_ACRONYM)-${{ parameters.environment }}
                      K8S_NAMESPACE: $(K8S_NAMESPACE)
                      CATALOG_INFO_FILE_CONTENT: $(CATALOG_INFO_FILE_CONTENT)

                  - task: VivoGovernance@1
                    inputs:
                      breakglass: false
                      serverEndpoint: 'governanceapi'
                      operation: deploy
                      component: $(APP_NAME)
                      version: $(NEXT_VERSION)
                      cluster: $(GOV_APP_ACRONYM)-${{ parameters.environment }}
                      namespace: $(K8S_NAMESPACE)
                      deployment: $(APP_NAME)
                      environment: ${{ parameters.environment }}
                      catalogInfo: $(CATALOG_INFO_FILE_CONTENT)
                    displayName: GovApp - deploy
                    continueOnError: true # devido falhas de timeout e redes mantem a entrega com warning
                    name: gov_app_integration
              failure:
                steps:
                - task: CatchLogsToLocalDirectoryFromVivo@4
                  displayName: Dump logs and metas
                  inputs:
                    dumpDir: $(Build.ArtifactStagingDirectory)/audit
                - task: PublishBuildArtifacts@1
                  displayName: 'Push Logs to Artifacts'
                  inputs:
                    ArtifactName: audit
                    PathtoPublish: $(Build.ArtifactStagingDirectory)/audit
