stages:
- stage: dip_report
  displayName: "Report"
  dependsOn:
    - dip_initial_validations
    - pipeline_init
    - build_test
    - gate
  variables:
    commitMsg: $[ stageDependencies.dip_initial_validations.validate_pipeline.outputs['CommitValidationTask.effectiveCommitMessage'] ]
    taskId: $[ stageDependencies.gate.sonarqube.outputs['sonar_task_id.SONAR_TASK_ID'] ]
  pool: $(PRIVATE_AGENT_DEFAULT)
  jobs:
  - job: run_report_callout
    displayName: 'Run Report'
    steps:
      - task: Bash@3
        displayName: 'Send Report'
        inputs:
          targetType: 'inline'
          script: 'curl --request POST --url https://commondomain-dev.api.redecorp.br/devops-tools/pipeline-snitch/v1/api/build -m 30 --header "content-type: application/x-www-form-urlencoded" --data buildId=$(Build.BuildId) --data taskId=$(taskId) --data "message=$(commitMsg)"'