steps:
- task: InvokeRESTAPI@1
  displayName: "Invoke REST API"
  inputs: 
    connectionType: 'connectedServiceName'
    serviceConnection: 'AzureDevopsAPIs'
    method: 'PATCH'
    headers: |
      {
        "Content-Type":"application/json",
        "Authorization": "Bearer $(System.AccessToken)"
      }
    body: |
      {
        "lastMergeSourceCommit": {
          "commitId": "a17dd4756936c50c1bbfc320f3460b88a3895351"
        },
        "completionOptions": {
          "deleteSourceBranch": false
        },
        "status": "completed"
      }
    urlSuffix: '/telefonica-vivo-brasil/edd19f42-eb02-4012-baa0-54e17a5ed414/_apis/git/repositories/4d4085d8-69bc-4455-abcf-724b9bc5dfa7/pullrequests/52494?api-version=7.1'
    waitForCompletion: 'false'