steps:
  - checkout: self
    submodules: true
    persistCredentials: true
    clean: false
    fetchDepth: 0
  
  - task: Bash@3
    displayName: 'Tagging SOA Composite'
    condition: and(succeeded(), in(variables['PROJECT_TYPE'], 'COMPOSITE'))
    inputs:
      targetType: 'inline'
      script: |
        git tag -a SOA-$(System.PullRequest.PullRequestId) -m "$(Build.SourceVersionMessage)"
        git push --tags

  - task: Bash@3
    displayName: 'Tagging SOA MDS'
    condition: and(succeeded(), in(variables['PROJECT_TYPE'], 'METADATA_STORE'))
    inputs:
      targetType: 'inline'
      script: |
        git tag -a MDS-$(System.PullRequest.PullRequestId) -m "$(Build.SourceVersionMessage)"
        git push --tags