parameters:
- name: environment
- name: resourceAddress
- name: resourceId
- name: setupGitConfigSSH

stages:
- stage: stage_import
  pool: $(PRIVATE_AGENT_SHARED)
  displayName: 'IMPORT -> ${{ parameters.environment }}'
  dependsOn: []
  jobs:
  - job: job_import
    displayName: 'IMPORT -> ${{ parameters.environment }}'
    steps:
    - checkout: self
    - template: /tech_products/tpaz/tasks/terraform/install.yml
    - template: /tech_products/tpaz/tasks/terraform/azure/init.yml
      parameters:
        setupGitConfigSSH: ${{ parameters.setupGitConfigSSH }}
    - template: /tech_products/tpaz/tasks/terraform/azure/import.yml
      parameters:
        commandOptions: "-var-file=$(tfvarsLocation) "
        resourceAddress: ${{ parameters.resourceAddress }}
        resourceId: ${{ parameters.resourceId }}