parameters:
- name: environment
- name: isDestroy
- name: action
- name: varFileSecureFileEnabled
- name: setupGitConfigSSH
- name: requiresManualApproval
  type: boolean
  default: 'false'


stages:
- stage: stage_plan
  pool: $(PRIVATE_AGENT_SHARED)
  displayName: 'PLAN -> ${{ parameters.environment }}'
  dependsOn: []
  jobs:
  - job: job_plan
    displayName: 'PLAN -> ${{ parameters.environment }}'
    steps:
    - checkout: self
    - template: /tech_products/tpaz/tasks/bash/welcome.yml
    - template: /tech_products/tpaz/tasks/terraform/install.yml
    - template: /tech_products/tpaz/tasks/terraform/azure/init.yml
      parameters:
        setupGitConfigSSH: ${{ parameters.setupGitConfigSSH }}
    - template: /tech_products/tpaz/tasks/artifacts/download_secure_files.yml
      parameters:
        name: tfvarsSecureFile
        secureFile: "$(Build.DefinitionName)-${{ lower(parameters.environment) }}.tfvars.json"
        enabled: ${{ parameters.varFileSecureFileEnabled }}
    - template: /tech_products/tpaz/tasks/terraform/azure/validate.yml

    - ${{ if eq(parameters.isDestroy, true) }}:
      - template: /tech_products/tpaz/tasks/terraform/azure/plan.yml
        parameters:
          ${{ if eq(parameters.varFileSecureFileEnabled, true) }}:
            commandOptions: "-var-file=$(tfvarsSecureFile.secureFilePath) -var-file=$(tfvarsLocation) -destroy"
          ${{ else }}:
            commandOptions: "-var-file=$(tfvarsLocation) -destroy"

    - ${{ else }}:
      - template: /tech_products/tpaz/tasks/terraform/azure/plan.yml
        parameters:
          ${{ if eq(parameters.varFileSecureFileEnabled, true) }}:
            commandOptions: "-var-file=$(tfvarsSecureFile.secureFilePath) -var-file=$(tfvarsLocation)"
          ${{ else }}:
            commandOptions: "-var-file=$(tfvarsLocation)"

      - template: /tech_products/tpaz/tasks/terraform/azure/show.yml
      - template: /tech_products/tpaz/tasks/infracost/breakdown.yml
      - template: /tech_products/tpaz/tasks/checkov/analysis.yml
      - template: /tech_products/tpaz/tasks/tfsec/analysis.yml
      - template: /tech_products/tpaz/tasks/tests/publish_tests_result.yml
        parameters:
          mergeTestResults: false

     # Adicionando a verificação de "ADD e DESTROY" juntos no tfplan.json

    - script: |
        set -e
        echo "Verificando se há recursos para destroy"

        # Extrai os tipos de ações do plano Terraform
        CREATE_COUNT=$(jq '[.resource_changes[] | select(.change.actions[] == "create")] | length' tfplan.json)
        DESTROY_COUNT=$(jq '[.resource_changes[] | select(.change.actions[] == "delete")] | length' tfplan.json)

        echo "Recursos a adicionar: $CREATE_COUNT"
        echo "Recursos a destruir: $DESTROY_COUNT"

        # Se houver pelo menos um add e um destroy ao mesmo tempo, barramos a execução
        if [ "$CREATE_COUNT" -gt 0 ] && [ "$DESTROY_COUNT" -gt 0 ]; then
          echo "Aviso: O plano detectou que há recursos sendo destruídos e recriados ao mesmo tempo."
          echo "Definindo variável de controle para aprovação manual..."
          echo "##vso[task.setvariable variable=requiresManualApproval;isOutput=true]true"  # Define a variável de controle
        else
          echo "##vso[task.setvariable variable=requiresManualApproval;isOutput=true]false"
          echo "Não há conflitos de ADD e DESTROY."
        fi
      displayName: 'Verificando se há recursos para destroy'
      name: setRequiresApproval   
      workingDirectory: $(Build.SourcesDirectory)
      #condition: eq('${{ parameters.isDestroy }}', false)
      condition: and(eq('${{ parameters.isDestroy }}', false), eq('${{ parameters.action }}', 'apply'))


   # Aprovação manual somente se a variável requiresManualApproval for verdadeira
  - job: waitForValidation 
    displayName: Aprovação Manual para destroy
    pool: server
    timeoutInMinutes: 4320
    dependsOn: job_plan 
    #condition: and(succeeded(), eq('${{ parameters.isDestroy }}', false))
    condition: and(succeeded(), eq('${{ parameters.isDestroy }}', false), eq('${{ parameters.action }}', 'apply'))
    variables:
      requiresManualApproval: $[ dependencies.job_plan.outputs['setRequiresApproval.requiresManualApproval'] ]
    steps:
    - task: ManualValidation@1
      condition: eq(variables['requiresManualApproval'], 'true') 
      inputs:
        instructions: |
          O plano detectou recursos sendo destruídos e recriados ao mesmo tempo. 
          Por favor, aprove ou negue a execução dessa mudança.
          Caso não deseje permitir a destruição e recriação dos recursos, recuse a execução.
        onTimeout: 'reject'