parameters:
- name: commandOptions
  default: ''

steps:
- task: TerraformTaskV4@4
  displayName: 'Terraform VALIDATE'
  inputs:
    command: validate
    commandOptions: ${{ parameters.commandOptions }}
    environmentServiceNameAzureRM: $(TF_PROVIDER_SERVICE_CONNECTION)
    workingDirectory: $(Build.SourcesDirectory)