parameters:
- name: branchName
  type: string

stages:
- stage: build_test_frontend
  dependsOn: pipeline_pre_init
  displayName: "Build local (Frontend)"
  condition: succeeded()
  pool:
    name: $(PRIVATE_AGENT_DEFAULT)
  variables:
    - group: lojaonline-sap-commerce-js-store-front-ng-dev
  jobs:
  - job: build_test_coverage_frontend
    workspace:
      clean: all
    displayName: Build
    condition: succeeded()
    steps:
    - checkout: JsStoreFront
      clean: true
      fetchDepth: 1
      fetchTags: false
      persistCredentials: true

    - bash: |
        echo "##[section]Stage para preparação do build do JsStoreFront"
        git fetch --no-tags origin "$BRANCH_NAME:$BRANCH_NAME" -f --depth 1
        git checkout "$BRANCH_NAME"
        git log
      displayName: "Reset branch JsStoreFront to ${{parameters.branchName }} (DEV)"
      env:
        BRANCH_NAME: "${{parameters.branchName}}"

    - template: /tech_products/ecmc/sap-commerce/task_groups/build/nodejs_build_test.yaml
      parameters:
        sourceFolder: $(Build.SourcesDirectory)/$(FOLDER_BASE_SRC)
        isDevelopment: True


