parameters:
- name: displayName

- name: tagName

steps:
- bash: |
    echo "##vso[build.addbuildtag]${TAG_NAME}"

  displayName: ${{ parameters.displayName }}
  env:
    TAG_NAME: ${{ parameters.tagName }}