parameters:
- name: skipSecurityGate
  default: false

steps:
- bash: |
    echo "SKIP_SECURITY_GATE: ${SKIP_SECURITY_GATE}"
    if [[ ! "${SKIP_SECURITY_GATE}" =~ ^(T|t)rue$ ]]; then
      echo "##vso[task.logissue type=error;]O Security Gate falhou pois foram encontradas potenciais vulnerabilidades críticas e altas por nossas ferramentas de segurança em código fonte para este projeto. Para mais informações, acesse a wiki do time de AppSec da Vivo em https://wikicorp.telefonica.com.br/pages/viewpage.action?pageId=524036659"
      echo "##vso[task.complete result=Failed;]"
      exit
    fi
    echo "##[warning]O Security Gate NÃO está habilitado para este projeto, entretanto, foram identificadas vulnerabilidades de alta criticidade em seu código fonte. Antes de seguir com este código para outros ambientes, consulte em O Security Gate não está habilitado para este projeto e podem existir alguns motivos para isso... Este projeto ainda não foi tombado pelo time de AppSec ou se trata de um ativo de testes. No entanto, foram identificadas vulnerabilidades críticas e altas no step anterior e recomendamos que estas vulnerabilidades sejam analisadas e a estratégia de correção das mesmas sejam avaliadas. Para mais informações, acesse a wiki do time de AppSec da Vivo em https://wikicorp.telefonica.com.br/pages/viewpage.action?pageId=524036659 para verificar como solicitar acesso as informações dessas descobertas para as respectivas tratativas. É responsabilidade de todos o mantimento de código fonte seguro no ambiente, faça sua parte."
  displayName: Gate Validation
  condition: in(variables['Agent.JobStatus'], 'SucceededWithIssues')
  env:
    SKIP_SECURITY_GATE: ${{ parameters.skipSecurityGate }}
