variables:
- template: /global/variables/pipeline.yml

- name: PRIVATE_AGENT_POOL
  value: GeneralPurposeLinuxAgentsCI

- name: HELM_VERSION
  value: latest

- name: CORPORATE_WIKI_DOC_URL
  value: "https://wikicorp.telefonica.com.br/display/AC/Modelo+Helm"

- name: DEFAULT_WORKDIR_ARTIFACTS
  value: $(Build.SourcesDirectory)

- name: DEFAULT_WORKDIR_DOCKER_ARTIFACTS
  value: "$(System.ArtifactsDirectory)/docker"