parameters:
  - name: dependsOn
    type: object
    default: []

stages:
  - stage: project_validations
    displayName: "Release Manager Validation"
    dependsOn: ${{ parameters.dependsOn }}
    jobs:
      - job: validate_release_manager
        displayName: "Validate Release Manager"
        pool: GeneralPurposeLinuxAgentsCI
        workspace:
          clean: outputs
        steps:
          - checkout: self
            clean: false
            persistCredentials: true
            
          - template: /tech_products/ecmc/core-pipelines/tasks/validations/validate_release_manager.yaml
            parameters:
              condition: and(
                succeeded(),
                eq(variables.VALIDATE_RELEASE_MANAGER, 'true'),
                ne(variables.flowIsMain, True)
                )