parameters:
- name: adobeBranch
  type: string
  default: ''
- name: gitPushParameter
  type: string
  default: ''
- name: dependsOn
  type: object
  default:
  - gate_java
  - gate_node
  - security

stages:
- stage: sync
  displayName: Sync
  isSkippable: false
  dependsOn: ${{ parameters.dependsOn }}
  pool: $(PRIVATE_AGENT_DEFAULT)
  condition: not(or(failed(), canceled()))
  jobs:
  - job: push_adobe
    workspace:
      clean: resources
    displayName: Push to Adobe Cloud
    steps:

    - template: /tech_products/ecmc/adbb-aem/global/general/set-output-variable.yml
      parameters:
        variable: SOURCE_BRANCH
        command: $(branchRef=$(Build.SourceBranch);echo ${branchRef#refs/heads/})

    - template: /tech_products/ecmc/core-pipelines/tasks/git/push_remote.yml
      parameters:
        sourceBranch: "${SOURCE_BRANCH}"
        targetRemoteUrl: "$(adobe_remote_url)"
        targetBranch: "${{parameters.adobeBranch}}"
        targetName: "Adobe"
        gitPushParameter: "${{parameters.gitPushParameter}}"
