parameters:
- name: target
  values:
  - 'apk'
  - 'ios'
  - 'both'
  default: both

stages:
- stage: build_test
  displayName: "Build & Test"
  dependsOn:
    - pipeline_init
  jobs:
  - job: build_app_android
    displayName: Build & Test & Coverage (Android)
    condition: ${{ in(parameters.target, 'apk', 'both') }}
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - template: /task_groups/build/flutter_build_test.yml
  - job: build_app_ios
    displayName: Build & Test & Coverage (iOS)
    condition: ${{ in(parameters.target, 'ios', 'both') }}
    pool:
      vmImage: 'macOS-latest'
    steps:
    - template: /task_groups/build/flutter_build_test.yml