parameters:
- name: environment
  default: dev

- name: appSlugAndroid
  type: string

- name: appSlugIOS
  type: string

- name: releaseNotesInput
  default: 'New release'

- name: target
  values:
  - 'apk'
  - 'ios'
  - 'both'
  default: both


- name: iosAppIdentifier
  type: string
  default: ''

- name: iosAppSpecificId
  type: string
  default: ''

- name: iosDeployment
  values:
  - 'appcenter'
  - 'testflight'
  - 'both'

stages:
- stage: deploy
  displayName: "Deploy ${{ parameters.environment }}"
  pool: $(PRIVATE_AGENT_DEFAULT)
  dependsOn:
  - package
  jobs:
  - deployment: ${{ parameters.environment }}_apk
    condition: and(always(), eq(variables.flowIsTagging, false), eq(variables.flowIsMain, true), in('${{ parameters.target }}', 'apk', 'both'))
    workspace:
      clean: all
    displayName: Deploy AppCenter (Android)
    environment: "deploy-${{ parameters.environment }}"
    strategy:
      runOnce:      
        deploy:
          steps:
          - download: none
          - template: /task_groups/deploy/app_center_distribute.yml
            parameters:
              appSlugAndroid: ${{ parameters.appSlugAndroid }}
              releaseNotesInput: ${{ parameters.releaseNotesInput }}
              target: 'apk'

  - deployment: ${{ parameters.environment }}_ios_appcenter
    condition: and(always(), eq(variables.flowIsTagging, false), eq(variables.flowIsMain, true), in('${{ parameters.target }}', 'ios', 'both'), in('${{ parameters.iosDeployment }}', 'appcenter', 'both'))
    workspace:
      clean: all
    displayName: Deploy AppCenter (iOS)
    environment: "deploy-${{ parameters.environment }}"
    strategy:
      runOnce:      
        deploy:
          steps:
          - download: none
          - template: /task_groups/deploy/app_center_distribute.yml
            parameters:
              appSlugIOS: ${{ parameters.appSlugIOS }}
              releaseNotesInput: ${{ parameters.releaseNotesInput }}
              target: 'ios'

  - deployment: ${{ parameters.environment }}_ios_testflight
    condition: and(always(), eq(variables.flowIsTagging, false), eq(variables.flowIsMain, true), in('${{ parameters.target }}', 'ios', 'both'), in('${{ parameters.iosDeployment }}', 'testflight', 'both'))
    workspace:
      clean: all
    displayName: Deploy TestFlight (iOS)
    environment: "deploy-${{ parameters.environment }}"
    pool:
      vmImage: 'macOS-latest'
    variables:
      IOS_TESTFLIGHT_API_KEY_ID: $[ stageDependencies.package.akv_secrets.outputs['export_secrets.IOS_TESTFLIGHT_API_KEY_ID'] ]
      IOS_TESTFLIGHT_API_ISSUER: $[ stageDependencies.package.akv_secrets.outputs['export_secrets.IOS_TESTFLIGHT_API_ISSUER'] ]
      IOS_TESTFLIGHT_API_TOKEN: $[ stageDependencies.package.akv_secrets.outputs['export_secrets.IOS_TESTFLIGHT_API_TOKEN'] ]
    strategy:
      runOnce:      
        deploy:
          steps:
          - download: none
          - template: /task_groups/deploy/testflight_distribute.yml
            parameters:
              appIdentifier: ${{ parameters.iosAppIdentifier }}
              appSpecificId: ${{ parameters.iosAppSpecificId }}