parameters:
- name: target
  values:
  - 'apk'
  - 'ios'
  - 'both'
  default: both

- name: iosProvProfileSecureFile
  type: string
  default: ''

stages:
- stage: package
  dependsOn:
  - build_test
  - security
  - gate
  displayName: "Package & Publish"
  pool: $(PRIVATE_AGENT_DEFAULT)
  jobs:
  - job: akv_secrets
    displayName: Get AKV Secrets
    steps:
    - template: /tasks/flutter/get_secrets.yml
    
  - job: "Package_android"
    dependsOn: akv_secrets
    condition: and(always(), eq(variables.flowIsTagging, false), eq(variables.flowIsMain, true), in('${{ parameters.target }}', 'apk', 'both'))
    displayName: "Package (Android)"
    variables:
      ANDROID_SIGNING_KEY_JKS: $[ dependencies.akv_secrets.outputs['export_secrets.ANDROID_SIGNING_KEY_JKS'] ]
      ANDROID_SIGNING_KEY_PASSWORD: $[ dependencies.akv_secrets.outputs['export_secrets.ANDROID_SIGNING_KEY_PASSWORD'] ]
      ANDROID_SIGNING_STORE_PASSWORD: $[ dependencies.akv_secrets.outputs['export_secrets.ANDROID_SIGNING_STORE_PASSWORD'] ]
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - template: /task_groups/package/flutter_package.yml
      parameters:
        target: 'apk'
  
  - job: "Package_ios"
    dependsOn: akv_secrets
    condition: and(always(), eq(variables.flowIsTagging, false), eq(variables.flowIsMain, true), in('${{ parameters.target }}', 'ios', 'both'))
    displayName: "Package (iOS)"
    variables:
      IOS_P12_CERTIFICATE_KEY: $[ dependencies.akv_secrets.outputs['export_secrets.IOS_P12_CERTIFICATE_KEY'] ]
      IOS_P12_CERTIFICATE_PWD: $[ dependencies.akv_secrets.outputs['export_secrets.IOS_P12_CERTIFICATE_PWD'] ]
    pool:
      vmImage: 'macOS-latest'
    steps:
    - template: /task_groups/package/flutter_package.yml
      parameters:
        target: 'ios'
        iosProvProfileSecureFile: ${{ parameters.iosProvProfileSecureFile }}