parameters:
- name: accessTokenEnabled
  default: true
- name: url
  type: string
  default: 'https://venus.redecorp.br'

steps:
- task: PythonScript@0
  displayName: 'Get Access Token'
  enabled: ${{ parameters.accessTokenEnabled }}
  inputs:
    scriptSource: inline
    script: |
      import requests
      import os
            
      base_url = os.getenv('SENHA_SEGURA_BASE_URL')
      client_id = os.getenv('SENHA_SEGURA_CLIENT_ID')
      client_secret = os.getenv('SENHA_SEGURA_CLIENT_SECRET')

      def oauth2_token():
        url = base_url + '/iso/oauth2/token'
        print('##[command] POST {} - Gerar access_token'.format(url))
        response = requests.post(
          url,
          data = {
            "client_id": client_id,
            "client_secret": client_secret,
            "grant_type": "client_credentials",
            "ttl": "60",
          },
          verify=False
        )
        response_json = response.json()
        return response_json['access_token']

      token = oauth2_token()
      print('##vso[task.setvariable variable=SENHA_SEGURA_ACCESS_TOKEN;isSecret=true]{}'.format(token))
  env:
    SENHA_SEGURA_BASE_URL: ${{ parameters.url }}
    SENHA_SEGURA_CLIENT_ID: ${{ parameters.clientId }}
    SENHA_SEGURA_CLIENT_SECRET: ${{ parameters.clientSecret }}