parameters:
- name: serviceConnectionSuffix
  type: string
  default: "$(subscriptionEnv)"
- name: subscriptionId
  type: string
- name: resourceGroup
  type: string
- name: apimName
  type: string
- name: environment
  type: string
- name: notes
  type: string
  default: "Created On: $(System.TeamProject) - Build Id: $(Build.BuildId)"
- name: apiName
  type: string
- name: apiRevision
  type: string
- name: condition
  type: object
  default: succeeded()

steps:
- task: AzureCLI@2
  displayName: "Set Current Revision - ${{ parameters.apiRevision }}"
  condition: ${{ parameters.condition }}
  inputs:
    azureSubscription: $(serviceConnectionPrefixName)-${{ parameters.serviceConnectionSuffix }}
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      set -euo pipefail

      az account set --subscription "${{ parameters.subscriptionId }}"

      az apim api release create \
        --api-id "${{ parameters.apiName }}-${{ parameters.environment }}" \
        --api-revision "${{ parameters.apiRevision }}" \
        --resource-group "${{ parameters.resourceGroup }}" \
        --service-name "${{ parameters.apimName }}" \
        --notes "${{ parameters.notes }}"

      echo "✅ Current Revision aplicada com sucesso!"