parameters:
- name: serviceConnectionSuffix
  type: string
  default: "$(subscriptionEnv)"
- name: subscriptionId
  type: string
- name: resourceGroup
  type: string
- name: apimName
  type: string
- name: apiDisplayName
  type: string
- name: apiVersionSet
  type: string
- name: environment
  type: string
- name: description
  type: string
  default: "Last Modify On: $(System.TeamProject)"
- name: apiName
  type: string
- name: apiRevision
  type: string
- name: apiVersion
  type: string
- name: apiPath
  type: string
- name: backendUrl
  type: string
- name: specPath
  type: string
- name: specFormat
  type: string
  default: "OpenApiJson"
- name: condition
  type: object
  default: succeeded()

steps:
- task: AzureCLI@2
  displayName: "Import API - ${{ parameters.apiDisplayName }} ${{ parameters.apiVersion }}-${{ parameters.environment }} (${{ parameters.apiRevision }})"
  condition: ${{ parameters.condition }}
  inputs:
    azureSubscription: $(serviceConnectionPrefixName)-${{ parameters.serviceConnectionSuffix }}
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      set -euo pipefail

      az account set --subscription "${{ parameters.subscriptionId }}"

      az apim api import \
        --resource-group "${{ parameters.resourceGroup }}" \
        --service-name "${{ parameters.apimName }}" \
        --api-id "${{ parameters.apiName }}-${{ parameters.environment }}" \
        --protocols https \
        --service-url "${{ parameters.backendUrl }}" \
        --api-revision "${{ parameters.apiRevision }}" \
        --path "${{ parameters.apiPath }}" \
        --display-name "${{ parameters.apiDisplayName }} ${{ parameters.apiVersion }}-${{ parameters.environment }}" \
        --api-version "${{ parameters.apiVersion }}" \
        --api-version-set-id "${{ parameters.apiVersionSet }}-${{ parameters.environment }}" \
        --subscription-required false \
        --specification-format "${{ parameters.specFormat }}" \
        --description "${{ parameters.description }}" \
        --specification-path "${{ parameters.specPath }}"

      echo "✅ API com Revision importada com sucesso!"