#(TO DO)
parameters:
- name: serviceConnectionSuffix
  type: string
  default: "$(subscriptionEnv)"
- name: subscriptionId
  type: string
- name: resourceGroup
  type: string
- name: apimName
  type: string
- name: environment
  type: string
- name: apiName
  type: string
- name: apiRevision
  type: string
- name: condition
  type: object
  default: succeeded()

steps:
- task: AzureCLI@2
  displayName: "Info Revision - ${{ parameters.apiRevision }}"
  condition: ${{ parameters.condition }}
  name: validate_revision
  inputs:
    azureSubscription: $(serviceConnectionPrefixName)-${{ parameters.serviceConnectionSuffix }}
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      set -euo pipefail

      az account set --subscription "${{ parameters.subscriptionId }}"

      echo "##[debug] Verify revision ${{ parameters.apiRevision }} alread exists"
      RESULT_API_REVISION_ISCURRENT=$(az apim api revision list \
        --api-id "${{ parameters.apiName }}-${{ parameters.environment }}" \
        --resource-group "${{ parameters.resourceGroup }}" \
        --service-name "${{ parameters.apimName }}" \
        --query "[?apiRevision=='${{ parameters.apiRevision }}'].isCurrent | [0]")
      
      if [ "$RESULT_API_REVISION_ISCURRENT" = "true" ]; then
        EXISTS_API_REVISION=true
        ISCURRENT_API_REVISION=true
      elif [ "$RESULT_API_REVISION_ISCURRENT" = "false" ]; then
        EXISTS_API_REVISION=true
        ISCURRENT_API_REVISION=false
      else
        EXISTS_API_REVISION=false
        ISCURRENT_API_REVISION=false
      fi

      echo "##vso[task.setvariable variable=EXISTS_API_REVISION;isoutput=true]${EXISTS_API_REVISION}"
      echo "##vso[task.logissue type=warning;] API Revision ${{ parameters.apiRevision }} alread exists: ${EXISTS_API_REVISION}"

      echo "##vso[task.setvariable variable=ISCURRENT_API_REVISION;isoutput=true]${ISCURRENT_API_REVISION}"
      echo "##vso[task.logissue type=warning;] API Revision ${{ parameters.apiRevision }} is current: ${ISCURRENT_API_REVISION}"

      echo "✅ Validation Revision running with success!"