steps:
- task: AzureKeyVault@2  
  displayName: 'Getting AKV credentials'
  timeoutInMinutes: 1
  retryCountOnTaskFailure: 5  
  inputs:    
    azureSubscription: DevOpsSharedResources    
    KeyVaultName: $(AKV_DEVOPS_NAME)
    SecretsFilter: 'HELM-REGISTRY-ACR-USERNAME, HELM-REGISTRY-ACR-PASSWORD'
  condition: and(eq(variables['HELM_REGISTRY_ACR_ENABLED'], 'true'), eq(variables['HELM-REGISTRY-ACR-USERNAME'], ''), eq(variables['HELM-REGISTRY-ACR-PASSWORD'], ''))

- script: |
    source ~/.bashrc
    echo "##[debug] HOST.......: ${HOST}"
    echo "##[debug] USERNAME...: ${USERNAME}"
    echo "##[debug] PASSWORD...: ************"

    helm registry login ${HOST} \
      --username ${USERNAME} \
      --password "${PASSWORD}"
  displayName: Helm registry login
  condition: and(succeeded(), eq(lower(variables['HELM_REGISTRY_ACR_ENABLED']), 'true'))
  env:
    HOST: $(HELM_REGISTRY_ACR_NAME)
    USERNAME: $(HELM-REGISTRY-ACR-USERNAME)
    PASSWORD: $(HELM-REGISTRY-ACR-PASSWORD)