stages:
- stage: repo_validations
  displayName: "Project validations"
  pool: $(PRIVATE_AGENT_DEFAULT)
  jobs:
    - job: "project_validations"
      displayName: "Start validations"
      workspace:
        clean: all
      steps:
        - checkout: CorePipelinesScripts
          persistCredentials: true
          fetchDepth: 1
        - checkout: self
          fetchDepth: 1

        - template: /tech_products/ecmc/core-pipelines/tasks/catalog_info/extract_variables.yml

        - task: PipAuthenticate@1
          displayName: 'Pip Authenticate'
          inputs:
            artifactFeeds: $(AZURE_ARTIFACTS_FEED)
          env:
            http_proxy: $(PROXY_AGENT_HTTP)
            https_proxy: $(PROXY_AGENT_HTTPS)
            no_proxy: $(PROXY_AGENT_NO_PROXY)
          condition: and(
                      succeeded(),
                      or(
                        eq(variables.DEVFLOW_VALIDATE_STANDARDS, true),
                        eq(variables.DEVFLOW_VALIDATE_JIRA_ISSUE, true)
                      ),
                      ne(variables.flowIsMain, true)
                    )

        - bash: |
            echo "##[debug] Instalando requirements.txt"
            cd $(Build.SourcesDirectory)/Vivo.Core.Pipelines.Scripts
            pip install -r requirements.txt
          condition: and(
                      succeeded(),
                      or(
                        eq(variables.DEVFLOW_VALIDATE_STANDARDS, true),
                        eq(variables.DEVFLOW_VALIDATE_JIRA_ISSUE, true)
                      ),
                      ne(variables.flowIsMain, true)
                    )
          displayName: "Install Python packages"

        - bash: |
            echo "##[debug] Skipando validações por ser ambiente de DEV ou a branch é main/master"
            echo "##[debug] Variável DEVELOPMENT_ENVIRONMENT_FLOW está com o valor = false"
          condition: or(ne(variables.DEVELOPMENT_ENVIRONMENT_FLOW, true), ne(variables.flowIsMain, true))
          displayName: "Validate Standards Branches and Variables"

        - bash: |
            echo "##[debug] Etapa de validação de branch e commits"
            echo "##[debug] Essa etapa valida os padrões de commit bem como a nomenclatura de branches"
          condition: and(
                        eq(variables.DEVFLOW_VALIDATE_STANDARDS, true),
                        or(
                          eq(variables.DEVFLOW_VALIDATE_BRANCH, true),
                          eq(variables.DEVFLOW_VALIDATE_COMMIT, true)
                        ),
                        ne(variables.flowIsMain, true)
                    )
          displayName: "Validate Standards Enabled/Disabled"

        - bash: |
            echo "##[debug] Skipando validação de branch e commits"
            echo "##[debug] Variáveis DEVFLOW_VALIDATE_STANDARDS, DEVFLOW_VALIDATE_BRANCH ou DEVFLOW_VALIDATE_COMMIT não estão com valor = true ou a branch é main/master"
          condition: or(
                      ne(variables.DEVFLOW_VALIDATE_STANDARDS, true),
                      ne(variables.DEVFLOW_VALIDATE_BRANCH, true),
                      ne(variables.DEVFLOW_VALIDATE_COMMIT, true),
                      eq(variables.flowIsMain, true)
                    )
          displayName: "Validate Standards Enabled/Disabled"

        - task: AzdoTaskValidateBranchPrCommits@1
          inputs:
            validationType: 'branch'
            patternBranch: "$(DEVFLOW_BRANCH_PATTERN)"
          displayName: "Validate Branch Name"
          condition: and(
                      succeeded(),
                      eq(variables.DEVFLOW_VALIDATE_STANDARDS, true),
                      ne(variables.flowIsMain, true),
                      or(
                        eq(variables.DEVFLOW_VALIDATE_BRANCH, true),
                        eq(variables.DEVFLOW_VALIDATE_COMMIT, true)
                      )
                    )

        - task: AzdoTaskValidateBranchPrCommits@1
          inputs:
            validationType: 'commit'
            pullRequestId: '$(System.PullRequest.PullRequestId)'
            patternCommitMessage: "$(DEVFLOW_COMMIT_PATTERN)"
            topCommits: $(DEVFLOW_VALIDATE_LIMIT_TOP_COMMITS)
          displayName: "Validate Pull Request Commits"
          condition: and(
                      succeeded(),
                      eq(variables.DEVFLOW_VALIDATE_STANDARDS, true),
                      ne(variables.flowIsMain, true),
                      or(
                        eq(variables.DEVFLOW_VALIDATE_BRANCH, true),
                        eq(variables.DEVFLOW_VALIDATE_COMMIT, true)
                      )
                    )

        - bash: |
            echo "##[debug] Etapa de validação de nome do Pull Request"
            echo "##[debug] Essa etapa valida se a nomenclatura do Pull Request está de acordo com o padrão"
          condition: and(
                      eq(variables.DEVFLOW_VALIDATE_PR_TITLE, true),
                      ne(variables.flowIsMain, true)
                    )
          displayName: "Validate Pull Request Name Enabled/Disabled"

        - bash: |
            echo "##[debug] Validação de nome do Pull Request"
            cd $(Build.SourcesDirectory)/$(Build.Repository.Name)
            python $(Build.SourcesDirectory)/Vivo.Core.Pipelines.Scripts/app.py --pull-request-title
            if [[ $? != 0 ]]; then
              exit 1
              echo "[error] Verifique se o nome do Pull Request está de acordo com o padrão definido. Exemplo: [PTIECOM05-1164] feat: implementa nova funcionalidade"
            fi
          condition: and(
                      eq(variables.DEVFLOW_VALIDATE_PR_TITLE, true),
                      ne(variables.flowIsMain, true)
                    )
          env:
            SYSTEM_ACCESSTOKEN: $(System.AccessToken)
            SYSTEM_ACCESSTOKEN_CUSTOM: $(SYSTEM_ACCESSTOKEN_CUSTOM)
          displayName: "Validate Pull Request Name"

        - bash: |
            echo "##[debug] Etapa de validação de issue no Jira"
            echo "##[debug] Essa etapa valida se a issue que foi passada no commit é válida"
          condition: and(
                      eq(variables.DEVFLOW_VALIDATE_JIRA_ISSUE, true),
                      ne(variables.flowIsMain, true)
                    )
          displayName: "Validate Jira Issue Enabled/Disabled"

        - bash: |
            echo "##[debug] Skipando validação de issue no Jira"
            echo "##[debug] Variável DEVFLOW_VALIDATE_JIRA_ISSUE não está com valor = true ou a branch é main/master"
          condition: or(ne(variables.DEVFLOW_VALIDATE_JIRA_ISSUE, true), eq(variables.flowIsMain, true))
          displayName: "Validate Jira Issue Enabled/Disabled"

        - bash: |
            echo "##[debug] Validação de Issue no Jira"
            cd $(Build.SourcesDirectory)/$(Build.Repository.Name)
            python $(Build.SourcesDirectory)/Vivo.Core.Pipelines.Scripts/app.py --jira
            if [[ $? != 0 ]]; then
              exit 1
            fi
          condition: and(
                      succeeded(),
                      eq(variables.DEVFLOW_VALIDATE_JIRA_ISSUE, true),
                      ne(variables.flowIsMain, true)
                    )
          env:
            SYSTEM_ACCESSTOKEN: $(System.AccessToken)
            SYSTEM_ACCESSTOKEN_CUSTOM: $(SYSTEM_ACCESSTOKEN_CUSTOM)
            JIRA_TOKEN: $(JIRA_TOKEN)
          displayName: "Validate Issue Jira"

        - template: /tech_products/ecmc/core-pipelines/tasks/validations/validate_release_manager.yaml
          parameters:
            condition: and(
                        succeeded(),
                        eq(variables.VALIDATE_RELEASE_MANAGER, 'true'),
                        ne(variables.flowIsMain, True)
                      )

        - template: /tech_products/ecmc/core-pipelines/tasks/bash/validate_configmap_for_pullrequest.yml
          parameters:
            namespaces: "$ARGOCD_NAMESPACES"
            display_name: "Verify ConfigMap in Pull Request (homologation)"
            enviroment_type: "homologação"
            conditions: and(succeeded(), eq(variables.CONFIG_MANAGEMENT, true), eq(variables.CONFIG_MANAGEMENT_FOR_PR, true), ne(variables.flowIsMain, true))

        - template: /tech_products/ecmc/core-pipelines/tasks/bash/validate_configmap_for_pullrequest.yml
          parameters:
            namespaces: "$(PRODUCTION_NAMESPACES_PRE_VALIDATE_CONFIGMAP)"
            display_name: "Verify ConfigMap in Pull Request (production)"
            enviroment_type: "produção"
            conditions: and(succeeded(), eq(variables.CONFIG_MANAGEMENT, true), eq(variables.CONFIG_MANAGEMENT_FOR_PR, true), ne(variables.flowIsMain, true))

        - bash: |
            echo "##[debug] Etapa de criação feature flag automática"
            echo "##[debug] Essa etapa cria a feature flag (desabilitada) no Hobknob"
          condition: and(
                      eq(variables.DEVFLOW_VALIDATE_STANDARDS, true),
                      eq(variables.DEVFLOW_VALIDATE_FEATURE_FLAGS_HOBKNOB, true),
                      ne(variables.flowIsMain, true)
                    )
          displayName: "Create Feature Flag automaticaly"

        - bash: |
            echo "##[debug] Skipando criação feature flag automática"
          condition: or(
                      ne(variables.DEVFLOW_VALIDATE_STANDARDS, true),
                      ne(variables.DEVFLOW_VALIDATE_FEATURE_FLAGS_HOBKNOB, true),
                      eq(variables.flowIsMain, true)
                    )
          displayName: "Validate environment to feature flag"

        - bash: |
            echo "##[debug] Criação/verificação de feature flag automática na Api do Hobknob"
            cd $(Build.SourcesDirectory)/$(Build.Repository.Name)
            export WIKI_FILE=wiki-data.html

            python $(Build.SourcesDirectory)/Vivo.Core.Pipelines.Scripts/app.py --feature-flags --wiki-data-file "$WIKI_FILE"
            if [[ $? != 0 ]]; then
              echo "[error] Não foi possível recuperar a descricão do Pull Request ou algum outro erro na verificação de feature flag ocorreu."
              exit 1
            fi
            if [ ! -f $WIKI_FILE ]; then
              echo "[error] Não foi possível recuperar a descricão do Pull Request ou algum outro erro na verificação de feature flag ocorreu."
              exit 1
            fi
          condition: and(
                      succeeded(),
                      eq(variables.DEVFLOW_VALIDATE_STANDARDS, true),
                      eq(variables.DEVFLOW_VALIDATE_FEATURE_FLAGS_HOBKNOB, true),
                      ne(variables.flowIsMain, true)
                    )
          env:
            SYSTEM_ACCESSTOKEN: $(System.AccessToken)
            SYSTEM_ACCESSTOKEN_CUSTOM: $(SYSTEM_ACCESSTOKEN_CUSTOM)
            HOBKNOB_PASSWORD: $(HOBKNOB_PASSWORD)
            HOBKNOB_USER: $(HOBKNOB_USER)
            JKS_PASS: $(JKS_PASS)
          displayName: "Create/check feature flags"

        - bash: |
            echo "##[debug] Etapa de envio dos dados do Pull Request para a api para posterior gravação no Confluence"

            cd $(Build.SourcesDirectory)/$(Build.Repository.Name)
            unset RESPONSE HTTP_STATUS_CODE RESPONSE_BODY

            if [ ! -f wiki-data.html ]; then
              echo "[error] Não foi possível recuperar a descricão do Pull Request ou algum outro erro na verificação de feature flag ocorreu. "
              exit 1
            fi

            DESCRIPTION=$(cat "wiki-data.html")

            BODY=$(jq --null-input \
                        --arg description "$DESCRIPTION" \
                        --argjson  pull_request_id $SYSTEM_PULLREQUEST_PULLREQUESTID \
                        --arg component_name "$APP_NAME" \
                        --arg owner "$SYSTEM_TEAMPROJECT" \
                        '{"description": $description, "merge_request_id": $pull_request_id, "component_name": $component_name, "owner": $owner}')
            RESPONSE=$(curl -s -w "\n%{http_code}" -X POST -H 'Content-Type: application/json'  "$DEVFLOW_API_PRE_WRITE" --data-raw "$BODY" )
            RESPONSE=(${RESPONSE[@]})
            HTTP_STATUS_CODE=${RESPONSE[-1]}
            RESPONSE_BODY=${RESPONSE[@]::${#RESPONSE[@]}-1}

            if [[ "$HTTP_STATUS_CODE" != "201" ]]; then
              echo "[error] Não foi possível gravar os dados na api"
              echo "[error] Código http $HTTP_STATUS_CODE"
              echo "[error] Abaixo está o retorno da api"
              echo "$RESPONSE_BODY"
              exit 1
            fi

            echo "##[debug] Dados do pull request gravados"
            unset RESPONSE HTTP_STATUS_CODE RESPONSE_BODY

          displayName: "Save pull request data"
          condition: and(
                      succeeded(),
                      eq(variables.DEVFLOW_VALIDATE_STANDARDS, true),
                      eq(variables.DEVFLOW_PUBLISH_CONFLUENCE, true),
                      ne(variables.flowIsMain, true)
                    )
