parameters:
- name: incrementLevel
  default: patch

stages:
  - stage: version
    displayName: Extract Version
    dependsOn:
      - pipeline_init
    pool: "$(PRIVATE_AGENT_DEFAULT)"
    jobs:
      - job: bump_version 
        displayName: Extract & Bump Version
        steps:
          - template: /tasks/nodejs/npm_extract_version.yml
            parameters:
              currentVersionVariableOut: LIB_CURRENT_VERSION
          - template: /tasks/versioning/bump_version.yml
            parameters:
              currentVersion: $(export_current_version.LIB_CURRENT_VERSION)
              newVersionVariableOut: LIB_NEW_VERSION
              incrementLevel: ${{ parameters.incrementLevel }}
          - template: /tasks/artifacts/publish_app.yml

