stages:
  - stage: extraction_scripts
    displayName: "Extração azure"
    pool:
      name: TestRunnerAgents
      demands:
      - Agent.Version -equals 3.232.3

    jobs:
      - job: extraction_scripts_repos
        displayName: Extração azure repos
        timeoutInMinutes: 120
        steps:

            - script: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
              displayName: 'Instalar dependências'

            - script: |
                python extracaoAzureRepos.py
              displayName: 'Executar extração Azure Repos'
              env:
                AZURE_TENANT_ID: $(AZURE_TENANT_ID)
                AZURE_CLIENT_ID: $(AZURE_CLIENT_ID)
                AZURE_CLIENT_SECRET: $(AZURE_CLIENT_SECRET)
                MYSQL_USER: $(MYSQL_USER)
                MYSQL_PASSWORD: $(MYSQL_PASSWORD)
            - task: Bash@3 
              displayName: "DEBUG"
              inputs:
                targetType: 'inline'
                script: |
                  echo 'ls Build.SourcesDirectory: ' && ls -lha $(Build.SourcesDirectory)
            - task: Bash@3
              displayName: 'Prepare Build Artifacts (rsync)'
              inputs:
                targetType: inline
                script: |
                  SRC="$(Build.SourcesDirectory)/"
                  DEST="$(Build.ArtifactStagingDirectory)/$(Build.Repository.Name)"

                  echo "Source: $SRC"
                  echo "Destination: $DEST"

                  mkdir -p "$DEST"

                  rsync -av \
                    --exclude=".git" \
                    --exclude="**/.git" \
                    --exclude=".gitignore" \
                    --exclude="**/.gitignore" \
                    --exclude="__pycache__" \
                    --exclude="**/__pycache__" \
                    "$SRC" "$DEST"
            - task: PublishPipelineArtifact@1
              displayName: 'Publicar relatório Excel'
              condition: succeededOrFailed()   # Publica mesmo se o script retornar warning
              inputs:
                targetPath: '$(Build.SourcesDirectory)/Relatorio_Final.xlsx'
                artifact: 'Relatorio_Final'
                publishLocation: 'pipeline'
            - task: Bash@3 
              displayName: "DEBUG"
              inputs:
                targetType: 'inline'
                script: |
                  echo 'ls Build.SourcesDirectory: ' && ls -lha $(Build.SourcesDirectory)
            - task: PublishPipelineArtifact@1
              displayName: 'Publish Build Artifact (code + dist/)'
              condition: succeeded()
              inputs:
                targetPath: '$(Build.ArtifactStagingDirectory)/$(Build.Repository.Name)'
                artifactName: '$(Build.Repository.Name)'
                publishLocation: 'pipeline'
            - task: Bash@3 
              displayName: "DEBUG"
              inputs:
                targetType: 'inline'
                script: |
                  echo 'ls Build.ArtifactStagingDirectory: ' && ls -lha $(Build.ArtifactStagingDirectory)