stages:
  - stage: SecurityAnalysis
    displayName: "Security Analysis"
    pool:
      name: GeneralPurposeLinuxAgentsCI
    jobs:
      - job: AppConfigKeys
        displayName: 'Get App Config Keys'
        timeoutInMinutes: 120
        steps:
        - template: /security/get_appconfig_keys.yml
          parameters:
            azureSubscription: DevOpsSharedResources
            appConfigurationEndpoint: https://appcs-azdevops-shared.azconfig.io
      - job: FortifyScan
        displayName: 'Fortify Scan (SAST)'
        dependsOn:
        - AppConfigKeys
        steps:
        - template: /security/define_appsec_app_version.yml
        
        - template: /security/run_fortify_scan.yml
          parameters:
            fortifyExclusionRepository: FortifyExclusion
            enableFortifyExclusions: true
      - job: SCAScan
        displayName: 'SCA Scan'
        dependsOn: 
        - AppConfigKeys
        timeoutInMinutes: 120
        steps:          
        - template: /security/define_appsec_app_version.yml

        - template: /security/run_sca_scan.yml
          parameters:
           appVersion: "$(FORTIFY_APP_VERSION)"
           buildArtifactName: $(Build.Repository.Name)