parameters:
- name: private_agent_pool
- name: environment
- name: kubeconfig
- name: git_tag
- name: helm_release_name_prefix
- name: skip_deploy
  default: false
- name: useExternalEnv
  type: boolean
  default: False

stages:
- ${{ if ne(parameters.skip_deploy, True) }}:
  - stage: deploy
    dependsOn:
    - validation
    pool: ${{ parameters.private_agent_pool }}
    displayName: "Deploy ${{ parameters.environment }}"
    jobs:
    - deployment: ${{ parameters.environment }}
      condition: and(always(), eq(variables.flowIsTagging, false), eq(variables.flowIsMain, true))
      workspace:
        clean: all
      displayName: Deploy
      environment: "deploy-${{ parameters.environment }}"
      strategy:
        runOnce:      
          deploy:
            steps:
            - template: /tech_products/srus/provisioners/app/trunkbased/java/regression_test/steps/deploy/deploy.yml
              parameters:
                environment: ${{ parameters.environment }}
                kubeconfig: ${{ parameters.kubeconfig }}
                git_tag: ${{ parameters.git_tag }}
                helm_release_name_prefix: ${{ parameters.helm_release_name_prefix }}
                useExternalEnv: ${{ parameters.useExternalEnv }}

          on:
            success:
              steps:
              - template: /tech_products/srus/provisioners/app/trunkbased/java/regression_test/steps/deploy/success.yml
                parameters:
                  environment: ${{ parameters.environment }}
                  kubeconfig: ${{ parameters.kubeconfig }}
                  git_tag: ${{ parameters.git_tag }}
                  helm_release_name_prefix: ${{ parameters.helm_release_name_prefix }}

              - template: /tech_products/srus/task_groups/governance/check_govapp_policies.yml
                parameters:
                  govAppBreakglass: false
                  govAppOperation: "deploy"
                  continueOnError: false
                  environment: ${{ parameters.environment }}
                  stack: "JAVA"
                
            failure:
              steps:
              - template: /tech_products/srus/provisioners/app/trunkbased/java/regression_test/steps/deploy/failure.yml
                parameters:
                  environment: ${{ parameters.environment }}
                  kubeconfig: ${{ parameters.kubeconfig }}
                  git_tag: ${{ parameters.git_tag }}
                  helm_release_name_prefix: ${{ parameters.helm_release_name_prefix }}