parameters:
- name: run_component_test
  type: boolean

stages:
- stage: package
  dependsOn:
  - security
  - gate
  - build_test
  - ${{ if eq(parameters.run_component_test, True)}}:
    - component_test
  displayName: "Package & Publish"
  pool: $(PRIVATE_AGENT_DEFAULT)
  jobs:
  - job: "Package"
    condition: and(always(), eq(variables.flowIsTagging, false), eq(variables.flowIsMain, true))
    displayName: "Package"
    variables:
    - name: SONAR_TASK_ID
      value: $[ stageDependencies.gate.sonarqube.outputs['sonar_task_id.SONAR_TASK_ID'] ]
    - name: APP_VERSION
      value: $[ stageDependencies.build_test.bump_version.outputs['component_bump_version.API_NEW_VERSION'] ]
    - name: USE_DT_DOCKER
      value: $[ stageDependencies.security.app_config_keys.outputs['evaluate_flags.USE_DT_DOCKER'] ]
    - name: USE_CONVISO
      value: $[ stageDependencies.security.app_config_keys.outputs['evaluate_flags.USE_CONVISO'] ]
    - name: SKIP_SECURITY_GATE_SCA
      value: $[ stageDependencies.security.app_config_keys.outputs['evaluate_flags.SKIP_SECURITY_GATE_SCA'] ]
    steps:
    - template: /tech_products/srus/tasks/catalog_info/extract_variables.yml
    - template: /tech_products/srus/task_groups/package/docker_package.yml
    - template: /tech_products/srus/tasks/maven/update_repo_version.yml
      parameters:
        newVersion: "$(APP_VERSION)"
        condition: eq(variables.BUMP_VERSION_ENABLED, true)