parameters:
- name: project_name
  type: string
- name: enable_devflow_validations
  type: boolean
  default: False
- name: qa_branch
  type: boolean
  default: False
- name: s1_branch
  type: boolean
  default: False

variables:
- template: /tech_products/ecmc/sap-commerce/provisioners/gitflow/variables/load.yaml

resources:
  repositories:
    - repository: FortifyExclusion

      name: DevOps/Vivo.Fortify.Exclusions
      type: git
      ref: refs/heads/master
      endpoint: CorePipelines

    - repository: CorePipelines
      name: DevOps/Vivo.Core.Pipelines
      type: git
      ref: refs/tags/v1
      endpoint: CorePipelines

    - repository: CorePipelinesScripts
      name: DevOps/Vivo.Core.Pipelines.Scripts
      type: git
      ref: refs/heads/master
      endpoint: CorePipelines

stages:
  - template: /tech_products/ecmc/sap-commerce/provisioners/gitflow/src-sap-commerce-js-store-front-ng/stages/init.yaml
    parameters:
      qa_branch: ${{ parameters.qa_branch }}
      s1_branch: ${{ parameters.s1_branch }}


  ## VALIDATE PREDEFINED STANDARDS (COMMIT MESSAGES, BRANCH NAME ETC)
  # - ${{ if and(eq(parameters.enable_devflow_validations, True), ne(parameters.qa_branch, True), ne(parameters.s1_branch, True)) }}:
  - ${{ if and(eq(variables['Build.Reason'],'PullRequest'), eq(parameters.enable_devflow_validations, True)) }}:
    - template: /tech_products/ecmc/sap-commerce/provisioners/gitflow/src-sap-commerce-js-store-front-ng/stages/validate_standards_dev_flow.yaml

  - template: /tech_products/ecmc/sap-commerce/provisioners/gitflow/src-sap-commerce-js-store-front-ng/stages/build_test.yaml
    parameters:
      enable_devflow_validations: ${{ parameters.enable_devflow_validations }}

  # QUALITY GATE
  - template: /tech_products/ecmc/sap-commerce/provisioners/gitflow/src-sap-commerce-js-store-front-ng/stages/gates.yaml

  # SECURITY
  - template: /tech_products/ecmc/sap-commerce/provisioners/gitflow/src-sap-commerce-js-store-front-ng/stages/security.yaml
    parameters:
      fortifyExclusionRepository: FortifyExclusion
