parameters:
- name: mavenSettingsLocation
  type: string
  default: $(DEFAULT_MAVEN_SETTINGS)
- name: artifactDir
  type: string
  default: "$(DEFAULT_WORKDIR_ARTIFACTS)"
- name: targetDir
  type: string
  default: "target"
- name: dependsOn
  type: object
  default: [quality_gates, security]

stages:
 - stage: publish_maven
   dependsOn: ${{ parameters.dependsOn }}
   displayName: Publish Maven
   pool: $(PRIVATE_AGENT_DEFAULT)
   jobs:
     - job: maven_publish
       strategy:
         matrix:
           All:
             ARTIFACT_DIR: "${{ parameters.artifactDir }}/all"
             TARGET_DIR: "${{ parameters.targetDir }}"
           App:
             ARTIFACT_DIR: "${{ parameters.artifactDir }}/app"
             TARGET_DIR: "${{ parameters.targetDir }}"
           Bundle:
             ARTIFACT_DIR: "${{ parameters.artifactDir }}/bundle"
             TARGET_DIR: "${{ parameters.targetDir }}"
           Conf:
             ARTIFACT_DIR: "${{ parameters.artifactDir }}/conf"
             TARGET_DIR: "${{ parameters.targetDir }}"
           Content:
             ARTIFACT_DIR: "${{ parameters.artifactDir }}/content"
             TARGET_DIR: "${{ parameters.targetDir }}"
           Firmatokenbundle:
             ARTIFACT_DIR: "${{ parameters.artifactDir }}/firmatokenbundle"
             TARGET_DIR: "${{ parameters.targetDir }}"
           Structure:
             ARTIFACT_DIR: "${{ parameters.artifactDir }}/structure"
             TARGET_DIR: "${{ parameters.targetDir }}"
           Common:
             ARTIFACT_DIR: "${{ parameters.artifactDir }}"
             ARTIFACT_NAME: "pom"
       displayName: Maven Publish
       steps:
         - template: /tasks/artifacts/download_app.yml@CorePipelines
         - template: /tasks/maven/publish_file_to_azure_artifacts.yml@CorePipelines
           parameters:
             artifactDir: $(ARTIFACT_DIR)
             artifactName: ${ARTIFACT_NAME}
             targetDir: ${TARGET_DIR}