parameters:
- name: appSlugAndroid
  type: string
  default: ""
- name: appSlugIOS
  type: string
  default: ""
- name: releaseNotesInput
  default: 'New release'
- name: target
  values:
  - 'apk'
  - 'ios'

steps:
- ${{ if eq(parameters.target, 'apk') }}:
  - template: /tech_products/hrcl/templates/tasks/flutter/deploy_app_center_apk.yml
    parameters:
      appSlugAndroid: ${{ parameters.appSlugAndroid }}
      releaseNotesInput: ${{ parameters.releaseNotesInput }}

- ${{ if eq(parameters.target, 'ios') }}:
  - template: /tech_products/hrcl/templates/tasks/flutter/deploy_app_center_ios.yml
    parameters:
      appSlugIOS: ${{ parameters.appSlugIOS }}
      releaseNotesInput: ${{ parameters.releaseNotesInput }}