parameters:
- name: publish_to_nexus
  type: boolean
  default: True
- name: generate_documentation
  type: boolean
  default: True

stages:
- stage: release
  displayName: "Release Library"
  pool: $(PRIVATE_AGENT_DEFAULT)
  jobs:
  - job: release_preparation
    displayName: "Prepare Release"
    steps:
    - template: /tech_products/ecmc/core-pipelines/tasks/catalog_info/extract_variables.yml
      parameters:
        skipDownload: true
        workingDirectory: $(Build.SourcesDirectory)
    - script: echo "Preparing release for $(Build.SourceBranchName)"
      displayName: "Release Info"

  - ${{ if eq(parameters.publish_to_nexus, True) }}:
    - deployment: release_publish
      condition: succeeded()
      dependsOn:
        - release_preparation
      workspace:
        clean: all     
      environment: "lib-release"
      displayName: "Release to Nexus"
      strategy:
        runOnce:
          deploy:
            steps:
              - template: /tech_products/ecmc/core-pipelines/tasks/catalog_info/extract_variables.yml
                parameters:
                    skipDownload: true
                    workingDirectory: $(Build.SourcesDirectory)
              - template: /tech_products/ecmc/core-pipelines/tasks/maven/custom_settings_setup.yml
                parameters:
                  mavenSettingsLocationOutputVarName: "MAVEN_SETTINGS_LOCATION"
              - template: /tech_products/ecmc/core-pipelines/tasks/maven/publish_to_nexus.yml
                parameters:
                  mavenSettingsLocation: $(MAVEN_SETTINGS_LOCATION)
          on:
            success:
              steps:
                - script: echo "Library released successfully to Nexus"
                  displayName: "Release Success"
                - template: /tech_products/ecmc/core-pipelines/tasks/telemetry/telemetry.yml
            failure:
              steps:
                - script: echo "Failed to release library to Nexus"
                  displayName: "Release Failed"
                - template: /tech_products/ecmc/core-pipelines/tasks/telemetry/telemetry.yml
