parameters:
- name: fortifyExclusionRepository

stages:
- stage: security
  displayName: "Security Analysis"
  dependsOn: gate
  pool: $(PRIVATE_AGENT_DEFAULT)
  jobs:
  - job: app_config_keys
    displayName: "Get AppSec Config Keys"
    steps:
    - template: /tasks/bash/welcome.yml@CorePipelines
    - template: /task_groups/security/get_appconfig_keys.yml@CorePipelines
  
  - job: fortify_scan
    dependsOn: app_config_keys
    variables:
      USE_FORTIFY: $[ dependencies.app_config_keys.outputs['evaluate_flags.USE_FORTIFY'] ]
      USE_CONVISO: $[ dependencies.app_config_keys.outputs['evaluate_flags.USE_CONVISO'] ]
      SKIP_SECURITY_GATE: $[ dependencies.app_config_keys.outputs['evaluate_flags.SKIP_SECURITY_GATE'] ]
    condition: and(
                succeeded(),
                eq(variables.USE_FORTIFY, 'true')
              )
    displayName: "SAST Scan"
    steps:
    - template: /task_groups/security/run_fortify_scan.yml@CorePipelines
      parameters:
        gateCondition: and(
                        succeeded(),
                        ne(variables.SKIP_SECURITY_GATE, 'true')
                      )
        fortifyExclusionRepository: ${{ parameters.fortifyExclusionRepository }}

  - job: sca_scan
    dependsOn: app_config_keys
    variables:
      USE_SCA: $[ dependencies.app_config_keys.outputs['evaluate_flags.USE_SCA'] ]
      SKIP_SECURITY_GATE_SCA: $[ dependencies.app_config_keys.outputs['evaluate_flags.SKIP_SECURITY_GATE_SCA'] ]
    condition: and(
                succeeded(),
                eq(variables.USE_SCA, 'true')
              )
    displayName: "SCA Scan"
    steps:
    - template: /task_groups/security/run_sca_scan.yml@CorePipelines
      parameters:
        gateCondition: and(
                        succeeded(),
                        ne(variables.SKIP_SECURITY_GATE_SCA, 'true')
                      )
