
parameters:
- name: fortifyExclusionRepository
  default: ''

stages:
- template: /tech_products/ecmc/core-pipelines/provisioners/app/trunkbased/nodejs/api_default/stages/security_sast_sca.yml
  parameters:
    fortifyExclusionRepository: FortifyExclusion
    dependsOn:
    - environment_init
    - ci_build
