parameters:
- name: backendApiID
- name: continueOnError
  default: true

steps:
- script: |
    echo "##[debug] API_MANAGER_BASE_URL.....: ${API_MANAGER_BASE_URL}"
    echo "##[debug] BACKEND_API_ID...........: ${BACKEND_API_ID}"

    if [ -z "${BACKEND_API_ID}" ]; then
      echo "##[warning] Unable to delete empty Backend API ID."
      exit
    fi

    echo "##[command] Delete Backend API. DELETE /apirepo/${BACKEND_API_ID}"
    curl -s -I -k --fail -X DELETE "${API_MANAGER_BASE_URL}/apirepo/${BACKEND_API_ID}" \
    --user "${ADMIN_USERNAME}:${ADMIN_PASSWORD}"
  displayName: Delete Backend API
  continueOnError: ${{ parameters.continueOnError }}
  env:
    API_MANAGER_BASE_URL: $(API_MANAGER_BASE_URL)
    ADMIN_USERNAME: $(ADMIN_USERNAME)
    ADMIN_PASSWORD: $(ADMIN_PASSWORD)
    BACKEND_API_ID: ${{ parameters.backendApiID }}