parameters: 
- name: displayName
  default: Multiple Reports Coverage Generator
- name: reportPath
  default: $(Build.SourcesDirectory)/**/*.cobertura.xml
- name: targetdir
  default: $(Build.SourcesDirectory)/CoverageResults

steps: 
- task: reportgenerator@5
  displayName: ${{ parameters.displayName }}
  inputs:
    reports: ${{ parameters.reportPath }}
    targetdir: ${{ parameters.targetdir }}