parameters:
- name: gateway
- name: environments
  type: object

stages:
- stage: stage_package_publish
  pool: $(PRIVATE_AGENT_DEFAULT)
  displayName: Package & Publish
  dependsOn:
  - stage_build
  variables:
    APP_VERSION: $[ stageDependencies.stage_build.job_set_version.outputs['set_version.APP_VERSION'] ]
  jobs:
  - ${{ each environment in parameters.environments }}:
    - job: job_package_publish_${{ environment }}
      displayName: ${{ environment }}
      steps:
      - checkout: self # self or none, none ( no checkount ).
      # Download files from Nexus.
      - template: /tasks/artifacts/download_pipeline.yml
        parameters:
          artifactName: manager
          targetPath: $(Agent.TempDirectory)
      - template: /tasks/nexus/download_files.yml
        parameters:
          repository: integracao-libfiles
          remoteFileLocation:
          - files/jdbc-java/mysql-connector-j-8.0.33.jar
          - files/apigateway/opentelemetry/aspectjweaver-1.9.6.jar
          - files/apigateway/opentelemetry/opentelemetry-apim-agent-2.0.0.jar
          - files/apigateway/opentelemetry/kotlin-stdlib-1.6.20.jar
          - files/apigateway/opentelemetry/okhttp-4.11.0.jar
          - files/apigateway/opentelemetry/okio-jvm-3.2.0.jar
          - files/apigateway/opentelemetry/opentelemetry-api-1.30.1.jar
          - files/apigateway/opentelemetry/opentelemetry-api-events-1.30.1-alpha.jar
          - files/apigateway/opentelemetry/opentelemetry-context-1.30.1.jar
          - files/apigateway/opentelemetry/opentelemetry-exporter-common-1.30.1.jar
          - files/apigateway/opentelemetry/opentelemetry-exporter-logging-1.30.1.jar
          - files/apigateway/opentelemetry/opentelemetry-exporter-otlp-1.30.1.jar
          - files/apigateway/opentelemetry/opentelemetry-exporter-otlp-common-1.30.1.jar
          - files/apigateway/opentelemetry/opentelemetry-exporter-sender-okhttp-1.30.1.jar
          - files/apigateway/opentelemetry/opentelemetry-extension-incubator-1.30.1-alpha.jar
          - files/apigateway/opentelemetry/opentelemetry-sdk-1.30.1.jar
          - files/apigateway/opentelemetry/opentelemetry-sdk-common-1.30.1.jar
          - files/apigateway/opentelemetry/opentelemetry-sdk-extension-autoconfigure-1.30.1.jar
          - files/apigateway/opentelemetry/opentelemetry-sdk-extension-autoconfigure-spi-1.30.1.jar
          - files/apigateway/opentelemetry/opentelemetry-sdk-logs-1.30.1.jar
          - files/apigateway/opentelemetry/opentelemetry-sdk-metrics-1.30.1.jar
          - files/apigateway/opentelemetry/opentelemetry-sdk-trace-1.30.1.jar
          - files/apigateway/opentelemetry/opentelemetry-semconv-1.30.1-alpha.jar
          - files/apigateway/emt-scripts/$(EMT_SCRIPT_VERION)/emt-scripts-$(EMT_SCRIPT_VERION).tar.gz
          - files/apigateway/patchs/apigateway_$(AXWAY_VERSION)_patchs.tar
          localFileLocation: $(Agent.TempDirectory)
      - task: Docker@2
        displayName: Docker login
        inputs:
          containerRegistry: $(DOCKER_REGISTRY_SERVICE_CONNECTION_NAME)
          command: login
      # Prepare Image
      # Move all files temporari folder.
      - script: |
          set +x
  
          echo "##[command] Create emt/apigateway/conf"
          mkdir -p ./emt/apigateway/conf
          cp ${BUILD_SOURCESDIRECTORY}/conf/jvm.xml emt/apigateway/conf
  
          echo "##[command] Create emt/apigateway/groups/emt-group/emt-service/conf"
          mkdir -p ./emt/apigateway/groups/emt-group/emt-service/conf
          cp ${BUILD_SOURCESDIRECTORY}/conf/service.xml emt/apigateway/groups/emt-group/emt-service/conf

          echo "##[command] Create emt/apigateway/webapps/apiportal/vordel/apiportal/app"
          mkdir -p ./emt/apigateway/webapps/apiportal/vordel/apiportal/app
          cp ${BUILD_SOURCESDIRECTORY}/api-manager/app.config emt/apigateway/webapps/apiportal/vordel/apiportal/app
  
          echo "##[command] Create emt/apigateway/ext/lib"
          mkdir -p ./emt/apigateway/ext/lib
          cp mysql-connector-j-8.0.33.jar emt/apigateway/ext/lib
          cp aspectjweaver-1.9.6.jar emt/apigateway/ext/lib
          cp opentelemetry-apim-agent-2.0.0.jar emt/apigateway/ext/lib
          cp kotlin-stdlib-1.6.20.jar emt/apigateway/ext/lib
          cp okhttp-4.11.0.jar emt/apigateway/ext/lib
          cp okio-jvm-3.2.0.jar emt/apigateway/ext/lib
          cp opentelemetry-api-1.30.1.jar emt/apigateway/ext/lib
          cp opentelemetry-api-events-1.30.1-alpha.jar emt/apigateway/ext/lib
          cp opentelemetry-context-1.30.1.jar emt/apigateway/ext/lib
          cp opentelemetry-exporter-common-1.30.1.jar emt/apigateway/ext/lib
          cp opentelemetry-exporter-logging-1.30.1.jar emt/apigateway/ext/lib
          cp opentelemetry-exporter-otlp-1.30.1.jar emt/apigateway/ext/lib
          cp opentelemetry-exporter-otlp-common-1.30.1.jar emt/apigateway/ext/lib
          cp opentelemetry-exporter-sender-okhttp-1.30.1.jar emt/apigateway/ext/lib
          cp opentelemetry-extension-incubator-1.30.1-alpha.jar emt/apigateway/ext/lib
          cp opentelemetry-sdk-1.30.1.jar emt/apigateway/ext/lib
          cp opentelemetry-sdk-common-1.30.1.jar emt/apigateway/ext/lib
          cp opentelemetry-sdk-extension-autoconfigure-1.30.1.jar emt/apigateway/ext/lib
          cp opentelemetry-sdk-extension-autoconfigure-spi-1.30.1.jar emt/apigateway/ext/lib
          cp opentelemetry-sdk-logs-1.30.1.jar emt/apigateway/ext/lib
          cp opentelemetry-sdk-metrics-1.30.1.jar emt/apigateway/ext/lib
          cp opentelemetry-sdk-trace-1.30.1.jar emt/apigateway/ext/lib
          cp opentelemetry-semconv-1.30.1-alpha.jar emt/apigateway/ext/lib

          if [[ "${APPLY_PATCH_ENABLE}" == "true" ]]; then
            echo "##[command] Apply patchs"
            tar -xvf apigateway_${AXWAY_VERSION}_patchs.tar && rm apigateway_${AXWAY_VERSION}_patchs.tar
  
            for patch in APIGateway_${AXWAY_VERSION}_Patch*.tgz; do
              if [ -f "$patch" ]; then
                tar -xzf "$patch" -C emt/apigateway && rm "$patch"
                echo "##[command] Arquivo $patch extraído para emt/apigateway"
              else
                echo "##[command] Nenhum patch .tzg encontrado."
              fi
            done
          
          else
            echo "##[command] Apply patchs disabled"
          fi
  
          echo "##[command] Check files"
          ls -la
          ls -Rla emt/
  
          echo "##[group] Unpack EMT scripts..."
          tar -zxvf emt-scripts-${emt_script_version}.tar.gz && rm emt-scripts-${emt_script_version}.tar.gz
          echo "##[endgroup]"
  
        displayName: Prepare for build
        workingDirectory: $(Agent.TempDirectory)
        env:
          emt_script_version: $(EMT_SCRIPT_VERION)
          AXWAY_VERSION: $(AXWAY_VERSION)
          APPLY_PATCH_ENABLE: $(APPLY_PATCH_ENABLE)
      # Download Librire and Secure ( Certificates ) file.
      # Variable Pass in variable groups on AzureDevops.
      # Values on Hashcorp Vault
      - ${{ each env in split('dev,noprod,prod', ',') }}:
        - script: |
            echo "##[debug] Create pass-${{ env }}.txt"
            echo "${pass}" > pass-${{ env }}.txt
          displayName: 'pass-${{ env }}.txt'
          workingDirectory: $(Agent.TempDirectory)
          env:
            pass: $(images-cert/${{ env }}/pass)
        - task: DownloadSecureFile@1
          name: certFile_${{ env }}
          displayName: 'DefaultDomain-cert-${{ parameters.gateway }}-${{ env }}.pem'
          inputs:
            secureFile: 'DefaultDomain-cert-${{ parameters.gateway }}-${{ env }}.pem'
        - task: DownloadSecureFile@1
          name: keyFile_${{ env }}
          displayName: 'DefaultDomain-key-${{ parameters.gateway }}-${{ env }}.pem'
          inputs:
            secureFile: 'DefaultDomain-key-${{ parameters.gateway }}-${{ env }}.pem'
      # Docker build
      #- ${{ each env in parameters.environments }}: #TODO alterações da feat
      - script: |
          echo "##[debug] ENVIRONMENT...............: ${ENVIRONMENT}"
          echo "##[debug] MERGE_DIR.................: ${MERGE_DIR}"
          echo "##[debug] GROUP_ID..................: ${GROUP_ID}"
          echo "##[debug] DOCKER_IMAGE_OUT..........: ${DOCKER_IMAGE_OUT}"
          echo "##[debug] PARENT_IMAGE_NAME.........: ${PARENT_IMAGE_NAME}"
          echo "##[debug] YAML_FILE.................: ${YAML_FILE}"

          if [[ "${ENVIRONMENT}" == "dev" ]]; then
            PASS_FILE="pass-dev.txt"
            CERT_FILE="DefaultDomain-cert-${GATEWAY_NAME}-dev.pem"
            KEY_FILE="DefaultDomain-key-${GATEWAY_NAME}-dev.pem"
          elif [[ "${ENVIRONMENT}" == "prod" ]]; then
            PASS_FILE="pass-prod.txt"
            CERT_FILE="DefaultDomain-cert-${GATEWAY_NAME}-prod.pem"
            KEY_FILE="DefaultDomain-key-${GATEWAY_NAME}-prod.pem"
          else
            PASS_FILE="pass-noprod.txt"
            CERT_FILE="DefaultDomain-cert-${GATEWAY_NAME}-noprod.pem"
            KEY_FILE="DefaultDomain-key-${GATEWAY_NAME}-noprod.pem"
          fi

          echo "##[debug] PASS_FILE.................: ${PASS_FILE}"
          echo "##[debug] CERT_FILE.................: ${CERT_FILE}"
          echo "##[debug] KEY_FILE..................: ${KEY_FILE}"

          echo "##[command] Copy config files"
          cp -fv $(Build.SourcesDirectory)/env-settings/${ENVIRONMENT}/envSettings.props emt/apigateway/groups/emt-group/emt-service/conf/envSettings.props
          cp -fv $(Build.SourcesDirectory)/conf/${ENVIRONMENT}/instanceRedaction.xml emt/apigateway/groups/emt-group/emt-service/conf/instanceRedaction.xml
          cp -fv $(Build.SourcesDirectory)/conf/${ENVIRONMENT}/customRedaction.xml emt/apigateway/groups/emt-group/emt-service/conf/customRedaction.xml

          echo "##[command] ./build_gw_image.py"
          ./build_gw_image.py \
          --remove-license \
          --domain-key-pass-file=${PASS_FILE} \
          --domain-cert=${CERT_FILE} \
          --domain-key=${KEY_FILE} \
          --yaml=${YAML_FILE} \
          --group-id=${GROUP_ID} \
          --merge-dir=${MERGE_DIR} \
          --parent-image=${PARENT_IMAGE_NAME} \
          --out-image=${DOCKER_IMAGE_OUT}
        displayName: "[${{ environment }}] Docker build"
        workingDirectory: $(Agent.TempDirectory)
        env:
          ENVIRONMENT: ${{ environment }}
          GROUP_ID: $(PREFIX_GROUP_NAME)-${{ environment }}
          MERGE_DIR: $(Agent.TempDirectory)/emt/apigateway
          DOCKER_IMAGE_OUT: $(IMAGE_REGISTRY_API_GATEWAY)/$(IMAGE_NAME)-${{ environment }}:$(APP_VERSION)
          PARENT_IMAGE_NAME: $(PARENT_IMAGE_NAME)
          YAML_FILE: gtw-grp-manager-yaml-${{ environment }}.tar.gz
          GATEWAY_NAME: ${{ parameters.gateway }}

      # Docker Push
      - script: |
          echo "##[debug] DOCKER_IMAGE.......: ${DOCKER_IMAGE}"

          echo "##[command] docker images"
          docker images | grep ${IMAGE_NAME}

          echo "##[command] docker push"
          docker push ${DOCKER_IMAGE}

          if [ $? -ne 0 ]; then
            echo "##[error] Docker push failed. Exiting with error."
            exit 1
          fi
        displayName: "[${{ environment }}] Docker push"
        env:
          DOCKER_IMAGE: $(IMAGE_REGISTRY_API_GATEWAY)/$(IMAGE_NAME)-${{ environment }}:$(APP_VERSION)
          IMAGE_NAME: $(IMAGE_NAME)
      - script: |
          echo "##[command] docker rmi ${DOCKER_IMAGE}"
          docker rmi ${DOCKER_IMAGE}
        displayName: Docker clean up
        condition: always()
        continueOnError: true
        env:
          DOCKER_IMAGE: $(IMAGE_REGISTRY_API_GATEWAY)/$(IMAGE_NAME)-${{ environment }}:$(APP_VERSION)