parameters:
  - name: environment
    displayName: Escolha a esteira em que deseja executar os testes
    type: string
    default: dev
    values:
    - dev
    - preprod
    - darklaunch

  - name: context
    displayName: Escolha o contexto do módulo
    type: string
    default: ms
    values:
    - ms
  
  - name: module
    displayName: Digite o nome do modulo
    type: string
    default: ''


## -> Resources:
resources:
  repositories:
  - repository: CorePipelines
    name: DevOps/Vivo.Core.Pipelines
    type: git
    ref: refs/tags/latest
    endpoint: CorePipelines

## -> Initialize global variables   
variables:
- template: /tech_products/appv/global/initialize/variables-global.yml
- template: /tech_products/appv/global/initialize/variables-nodejs.yml
- template: /tech_products/appv/global/initialize/variables-docker.yml


## -> Override global variables, with variables set in Library/Variable Groups (Pipelines)
## -> Use this to change the variables on runtime
- group: "src.src-framework-brasil-e2e-tests"

# - name: CORPORATE_WIKI_DOC_URL
#   value: "TBD"

stages:

## -> Initialize pipeline enviroment
- template: /tech_products/appv/global/initialize/nodejs-environment.yml




## -> Build for CI - NodeJS
- template: /tech_products/appv/appv_e2e_test/templates/ci/ms/ci_route_orchestrator_e2e_test.yml
  parameters:
    environment: "${{parameters.environment}}"
    context: "${{parameters.context}}"
    module: "${{parameters.module}}"


