## -> Parameters:
parameters:
  - name: environment
    displayName: "Escolha o ambiente para publicar"
    type: string
    default: dev
    values:
      - dev
      - esteira1
      - esteira2
      - preprod
      - prodlike
      - producao
  - name: packageName
    type: string
    default: ""
  - name: packageVersion
    type: string
    default: ""
  - name: deployOnly
    type: boolean
    default: false
  - name: infrastructureType
    type: string
    default: "weblogic"
    values:
      - weblogic


variables:
  ## -> Override global variables, with variables set in Library/Variable Groups (Pipelines)
  ## -> Use this to change the variables on runtime
  - group: "${{ variables['Build.Repository.Name'] }}"
  - template: /tech_products/vv30/externals-packages/initializers/global_initializer.yml

stages:
  ## -> Entrypoint
  - ${{ if eq(parameters.deployOnly, false) }}:
      - template: /tech_products/vv30/externals-packages/pipeline_dvps_external_package_ci_v1.yaml
        parameters:
          environment: "${{ variables.environment }}"
          infrastructureType: "${{ parameters.infrastructureType }}"
          packageName: "${{ parameters.packageName }}"
          packageVersion: "${{ parameters.packageVersion }}"

  - ${{ else }}:
      - template: /tech_products/vv30/externals-packages/pipeline_dvps_external_package_cd_v1.yaml
        parameters:
          environment: "${{ parameters.environment }}"
          infrastructureType: "${{ parameters.infrastructureType }}"
          packageVersion: "${{ parameters.packageVersion }}"
          packageName: "${{ parameters.packageName }}"
