stages:
- stage: extract_version
  displayName: Bump Version
  dependsOn: pipeline_init
  pool: $(PRIVATE_AGENT_DEFAULT)
  jobs:
  - job: bump_version
    displayName: Bumping Version
    steps:
    - template: /tasks/git/checkout_last_commit.yml
      parameters:
        branchName: "$(Build.SourceBranchName)"
    - template: /tasks/nodejs/npm_extract_version.yml
      parameters:
        currentVersionVariableOut: API_CURRENT_VERSION
    - template: /tasks/versioning/bump_version.yml
      parameters:
        currentVersion: $(export_current_version.API_CURRENT_VERSION)
        newVersionVariableOut: API_NEW_VERSION