parameters:
- name: run_component_test
  type: boolean

stages:
- ${{ if eq(parameters.run_component_test, True)}}:
  - stage: component_test
    displayName: "Component Test"
    dependsOn:
      - build_test_bff_and_client
    pool: GeneralPurposeLinuxAgentsCI
    jobs:
    - job: component_test
      timeoutInMinutes: 120
      variables:
        - name: APP_VERSION
          value: $[ stageDependencies.build_test_bff_and_client.bump_version.outputs['component_bump_version.API_NEW_VERSION'] ]
      steps:
      - template: /provisioners/app/trunkbased/nodejs/bff_client_default/steps/component_test/component_test.yml
        parameters:
          run_component_test: "${{parameters.run_component_test}}"
