stages:
- stage: default_initializer_cd
  displayName: "Setup Environment"
  pool:
    name: $(AGENT_POOL_CD)

  jobs:

  - job: environment
    displayName: Set up environment
    steps:
    ## -> Clean the pipeline workspace and checkout the code.
    - checkout: self
      displayName: Checkout Code
      name: checkout_code
      submodules: true
      persistCredentials: true
      path: source_code

    ## -> Checkout the working branch.
    - task: Bash@3
      displayName: Checkout Last Commit
      name: checkout_last_commit
      condition: succeeded()
      continueOnError: false
      inputs:
        workingDirectory: $(Agent.BuildDirectory)/source_code
        targetType: inline
        script: |
          echo "##[debug] Checkout branch '$(Build.SourceBranchName)'"

          git config pull.rebase true
          git fetch -f --depth 1 origin $(Build.SourceBranchName):$(Build.SourceBranchName)
          git checkout -f $(Build.SourceBranchName)

    ## -> Initialize Catalog-Info
    - template: /tech_products/cnte/externals-packages/initializers/catalog-info_initializer.yml
      parameters:
        workingDirectory: $(Agent.BuildDirectory)/source_code