parameters:
  - name: oracleBaseImageUpdate
    type: object

stages:
  - stage: stage_download
    displayName: "Download"
    pool: $(POOL)
    dependsOn:
      - stage_prep
    condition: |
      and(
        ne(variables['ORACLE_IMAGE_LINK'], '-'),
        in(dependencies.stage_prep.result, 'Succeeded', 'SucceededWithIssues')
      )
    variables:
      - name: ARTIFACT
        value: $[ stageDependencies.stage_prep.informations.outputs['task_information.ARTIFACT'] ]
      - name: ARTIFACT_EXTENSION
        value: $[ stageDependencies.stage_prep.informations.outputs['task_information.ARTIFACT_EXTENSION'] ]
      - name: ARTIFACT_NEW_NAME
        value: $[ stageDependencies.stage_prep.informations.outputs['task_information.ARTIFACT_NEW_NAME'] ]
    jobs:
      - job: download
        displayName: "Downloading Image"
        steps:
          - checkout: none

          - task: CmdLine@2
            name: task_download
            displayName: "Downloading"
            inputs:
              script: |
                echo "##[debug] DOWNLOADED COMPACTED IMAGES FOLDER ............................: $DOWNLOADED_COMPACTED_IMAGES_FOLDER"
                echo "##[debug] DOWNLOADED COMPACTED IMAGES FOLDER PATH .......................: $DOWNLOADED_COMPACTED_IMAGES_FOLDER_PATH"
                echo "##[debug] ORACLE IMAGE LINK .............................................: ${ORACLE_IMAGE_LINK}"
                echo "##[debug] ARTIFACT ......................................................: $ARTIFACT"
                echo "##[debug] ARTIFACT EXTENSION ............................................: $ARTIFACT_EXTENSION"
                echo "##[debug] ARTIFACT NEW NAME .............................................: $ARTIFACT_NEW_NAME"
                echo "##[debug] ORACLE SUPPORT USER ...........................................: $ORACLE_SUPPORT_USER"

                # Create a directory to store the downloaded artifact
                echo "##[command]mkdir -p $DOWNLOADED_COMPACTED_IMAGES_FOLDER_PATH"
                mkdir -p $DOWNLOADED_COMPACTED_IMAGES_FOLDER_PATH

                # Print a message indicating the artifact being downloaded and the download link
                printf ">>>>> Downloading the Artifact [$ARTIFACT] through the link: [${ORACLE_IMAGE_LINK}]\n\n"

                # Use wget to download the artifact using the provided link and save it with the specified name and extension
                echo "##[command]wget --http-user="$ORACLE_SUPPORT_USER" --http-password="$(ORACLE_SUPPORT_PASSWORD)" --no-check-certificate "${ORACLE_IMAGE_LINK}" -O "$DOWNLOADED_COMPACTED_IMAGES_FOLDER_PATH/$ARTIFACT_NEW_NAME.$ARTIFACT_EXTENSION""
                wget --http-user="$ORACLE_SUPPORT_USER" --http-password="$(ORACLE_SUPPORT_PASSWORD)" --no-check-certificate "${ORACLE_IMAGE_LINK}" -O "$DOWNLOADED_COMPACTED_IMAGES_FOLDER_PATH/$ARTIFACT_NEW_NAME.$ARTIFACT_EXTENSION"
            env:
              ORACLE_IMAGE_LINK: ${{ parameters.oracleBaseImageUpdate.oracleImageLink }}

          - template: ../../../task_groups/artifact/publish.yml
            parameters:
              artifactName: "$(DOWNLOADED_COMPACTED_IMAGES_FOLDER)"
              targetPath: "$(DOWNLOADED_COMPACTED_IMAGES_FOLDER_PATH)"
