stages:
- stage: stage_finish
  displayName: "Finish"
  pool: $(POOL)
  dependsOn: 
  - stage_prep
  - stage_download
  - stage_process
  - stage_security_analysis
  - stage_publish
  condition: always()
  jobs:
    - job: acr_images
      displayName: "ACR Fnix Images"
      steps: 
      - checkout: none
      - task: CmdLine@2
        displayName: "Get All Images"
        inputs:
          script: |
            echo "##[debug] ACR....................................................................: $(ACR_REGISTRY_NAME)"
            echo "##[debug] ACR USER...............................................................: $ACR_USER"

            # Logs in to the Azure Container Registry (ACR).
            echo "##[command]az acr login --name $(ACR_REGISTRY_NAME) -u $(ACR_USER) -p $(ACR_PASSWORD)"
            az acr login --name $(ACR_REGISTRY_NAME) -u $(ACR_USER) -p $(ACR_PASSWORD)
            touch all_images.txt

            # Retrieves the list of repositories in ACR that start with "fnix/test".
            echo "##[command]az acr repository list -n $(ACR_REGISTRY_NAME) -u $(ACR_USER) -p $(ACR_PASSWORD) --query '[?starts_with(@,'fnix')]' --output tsv"
            repos="$(az acr repository list -n $(ACR_REGISTRY_NAME) -u $(ACR_USER) -p $(ACR_PASSWORD) --query "[?starts_with(@,'fnix')]" --output tsv)"

            # Iterates over the repositories and retrieves the tags for each repository.
            for i in $repos; do
              images="$(az acr repository show-tags -n $(ACR_REGISTRY_NAME) -u $(ACR_USER) -p $(ACR_PASSWORD) --repository $i --output tsv --orderby time_desc)"
              printf "\n========== $i ==========\n" >> all_images.txt;
              for j in $images; do
                echo $i":"$j >> all_images.txt;
              done;
            done;

            # Prints the Oracle images in ACR.
            printf "\n>>>>>>>>>>>>>>>>>>>> Oracle Images in ACR <<<<<<<<<<<<<<<<<<<<\n"
            cat all_images.txt