steps:
  - checkout: self
    persistCredentials: true

  - bash: |
      echo ${FILES_LIST}
      for filename in ${FILES_LIST}; do
        echo $filename
        if echo "$filename" | grep -q "CustomizationFile-E1.xml"; then
          echo "##vso[task.setvariable variable=CUST_FILE_E1]$filename"
          echo "##vso[task.setvariable variable=custE1IsPresent]true"
        elif echo "$filename" | grep -q "CustomizationFile-E2.xml"; then
          echo "##vso[task.setvariable variable=CUST_FILE_E2]$filename"
          echo "##vso[task.setvariable variable=custE2IsPresent]true"
        else
          echo "##vso[task.setvariable variable=CUST_FILE_PREPROD]$filename"
          echo "##vso[task.setvariable variable=custPreProdIsPresent]true"
        fi
      done
    env:
      FILES_LIST: $(FILES_LIST)
     
  - task: NexusUploadMvnFromVivo@5
    displayName: "Upload Customization File E1"
    condition: and(succeeded(), eq(variables.custE1IsPresent, true))
    inputs:
      nexusEndpoint: 'NEXUS-DEVOPS'
      nexusRepoMaven: '$(NEXUS_PUBLISH_REPOSITORY)'
      groupId: '$(NEXUS_PUBLISH_REPOSITORY_GROUP_ID)'
      artifactId: 'customization_file'
      artifactVersion: '$(System.PullRequest.PullRequestId)'
      artifactFile1: $(CUST_FILE_E1)
      artifactExtension1: 'e1.xml'

  - task: NexusUploadMvnFromVivo@5
    displayName: "Upload Customization File E2"
    condition: and(succeeded(), eq(variables.custE2IsPresent, true))
    inputs:
      nexusEndpoint: 'NEXUS-DEVOPS'
      nexusRepoMaven: '$(NEXUS_PUBLISH_REPOSITORY)'
      groupId: '$(NEXUS_PUBLISH_REPOSITORY_GROUP_ID)'
      artifactId: 'customization_file'
      artifactVersion: '$(System.PullRequest.PullRequestId)'
      artifactFile1: $(CUST_FILE_E2)
      artifactExtension1: 'e2.xml'

  - task: NexusUploadMvnFromVivo@5
    displayName: "Upload Customization File PreProd"
    condition: and(succeeded(), eq(variables.custPreProdIsPresent, true))
    inputs:
      nexusEndpoint: 'NEXUS-DEVOPS'
      nexusRepoMaven: '$(NEXUS_PUBLISH_REPOSITORY)'
      groupId: '$(NEXUS_PUBLISH_REPOSITORY_GROUP_ID)'
      artifactId: 'customization_file'
      artifactVersion: '$(System.PullRequest.PullRequestId)'
      artifactFile1: $(CUST_FILE_PREPROD)
      artifactExtension1: 'pre-prod.xml'

  - bash: |
      git tag -a CUST-$(System.PullRequest.PullRequestId) -m "Customization Files"
      git push --tags
    displayName: "Create Tag"
            