steps:
- bash: |
    FILES_LIST=`git diff --name-only origin/$(System.PullRequest.TargetBranchName)..origin/$SOURCE_BRANCH_NAME`
    echo "##[debug] Files: $FILES_LIST"
    contains_element () {
    local filename=$1
    for element in "${@:2}"; do
        if echo "$filename" | grep -q "${element}$"; then
            return 0
        fi
    done
    return 1
    }
    main_function () {
    local fixed_list=("CustomizationFile-E1.xml" "CustomizationFile-E2.xml" "CustomizationFile-PreProd.xml")
    local match_counter=0
    local file_counter=0
    for filename in "$@"; do
        ((file_counter++))
        if contains_element "$filename" "${fixed_list[@]}"; then
            ((match_counter++))
        fi
    done
    echo "##[debug] Total Files: $file_counter"
    echo "##[debug] Total Matches: $match_counter"
    if [ "$file_counter" -eq "$match_counter" ]; then
        TYPE_PR="customization"
    elif [ "$match_counter" -eq 0 ]; then
        TYPE_PR="service"
    else
        echo "##vso[task.complete result=Failed;]"
    fi
    }
    main_function $FILES_LIST
    echo "##[debug] Tipo da PR: $TYPE_PR"
    FILES_LIST=`echo $FILES_LIST | sed ':a;N;$!ba;s/\n/ /g'`
    echo "##vso[task.setvariable variable=TYPE_PR;isOutput=true]$TYPE_PR"
    echo "##vso[task.setvariable variable=FILES_LIST;isOutput=true]$FILES_LIST"
  displayName: "Check PR Type"
  name: check_pr_type