parameters:
- name: jira_id
  displayName: ID da história que deve ser testada
  type: string
- name: test_environment
  displayName: Ambiente onde o teste será executado
  type: string
- name: component_test_id
  displayName: Componente que será testado
  type: string
  default: ""
- name: octane_workspace
  displayName: Workspace onde estão os testes no Octane
  type: string
  default: ""
- name: docker_image
  type: string
  default: selenium
- name: framework
  type: string
  default: JUnit
- name: octane_environment
  type: string
  default: 'PROD'
- name: dependsOn
  type: object
  default: []
- name: extra_env
  displayName: Variáveis de ambiente extras para execução dos testes
  type: object
  default: {}

stages:
  - template: /tech_products/rbqa/test-execution-stage/latest/pipeline_rbqa_testexecution_stage.yml@CodePlay 
    parameters:
      test_environment: ${{ parameters.test_environment }}
      jira_id: ${{ parameters.jira_id }}
      component_test_id: ${{ parameters.component_test_id }}
      octane_workspace: ${{ parameters.octane_workspace }}
      docker_image: ${{ parameters.docker_image }}
      framework: ${{ parameters.framework }}
      dependsOn: ${{ parameters.dependsOn }}
      octane_environment: ${{ parameters.octane_environment }}
      extra_env: ${{ parameters.extra_env }}