# This YAML file defines a build pipeline for building a Docker image.

parameters:
  # The path to the Dockerfile used for building the image.
  - name: dockerfile
  # Additional build arguments passed to the Docker build command.
  - name: buildArgs
  - name: imageRegistry
  - name: imageName
  - name: imageVersion
  # The build context directory for the Docker build command.
  - name: buildContext
  # The path to the output file where the Docker build command output will be saved.
  - name: outputFile

steps:
  # ==================================================================
  # [Compliance] Verifica se o repositório está em conformidade com as políticas de configuração
  # ==================================================================
  - task: VivoDevOpsConfigCompliance@1
    displayName: 'Check DevOps Config Compliance'
    inputs:
      workDir: ${{ parameters.buildContext }}
      policySets: |
        image-definition-files
  - task: CmdLine@2
    name: build_image
    displayName: "Build Application Image"
    inputs:
      script: |
        set -euo pipefail

        # Remove the value of $(ACR_BRM_REPOSITORY) from the IMAGE_TAG variable
        IMAGE_TAG_RAW=$(echo ${IMAGE_TAG} | sed "s|${IMAGE_REGISTRY}||g")
        # Check if IMAGE_TAG_RAW contains a '/' and split it to take only the second part
        if [[ "$IMAGE_TAG_RAW" == *"/"* ]]; then
          IMAGE_TAG_RAW=$(echo "$IMAGE_TAG_RAW" | awk -F'/' '{print $2}')
        fi

        # Print debug information about the build parameters.
        echo "##[debug] DOCKERFILE ..........................: ${DOCKERFILE}"
        echo "##[debug] BUILD_ARGS ..........................: ${BUILD_ARGS}"
        echo "##[debug] IMAGE_REGISTRY ......................: ${IMAGE_REGISTRY}"
        echo "##[debug] IMAGE_TAG ...........................: ${IMAGE_TAG}"
        echo "##[debug] IMAGE_TAG_RAW .......................: ${IMAGE_TAG_RAW}"
        echo "##[debug] BUILD_CONTEXT .......................: ${BUILD_CONTEXT}"
        echo "##[debug] OUTPUT_FILE .........................: ${OUTPUT_FILE}"
        echo "##[debug] DOCKER_BUILDKIT .....................: ${DOCKER_BUILDKIT}"

        # Run the Docker build command and save the output to the specified file.
        echo "##[command]docker build --no-cache -f ${DOCKERFILE} ${BUILD_ARGS} -t ${IMAGE_TAG} ${BUILD_CONTEXT} 2>&1 | tee ${OUTPUT_FILE}"
        docker build --no-cache -f ${DOCKERFILE} ${BUILD_ARGS} -t ${IMAGE_TAG} ${BUILD_CONTEXT} 2>&1 | tee ${OUTPUT_FILE}

        echo "##vso[task.setvariable variable=IMAGE_TAG;isOutput=true]$IMAGE_TAG"
        echo "##vso[task.setvariable variable=IMAGE_NAME;isOutput=true]$IMAGE_TAG_RAW"
    env:
      DOCKERFILE: ${{ parameters.dockerfile }}
      BUILD_ARGS: ${{ parameters.buildArgs }}
      IMAGE_REGISTRY: ${{ parameters.imageRegistry }}
      IMAGE_TAG: ${{ parameters.imageName }}:${{ parameters.imageVersion }}
      IMAGE_NAME: ${{ parameters.imageName }}
      IMAGE_VERSION: ${{ parameters.imageVersion }}
      BUILD_CONTEXT: ${{ parameters.buildContext }}
      OUTPUT_FILE: ${{ parameters.outputFile }}
      DOCKER_BUILDKIT: 1
