parameters:
- name: blue_green
  type: string
  default: 'Não'
  values:
  - 'Não'
  - 'Sim'
- name: build_name
  type: string
  default: ''
- name: database_update_mode
  type: string
  default: NONE
  values:
  - NONE
  - UPDATE
- name: deploy_strategy
  type: string
  default: RECREATE
  values:
  - RECREATE
  - ROLLING_UPDATE
- name: environment_for_deploy
  type: string
  default: d15
  values:
  - p1
  - s1
  - s2
  - s3
  - d1
  - d2
  - d3
  - d4
  - d5
  - d6
  - d7
  - d8
  - d9
  - d10
  - d11
  - d12
  - d13
  - d14
  - d15
- name: is_rollback
  type: boolean
  default: false

variables:
- group: azdo-team-project-variables
- template: /tech_products/ecmc/sap-commerce/global/variables/init.yaml
- group: lojaonline-sap-commerce-cloud

jobs:
- template: /tech_products/ecmc/sap-commerce/provisioners/gitflow/src-sap-commerce-cloud/blue-green/start-deploy.yaml
  parameters:
    blue_green: ${{ parameters.blue_green }}
    build_name: ${{ parameters.build_name }}
    database_update_mode: ${{ parameters.database_update_mode }}
    deploy_strategy: ${{ parameters.deploy_strategy }}
    environment_for_deploy: ${{ parameters.environment_for_deploy }}

- template: /tech_products/ecmc/sap-commerce/provisioners/gitflow/src-sap-commerce-cloud/blue-green/watch-deploy.yaml
  parameters:
    build_name: ${{ parameters.build_name }}
    database_update_mode: ${{ parameters.database_update_mode }}
    deploy_strategy: ${{ parameters.deploy_strategy }}
    environment_for_deploy: ${{ parameters.environment_for_deploy }}

- template: /tech_products/ecmc/sap-commerce/provisioners/gitflow/src-sap-commerce-cloud/blue-green/manual-approve-reject.yaml
  parameters:
    blue_green: ${{ parameters.blue_green }}
    environment_for_deploy: ${{ parameters.environment_for_deploy }}

- template: /tech_products/ecmc/sap-commerce/provisioners/gitflow/src-sap-commerce-cloud/blue-green/start-deploy-after-accept.yaml
  parameters:
    blue_green: ${{ parameters.blue_green }}
    build_name: ${{ parameters.build_name }}
    database_update_mode: ${{ parameters.database_update_mode }}
    deploy_strategy: ${{ parameters.deploy_strategy }}
    environment_for_deploy: ${{ parameters.environment_for_deploy }}

- template: /tech_products/ecmc/sap-commerce/provisioners/gitflow/src-sap-commerce-cloud/blue-green/reject-deploy.yaml
  parameters:
    blue_green: ${{ parameters.blue_green }}
    environment_for_deploy: ${{ parameters.environment_for_deploy }}

- ${{ if ne(parameters.is_rollback, true) }}:
  - template: /tech_products/ecmc/sap-commerce/provisioners/gitflow/src-sap-commerce-cloud/blue-green/create-pr-after-deploy.yaml
    parameters:
      environment_for_deploy: ${{ parameters.environment_for_deploy }}
      targetRepo: src-sap-commerce-cloud

