parameters:
- name: dev_namespace_to_deploy
  type: string
  default: ''
- name: project_name
  type: string
- name: enable_devflow_validations
  type: boolean
  default: False
- name: show_pos_validate
  type: boolean
  default: False
- name: environment_code
  type: string
  values:
  - d1
  - d2
  - d3
  - d4
  - d5
  - d6
  - d7
  - d8
  - d9
  - d10
  - d11
  - d12
- name: database_update_mode
  type: string
  values:
  - NONE
  - UPDATE
- name: deploy_strategy
  type: string
  values:
  - RECREATE
  - ROLLING_UPDATE
- name: branch_backend
  type: string
  default: ''
- name: branch_frontend
  type: string
  default: ''
- name: qa_branch
  type: boolean
  default: False
- name: s1_branch
  type: boolean
  default: False
- name: git_strategy
  type: string
- name: save_backup
  type: boolean
  default: True
- name: isUpgradeSap
  type: boolean
  default: False

variables:
- template: /tech_products/ecmc/sap-commerce/provisioners/${{parameters.git_strategy }}/variables/load.yaml
- name: EXTRACT_TAR_GZ
  value: "true"

resources:
  repositories:
    - repository: FortifyExclusion
      name: DevOps/Vivo.Fortify.Exclusions
      type: git
      ref: refs/heads/master
      endpoint: CorePipelines

    - repository: CorePipelines
      name: DevOps/Vivo.Core.Pipelines
      type: git
      ref: refs/tags/v1
      endpoint: CorePipelines

    - repository: CorePipelinesScripts
      name: DevOps/Vivo.Core.Pipelines.Scripts
      type: git
      ref: refs/heads/master
      endpoint: CorePipelines

    - repository: EcmcPythonScripts
      name: ECMC - Ecomm Cloud B2C/src-devops-scripts
      type: git
      ref: refs/heads/master
      endpoint: CorePipelines

    - repository: CoreCustomize
      name: ECMC - Ecomm Cloud B2C/src-sap-commerce-core-customize-java
      type: git
      ref: refs/heads/master

    - repository: JsStoreFront
      name: ECMC - Ecomm Cloud B2C/src-sap-commerce-js-store-front-ng
      type: git
      ref: refs/heads/master

stages:
- template: /tech_products/ecmc/sap-commerce/provisioners/gitflow/src-sap-commerce-cloud/stages/dev/init.yaml

# # BUILD BACKEND
# - template: /tech_products/ecmc/sap-commerce/provisioners/gitflow/src-sap-commerce-cloud/stages/dev/build_test_backend.yaml
#   parameters:
#     branchName: ${{ parameters.branch_backend }}
#     isUpgradeSap: ${{ parameters.isUpgradeSap }}

# ## SECURITY BACKEND
# - template: /tech_products/ecmc/sap-commerce/provisioners/gitflow/src-sap-commerce-cloud/stages/dev/security_backend.yaml
#   parameters:
#     branchName: ${{ parameters.branch_backend }}
#     fortifyExclusionRepository: FortifyExclusion
#     dependsOn:
#     - pipeline_pre_init
#     - build_test_backend_part_1
#     - build_test_backend_part_2

# ## BUILD FRONTEND
# - template: /tech_products/ecmc/sap-commerce/provisioners/gitflow/src-sap-commerce-cloud/stages/dev/build_test_frontend.yaml
#   parameters:
#     branchName: ${{ parameters.branch_frontend }}

# ## SECURITY FRONTEND
# - template: /tech_products/ecmc/sap-commerce/provisioners/gitflow/src-sap-commerce-cloud/stages/dev/security_frontend.yaml
#   parameters:
#     branchName: ${{ parameters.branch_frontend }}
#     fortifyExclusionRepository: FortifyExclusion
#     dependsOn:
#     - pipeline_pre_init
#     - build_test_frontend

- template: /tech_products/ecmc/sap-commerce/provisioners/gitflow/src-sap-commerce-cloud/stages/dev/init_build.yaml
  parameters:
    environment_code: ${{ parameters.environment_code}}
    ${{ if and(eq(variables['Build.Reason'], 'Manual'), ne(parameters.branch_frontend, ''), ne(parameters.branch_backend, '')) }}:
      branch_frontend: ${{ parameters.branch_frontend }}
      branch_backend: ${{ parameters.branch_backend }}

- template: /tech_products/ecmc/sap-commerce/provisioners/gitflow/src-sap-commerce-cloud/stages/build.yaml
  parameters:
    environment_code: ${{ parameters.environment_code}}
    ${{ if and(eq(variables['Build.Reason'], 'Manual'), ne(parameters.branch_frontend, ''), ne(parameters.branch_backend, ''), ne(parameters.database_update_mode, '')) }}:
      branch_frontend: ${{ parameters.branch_frontend }}
      branch_backend: ${{ parameters.branch_backend }}

- template: /tech_products/ecmc/sap-commerce/provisioners/gitflow/src-sap-commerce-cloud/stages/send_message.yaml
  parameters:
    project_name: ${{ parameters.project_name }}
    environment_code: ${{ parameters.environment_code }}
    database_update_mode: ${{ parameters.database_update_mode }}
    deploy_strategy: ${{ parameters.deploy_strategy }}
    branch_frontend: ${{ parameters.branch_frontend }}
    branch_backend: ${{ parameters.branch_backend }}
    pipeline_status: 'STARTED'
    work_item_title_prefix: 'Build'

- template: /tech_products/ecmc/sap-commerce/provisioners/gitflow/src-sap-commerce-cloud/stages/deploy.yaml
  parameters:
    environment_code: ${{ parameters.environment_code}}
    ${{ if and(in(variables['Build.Reason'], 'Manual', 'Schedule'), ne(parameters.deploy_strategy, ''), ne(parameters.database_update_mode, ''))  }}:
      database_update_mode: ${{ parameters.database_update_mode }}
      deploy_strategy: ${{ parameters.deploy_strategy }}

- template: /tech_products/ecmc/sap-commerce/provisioners/gitflow/src-sap-commerce-cloud/stages/send_message.yaml
  parameters:
    project_name: ${{ parameters.project_name }}
    environment_code: ${{ parameters.environment_code }}
    database_update_mode: ${{ parameters.database_update_mode }}
    deploy_strategy: ${{ parameters.deploy_strategy }}
    branch_frontend: ${{ parameters.branch_frontend }}
    branch_backend: ${{ parameters.branch_backend }}
    pipeline_status: 'DEPLOYED'
    work_item_title_prefix: 'Deploy'

