parameters:
- name: work_item_type
  type: string
  default: 'task'
- name: work_item_title
  type: string
  default: 'Merge em branch do projeto'
- name: area_path
  type: string
  default: 'ECMC - Ecomm Cloud B2C\\MERGED-SAPCOMMERCE'
- name: iteration_path
  type: string
  default: 'ECMC - Ecomm Cloud B2C'
- name: display_name
  type: string
  default: 'Creating work item'

stages:
- stage: send_message_merge
  displayName: "Send message in branch update"
  pool:
    name: $(PRIVATE_AGENT_DEFAULT)
  jobs:
  - job:
    workspace:
      clean: outputs
    displayName: "Sending message"
    steps:
    - bash: |
        WORK_ITEM_DATA="🚀🔗 <a href='https://dev.azure.com/telefonica-vivo-brasil/ECMC%20-%20Ecomm%20Cloud%20B2C/_build/results?buildId=$(Build.BuildId)'>Link para a pipe</a> 🔗🚀<br><br> \
          Repositório: <b>$(Build.Repository.Name)</b> 🗄️<br><br> \
          Pipeline: <b>$(Build.DefinitionName)</b> 🚧<br><br> \
          Foi realizado um novo MERGE na branch $(PROJECT_SOURCE_BRANCH)</b> 🌿<br><br>"
        
        CREATE_WIT=$(az boards work-item create \
          --title "${{ parameters.work_item_title }} - $(PROJECT_SOURCE_BRANCH)" \
          --description "$WORK_ITEM_DATA" \
          --type ${{ parameters.work_item_type }} \
          --project "$(System.TeamProject)" \
          --org "$(System.TeamFoundationCollectionUri)" \
          --fields "System.AreaPath=${{ parameters.area_path }}" "System.IterationPath=${{ parameters.iteration_path }}")
        
        echo "Resposta: $CREATE_WIT"
      displayName: ${{ parameters.display_name }}
      env: 
        AZURE_DEVOPS_EXT_PAT: $(SYSTEM_ACCESS_TOKEN_JOBS)