parameters:
- name: qa_environment
  type: string
- name: enable_rollback
  type: boolean
  default: False

variables:
  - template: /tech_products/srus/provisioners/db/trunkbased/liquibase/maven/variables/load.yml    
  - template: /tech_products/srus/provisioners/db/global/variables/workflow-variables.yml
    parameters:
      qa_environment: ${{ parameters.qa_environment }}
      enable_rollback: ${{ parameters.enable_rollback }}

resources:
  repositories:
    - repository: FortifyExclusion
      name: DevOps/Vivo.Fortify.Exclusions
      type: git
      ref: refs/heads/master
      endpoint: CorePipelines

stages:
## INIT
- template: /tech_products/srus/provisioners/db/trunkbased/liquibase/maven/stages/init.yml

## BUILD & TEST
- template: /tech_products/srus/provisioners/db/trunkbased/liquibase/maven/stages/build_test.yml

## GATES
- template: /tech_products/srus/provisioners/db/trunkbased/liquibase/maven/stages/gates.yml

## SECURITY
- template: /tech_products/srus/provisioners/db/trunkbased/liquibase/maven/stages/security.yml
  parameters:
    fortifyExclusionRepository: FortifyExclusion

## VALIDATIONS
- template: /tech_products/srus/provisioners/db/trunkbased/liquibase/maven/stages/validation.yml

## DEPLOY
# - ${{ if and( ne(variables['Build.Reason'], 'PullRequest'), or( startsWith(variables['Build.SourceBranch'], 'refs/heads/'), eq(variables['Build.SourceBranch'], 'refs/heads/main'),  eq(variables['Build.SourceBranch'], 'refs/heads/master') ))}}:
- template: /tech_products/srus/provisioners/db/trunkbased/liquibase/maven/stages/deploy.yml
  parameters:
    environment: ${{ parameters.qa_environment }}

# # ROLLBACK
- ${{ if eq(parameters.enable_rollback, 'true') }}:
  - template: /tech_products/srus/provisioners/db/trunkbased/liquibase/maven/stages/rollback.yml
    parameters:
      environment: ${{ parameters.qa_environment }}