stages:
  - stage: gates
    displayName: "Quality Gates"
    dependsOn:
    - build_test_bff_and_client
    pool: $(PRIVATE_AGENT_DEFAULT)
    jobs:
      - job: sonarqube_bff
        condition: and(succeeded(), eq(variables.flowIsTagging, false), ne(variables.skip_sonarqube, true))
        displayName: Code Analysis bff
        variables:
        - name: APP_VERSION
          value: $[ stageDependencies.build_test_bff_and_client.bump_version.outputs['component_bump_version.API_NEW_VERSION'] ]
        steps:
          - ${{ if in(variables['Build.SourceBranch'], 'refs/heads/master', 'refs/heads/main') }}:
              - template: /tech_products/srus/tasks/catalog_info/extract_variables.yml
                parameters:
                  workingDirectory: $(Build.SourcesDirectory)
                  skipDownload: true
              - template: /tech_products/srus/task_groups/gates/run_sonarqube_scan.yml
                parameters:
                  stack: "NODE"
                  configFile: $(BFF_SONARQUBE_CONFIG_FILE)
                  workdirArtifacts: $(Build.ArtifactStagingDirectory)/extracted_tars/app-bff/bff
                  artifactName: app-bff
                  artifactType: "build"
                  projectKey: "$(SONAR_PROJECT_KEY)-bff"
                  version: $(APP_VERSION)
                  eslintPath: $(BFF_ESLINT_RESULT_PATH)
      - job: sonarqube_client
        condition: and(succeeded(), eq(variables.flowIsTagging, false), ne(variables.skip_sonarqube, true))
        displayName: Code Analysis client
        variables:
        - name: APP_VERSION
          value: $[ stageDependencies.build_test_bff_and_client.bump_version.outputs['component_bump_version.API_NEW_VERSION'] ]
        steps:
          - ${{ if in(variables['Build.SourceBranch'], 'refs/heads/master', 'refs/heads/main') }}:
            - template: /tech_products/srus/tasks/catalog_info/extract_variables.yml
              parameters:
                workingDirectory: $(Build.SourcesDirectory)
                skipDownload: true
            - template: /tech_products/srus/task_groups/gates/run_sonarqube_scan.yml
              parameters:
                stack: "NODE"
                configFile: $(CLIENT_SONARQUBE_CONFIG_FILE)
                workdirArtifacts: $(Build.ArtifactStagingDirectory)/extracted_tars/app-client/client
                artifactName: app-client
                artifactType: "build"
                projectKey: "$(SONAR_PROJECT_KEY)-client"
                version: $(APP_VERSION)
                eslintPath: $(CLIENT_ESLINT_RESULT_PATH)
      - job: grafeas_sonar_occurrence
        dependsOn: [sonarqube_bff, sonarqube_client]
        condition: eq(variables['GRAFEAS_INTEGRATION_ENABLED'], true)
        displayName: Create Grafeas Occurrence
        variables:
        - name: APP_VERSION
          value: $[ stageDependencies.build_test_bff_and_client.bump_version.outputs['component_bump_version.API_NEW_VERSION'] ]
        steps:
        - template: /tech_products/srus/tasks/catalog_info/extract_variables.yml
        - template: /tech_products/srus/tasks/grafeas/sonar_occurrence.yml
          parameters:
            dockerAppName: $(APP_NAME)
            dockerAppVersion: $(APP_VERSION)
            sonarProjectKey: $(SONAR_PROJECT_KEY)
            sonarTaskId: ''
            isBffClient: true