## -> Parameters:
parameters:
  - name: packageName

stages:
  - stage: ci_security
    displayName: "CI - Security Gates"
    pool:
      name: $(AGENT_POOL_CI)
    dependsOn:
      - gates_environment_init
    condition: succeeded()

    variables:
      - name: FORTIFY_SSC_CLI_TOKEN
        value: $[ stageDependencies.gates_environment_init.environment.outputs['security_credentials.FORTIFY_SSC_CLI_TOKEN'] ]
      - name: FORTIFY_SCANCENTRAL_CLIENT_TOKEN
        value: $[ stageDependencies.gates_environment_init.environment.outputs['security_credentials.FORTIFY_SCANCENTRAL_CLIENT_TOKEN'] ]
      - name: USE_FORTIFY
        value: $[ stageDependencies.gates_environment_init.environment.outputs['evaluate_flags.USE_FORTIFY'] ]
      - name: CONVISO_API_KEY
        value: $[ stageDependencies.gates_environment_init.environment.outputs['security_credentials.CONVISO_API_KEY'] ]
      - name: USE_CONVISO
        value: $[ stageDependencies.gates_environment_init.environment.outputs['evaluate_flags.USE_CONVISO'] ]
      - name: USE_CHECKMARX
        value: $[ stageDependencies.gates_environment_init.environment.outputs['evaluate_flags.USE_CHECKMARX'] ]
      - name: SKIP_SECURITY_GATE
        value: $[ stageDependencies.gates_environment_init.environment.outputs['evaluate_flags.SKIP_SECURITY_GATE'] ]
      - name: USE_DEPENDENCY_TRACK
        value: $[ stageDependencies.gates_environment_init.environment.outputs['evaluate_flags.USE_DEPENDENCY_TRACK'] ]
      - name: USE_DT_DOCKER
        value: $[ stageDependencies.gates_environment_init.environment.outputs['evaluate_flags.USE_DT_DOCKER'] ]
      - name: APP_LANGUAGE
        value: $[ stageDependencies.environment_init.environment.outputs['catalog_info.APP_LANGUAGE'] ]

    jobs:
      - job: sca_scan
        condition: and(
          succeeded(),
          eq(variables.USE_DEPENDENCY_TRACK, 'true'),
          eq(variables.USE_DT_DOCKER, 'false')
          )
        displayName: "SCA Scan"
        steps:
          - checkout: none

          - task: DownloadPipelineArtifact@2
            displayName: "Fetching Uploaded Artifact"
            inputs:
              buildType: "current"
              packageName: "${{ parameters.packageName }}"
              targetPath: "$(Build.SourcesDirectory)"

          ## -> Set artifact information to variables.
          - task: Bash@3
            displayName: Artifact Info
            continueOnError: true
            inputs:
              workingDirectory: "$(Build.SourcesDirectory)"
              targetType: inline
              script: |

                pwd
                echo "##[debug] Check package structure:"
                echo "##[group] Package tree"
                tree . -a
                echo "##[endgroup]"

          - template: /tech_products/gdoc/templates/ci/ci_run_sca_scan.yml
            parameters:
              gateCondition: and(
                succeeded(),
                ne(variables.USE_CONVISO, 'true')
                )
              skipSecurityGate: $(SKIP_SECURITY_GATE)
