## -> Parameters:
parameters:
  - name: packageName

stages:
  - stage: ci_upload_async
    displayName: "CI - Upload External Package"
    dependsOn:
      - default_initializer
    condition: succeeded()

    jobs:
      - job: upload_files
        displayName: "Files Upload"
        pool: Server
        condition: succeeded()
        steps:
          - task: ManualValidation@0
            displayName: "Waiting Upload and Approval"
            inputs:
              notifyUsers: "" # string. Required. Notify users.
              instructions: |
                EXECUTE AS SEGUINTES AÇÕES(POWERSHELL):

                Adicione a variável de ambiente
                - $env:AZURE_CLI_DISABLE_CONNECTION_VERIFICATION=1

                Instale o azure CLI (veja as instruções)
                - https://learn.microsoft.com/en-us/azure/devops/cli/?view=azure-devops

                Instale a extensão do Azure DevOps
                - az extension add -n azure-devops

                Faça o login
                - az login

                Faça o upload do artefato
                - az pipelines runs artifact upload --artifact-name ${{ parameters.packageName }} --path CAMINHO_ABSOLUTO_DO_ARTEFATO_LOCAL --run-id $(Build.BuildId) --organization $(System.CollectionUri) --project "$(System.TeamProject)"
                
                Após o upload, clique em 'Resume' para continuar.
              onTimeout: "reject" # 'reject' | 'resume'. On timeout. Default: reject.
