stages:
- stage: BuildAndPackage
  displayName: Build & Package
  pool: GeneralPurposeLinuxAgentsCI
  dependsOn:
  - Validate
  jobs:
    - job: Build
      displayName: "Building"
      condition: succeeded()
      variables:
        AGENT_NAME: $[ stageDependencies.Validate.Validate.outputs['GetAgent.AGENT_NAME']]
        EXECUTION_TYPE: $[ stageDependencies.Validate.Validate.outputs['IdentifyCommitsAndTypeOfExecution.EXECUTION_TYPE']]
        PROJECT_TYPE: $[ stageDependencies.Validate.Validate.outputs['IdentifyTypeOfProject.PROJECT_TYPE']]
        PARTITION: $[ stageDependencies.Validate.Validate.outputs['ValidatingChangedFilesAndProject.PARTITION']]
        PROJECT: $[ stageDependencies.Validate.Validate.outputs['ValidatingChangedFilesAndProject.PROJECT']]
        COMPOSITE_VERSION: $[ stageDependencies.Validate.Validate.outputs['GetCompositeVersion.COMPOSITE_VERSION']]
        FILES: $[ stageDependencies.Validate.Validate.outputs['ValidatingChangedFilesAndProject.FILES']]
      pool:
        name: GeneralPurposeLinuxAgentsCI
        demands: Agent.Name -equals $(AGENT_NAME)
      steps:
        - template: /tech_products/orss/soa-refactor/tasks/soa_build.yml

    - job: Publish
      displayName: "Publishing"
      condition: succeeded()
      dependsOn:
      - Build
      variables:
        AGENT_NAME: $[ stageDependencies.Validate.Validate.outputs['GetAgent.AGENT_NAME']]
        EXECUTION_TYPE: $[ stageDependencies.Validate.Validate.outputs['IdentifyCommitsAndTypeOfExecution.EXECUTION_TYPE']]
        PROJECT_TYPE: $[ stageDependencies.Validate.Validate.outputs['IdentifyTypeOfProject.PROJECT_TYPE']]
      pool:
        name: GeneralPurposeLinuxAgentsCI
        demands: Agent.Name -equals $(AGENT_NAME)
      steps:
        - template: /tech_products/orss/soa-refactor/tasks/soa_publish.yml

    - job: Tagging
      displayName: "Tagging"
      condition: succeeded()
      dependsOn:
      - Build
      - Publish
      variables:
        AGENT_NAME: $[ stageDependencies.Validate.Validate.outputs['GetAgent.AGENT_NAME']]
        EXECUTION_TYPE: $[ stageDependencies.Validate.Validate.outputs['IdentifyCommitsAndTypeOfExecution.EXECUTION_TYPE']]
        PROJECT_TYPE: $[ stageDependencies.Validate.Validate.outputs['IdentifyTypeOfProject.PROJECT_TYPE']]
      pool:
        name: GeneralPurposeLinuxAgentsCI
        demands: Agent.Name -equals $(AGENT_NAME)
      steps:
        - template: /tech_products/orss/soa-refactor/tasks/soa_tagging.yml