stages:
- stage: PublishAndTagging
  displayName: Publish & Tagging
  pool: GeneralPurposeLinuxAgentsCI
  dependsOn:
  - BuildAndPackage
  jobs:
    - job: Publish
      displayName: "Publishing"
      condition: succeeded()
      variables:
        AGENT_NAME: $[ stageDependencies.Validate.Validate.outputs['GetAgent.AGENT_NAME']]
        EXECUTION_TYPE: $[ stageDependencies.Validate.Validate.outputs['IdentifyCommitsAndTypeOfExecution.EXECUTION_TYPE']]
        PROJECT_TYPE: $[ stageDependencies.Validate.Validate.outputs['IdentifyTypeOfProject.PROJECT_TYPE']]
      pool:
        name: GeneralPurposeLinuxAgentsCI
        demands: Agent.Name -equals $(AGENT_NAME)
      steps:
        - template: /tech_products/orss/soa-refactor/tasks/soa_publish.yml

    - job: Tagging
      displayName: "Tagging"
      condition: succeeded()
      dependsOn:
      - Publish
      variables:
        AGENT_NAME: $[ stageDependencies.Validate.Validate.outputs['GetAgent.AGENT_NAME']]
        EXECUTION_TYPE: $[ stageDependencies.Validate.Validate.outputs['IdentifyCommitsAndTypeOfExecution.EXECUTION_TYPE']]
        PROJECT_TYPE: $[ stageDependencies.Validate.Validate.outputs['IdentifyTypeOfProject.PROJECT_TYPE']]
      pool:
        name: GeneralPurposeLinuxAgentsCI
        demands: Agent.Name -equals $(AGENT_NAME)
      steps:
        - template: /tech_products/orss/soa-refactor/tasks/soa_tagging.yml