parameters:
- name: appIdentifier
- name: appSpecificId

steps:
- template: /tech_products/hrcl/templates/tasks/artifacts/download_pipeline.yml
  parameters:
    artifactName: 'ios_package'
    targetPath: '$(DEFAULT_WORKDIR_ARTIFACTS)'

- task: AppStoreRelease@1
  displayName: "App Store Release - TestFlight"
  inputs:
    authType: 'ApiKey'
    apiKeyId: $(IOS_TESTFLIGHT_API_KEY_ID)
    apiKeyIssuerId: $(IOS_TESTFLIGHT_API_ISSUER)
    apitoken: $(IOS_TESTFLIGHT_API_TOKEN)
    releaseTrack: 'TestFlight'
    appIdentifier: ${{ parameters.appIdentifier }}
    appType: 'iOS'
    ipaPath: '$(DEFAULT_WORKDIR_ARTIFACTS)/**/Runner.ipa/*.ipa'
    shouldSkipWaitingForProcessing: true
    shouldSkipSubmission: true
    appSpecificId: ${{ parameters.appSpecificId }}
    installFastlane: false