steps: 
- task: AzureKeyVault@2
  displayName: 'Getting AKV credentials'
  timeoutInMinutes: 1
  retryCountOnTaskFailure: 5  
  inputs:    
    azureSubscription: DevOpsSharedResources    
    KeyVaultName: $(AKV_DEVOPS_NAME)
    SecretsFilter: 'ANDROID-SIGNING-KEY-JKS, ANDROID-SIGNING-KEY-PASSWORD, ANDROID-SIGNING-STORE-PASSWORD, IOS-P12-CERTIFICATE-KEY, IOS-P12-CERTIFICATE-PWD, IOS-TESTFLIGHT-API-KEY-ID, IOS-TESTFLIGHT-API-ISSUER, IOS-TESTFLIGHT-API-TOKEN'

- bash: |
    echo "##[debug]Exporting 'ANDROID-SIGNING-KEY-JKS' secret to 'ANDROID_SIGNING_KEY_JKS' var"
    echo "##vso[task.setvariable variable=ANDROID_SIGNING_KEY_JKS;issecret=true;isOutput=true;]$(ANDROID-SIGNING-KEY-JKS)"
    
    echo "##[debug]Exporting 'ANDROID-SIGNING-KEY-PASSWORD' secret to 'ANDROID_SIGNING_KEY_PASSWORD' var"
    echo "##vso[task.setvariable variable=ANDROID_SIGNING_KEY_PASSWORD;issecret=true;isOutput=true;]$(ANDROID-SIGNING-KEY-PASSWORD)"
    
    echo "##[debug]Exporting 'ANDROID-SIGNING-STORE-PASSWORD' secret to 'ANDROID_SIGNING_STORE_PASSWORD' var"
    echo "##vso[task.setvariable variable=ANDROID_SIGNING_STORE_PASSWORD;issecret=true;isOutput=true;]$(ANDROID-SIGNING-STORE-PASSWORD)"
    
    echo "##[debug]Exporting 'IOS-P12-CERTIFICATE-KEY' secret to 'IOS_P12_CERTIFICATE_KEY' var"
    echo "##vso[task.setvariable variable=IOS_P12_CERTIFICATE_KEY;issecret=true;isOutput=true;]$(IOS-P12-CERTIFICATE-KEY)"
    
    echo "##[debug]Exporting 'IOS-P12-CERTIFICATE-PWD' secret to 'IOS_P12_CERTIFICATE_PWD' var"
    echo "##vso[task.setvariable variable=IOS_P12_CERTIFICATE_PWD;issecret=true;isOutput=true;]$(IOS-P12-CERTIFICATE-PWD)"
    
    echo "##[debug]Exporting 'IOS-TESTFLIGHT-API-KEY-ID' secret to 'IOS_TESTFLIGHT_API_KEY_ID' var"
    echo "##vso[task.setvariable variable=IOS_TESTFLIGHT_API_KEY_ID;issecret=true;isOutput=true;]$(IOS-TESTFLIGHT-API-KEY-ID)"
    
    echo "##[debug]Exporting 'IOS-TESTFLIGHT-API-ISSUER' secret to 'IOS_TESTFLIGHT_API_ISSUER' var"
    echo "##vso[task.setvariable variable=IOS_TESTFLIGHT_API_ISSUER;issecret=true;isOutput=true;]$(IOS-TESTFLIGHT-API-ISSUER)"
    
    echo "##[debug]Exporting 'IOS-TESTFLIGHT-API-TOKEN' secret to 'IOS_TESTFLIGHT_API_TOKEN' var"
    echo "##vso[task.setvariable variable=IOS_TESTFLIGHT_API_TOKEN;issecret=true;isOutput=true;]$(IOS-TESTFLIGHT-API-TOKEN)"
  name: export_secrets
  displayName: Exporting Secrets