## -> Parameters:
parameters:
- name: setEnvironment
  type: string
  default: ''
- name: enableDevflowValidations
  type: boolean
  default: false
- name: enableMsgStatus
  type: boolean
  default: false

## -> Resources:
resources:
  repositories:
    - repository: FortifyExclusion
      name: DevOpsVivo.Fortify.Exclusions
      type: git
      ref: refs/heads/master
      endpoint: CorePipelines

    - repository: CorePipelines
      name: DevOpsVivo.Core.Pipelines
      type: git
      ref: refs/heads/master
      endpoint: CorePipelines

    - repository: Codeplay
      name: DevOps/Vivo.CodePlay.Pipelines
      type: git
      ref: refs/heads/master
      endpoint: CorePipelines

## -> Initialize global variables   
variables:
- template: /tech_products/appv/global/initialize/variables-global.yml
- template: /tech_products/appv/global/initialize/variables-nodejs.yml
- template: /tech_products/appv/global/initialize/variables-gates.yml
- template: /tech_products/appv/global/initialize/variables-docker.yml
- ${{ if eq(parameters.enableDevflowValidations, True) }}:
  - template: /.azuredevops/variables/private.yml@self
- name: CORPORATE_WIKI_DOC_URL
  value: "TBD"

## -> Override global variables, with variables set in Library/Variable Groups (Pipelines)
## -> Use this to change the variables on runtime
- group: "${{ variables['Build.DefinitionName'] }}"

stages:
## -> Initialize validations for commit messages, branch names and verify if PTI exists in Jira
- ${{ if eq(parameters.enableDevflowValidations, True) }}:
  - template: /provisioners/app/trunkbased/nodejs/api_default/stages/init.yml@CorePipelines

  - template: /provisioners/app/trunkbased/nodejs/api_default/stages/validate_standards_dev_flow.yml@CorePipelines
## -> Initialize pipeline enviroment
- template: /tech_products/appv/global/initialize/nodejs-environment.yml




## -> Build for CI - NodeJS
- template: /tech_products/appv/appv_mergevalidator/templates/ci/app-build-validator-nodejs.yml

## -> Component Test for CI - NodeJS
##- ${{ if ne(parameters.skipComponentTest, True) }}:
  ##TODO- template: /tech_products/appv/templates/ci/ci_component_test_nodejs_appv.yml  


## -> initialize gates environment

- template: /tech_products/appv/global/initialize/gates-environment.yml

## -> Security Gates (SonarQube)
- template: /tech_products/appv/appv_mergevalidator/templates/ci/app-qualitygate.yml
## -> Security Gates (Fortify)

## -> Security Gates (Fortify)
- template: /tech_products/appv/appv_mergevalidator/templates/ci/app-securitygate.yml
  parameters:
    fortifyExclusionRepository: FortifyExclusion

## -> Send Notification to Teams
- template: /tech_products/appv/appv_mergevalidator/templates/ci/app-sendmsg.yml
  parameters:
    enableMsgStatus: ${{ parameters.enableMsgStatus }}