parameters:
  - name: environment
    displayName: Escolha a esteira em que deseja executar os testes
    type: string
    default: dev
    values:
    - dev
    - preprod
    - darklaunch

  - name: context
    displayName: Escolha o contexto do módulo
    type: string
    default: ms
    values:
    - ms

  - name: module
    displayName: Digite o nome do modulo
    type: string
    default: ''

  - name: massaCpf
    displayName: Digite o CPF para teste
    type: string
    default: ''

  - name: massaLinha
    displayName: Digite a Linha para teste
    type: string
    default: ''

  - name: massaSenha
    displayName: Digite a Senha da massa para teste
    type: string
    default: ''

  - name: tags
    displayName: Digite as tags de teste
    type: string
    default: ' '

  - name: webviewId
    displayName: Digite a webviewId para teste
    type: string
    default: ''


## -> Resources:
resources:
  repositories:
  - repository: CorePipelines
    name: DevOps/Vivo.Core.Pipelines
    type: git
    ref: refs/tags/latest
    endpoint: CorePipelines

## -> Initialize global variables
variables:
- template: /tech_products/ecmc/framework-brasil/appv/initialize/variables_global.yml
- template: /tech_products/ecmc/framework-brasil/appv/initialize/variables_nodejs.yml
- template: /tech_products/ecmc/framework-brasil/appv/initialize/variables_docker.yml


## -> Override global variables, with variables set in Library/Variable Groups (Pipelines)
## -> Use this to change the variables on runtime
- group: "src.src-framework-brasil-e2e-tests"

# - name: CORPORATE_WIKI_DOC_URL
#   value: "TBD"

stages:

## -> Initialize pipeline enviroment
- template: /tech_products/ecmc/framework-brasil/appv/initialize/nodejs_environment.yml




## -> Build for CI - NodeJS
- template: /tech_products/appv_e2e_test/templates/ci/ms/ci_route_validator_e2e_test.yml
  parameters:
    environment: "${{parameters.environment}}"
    context: "${{parameters.context}}"
    module: "${{parameters.module}}"
    massaCpf: "${{parameters.massaCpf}}"
    massaSenha: "${{parameters.massaSenha}}"
    tags: "${{parameters.tags}}"
    webviewId: "${{parameters.webviewId}}"



