parameters:
- name: chartName
  default: $(CHART_NAME)
- name: chartVersion
  default: $(CHART_VERSION)
- name: chartNewVersion
  default: ""
  type: string
- name: workingDirectory
  default: $(Build.ArtifactStagingDirectory)/helm/package

steps:
- task: AzureKeyVault@2  
  displayName: '[Helm Nexus] Getting AKV credentials'
  timeoutInMinutes: 1
  retryCountOnTaskFailure: 5  
  inputs:    
    azureSubscription: DevOpsSharedResources    
    KeyVaultName: $(AKV_DEVOPS_NAME)
    SecretsFilter: 'HELM-REGISTRY-NEXUS-USERNAME, HELM-REGISTRY-NEXUS-PASSWORD'
  condition: eq(lower(variables['HELM_REGISTRY_NEXUS_ENABLED']), 'true')

- script: |
    FULLY_QUALIFIED_TARGET_REPOSITORY="${REPOSITORY_URL}/${REPOSITORY_NAMESPACE}/"
    
    if [[ -z "${CHART_NEW_VERSION}" ]]; then
      CHART_ARCHIVE="${CHART_NAME}-${CHART_VERSION}.tgz"
    else
      CHART_ARCHIVE="${CHART_NAME}-${CHART_NEW_VERSION}.tgz"
    fi

    echo "##[debug] REPOSITORY_URL.......................: ${REPOSITORY_URL}"
    echo "##[debug] REPOSITORY_NAMESPACE.................: ${REPOSITORY_NAMESPACE}"
    echo "##[debug] FULLY_QUALIFIED_TARGET_REPOSITORY....: ${FULLY_QUALIFIED_TARGET_REPOSITORY}"
    echo "##[debug] CHART_ARCHIVE........................: ${CHART_ARCHIVE}"
    echo "##[debug] HTTPS_PROXY..........................: ${HTTPS_PROXY}"
    echo "##[debug] HTTP_PROXY...........................: ${HTTP_PROXY}"

    echo "##[command] curl --fail -s -u ${USERNAME}:***** ${FULLY_QUALIFIED_TARGET_REPOSITORY} --upload-file ${CHART_ARCHIVE}"
    curl --fail -s -u ${USERNAME}:${PASSWORD} ${FULLY_QUALIFIED_TARGET_REPOSITORY} --upload-file ${CHART_ARCHIVE}
  displayName: Publish to Nexus
  condition: and(succeeded(), eq(lower(variables['HELM_REGISTRY_NEXUS_ENABLED']), 'true'))
  workingDirectory: ${{ parameters.workingDirectory }}
  env:
    USERNAME: $(HELM-REGISTRY-NEXUS-USERNAME)
    PASSWORD: $(HELM-REGISTRY-NEXUS-PASSWORD)
    REPOSITORY_URL: $(HELM_REGISTRY_NEXUS_URL)
    REPOSITORY_NAMESPACE: $(HELM_REGISTRY_NEXUS_REPO_NAME)
    CHART_NAME: '${{ parameters.chartName }}'
    CHART_VERSION: '${{ parameters.chartVersion }}'
    CHART_NEW_VERSION: '${{ parameters.chartNewVersion }}'