parameters:
- name: environment
- name: workDir
- name: k8sNamespace
- name: dockerRegistry
- name: dockerServer
- name: dockerUsername
- name: dockerPassword
- name: dockerEmail
- name: k8sKubeconfig
- name: argocd_enabled
  type: boolean
  default: false
- name: azureSubscription
  default: "$(APP_CONFIGURATION_AZURE_SUBSCRIPTION)"
- name: appConfigurationEndpoint
  default: "$(APP_CONFIGURATIN_ENDPOINT)"
- name: forceDockerK8sSecretCreation
  default: $(FORCE_DOCKER_K8S_SECRET_CREATION)


steps:
- task: CreateK8sNamespaceIfNotExists@1
  displayName: 'Create namespace if not exists'
  inputs:
    k8sKubeconfig: '${{parameters.k8sKubeconfig}}'
    k8sNamespace: '${{parameters.k8sNamespace}}'
  condition: and(ne(${{ parameters.argocd_enabled }}, true), eq(variables['ENABLE_CREATE_NAMESPACE_IF_NOT_EXISTS'], 'true'))
   

- task: AzureAppConfiguration@8
  displayName: 'Retrieve date for ACR credential renewal.'
  timeoutInMinutes: 1
  retryCountOnTaskFailure: 5
  inputs:
    azureSubscription: ${{ parameters.azureSubscription }}
    AppConfigurationEndpoint: ${{ parameters.appConfigurationEndpoint }}
    KeyFilter: "THRESHOLD_DATE_FOR_CLUSTER_INJECTED_DOCKER_SECRET_OVERWRITE"
    Label: 'VIVO-CORE-PIPELINES'
  condition: ne(${{ parameters.argocd_enabled }}, true)
  env:
    HTTPS_PROXY: $(PROXY_AGENT_HTTPS)
    HTTP_PROXY: $(PROXY_AGENT_HTTP)
    NO_PROXY: $(PROXY_AGENT_NO_PROXY)


- task: CreateDockerRegistryK8sSecret@1
  displayName: 'Create docker registry secret'
  inputs:
    k8sKubeconfig: '${{parameters.k8sKubeconfig}}'
    k8sNamespace: '${{parameters.k8sNamespace}}'
    k8sSecretName: '${{parameters.dockerRegistry}}'
    forceDockerK8sSecretCreation: '${{parameters.forceDockerK8sSecretCreation}}'
    dockerServer: '${{parameters.dockerServer}}'
    dockerUsername: '${{parameters.dockerUsername}}'
    dockerPassword: '${{parameters.dockerPassword}}'
    dockerEmail: '${{parameters.dockerEmail}}'
    overwriteThresholdDate: $(THRESHOLD_DATE_FOR_CLUSTER_INJECTED_DOCKER_SECRET_OVERWRITE)
  condition: and(ne(${{ parameters.argocd_enabled }}, true), eq(variables['CREATE_REGISTRY_CREDENTIALS'], 'true'))