parameters:
- name: recipe
  type: string
  values:
  - nodejs_docker
  - sbt_data
  - maven_docker
  - docker
  - maven_libs
  - python_docker
  - php_docker
  - golang-binary
  - mlops_v1
  - mlops_v2
- name: branching_strategy
  type: string
  values:
  - gitlabflow
  - releaseflow
  - stb
  default: stb
- name: runSonar
  type: boolean
  default: false
- name: envs
  type: object
  default: {}

stages:
#### PREPARATION #############################
  - stage: preparation
    displayName: Preparation - ${{ parameters.recipe }} recipe
    jobs:
    - template: /tech_products/hdop/recipes/build/${{ parameters.recipe }}/prep.yaml
    variables:
      - group: '4p-core-default-variables'
      - template: /tech_products/hdop/recipes/build/${{ parameters.recipe }}/variables.yaml
        parameters:
          envs: ${{ parameters.envs }}
      - name: RECIPE
        value: ${{ parameters.recipe }}
      - name: BRANCHING_STRATEGY
        value: ${{ parameters.branching_strategy }}
      - ${{ if and(eq( parameters.branching_strategy, 'gitlabflow'), ne(variables['Build.SourceBranchName'], '')) }}:
        - template: /tech_products/hdop/recipes/build/${{ parameters.recipe }}/variables/${{ variables['Build.SourceBranchName'] }}.yaml  
      ### Security #############################
  # - stage: security
  #   displayName: Security Analysis
  #   condition: succeeded()
  #   dependsOn:
  #   - preparation
  #   jobs:
  #   # - template: /tech_products/hdop/recipes/build/commons/fortify.yaml
  #   # - template: /tech_products/hdop/recipes/build/commons/sca.yaml
  #   variables:
  #     - group: '4p-core-default-variables'
  #     - template: /tech_products/hdop/recipes/build/${{ parameters.recipe }}/variables.yaml
  #       parameters:
  #         envs: ${{ parameters.envs }}
  #     - name: RECIPE
  #       value: ${{ parameters.recipe }}
  #     - name: BRANCHING_STRATEGY
  #       value: ${{ parameters.branching_strategy }}
  #     - ${{ if and(eq( parameters.branching_strategy, 'gitlabflow'), ne(variables['Build.SourceBranchName'], '')) }}:
  #       - template: /tech_products/hdop/recipes/build/${{ parameters.recipe }}/variables/${{ variables['Build.SourceBranchName'] }}.yaml  

### BUILD #############################
  - stage: build
    displayName: Build - ${{ parameters.recipe }} recipe
    condition: succeeded()
    dependsOn:
    - preparation
    jobs:
    - template: /tech_products/hdop/recipes/build/${{ parameters.recipe }}/build.yaml
    variables:
      - group: '4p-core-default-variables'
      - template: /tech_products/hdop/recipes/build/${{ parameters.recipe }}/variables.yaml
        parameters:
          envs: ${{ parameters.envs }}
      - name: RECIPE
        value: ${{ parameters.recipe }}
      - name: BRANCHING_STRATEGY
        value: ${{ parameters.branching_strategy }}
      - ${{ if and(eq( parameters.branching_strategy, 'gitlabflow'), ne(variables['Build.SourceBranchName'], '')) }}:
        - template: /tech_products/hdop/recipes/build/${{ parameters.recipe }}/variables/${{ variables['Build.SourceBranchName'] }}.yaml  

### TESTS #############################
  - stage: tests
    displayName: Tests - ${{ parameters.recipe }} recipe
    condition: succeeded()
    dependsOn:
    - build
    jobs:
    - template: /tech_products/hdop/recipes/build/${{ parameters.recipe }}/tests.yaml
    variables:
      - group: '4p-core-default-variables'
      - template: /tech_products/hdop/recipes/build/${{ parameters.recipe }}/variables.yaml
        parameters:
          envs: ${{ parameters.envs }}
      - name: RECIPE
        value: ${{ parameters.recipe }}
      - name: BRANCHING_STRATEGY
        value: ${{ parameters.branching_strategy }}
      - ${{ if and(eq( parameters.branching_strategy, 'gitlabflow'), ne(variables['Build.SourceBranchName'], '')) }}:
        - template: /tech_products/hdop/recipes/build/${{ parameters.recipe }}/variables/${{ variables['Build.SourceBranchName'] }}.yaml  

### SONAR #############################
  - stage: sonar
    displayName: Sonar Analysis
    condition: succeeded()
    dependsOn:
    - tests
    jobs:
    - template: /tech_products/hdop/recipes/build/commons/sonar.yaml
      parameters:
        runSonar: ${{ parameters.runSonar }}
    variables:
      - group: '4p-core-default-variables'
      - template: /tech_products/hdop/recipes/build/${{ parameters.recipe }}/variables.yaml
        parameters:
          envs: ${{ parameters.envs }}
      - name: RECIPE
        value: ${{ parameters.recipe }}
      - name: BRANCHING_STRATEGY
        value: ${{ parameters.branching_strategy }}
      - ${{ if and(eq( parameters.branching_strategy, 'gitlabflow'), ne(variables['Build.SourceBranchName'], '')) }}:
        - template: /tech_products/hdop/recipes/build/${{ parameters.recipe }}/variables/${{ variables['Build.SourceBranchName'] }}.yaml  

# ### Gates #############################
#   - stage: gates
#     displayName: Security and Quality Gates
#     condition: succeeded()
#     dependsOn:
#     - security
#     - sonar
#     jobs:
#     - template: /tech_products/hdop/recipes/build/commons/gates.yaml
#     variables:
#       - group: '4p-core-default-variables'
#       - template: /tech_products/hdop/recipes/build/${{ parameters.recipe }}/variables.yaml
#         parameters:
#           envs: ${{ parameters.envs }}
#       - name: RECIPE
#         value: ${{ parameters.recipe }}
#       - name: BRANCHING_STRATEGY
#         value: ${{ parameters.branching_strategy }}
#       - ${{ if and(eq( parameters.branching_strategy, 'gitlabflow'), ne(variables['Build.SourceBranchName'], '')) }}:
#         - template: /tech_products/hdop/recipes/build/${{ parameters.recipe }}/variables/${{ variables['Build.SourceBranchName'] }}.yaml  
