## -> Parameters:
parameters:
- name: setEnvironment
  type: string
  default: ''
- name: skipComponentTest
  type: boolean
  default: True
- name: skipPackage
  type: boolean
  default: True
- name: skipDeploy
  type: boolean
  default: True
- name : notifyChangelog
  type: boolean
  default: False

## -> Resources:
resources:
  repositories:
  - repository: FortifyExclusion
    name: DevOps/Vivo.Fortify.Exclusions
    type: git
    ref: refs/heads/master
    endpoint: CorePipelines
  - repository: CorePipelines
    name: DevOps/Vivo.Core.Pipelines
    type: git
    ref: refs/tags/latest
    endpoint: CorePipelines

## -> Initialize global variables
variables:

- template: /tech_products/ecmc/framework-brasil/appv/initialize/variables_global.yml
- template: /tech_products/ecmc/framework-brasil/appv/initialize/variables_nodejs.yml
- ${{ if ne(parameters.skipPackage, True) }}:
  - template: /tech_products/ecmc/framework-brasil/appv/initialize/variables_docker.yml

## -> Override global variables, with variables set in Library/Variable Groups (Pipelines)
## -> Use this to change the variables on runtime
- group: "${{ variables['Build.DefinitionName'] }}"

- name: CORPORATE_WIKI_DOC_URL
  value: "TBD"

stages:

## -> Initialize pipeline enviroment
- template: /tech_products/ecmc/framework-brasil/appv/initialize/nodejs_environment.yml

## -> Build for CI - NodeJS
- template: /tech_products/ecmc/framework-brasil/appv_storybook/templates/ci/ci_build_nodejs_appv_storybook.yml


## -> Publish Build for CI - NodeJS
- template: /tech_products/ecmc/framework-brasil/appv_storybook/templates/ci/ci_publish_nodejs_appv_storybook.yml
- ${{ if eq(parameters.notifyChangelog, True) }}:
  - template: /tech_products/ecmc/framework-brasil/appv/templates/ci/ci_changelog_notification_appv.yml
