parameters:
- name: blue_green
  type: string
  default: 'Não'
  values:
  - 'Não'
  - 'Sim'
- name: environment_for_deploy
  type: string
  default: d15
  values:
  - p1
  - s1
  - s2
  - s3
  - d1
  - d2
  - d3
  - d4
  - d5
  - d6
  - d7
  - d8
  - d9
  - d10
  - d11
  - d12
  - d13
  - d14
  - d15
jobs:
- job: task_manual
  displayName: "${{ parameters.environment_for_deploy }} - Aprovação para Deploy Blue/Green"
  dependsOn:
  - verificar_deploy_job
  - acompanhar_deploy_job
  condition: eq('${{ parameters.blue_green }}', 'Sim')
  pool: server
  timeoutInMinutes: 120
  steps:
  - task: ManualValidation@1
    inputs:
      instructions: "Aprovar ou rejeitar o deploy blue/green"
      onTimeout: 'reject'
    name: validacao_manual
