parameters:
- name: workDir
  default: $(Build.SourcesDirectory)

steps:
- bash: |
     echo "##[debug] Pipeline workSpace is: $(Pipeline.Workspace)"
     echo "##[debug] Param WorkDir is: ${{ parameters.workDir }}"
     ch_path=$(realpath -s --relative-to=$(Pipeline.Workspace) ${{ parameters.workDir }})
     echo "##vso[task.setvariable variable=checkoutPath;]$ch_path"
     echo "##[debug] External-Env checkoutPath is: $ch_path"
  displayName: "Set External-Env checkout path"

- checkout: ExternalizedEnv
  path: $(checkoutPath)
  clean: false
  persistCredentials: true
  displayName: "Checkout External-Env repo for deploy"