parameters:
- name: newVersion
  type: string
- name: condition
  type: object
- name: createGitTag
  type: boolean
  default: true

steps:
- template: /tech_products/srus/tasks/versioning/update_repo_version_frontend.yml
  parameters:
    condition: ${{ parameters.condition }}
    componentNewVersion: ${{ parameters.newVersion }}
    createGitTag: ${{ parameters.createGitTag }}
    bashScript: 
      content: |
        cd $(Build.SourcesDirectory)/$(Build.Repository.Name)

        echo "##[debug] Update Repository Version:"
        
        # A versão utilizada do NPM é a versão default do Node.js nos agentes
        # Caso seja necessário uma versão diferente, é necessário adicionar o .tool-versions (ASDF)na pasta do projeto 
        npm --no-git-tag-version version ${NEW_VERSION} --allow-same-version
      envs:
        NEW_VERSION: ${{ parameters.newVersion }}