parameters:
- name: private_agent_pool
- name: environment
- name: kubeconfig
- name: git_tag
- name: helm_release_name_prefix
- name: skip_deploy
  default: false
- name: useExternalEnv
  default: false
- name: azureServiceConnectionEnabled
  default: false
- name: kubernetesServiceConnectionEnabled
  default: false

stages:
- stage: deploy
  dependsOn:
  - validation
  pool: ${{ parameters.private_agent_pool }}
  displayName: "Deploy ${{ parameters.environment }}"
  jobs:
  - deployment: ${{ parameters.environment }}
    condition: and(always(), eq(variables.flowIsTagging, false), eq(variables.flowIsMain, true))
    workspace:
      clean: all
    displayName: Deploy
    environment: "deploy-${{ parameters.environment }}"
    strategy:
      runOnce:      
        deploy:
          steps:
          - checkout: self
          - template: /tasks/git/checkout_master_deploy.yml
          - ${{ if or(eq(parameters.azureServiceConnectionEnabled, true), eq(parameters.kubernetesServiceConnectionEnabled, true)) }}:
            - template: /task_groups/deploy/run_deploy_with_service_connection.yml
              parameters:
                environment: ${{ parameters.environment }}
                helmReleaseNamePrefix: ${{ parameters.helm_release_name_prefix }}
                useExternalEnv: ${{ parameters.useExternalEnv }}
                azureServiceConnectionEnabled: ${{ parameters.azureServiceConnectionEnabled }}
                kubernetesServiceConnectionEnabled: ${{ parameters.kubernetesServiceConnectionEnabled }}
          - ${{ else }}:
            - template: /task_groups/deploy/run_deploy.yml
              parameters:
                environment: ${{ parameters.environment }}
                kubeconfig: ${{ parameters.kubeconfig }}
                helmReleaseNamePrefix: ${{ parameters.helm_release_name_prefix }}
                useExternalEnv: ${{ parameters.useExternalEnv }}
        on:
          success:
            steps:
            - ${{ if and( not(startsWith(variables['Build.SourceBranch'], 'refs/tags')), eq(parameters.git_tag, 'true') ) }}:
              - template: /task_groups/deploy/run_pos_deploy_success.yml
                parameters:
                  environment: ${{ parameters.environment }}
            - template: /task_groups/governance/check_govapp_policies.yml
              parameters:
                govAppBreakglass: false
                govAppOperation: "deploy"
                continueOnError: false
                environment: ${{ parameters.environment }}
                stack: "JAVA"
              
          failure:
            steps:
            - template: /task_groups/deploy/run_pos_deploy_failure.yml