stages:
- stage: validation
  displayName: "Validation"
  dependsOn:
  - gate
  - security
  condition: and(in(dependencies.gate.result, 'Succeeded', 'SucceededWithIssues', 'Skipped'), in(dependencies.security.result, 'Succeeded', 'SucceededWithIssues', 'Skipped'), in(dependencies.build_test.result, 'Succeeded', 'SucceededWithIssues')) # targets the result of the previous job 
  pool: $(PRIVATE_AGENT_DEFAULT)
  jobs:
    - job: liquibase_validation
      condition: succeeded()
      displayName: "Liquibase Validation"
      steps:
      - template: /tech_products/srus/tasks/bash/welcome.yml
        parameters:
          message: $(DB_VALIDATION_WELCOME_MSG)
      - template: /tech_products/srus/task_groups/validation/liquibase_validation.yml
