parameters:
- name: environment
  type: string
  values:
  - esteira1
  - esteira2
  - preprod
  - prodlike

stages:
- ${{ if in(variables['Build.SourceBranch'], 'refs/heads/main', 'refs/heads/master') }}:
  ## DEPLOY AUTOMATICO
  - template: /tech_products/orss/soa-refactor/stages/deploy.yml
    parameters:
      environment: esteira1

  - template: /tech_products/orss/soa-refactor/stages/deploy.yml
    parameters:
      environment: esteira2
  
  - template: /tech_products/orss/soa-refactor/stages/deploy.yml
    parameters:
      environment: preprod

  - template: /tech_products/orss/soa-refactor/stages/deploy.yml
    parameters:
      environment: prodlike

- ${{ elseif startsWith(variables['Build.SourceBranch'], 'refs/tags/') }}:
  ## DEPLOY MANUAL
  - template: /tech_products/orss/soa-refactor/stages/prepare_deploy.yml
    parameters:
      environment: ${{ parameters.environment }}

  - template: /tech_products/orss/soa-refactor/stages/deploy.yml
    parameters:
      environment: ${{ parameters.environment }}

- ${{ else }}:
  - template: /tech_products/orss/soa-refactor/stages/complete_pr.yml

  - template: /tech_products/orss/soa-refactor/stages/prepare_deploy.yml
    parameters:
      environment: esteira1
  
  - template: /tech_products/orss/soa-refactor/stages/deploy.yml
    parameters:
      environment: esteira1

  - template: /tech_products/orss/soa-refactor/stages/deploy.yml
    parameters:
      environment: esteira2
  
  - template: /tech_products/orss/soa-refactor/stages/deploy.yml
    parameters:
      environment: preprod

  - template: /tech_products/orss/soa-refactor/stages/deploy.yml
    parameters:
      environment: prodlike

- ${{ else }}:
  - stage: Error
    jobs:
    - job: Error
      steps:  
      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: |
            script: |
              print("##vso[task.logissue type=error;]Do Not Run Pipelines Without a Pull Request")
              print("##vso[task.complete result=Failed;]Text")