stages:
- stage: gates_environment_init
  displayName: "CI - Gates - Environment"
  pool:
    name: GeneralPurposeLinuxAgentsCI

  jobs:      

  - job: environment
    displayName: Set up environment
    steps: 

    ## -> Checkout code
    - checkout: none    

    ## -> Download SONARQUBE Token
    - task: AzureKeyVault@2  
      displayName: 'Getting AKV credentials'
      timeoutInMinutes: 1
      retryCountOnTaskFailure: 5  
      inputs:    
        azureSubscription: DevOpsSharedResources    
        KeyVaultName: $(AKV_DEVOPS_NAME)
        SecretsFilter: 'SONARQUBE-TOKEN'
     
    ## -> Set SONARQUBE credentials to variables. This allows it to used in other stages, jobs or tasks.
    - task: Bash@3
      displayName: 'Set Credentials Variables'
      name: sonarqube_credentials
      condition: succeeded()
      continueOnError: false
      inputs:
        targetType: inline
        script: |
          echo "##[group] Secrets for SONARQUBE"

          echo "##[debug] SONARQUBE-TOKEN: $(SONARQUBE-TOKEN). Use as >> SONARQUBE_TOKEN. "
          echo "##vso[task.setvariable variable=SONARQUBE_TOKEN;isOutput=true;isSecret=true]$(SONARQUBE-TOKEN)"

          echo "##[endgroup]"
          echo "##[debug] To open and check the information above, click the arrows on the left."
        KeyVaultName: $(AKV_DEVOPS_NAME)
        SecretsFilter: 'SONARQUBE-TOKEN'

    ## -> Download Fortify Token
    - task: AzureKeyVault@2
      displayName: 'Getting AKV credentials'
      timeoutInMinutes: 1
      retryCountOnTaskFailure: 5  
      inputs:    
        azureSubscription: DevOpsSharedResources    
        KeyVaultName: $(AKV_DEVOPS_NAME)
        SecretsFilter: 'FORTIFY-SSC-CLI-TOKEN, FORTIFY-SCANCENTRAL-CLIENT-TOKEN'

     ## -> Set Fortify credentials to variables. This allows it to used in other stages, jobs or tasks.
    - task: Bash@3
      displayName: 'Set Credentials Variables'
      name: fortify_credentials
      condition: succeeded()
      continueOnError: false
      inputs:
        targetType: inline
        script: |
          echo "##[group] Secrets for Fortify"
          
          echo "##[debug] FORTIFY-SSC-CLI-TOKEN: $(FORTIFY-SSC-CLI-TOKEN). Use as >> FORTIFY_SSC_CLI_TOKEN. "
          echo "##vso[task.setvariable variable=FORTIFY_SSC_CLI_TOKEN;isOutput=true;isSecret=true]$(FORTIFY-SSC-CLI-TOKEN)"

          echo "##[debug] FORTIFY-SCANCENTRAL-CLIENT-TOKEN: $(FORTIFY-SCANCENTRAL-CLIENT-TOKEN). Use as >> FORTIFY_SCANCENTRAL_CLIENT_TOKEN. "
          echo "##vso[task.setvariable variable=FORTIFY_SCANCENTRAL_CLIENT_TOKEN;isOutput=true;isSecret=true]$(FORTIFY-SSC-CLI-TOKEN)"

          echo "##[endgroup]"
          echo "##[debug] To open and check the information above, click the arrows on the left."
        KeyVaultName: $(AKV_DEVOPS_NAME)
        SecretsFilter: 'SONARQUBE-TOKEN'
    
    - task: Bash@3
      displayName: 'Generate Azure App Configuration Keys'
      name: azure_app_configuration_keys
      condition: succeeded()
      continueOnError: false
      inputs:
        targetType: inline
        script: |

          REPO_ID="`echo $(Build.Repository.ID) | tr '-' '_'`"
          REPO_NAME="$(Build.Repository.Name)"
          TEAM_PROJECT_NAME="$(System.TeamProject)"
          TEAM_PROJECT_ID="`echo $(System.TeamProjectId) | tr '-' '_'`"
          
          LABEL_GLOBAL="GLOBAL"
          KEY_GLOBAL_FORTIFY="FORTIFY"
          KEY_GLOBAL_CONVISO="CONVISO"
          KEY_GLOBAL_CHECKMARX="CHECKMARX"
          KEY_GLOBAL_SKIP_SECURITY_GATE="SKIP_SECURITY_GATE"
          
          LABEL_PROJECT="$TEAM_PROJECT_NAME"
          KEY_PROJECT_FORTIFY=$(echo "FORTIFY_$TEAM_PROJECT_ID" | awk 'BEGIN { getline; print toupper($0) }')
          KEY_PROJECT_CONVISO=$(echo "CONVISO_$TEAM_PROJECT_ID" | awk 'BEGIN { getline; print toupper($0) }')
          KEY_PROJECT_CHECKMARX=$(echo "CHECKMARX_$TEAM_PROJECT_ID" | awk 'BEGIN { getline; print toupper($0) }')
          KEY_PROJECT_SKIP_SECURITY_GATE=$(echo "SKIP_SECURITY_GATE_$TEAM_PROJECT_ID" | awk 'BEGIN { getline; print toupper($0) }')
          
          LABEL_COMPONENT="$TEAM_PROJECT_NAME/$REPO_NAME"
          KEY_COMPONENT_FORTIFY=$(echo "FORTIFY_$REPO_ID" | awk 'BEGIN { getline; print toupper($0) }')
          KEY_COMPONENT_CONVISO=$(echo "CONVISO_$REPO_ID" | awk 'BEGIN { getline; print toupper($0) }')
          KEY_COMPONENT_CHECKMARX=$(echo "CHECKMARX_$REPO_ID" | awk 'BEGIN { getline; print toupper($0) }')
          KEY_COMPONENT_SKIP_SECURITY_GATE=$(echo "SKIP_SECURITY_GATE_$REPO_ID" | awk 'BEGIN { getline; print toupper($0) }')
          
          echo "##[debug] LABEL_GLOBAL.......................: $LABEL_GLOBAL"
          echo "##[debug] KEY_GLOBAL_FORTIFY.................: $KEY_GLOBAL_FORTIFY"
          echo "##[debug] KEY_GLOBAL_CONVISO.................: $KEY_GLOBAL_CONVISO"
          echo "##[debug] KEY_GLOBAL_CHECKMARX...............: $KEY_GLOBAL_CHECKMARX"
          echo "##[debug] KEY_GLOBAL_SKIP_SECURITY_GATE......: $KEY_GLOBAL_SKIP_SECURITY_GATE"
          echo ""
          
          echo "##[debug] LABEL_PROJECT......................: $LABEL_PROJECT"
          echo "##[debug] KEY_PROJECT_FORTIFY................: $KEY_PROJECT_FORTIFY"
          echo "##[debug] KEY_PROJECT_CONVISO................: $KEY_PROJECT_CONVISO"
          echo "##[debug] KEY_PROJECT_CHECKMARX..............: $KEY_PROJECT_CHECKMARX"
          echo "##[debug] KEY_PROJECT_SKIP_SECURITY_GATE.....: $KEY_PROJECT_SKIP_SECURITY_GATE"
          echo ""
          
          echo "##[debug] LABEL_COMPONENT....................: $LABEL_COMPONENT"
          echo "##[debug] KEY_COMPONENT_FORTIFY..............: $KEY_COMPONENT_FORTIFY"
          echo "##[debug] KEY_COMPONENT_CONVISO..............: $KEY_COMPONENT_CONVISO"
          echo "##[debug] KEY_COMPONENT_CHECKMARX............: $KEY_COMPONENT_CHECKMARX"
          echo "##[debug] KEY_COMPONENT_SKIP_SECURITY_GATE...: $KEY_COMPONENT_SKIP_SECURITY_GATE"
          echo ""
          
          echo "##vso[task.setvariable variable=OUT_LABEL_GLOBAL]$LABEL_GLOBAL"
          echo "##vso[task.setvariable variable=OUT_KEY_GLOBAL_FORTIFY]$KEY_GLOBAL_FORTIFY"
          echo "##vso[task.setvariable variable=OUT_KEY_GLOBAL_CONVISO]$KEY_GLOBAL_CONVISO"
          echo "##vso[task.setvariable variable=OUT_KEY_GLOBAL_CHECKMARX]$KEY_GLOBAL_CHECKMARX"
          echo "##vso[task.setvariable variable=OUT_KEY_GLOBAL_SKIP_SECURITY_GATE]$KEY_GLOBAL_SKIP_SECURITY_GATE"
          
          echo "##vso[task.setvariable variable=OUT_LABEL_PROJECT]$LABEL_PROJECT"
          echo "##vso[task.setvariable variable=OUT_KEY_PROJECT_FORTIFY]$KEY_PROJECT_FORTIFY"
          echo "##vso[task.setvariable variable=OUT_KEY_PROJECT_CONVISO]$KEY_PROJECT_CONVISO"
          echo "##vso[task.setvariable variable=OUT_KEY_PROJECT_CHECKMARX]$KEY_PROJECT_CHECKMARX"
          echo "##vso[task.setvariable variable=OUT_KEY_PROJECT_SKIP_SECURITY_GATE]$KEY_PROJECT_SKIP_SECURITY_GATE"
          
          echo "##vso[task.setvariable variable=OUT_LABEL_COMPONENT]$LABEL_COMPONENT"
          echo "##vso[task.setvariable variable=OUT_KEY_COMPONENT_FORTIFY]$KEY_COMPONENT_FORTIFY"
          echo "##vso[task.setvariable variable=OUT_KEY_COMPONENT_CONVISO]$KEY_COMPONENT_CONVISO"
          echo "##vso[task.setvariable variable=OUT_KEY_COMPONENT_CHECKMARX]$KEY_COMPONENT_CHECKMARX"
          echo "##vso[task.setvariable variable=OUT_KEY_COMPONENT_SKIP_SECURITY_GATE]$KEY_COMPONENT_SKIP_SECURITY_GATE"
        
    # - task: AzureAppConfiguration.azure-app-configuration-task.custom-build-release-task.AzureAppConfiguration@6
    #   displayName: 'Download Azure App Configuration keys'
    #   condition: and(
    #     succeeded(), 
    #     eq(variables['AZURE_APP_CONFIGURATION_ENABLED'], 'true'))
    #   timeoutInMinutes: 1
    #   retryCountOnTaskFailure: 5
    #   inputs:
    #     azureSubscription: $(AZURE_APP_CONFIGURATION_AZURE_SUBSCRIPTION)
    #     AppConfigurationEndpoint: $(AZURE_APP_CONFIGURATIN_ENDPOINT)
    #     Label: '$(OUT_LABEL_GLOBAL),$(OUT_LABEL_PROJECT),$(OUT_LABEL_COMPONENT)'
    #   env:
    #     HTTPS_PROXY: $(PROXY_AGENT_HTTPS)
    #     HTTP_PROXY: $(PROXY_AGENT_HTTP)
    #     NO_PROXY: $(PROXY_AGENT_NO_PROXY)

    - task: Bash@3
      displayName: 'Validate Azure App Configuration Keys'      
      condition: and(
       succeeded(),
       eq(variables['AZURE_APP_CONFIGURATION_ENABLED'], 'true'))
      continueOnError: false
      inputs:
        targetType: inline
        script: |
        
          get_app_configuration_key() {
              VAR_NAME="$1";
              DEFAULT_VALUE="$2"
              eval VAR_VALUE="\$$VAR_NAME";
              [ -z "$VAR_VALUE" ] && echo "$DEFAULT_VALUE" || echo "$VAR_VALUE"
          }
          
          GLOBAL_FORTIFY_VALUE=`get_app_configuration_key $OUT_KEY_GLOBAL_FORTIFY "true"`
          GLOBAL_CONVISO_VALUE=`get_app_configuration_key $OUT_KEY_GLOBAL_CONVISO "false"`
          GLOBAL_CHECKMARX_VALUE=`get_app_configuration_key $OUT_KEY_GLOBAL_CHECKMARX "false"`
          GLOBAL_SKIP_SECURITY_GATE_VALUE=`get_app_configuration_key $OUT_KEY_GLOBAL_SKIP_SECURITY_GATE "false"`
          
          PROJECT_FORTIFY_VALUE=`get_app_configuration_key $OUT_KEY_PROJECT_FORTIFY "true"`
          PROJECT_CONVISO_VALUE=`get_app_configuration_key $OUT_KEY_PROJECT_CONVISO "false"`
          PROJECT_CHECKMARX_VALUE=`get_app_configuration_key $OUT_KEY_PROJECT_CHECKMARX "false"`
          PROJECT_SKIP_SECURITY_GATE_VALUE=`get_app_configuration_key $OUT_KEY_PROJECT_SKIP_SECURITY_GATE "false"`
          
          COMPONENT_FORTIFY_VALUE=`get_app_configuration_key $OUT_KEY_COMPONENT_FORTIFY "true"`
          COMPONENT_CONVISO_VALUE=`get_app_configuration_key $OUT_KEY_COMPONENT_CONVISO "false"`
          COMPONENT_CHECKMARX_VALUE=`get_app_configuration_key $OUT_KEY_COMPONENT_CHECKMARX "false"`
          COMPONENT_SKIP_SECURITY_GATE_VALUE=`get_app_configuration_key $OUT_KEY_COMPONENT_SKIP_SECURITY_GATE "false"`
          
          echo "##[debug] GLOBAL VARIABLES"
          echo "##[debug] OUT_KEY_GLOBAL_FORTIFY.................: $GLOBAL_FORTIFY_VALUE"
          echo "##[debug] OUT_KEY_GLOBAL_CONVISO.................: $GLOBAL_CONVISO_VALUE"
          echo "##[debug] OUT_KEY_GLOBAL_CHECKMARX...............: $GLOBAL_CHECKMARX_VALUE"
          echo "##[debug] OUT_KEY_GLOBAL_SKIP_SECURITY_GATE......: $GLOBAL_SKIP_SECURITY_GATE_VALUE"
          echo ""
          
          echo "##[debug] PROJECT VARIABLES"
          echo "##[debug] OUT_KEY_PROJECT_FORTIFY................: $PROJECT_FORTIFY_VALUE"
          echo "##[debug] OUT_KEY_PROJECT_CONVISO................: $PROJECT_CONVISO_VALUE"
          echo "##[debug] OUT_KEY_PROJECT_CHECKMARX..............: $PROJECT_CHECKMARX_VALUE"
          echo "##[debug] OUT_KEY_PROJECT_SKIP_SECURITY_GATE.....: $PROJECT_SKIP_SECURITY_GATE_VALUE"
          echo ""
          
          echo "##[debug] COMPONENT VARIABLES"
          echo "##[debug] OUT_KEY_COMPONENT_FORTIFY..............: $COMPONENT_FORTIFY_VALUE"
          echo "##[debug] OUT_KEY_COMPONENT_CONVISO..............: $COMPONENT_CONVISO_VALUE"
          echo "##[debug] OUT_KEY_COMPONENT_CHECKMARX............: $COMPONENT_CHECKMARX_VALUE"
          echo "##[debug] OUT_KEY_COMPONENT_SKIP_SECURITY_GATE...: $COMPONENT_SKIP_SECURITY_GATE_VALUE"
          echo ""
          
          echo "AGENT_TEMPDIRECTORY: ${AGENT_TEMPDIRECTORY}"

          cat <<EOF > ${AGENT_TEMPDIRECTORY}/app_config_vars.json
          {
            "items": [
              {"key": "$OUT_KEY_GLOBAL_FORTIFY","value": "$GLOBAL_FORTIFY_VALUE","label": "$OUT_LABEL_GLOBAL","content_type": null,"tags": {}},
              {"key": "$OUT_KEY_GLOBAL_CONVISO","value": "$GLOBAL_CONVISO_VALUE","label": "$OUT_LABEL_GLOBAL","content_type": null,"tags": {}},
              {"key": "$OUT_KEY_GLOBAL_CHECKMARX","value": "$GLOBAL_CHECKMARX_VALUE","label": "$OUT_LABEL_GLOBAL","content_type": null,"tags": {}},
              {"key": "$OUT_KEY_GLOBAL_SKIP_SECURITY_GATE","value": "$GLOBAL_SKIP_SECURITY_GATE_VALUE","label": "$OUT_LABEL_GLOBAL","content_type": null,"tags": {}},
              {"key": "$OUT_KEY_PROJECT_FORTIFY", "value": "$PROJECT_FORTIFY_VALUE","label": "$OUT_LABEL_PROJECT","content_type": null,"tags": {}},
              {"key": "$OUT_KEY_PROJECT_CONVISO","value": "$PROJECT_CONVISO_VALUE","label": "$OUT_LABEL_PROJECT","content_type": null,"tags": {}},
              {"key": "$OUT_KEY_PROJECT_CHECKMARX","value": "$PROJECT_CHECKMARX_VALUE","label": "$OUT_LABEL_PROJECT","content_type": null,"tags": {}},
              {"key": "$OUT_KEY_PROJECT_SKIP_SECURITY_GATE","value": "$PROJECT_SKIP_SECURITY_GATE_VALUE","label": "$OUT_LABEL_PROJECT","content_type": null,"tags": {}},
              {"key": "$OUT_KEY_COMPONENT_FORTIFY","value": "$COMPONENT_FORTIFY_VALUE","label": "$OUT_LABEL_COMPONENT","content_type": null,"tags": {}},
              {"key": "$OUT_KEY_COMPONENT_CONVISO","value": "$COMPONENT_CONVISO_VALUE","label": "$OUT_LABEL_COMPONENT","content_type": null,"tags": {}},
              {"key": "$OUT_KEY_COMPONENT_CHECKMARX","value": "$COMPONENT_CHECKMARX_VALUE","label": "$OUT_LABEL_COMPONENT","content_type": null,"tags": {}},
              {"key": "$OUT_KEY_COMPONENT_SKIP_SECURITY_GATE","value": "$COMPONENT_SKIP_SECURITY_GATE_VALUE","label": "$OUT_LABEL_COMPONENT","content_type": null,"tags": {}}
            ]
          }
          EOF

    # - task: AzureAppConfiguration.azure-app-configuration-task-push.custom-build-release-task.AzureAppConfigurationPush@6
    #   displayName: 'Push Azure App Configuration Keys'
    #   condition: and(
    #     succeeded(),
    #     eq(variables['AZURE_APP_CONFIGURATION_ENABLED'], 'true'))
    #   inputs:
    #     azureSubscription: $(AZURE_APP_CONFIGURATION_AZURE_SUBSCRIPTION)
    #     AppConfigurationEndpoint: $(AZURE_APP_CONFIGURATIN_ENDPOINT)
    #     ConfigurationFile: '$(Agent.TempDirectory)/app_config_vars.json'
    #     FileContentProfile: appconfig/kvset
    #   env:
    #     HTTPS_PROXY: $(PROXY_AGENT_HTTPS)
    #     HTTP_PROXY: $(PROXY_AGENT_HTTP)
    #     NO_PROXY: $(PROXY_AGENT_NO_PROXY)

    - task: Bash@3
      displayName: 'Validate Azure App Configuration Keys'
      name: evaluate_flags
      condition: succeeded()
      continueOnError: false
      inputs:
        targetType: inline
        script: |
       
          getvar() {
              VAR_NAME="$1"; 
              eval VAR_VALUE="\$$VAR_NAME"; 
              [ -z "$VAR_VALUE" ] && echo "false" || echo "$VAR_VALUE"
          }
          
          USE_FORTIFY=false
          USE_CONVISO=false
          USE_CHECKMARX=false
          SKIP_GATE=false
          USE_APPCONFIG="$(AZURE_APP_CONFIGURATION_ENABLED)"
          
          if [ "$USE_APPCONFIG" = "true" ]; then
            # FORTIFY SETTING
            FORTIFY_GLOBAL="$(getvar $OUT_KEY_GLOBAL_FORTIFY)"
            FORITFY_PROJECT="$(getvar "$OUT_KEY_PROJECT_FORTIFY" )"
            FORTIFY_COMPONENT="$(getvar $OUT_KEY_COMPONENT_FORTIFY)"
            if [ "$FORTIFY_GLOBAL" = "true" ] && [ "$FORITFY_PROJECT" = "true" ] && [ "$FORTIFY_COMPONENT" = "true" ]; then
                USE_FORTIFY=true
            fi
            
            # CONVISO SETTING
            CONVISO_GLOBAL="$(getvar $OUT_KEY_GLOBAL_CONVISO)"
            CONVISO_PROJECT="$(getvar $OUT_KEY_PROJECT_CONVISO)"
            CONVISO_COMPONENT="$(getvar $OUT_KEY_COMPONENT_CONVISO)"
            if [ "$CONVISO_GLOBAL" = "true" ] && [ "$CONVISO_PROJECT" = "true" ] && [ "$CONVISO_COMPONENT" = "true" ]  && [ "$USE_FORTIFY" = "true" ]; then
                USE_CONVISO=true
            fi
            
            # CHECKMARX SETTING
            CHECKMARX_GLOBAL="$(getvar $OUT_KEY_GLOBAL_CHECKMARX)"
            CHECKMARX_PROJECT="$(getvar $OUT_KEY_PROJECT_CHECKMARX)"
            CHECKMARX_COMPONENT="$(getvar $OUT_KEY_COMPONENT_CHECKMARX)"
            if [ "$CHECKMARX_GLOBAL" = "true" ] && [ "$CHECKMARX_PROJECT" = "true" ] && [ "$CHECKMARX_COMPONENT" = "true" ]; then
                USE_CHECKMARX=true
                USE_FORTIFY=false
                USE_CONVISO=false
            fi

            # SKIP_SECURITY_GATE SETTING
            SKIP_SECURITY_GATE_GLOBAL="$(getvar $OUT_KEY_GLOBAL_SKIP_SECURITY_GATE)"
            SKIP_SECURITY_GATE_PROJECT="$(getvar $OUT_KEY_PROJECT_SKIP_SECURITY_GATE)"
            SKIP_SECURITY_GATE_COMPONENT="$(getvar $OUT_KEY_COMPONENT_SKIP_SECURITY_GATE)"
            if [ "$SKIP_SECURITY_GATE_GLOBAL" = "true" ] || [ "$SKIP_SECURITY_GATE_PROJECT" = "true" ] || [ "$SKIP_SECURITY_GATE_COMPONENT" = "true" ]; then
                SKIP_GATE=true
            fi

            echo "##[debug] GLOBAL VARIABLES"
            echo "##[debug] FORTIFY_GLOBAL................: $FORTIFY_GLOBAL"
            echo "##[debug] CONVISO_GLOBAL................: $CONVISO_GLOBAL"
            echo "##[debug] CHECKMARX_GLOBAL..............: $CHECKMARX_GLOBAL"
            echo "##[debug] SKIP_SECURITY_GATE_GLOBAL.....: $SKIP_SECURITY_GATE_GLOBAL"
            echo ""
            
            echo "##[debug] PROJECT VARIABLES"
            echo "##[debug] FORITFY_PROJECT...............: $FORITFY_PROJECT"
            echo "##[debug] CONVISO_PROJECT...............: $CONVISO_PROJECT"
            echo "##[debug] CHECKMARX_PROJECT.............: $CHECKMARX_PROJECT"
            echo "##[debug] SKIP_SECURITY_GATE_PROJECT....: $SKIP_SECURITY_GATE_PROJECT"
            echo ""
            
            echo "##[debug] COMPONENT VARIABLES"
            echo "##[debug] FORTIFY_COMPONENT.............: $FORTIFY_COMPONENT"
            echo "##[debug] CONVISO_COMPONENT.............: $CONVISO_COMPONENT"
            echo "##[debug] CHECKMARX_COMPONENT...........: $CHECKMARX_COMPONENT"
            echo "##[debug] SKIP_SECURITY_GATE_COMPONENT..: $SKIP_SECURITY_GATE_COMPONENT"
            echo ""
            
            echo "##[debug] USE_FORTIFY..........: $USE_FORTIFY"
            echo "##[debug] USE_CONVISO..........: $USE_CONVISO"
            echo "##[debug] USE_CHECKMARX........: $USE_CHECKMARX"
            echo "##[debug] SKIP_SECURITY_GATE...: $SKIP_GATE"
            echo ""
          else
            USE_FORTIFY="false"
            USE_CONVISO="false"
            USE_CHECKMARX="$(USE_CHECKMARX)"
            SKIP_GATE="$(SKIP_SECURITY_GATE)"

            SKIP_SECURITY="$(skip_security)"
            SKIP_FORTIFY_GATE="$(skip_fortify_gate)"
            SKIP_CONVISO_SECURITY_GATE="$(SKIP_CONVISO_SECURITY_GATE)"

            if [ "$SKIP_SECURITY" != "true" ]; then

              if [ "$SKIP_FORTIFY_GATE" != 'true' ]; then
                USE_FORTIFY="true"
              fi

              if [ "$SKIP_CONVISO_SECURITY_GATE" != 'true' ]; then
                USE_CONVISO="true"
              fi

              if [ "$USE_CHECKMARX" = 'true' ]; then
                USE_FORTIFY="false"
                USE_CONVISO="false"
              fi
            else
              USE_CHECKMARX="false"
            fi

            echo "##[debug] SKIP_SECURITY...............: $SKIP_SECURITY"
            echo "##[debug] SKIP_FORTIFY_GATE...........: $SKIP_FORTIFY_GATE"
            echo "##[debug] SKIP_CONVISO_SECURITY_GATE..: $SKIP_CONVISO_SECURITY_GATE"
            echo ""

            echo "##[debug] USE_FORTIFY..........: $USE_FORTIFY"
            echo "##[debug] USE_CONVISO..........: $USE_CONVISO"
            echo "##[debug] USE_CHECKMARX........: $USE_CHECKMARX"
            echo "##[debug] SKIP_SECURITY_GATE...: $SKIP_GATE"
            echo ""
          fi

          echo "##vso[task.setvariable variable=USE_FORTIFY;isOutput=true;]$USE_FORTIFY"
          echo "##vso[task.setvariable variable=USE_CONVISO;isOutput=true;]$USE_CONVISO"
          echo "##vso[task.setvariable variable=USE_CHECKMARX;isOutput=true;]$USE_CHECKMARX"
          echo "##vso[task.setvariable variable=SKIP_SECURITY_GATE;isOutput=true;]$SKIP_GATE"