parameters:
- name: currentVersion
  type: string
- name: newVersionVariableOut
  type: string
- name: incrementLevel
  type: string
  values:
    - major
    - minor
    - patch
    - prerelease
  default: patch
- name: bumpVersionOnManual
  type: boolean
  default: false

steps:
  - bash: |
      cd $(Build.SourcesDirectory)/$(Build.Repository.Name)
      # CURRENT_VERSION=$(cat VERSION)
      CURRENT_VERSION=$(GET_VERSION_FILE)
      SET_VERSION=$(date '+%Y%m%d.%H%M%S') 
      echo -n $SET_VERSION > VERSION
      echo "Nova versão: $SET_VERSION"
      echo "##vso[task.setvariable variable=NEW_VERSION;]$SET_VERSION"
      echo "##vso[task.setvariable variable=COMPONENT_VERSION;]$SET_VERSION"
    name: upgrade_version_file
    displayName: 'Bump Version file'
    condition: and(
                eq(variables.USE_VERSION_FILE, 'true'),
                eq(variables.flowIsQa, True),
                or(
                  and(succeeded(), eq(variables.BUMP_VERSION_ENABLED, 'true'), eq(variables['Build.Reason'], 'IndividualCI')), 
                  and(succeeded(), eq(variables.BUMP_VERSION_ENABLED, 'true'), eq(variables['Build.Reason'], 'BatchedCI')),
                  and(succeeded(), eq(${{ parameters.bumpVersionOnManual }}, true), eq(variables['Build.Reason'], 'Manual'))
                )
              )
  
  - bash: |
      CURRENT_VERSION=$(date '+%Y%m%d.%H%M%S') 
      NEW_VERSION=$CURRENT_VERSION
      echo "##[command]New version is $NEW_VERSION"
      echo "##vso[task.setvariable variable=NEW_VERSION;isOutput=true]$NEW_VERSION"
      echo "##vso[task.setvariable variable=COMPONENT_VERSION;]$NEW_VERSION"
      echo "##[command]Setting variable 'COMPONENT_VERSION': $NEW_VERSION"
    name: set_custom_version_gitflow
    displayName: 'Bump Custom Version '
    condition: and(
                succeeded(),
                eq(variables.flowIsQa, True),
                eq(variables.flowIsTriggerCI, True)
              )

  - bash: |
      echo "##vso[task.setvariable variable=COMPONENT_VERSION]$COMPONENT_VERSION"
      echo "##[command]Setting variable 'COMPONENT_VERSION': $COMPONENT_VERSION"
    displayName: 'Set Current Version'
    env:
      COMPONENT_VERSION: ${{ parameters.currentVersion }}
    condition: or(eq(variables.flowIsMain, True), eq(variables.flowIsQa, True))

  - bash: |
      CURRENT_VERSION=$(GET_VERSION_FILE)
      IFS='.' read -ra VERSION_PARTS <<< "$CURRENT_VERSION"
      PATCH_VERSION=$((${VERSION_PARTS[2]} + 1))
      NEW_VERSION="${VERSION_PARTS[0]}.${VERSION_PARTS[1]}.${PATCH_VERSION}"
      echo "##[command]New version is $NEW_VERSION"
      echo "##vso[task.setvariable variable=NEW_VERSION;isOutput=true]$NEW_VERSION"
      echo "##vso[task.setvariable variable=COMPONENT_VERSION;]$NEW_VERSION"
      echo "##[command]Setting variable 'COMPONENT_VERSION': $NEW_VERSION"
    # name: set_custom_version_gitflow
    displayName: 'Bump version from $(Build.SourceBranch)'
    condition: and(
                succeeded(),
                eq(variables.flowIsMain, True),
                eq(variables.flowIsTriggerCI, True)
              )

  - bash: |
      echo "##vso[task.setvariable variable=SET_NEW_VERSION]${NEW_VERSION}"
      echo "##vso[task.setvariable variable=NEW_VERSION;isOutput=true]${NEW_VERSION}"
      echo "##vso[task.setvariable variable=NEW_VERSION_OUT;isOutput=true]${NEW_VERSION}"
      # echo "##[command]Exporting variable '\$NEW_VERSION': $NEW_VERSION"
      echo "##[command]Exporting variable '$NEW_VERSION_OUT': $NEW_VERSION"
    displayName: 'Defining New Component Version'
    name: component_bump_version
    env:
      NEW_VERSION: $(COMPONENT_VERSION)
      NEW_VERSION_OUT: "${{ parameters.newVersionVariableOut }}"