parameters:
- name: isCore
  type: boolean
  default: true
- name: workingDirectory
  type: string
  default: $(Build.SourcesDirectory)/$(Build.Repository.Name)

steps:
- ${{ if eq(parameters.isCore, 'true') }}:
  - bash: |
      verify_and_stop_if_error() {
        if [[ $1 != 0 ]]; then
          exit 1
        fi
      }
      if [[ "$NEW_VERSION_FILE" == "" ]]; then
        MSG="Problema ao recuperar a versão"
        echo "##[command]$MSG"
        echo "##vso[task.logissue type=error;] $MSG"
        echo "##vso[task.complete result=Failed;]"
        exit 1
      fi

      git config --replace-all user.name "Azure DevOps" && git config --replace-all user.email "azuredevops@telefonicati.onmicrosoft.com"
      GIT_CURRENT_SHA=$(git rev-parse HEAD)
  
      if [ "$USE_SEMANTIC_VERSION" == "true" ]; then
        echo "##[debug]<<<Tamplate semantic version on, Set version: $NEW_VERSION_FILE >>>"
      else
        echo "##[debug]<<<Tamplate semantic version off, Set version: $NEW_VERSION_FILE >>>"

        git reset --hard $GIT_CURRENT_SHA_AGGREGATOR
        echo "##[section]COMMIT HASH DO PROJETO: $GIT_CURRENT_SHA"
        echo -n $NEW_VERSION_FILE > VERSION
      fi

      cat VERSION
      git commit -am "[CI SKIP] Project version updated to ${NEW_VERSION_FILE}"
      verify_and_stop_if_error $(echo $?)
      CMD_RUN="push origin HEAD:$(PROJECT_SOURCE_BRANCH)"
      echo "##[command]git $CMD_RUN"
      git $CMD_RUN

      if [[ "$TAG_REPO" == "true" ]]; then
        CMD_TAG="tag $NEW_VERSION_FILE"
        echo "##[command]Enviando $CMD_TAG"
        git $CMD_TAG
        git push origin refs/tags/$NEW_VERSION_FILE
        if [ $? -ne 0 ]; then
          echo "##vso[task.logissue type=error;] Git push tag"
          echo "##vso[task.complete result=Failed;]"
          exit 1
        fi
      fi

      if [ $? -ne 0 ]; then
        echo "##vso[task.logissue type=error;] Git push failed"
        echo "##vso[task.complete result=Failed;]"
        exit 1
      fi
    displayName: "Update Version"
    name: core_new_version_commit
    condition: succeeded()