parameters:
- name: applicationFile
- name: organizationID
- name: userID

steps:
- script: |
    echo "##[debug] API_MANAGER_BASE_URL....: ${API_MANAGER_BASE_URL}"
    echo "##[debug] APPLICATION_FILE........: ${APPLICATION_FILE}"
    echo "##[debug] ORGANIZATION_ID.........: ${ORGANIZATION_ID}"
    echo "##[debug] USER_ID.................: ${USER_ID}"

    echo "##[command] POST /migrate/applications/import"
    curl -s -i -k --fail -X POST "${API_MANAGER_BASE_URL}/migrate/applications/import" \
    --user "${ADMIN_USERNAME}:${ADMIN_PASSWORD}" \
    --form "file=@${APPLICATION_FILE}" \
    --form "organizationId=${ORGANIZATION_ID}" \
    --form "userId=${USER_ID}" \
    --form "password=${DAT_FILE_PASSWORD}" \
    --form "uploadType=html"
  displayName: Import Application
  env:
    API_MANAGER_BASE_URL: $(API_MANAGER_BASE_URL)
    ADMIN_USERNAME: $(ADMIN_USERNAME)
    ADMIN_PASSWORD: $(ADMIN_PASSWORD)
    DAT_FILE_PASSWORD: $(DAT_FILE_PASSWORD)
    APPLICATION_FILE: ${{ parameters.applicationFile }}
    ORGANIZATION_ID: ${{ parameters.organizationID }}
    USER_ID: ${{ parameters.userID }}

