parameters:
- name: applicationID
- name: clientID
- name: corsOrigins
  default: "*"

steps:
- script: |
    echo "##[debug] API_MANAGER_BASE_URL.....: ${API_MANAGER_BASE_URL}"
    echo "##[debug] APPLICATION_ID...........: ${APPLICATION_ID}"
    echo "##[debug] CLIENT_ID................: ${CLIENT_ID}"

    echo "##[command] GET /applications/${APPLICATION_ID}/extclients"
    RESPONSE_CLIENT_ID=$(curl -s -k "${API_MANAGER_BASE_URL}/applications/${APPLICATION_ID}/extclients" \
    --user "${ADMIN_USERNAME}:${ADMIN_PASSWORD}" | jq -r '.[0].clientId // empty')

    if [[ "${RESPONSE_CLIENT_ID}" == "${CLIENT_ID}" ]]; then
      echo "##vso[task.logissue type=warning] Client ID already exists."
      echo "##[debug] RESPONSE_CLIENT_ID.......: ${RESPONSE_CLIENT_ID}"
      echo "##vso[task.complete result=SucceededWithIssues;]"
      exit
    fi

    echo "##[section] Client ID is valid to be created."
    echo "##vso[task.setvariable variable=isValidCredential]Yes"
  displayName: Validate External Credential
  env:
    API_MANAGER_BASE_URL: $(API_MANAGER_BASE_URL)
    ADMIN_USERNAME: $(ADMIN_USERNAME)
    ADMIN_PASSWORD: $(ADMIN_PASSWORD)
    APPLICATION_ID: ${{ parameters.applicationID }}
    CLIENT_ID: ${{ parameters.clientID }}

- script: |
    set -e

    request_body()
    {
      cat <<EOF
    {
      "enabled": true,
      "corsOrigins": ["${CORS_ORIGINS}"],
      "clientId": "${CLIENT_ID}"
    }
    EOF
    }

    echo "##[debug] Request Body"
    request_body

    echo "##[command] POST /applications/${APPLICATION_ID}/extclients"
    RESPONSE_HTTP_CODE=$(curl -s -k -o /dev/null -w "%{http_code}\n" "${API_MANAGER_BASE_URL}/applications/${APPLICATION_ID}/extclients" \
    --user "${ADMIN_USERNAME}:${ADMIN_PASSWORD}" \
    --header "content-type: application/json" \
    --data-raw "$(request_body)")

    if [ ${RESPONSE_HTTP_CODE} -eq 409 ] ; then
      echo "##[debug] RESPONSE_HTTP_CODE.......: ${RESPONSE_HTTP_CODE}"
      echo "##vso[task.logissue type=error] Client ID already exists for another Application."
      exit 1
    fi
  displayName: Create External Credentials
  condition: and(succeeded(), eq(variables.isValidCredential, 'Yes'))
  env:
    API_MANAGER_BASE_URL: $(API_MANAGER_BASE_URL)
    ADMIN_USERNAME: $(ADMIN_USERNAME)
    ADMIN_PASSWORD: $(ADMIN_PASSWORD)
    APPLICATION_ID: ${{ parameters.applicationID }}
    CLIENT_ID: ${{ parameters.clientID }}
    CORS_ORIGINS: ${{ parameters.corsOrigins }}