parameters:
- name: applicationName
- name: organizationID
- name: description
- name: email
- name: phone

steps:
- script: |
    echo "##[debug] API_MANAGER_BASE_URL.....: ${API_MANAGER_BASE_URL}"
    echo "##[debug] APPLICATION_NAME.........: ${APPLICATION_NAME}"

    APPLICATION_ID=$(curl -s -k --fail --get \
    --data-urlencode "field=name" \
    --data-urlencode "op=eq" \
    --data-urlencode "value=${APPLICATION_NAME}" \
    --user "${ADMIN_USERNAME}:${ADMIN_PASSWORD}" \
    "${API_MANAGER_BASE_URL}/applications" | jq -r '.[0].id // empty')

    if [ ! -z "${APPLICATION_ID}" ]; then
      echo "##vso[task.logissue type=warning] Application '${APPLICATION_NAME}' already exists."
      echo "##[debug] APPLICATION_ID...........: ${APPLICATION_ID}"
      echo "##vso[task.setvariable variable=APPLICATION_ID]${APPLICATION_ID}"
      echo "##vso[task.complete result=SucceededWithIssues;]"
      exit
    fi

    echo "##[section] Application is valid to be created."
    echo "##vso[task.setvariable variable=isValidApplication]Yes"
  displayName: Validate Application
  env:
    API_MANAGER_BASE_URL: $(API_MANAGER_BASE_URL)
    ADMIN_USERNAME: $(ADMIN_USERNAME)
    ADMIN_PASSWORD: $(ADMIN_PASSWORD)
    APPLICATION_NAME: ${{ parameters.applicationName }}

- script: |
    request_body()
    {
      cat <<EOF
    {
      "name": "${APPLICATION_NAME}",
      "image": "",
      "phone": "${PHONE}",
      "email": "${EMAIL}",
      "apis": [],
      "description": "${DESCRIPTION}",
      "enabled": true,
      "organizationId": "${ORGANIZATION_ID}"
    }
    EOF
    }

    echo "##[debug] Request Body"
    request_body
    
    echo "##[command] POST /applications"
    APPLICATION_ID=$(curl -s -k --fail "${API_MANAGER_BASE_URL}/applications" \
    --user "${ADMIN_USERNAME}:${ADMIN_PASSWORD}" \
    --header "content-type: application/json" \
    --data-raw "$(request_body)" | jq -r '.id // empty')

    echo "##[debug] APPLICATION_ID...........: ${APPLICATION_ID}"
    echo "##vso[task.setvariable variable=APPLICATION_ID]${APPLICATION_ID}"
  displayName: Create Application
  condition: and(succeeded(), eq(variables.isValidApplication, 'Yes'))
  env:
    API_MANAGER_BASE_URL: $(API_MANAGER_BASE_URL)
    ADMIN_USERNAME: $(ADMIN_USERNAME)
    ADMIN_PASSWORD: $(ADMIN_PASSWORD)
    APPLICATION_NAME: ${{ parameters.applicationName }}
    ORGANIZATION_ID: ${{ parameters.organizationID }}
    DESCRIPTION: ${{ parameters.description }}
    EMAIL: ${{ parameters.email }}
    PHONE: ${{ parameters.phone }}