parameters:
- name: description
  displayName: "Descrição do cenário"
  type: string
  default: "Execução cenário"
- name: docker_image
  displayName: "Tecnologia utilizada no cenário"
  type: string
  default: selenium
  values:
  - selenium
- name: maven_command
  displayName: "Comando maven para execução"
  type: string
- name: branch
  type: string
  default: master
- name: update_alm_tool
  displayName: "Atualizar ou não o Octane?"
  type: boolean
  default: False
- name: test_environment
  displayName: "Ambiente onde o teste deve ser executado"
  type: string
  default: "PREPROD"
  values:
  - "PREPROD"
  - "ESTEIRA1"
  - "ESTEIRA2"
  - "PRODLIKE"  
- name: execution_parameters
  type: string
  default: ""  
  
stages:
  - template: /tech_products/srus/provisioners/qa/trunkbased/java/scenarios_default/stages/scenarios_exec.yml
    parameters:
      maven_command: "${{ parameters.maven_command }}"
      description: "${{ parameters.description }}"
      docker_image: "{{ parameters.docker_image }}"
      execution_parameters: "${{ parameters.execution_parameters }}"

