parameters:
- name: displayName
  default: Download Pipeline Artifact
- name: artifactName
  default: ''
- name: targetPath
  default: $(Pipeline.Workspace)
- name: itemPattern
  default: '**'
- name: condition
  default: succeeded()

steps:
- task: DownloadPipelineArtifact@2
  displayName: ${{ parameters.displayName }}
  condition: ${{ parameters.condition }}
  inputs:
    buildType: current
    artifactName: ${{ parameters.artifactName }}
    targetPath: ${{ parameters.targetPath }}
    itemPattern: ${{ parameters.itemPattern }}