parameters:
- name: microserviceName
- name: appVersion

steps:
- task: Bash@3
  displayName: 'Download docker image settings'
  inputs:
    targetType: 'inline'
    script: |
      set -e
      echo "Baixando o Universal Package"
      
      az artifacts universal download \
        --organization https://dev.azure.com/telefonica-vivo-brasil/ \
        --feed DevOps \
        --name "${{ parameters.microserviceName }}-docker-metada" \
        --version "${{ parameters.appVersion }}" \
        --path $(Build.ArtifactStagingDirectory)/docker

      echo "Package downloaded successfully."
  env:
    AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)
