parameters:
- name: contents
  default: |
    **/*
    !.git/**/*
    !?/**/*
    !**/*.log

steps:
- template: copy_to_staging.yml
  parameters:
    contents: ${{ parameters.contents }}

- task: PublishBuildArtifacts@1
  name: t_publish_artifact
  displayName: 'Publish Artifact'
  inputs:
    ArtifactName: db
    StoreAsTar: true