steps:
- task: CopyFiles@2
  displayName: 'Copy to Staging Directory'
  inputs:
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    OverWrite: true
    CleanTargetFolder: true
    Contents: |
      docker.json

- bash: | 
    echo "Nome que será atribuito ao artefato: $(MICROSERVICE_NAME)-docker-metada"
  displayName: 'Debug'
  
- task: Bash@3
  displayName: 'Publish docker image settings'
  inputs:
    targetType: 'inline'
    script: |
      set -e
      
      az artifacts universal publish \
        --organization https://dev.azure.com/telefonica-vivo-brasil/ \
        --feed DevOps \
        --name "$(MICROSERVICE_NAME)-docker-metada" \
        --version "$(APP_VERSION)" \
        --description "Docker metadata" \
        --path $(Build.ArtifactStagingDirectory)/docker.json
      
      echo "Package published successfully."
  env:
    AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)
    MICROSERVICE_NAME: $(MICROSERVICE_NAME) 
