parameters:
  - name: sshEndpoint

steps:
  - template: ../../tasks/ssh/get_k8s_resource_status.yml
    parameters:
      resource: nodes
      sshEndpoint: ${{ parameters.sshEndpoint }}

  - task: CmdLine@2
    name: environment_state
    displayName: "Environment State"
    inputs:
      script: |
        NODES=""
        ENV_OFF=0
        ENV_STATE="OFF"

        echo "##[group]Nodes"
        IFS=';' read -ra ADDR <<< "$NODES_STATUS"
        for log_line in "${ADDR[@]}"; do
          if [[ ${log_line} != *"NAME"* ]]; then
            IFS=' ' read -ra ADDR <<< "${log_line}"

            if [ "${#NODES}" -gt 0 ]; then
              NODES+=";${ADDR[0]},${ADDR[1]},${ADDR[3]},${ADDR[4]}"
            else
              NODES+="${ADDR[0]},${ADDR[1]},${ADDR[3]},${ADDR[4]}"
            fi

            case "${ADDR[1]}" in
              "Ready")
                echo "🟢 Node [${ADDR[0]} <> ${ADDR[1]}]"
                ENV_OFF=1
                ;;
              *) echo "🔴 Node [${ADDR[0]} <> ${ADDR[1]}]" ;;
            esac
          fi
        done
        echo "##[endgroup]"

        echo ""
        if [ "$ENV_OFF" -eq 0 ]; then
          echo ">>>>> 🔴 BRM turned OFF in poc <<<<<"
        else
          echo ">>>>> 🟢 BRM ON in poc <<<<<"
          ENV_STATE="ON"
        fi

        echo "##vso[task.setvariable variable=BRM_ENVIRONMENT_STATE;isoutput=true]$ENV_STATE"
