## -> Parameters:
parameters:
  - name: environment
    displayName: "Escolha o ambiente para publicar"
    type: string
    default: producao
    values:
      - producao
  - name: packageName
  - name: packageVersion
  - name: rollbackDate

stages:
  ## -> Entrypoint
    - template: /tech_products/gdoc/templates/cd/cd_rollback_apache.yml
      parameters:
        environment: "${{ parameters.environment }}"
        packageName: "${{ parameters.packageName }}"
        packageVersion: "${{ parameters.packageVersion }}"
        rollbackDate: "${{ parameters.rollbackDate }}"