## -> Parameters:
parameters:
  - name: environment
    displayName: "Escolha o ambiente para publicar"
    type: string
    default: producao
    values:
      - producao
  - name: packageVersion
    type: string
    default: ""
  - name: packageName
    type: string
    default: ""
  - name: deliveryModel
    displayName: Modelo de entrega
    type: string
    default: default
    values:
    - default
    - deployOnly
    - rollbackOnly
  - name: rollbackDate
    type: string
    default: "aaaa-mm-dd_HHMM"

## -> Resources:
resources:
  repositories:
  
  ## -> Scripts
  - repository: GDOCScripts
    name: 'GDOC - GEDOC/comp-gedoc-scripts'
    type: git
    ref: refs/heads/master
    endpoint: CorePipelines

variables:
  ## -> Override global variables, with variables set in Library/Variable Groups (Pipelines)
  ## -> Use this to change the variables on runtime
  - group: "${{ variables['Build.Repository.Name'] }}"
  - template: /tech_products/gdoc/initializers/global_initializer.yml

stages:
  ## -> Entrypoint
  - ${{ if eq(parameters.deliveryModel, 'default') }}:
      - template: /tech_products/gdoc/pipeline_external_package_ci_v1.yaml
        parameters:
          environment: "${{ variables.environment }}"
          packageVersion: "${{ parameters.packageVersion }}"
          packageName: "${{ parameters.packageName }}"
      - template: /tech_products/gdoc/pipeline_external_package_cd_v1.yaml
        parameters:
          environment: "${{ parameters.environment }}"
          packageVersion: "${{ parameters.packageVersion }}"
          packageName: "${{ parameters.packageName }}"

  - ${{ elseif eq(parameters.deliveryModel, 'deployOnly') }}:
      - template: /tech_products/gdoc/pipeline_external_package_cd_v1.yaml
        parameters:
          environment: "${{ parameters.environment }}"
          packageVersion: "${{ parameters.packageVersion }}"
          packageName: "${{ parameters.packageName }}"

  - ${{ elseif eq(parameters.deliveryModel, 'rollbackOnly') }}:
      - template: /tech_products/gdoc/pipeline_external_package_rb_v1.yaml
        parameters:
          environment: "${{ parameters.environment }}"
          packageVersion: "${{ parameters.packageVersion }}"
          packageName: "${{ parameters.packageName }}"
          rollbackDate: "${{ parameters.rollbackDate }}"
