parameters:
- name: displayName
  default: Download Pipeline Artifact
- name: artifactName
  default: "test-results"
- name: targetPath
  default: "$(System.ArtifactsDirectory)"
- name: itemPattern
  default: '**/*'
- name: condition
  default: succeeded()

steps:
- task: DownloadPipelineArtifact@2
  displayName: ${{ parameters.displayName }}
  condition: ${{ parameters.condition }}
  inputs:
    buildType: current
    artifactName: ${{ parameters.artifactName }}
    targetPath: ${{ parameters.targetPath }}
    itemPattern: ${{ parameters.itemPattern }}
