parameters:
- name: artifactPublishName
  type: string
  default: app
- name: pathtoPublish
  type: string
  default: $(Build.ArtifactStagingDirectory)
- name: sourceFolder
  default: $(Build.SourcesDirectory)
- name: excludeFiles
  default: '{"*\.tar","*.tar\.gz","*/dist","\.pnpm-store","\.angular","*/mock","*/.git",".git/"}'

steps:
- bash: |
    cd $(Build.SourcesDirectory)
    echo "##[section]CRIANDO ARQUIVO .tar.gz SEM OS ARQUIVOS: $EXCLUDE_FILES"
    tar --exclude=$EXCLUDE_FILES --warning=no-file-changed -hczf $FILE_TO_PUBLISH ./*

    STATUS_TAR_CREATION=$?
    if [[ $STATUS_TAR_CREATION != 0 ]]; then
      SET_MSG="NÃO FOI POSSÍVEL GERAR O ARQUIVO app.tar.gz"
      echo "##[error]$SET_MSG"
      echo "##vso[task.logissue type=error;]$SET_MSG"
      exit 1
    fi

    echo "##[section]ARQUIVO TAR CRIADO COM SUCESSO"
    tar -tf $FILE_TO_PUBLISH
  displayName: "Generate app.tar.gz"
  env:
    EXCLUDE_FILES: ${{ parameters.excludeFiles }}
    FILE_TO_PUBLISH: $(Build.SourcesDirectory)/app.tar.gz

- task: CopyFiles@2
  displayName: "Copy app.tar.gz to Staging Directory"
  inputs:
    TargetFolder: "$(Build.ArtifactStagingDirectory)"
    OverWrite: true
    CleanTargetFolder: true
    Contents: |
      $(Build.SourcesDirectory)/app.tar.gz

- task: PublishPipelineArtifact@1
  displayName: "Publish app.tar.gz"
  inputs:
    artifactName: "app"
    targetPath: "$(Build.ArtifactStagingDirectory)"
