parameters:
- name: stack
  type: string
  values:
  - JAVA
  - NODE
  - PYTHON
- name: serviceConnectionName
- name: configFile
- name: librariesPath
- name: workdirArtifacts
- name: projectKey
- name: version
- name: pythonVersion

steps:
- ${{ if eq(parameters['stack'], 'JAVA')}}:
  - template: /tech_products/srus/tasks/sonar/prepare_analysis_java.yml
    parameters:
      serviceConnectionName: '${{ parameters.serviceConnectionName }}'
      configFile: '${{ parameters.configFile }}'
      librariesPath: '${{ parameters.librariesPath }}'
      workdirArtifacts: '${{ parameters.workdirArtifacts }}'
      projectKey: '${{ parameters.projectKey }}'
      version: '${{ parameters.version }}'

- ${{ if eq(parameters['stack'], 'NODE')}}:
  - template: /tech_products/srus/tasks/sonar/prepare_analysis_nodejs.yml
    parameters:
      serviceConnectionName: '${{ parameters.serviceConnectionName }}'
      configFile: '${{ parameters.configFile }}'
      workdirArtifacts: '${{ parameters.workdirArtifacts }}'
      projectKey: '${{ parameters.projectKey }}'
      version: '${{ parameters.version }}'

- ${{ if eq(parameters['stack'], 'PYTHON')}}:
  - template: /tech_products/srus/tasks/sonar/prepare_analysis_python.yml
    parameters:
      serviceConnectionName: '${{ parameters.serviceConnectionName }}'
      configFile: '${{ parameters.configFile }}'
      workdirArtifacts: '${{ parameters.workdirArtifacts }}'
      projectKey: '${{ parameters.projectKey }}'
      version: '${{ parameters.version }}'
      pythonVersion: '${{ parameters.pythonVersion }}'
