steps:
# - template: /tasks/artifacts/download_app.yml
#   parameters:
#     downloadPath: $(DEFAULT_WORKDIR_ARTIFACTS)

- task: DownloadBuildArtifacts@1
  displayName: 'Download Build Artifacts'
  inputs:
    artifactName: db
    parallelizationLimit: 20
    extractTars: true

- template: /tech_products/srus/global/general/set-output-variable.yml
  parameters:
    variable: SONAR_PROJECT_KEY
    command: $(DOCKER-CMD-EXTRACT-SONAR-PROJECT-KEY)

- template: /tech_products/srus/global/general/set-output-variable.yml
  parameters:
    variable: APP_VERSION
    command: $(DOCKER_CMD_EXTRACT_POM_XML_VERSION)

- template: /tech_products/srus/global/general/set-output-variable.yml
  parameters:
    variable: LIBRARIES_PATH
    command: $(echo $(MAVEN_CACHE_FOLDER))
