parameters:
- name: gateway
- name: gatewayVersion
- name: apiName
- name: apiVersion
- name: apiType

stages:
- stage: stage_validate
  pool: $(PRIVATE_AGENT_DEFAULT)
  displayName: Validate Deploy
  dependsOn: []
  jobs:
  - job: show_info
    displayName: 'Show Info'
    steps:
    - checkout: none
    - script: |
        echo "##vso[task.logissue type=warning] Deploying API '${{ parameters.apiName}}' (${{ parameters.apiType }}) version '${{ parameters.apiVersion }}' in gateway '${{ parameters.gateway}}' (${{ parameters.gatewayVersion }})"
  - job: wait
    displayName: Validate Manual API Deploy
    pool: server    
    dependsOn: 
    - show_info
    timeoutInMinutes: 1440
    steps:
    - task: ManualValidation@0
      condition: and(succeeded(), eq(variables.MANUAL_VALIDATION_ENABLED, true))
      timeoutInMinutes: 1440
      inputs:
        notifyUsers: "$(Build.RequestedForEmail)"
        instructions: |
          Você disparou um deploy de API Gateway com as seguintes informações:

          -> Gateway: ${{ parameters.gateway }}
          -> Gateway Version: ${{ parameters.gatewayVersion }}
          -> API Name: ${{ parameters.apiName }}
          -> API Version: ${{ parameters.apiVersion }}
          -> API Type: ${{ parameters.apiType }}

          Para prosseguir com o deploy nos ambientes prossiga em 'Resume'
        onTimeout: "reject"