steps:
- task: Npm@1
  inputs:
    command: 'install'
  displayName: Npm install Dependencies
- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'run install:all'
  displayName: Npm install Tasks
- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'run coverage'
  displayName: Build & Tests & Coverage
- template: /tech_products/loja-online/task_groups/tests/publish_tests_reports.yml
  parameters:
    testResultsFilesPattern: "**/ResultsFile.xml"
    coverageFilePattern: "**/lcov.info"
    codeCoverageTool: "Cobertura"