## -> Parameters:
parameters:
- name: environment
- name: infrastructureType
- name: skipComponentTest
- name: deployAppsettings
- name: servicePrincipalEnv
- name: skipDeploy

stages:

## -> CI

## -> Initialize enviroment
- template: /tech_products/oss/initialize/default_environment.yml

## -> Build for CI - Java
- template: /tech_products/oss/templates/ci/ci_build_java_oss.yml
  parameters:
    environment: "${{ parameters.environment }}"

## -> Component Test for CI - Java
##- ${{ if ne(parameters.skipComponentTest, True) }}:
  ##TODO- template: /tech_products/oss/templates/ci/ci_component_test_java_oss.yml

## -> Initialize Gates enviroment
- template: /tech_products/oss/initialize/gates_environment.yml

## -> Quality Gates (SonarQube)
- template: /tech_products/oss/templates/ci/ci_quality_gate_oss.yml
  parameters:
    environment: "${{ parameters.environment }}"

## -> Security Gates (Fortify)
- template: /tech_products/oss/templates/ci/ci_security_oss.yml
  parameters:
    fortifyExclusionRepository: FortifyExclusion

## -> Publish Build for CI - Java
- template: /tech_products/oss/templates/ci/ci_publish_azure_function.yml
  parameters:
    infrastructureType: "${{ parameters.infrastructureType }}"


## -> CD

# ## -> Initialize Deploy enviroment
# ## -> Skip Deploy enviroment for WEBLOGIC
- ${{ if ne(parameters.skipDeploy, True) }}:
  - template: /tech_products/oss/templates/cd/cd_deploy_azure_function_oss.yml
    parameters:
      environment: "${{ parameters.environment }}"
      serviceConnection: "${{ parameters.infrastructureType }}-${{ parameters.servicePrincipalEnv }}"
      deployAppsettings: "${{ parameters.deployAppsettings }}"
