## -> Parameters:
parameters:
- name: environment
  type: string
  default: ''
- name: infrastructureType
  type: string
  default: 'aksBinv'
- name: skipDeploy
  type: boolean
  default: false

## -> Resources:
resources:
  repositories:
  - repository: FortifyExclusion
    name: DevOps/Vivo.Fortify.Exclusions
    type: git
    ref: refs/heads/master
    endpoint: CodePlay
  - repository: OSSDevOpsExclusions
    name: 'OSSD - OSS DEVOPS/exclusions-oss-default'
    type: git
    ref: refs/heads/master
    endpoint: CodePlay
  - repository: OSSDevOpsSettings
    name: 'OSSD - OSS DEVOPS/settings-oss-default'
    type: git
    ref: refs/heads/master
    endpoint: CodePlay  

## -> Initialize global variables
variables:
- template: /tech_products/oss/initialize/variables_global.yml
- template: /tech_products/oss/initialize/variables_java.yml
- template: /tech_products/oss/initialize/variables_gates.yml
- template: /tech_products/oss/initialize/variables_docker.yml
- group: "${{ variables['Build.DefinitionName'] }}"
- name: CORPORATE_WIKI_DOC_URL
  value: "TBD"
- name: infrastructureType
  value: ${{parameters.infrastructureType}}
- ${{ if in(variables['Build.SourceBranchName'],'master','main' )}}:
  - name: environment
    value: producao
- ${{ elseif in(variables['Build.SourceBranchName'],'dev','esteira1','esteira2','preprod','prodlike','producao' )}}:
  - name: environment
    value: ${{variables['Build.SourceBranchName']}}
- ${{ else }}:
  - name: environment
    value: ${{parameters.environment}}

stages:
## -> CI

## -> Initialize enviroment
- template: /tech_products/oss/initialize/default_environment.yml

## -> Build to create a new custpackage
- template: /tech_products/oss/templates/ci/ci_build_custpackage_oss.yml

## -> CD
- ${{ if eq(parameters.skipDeploy, false) }}:

  ## -> DEPLOY 2408
  - template: /tech_products/oss/templates/cd/cd_deploy_bpi_custpackage_oss.yml
    parameters:
      infrastructureType: ${{parameters.infrastructureType}}
      environment: ${{variables.environment}}

  ## -> ROLLBACK 2408
  - template: /tech_products/oss/templates/cd/cd_rollback_bpi_custpackage_oss.yml
    parameters:
      environment: ${{variables.environment}}
      infrastructureType: ${{parameters.infrastructureType}}
      custArtifactsType: neo4jScripts