## -> Parameters:
parameters:
- name: environment
  type: string
  default: ''
- name: infrastructureType
  type: string
  default: 'aksBinv'
- name: skipComponentTest
  type: boolean
  default: False
- name: skipPackage
  type: boolean
  default: False
- name: skipDeploy
  type: boolean
  default: False
- name: custArtifactsType
  type: string
  values:
  - neo4jPlugins
  - webWebapps
  - neo4jScripts
  - chetakScripts

## -> Resources:
resources:
  repositories:
  - repository: FortifyExclusion
    name: DevOps/Vivo.Fortify.Exclusions
    type: git
    ref: refs/heads/master
    endpoint: CodePlay
  - repository: OSSDevOpsExclusions
    name: 'OSSD - OSS DEVOPS/exclusions-oss-default'
    type: git
    ref: refs/heads/master
    endpoint: CodePlay
  - repository: OSSDevOpsHosts
    name: 'OSSD - OSS DEVOPS/hosts-oss-default'
    type: git
    ref: refs/heads/master
    endpoint: CodePlay
  - repository: OSSDevOpsSettings
    name: 'OSSD - OSS DEVOPS/settings-oss-default'
    type: git
    ref: refs/heads/master
    endpoint: CodePlay  

## -> Initialize global variables
variables:
- template: /tech_products/oss/initialize/variables_global.yml
- template: /tech_products/oss/initialize/variables_java.yml
- template: /tech_products/oss/initialize/variables_gates.yml
- template: /tech_products/oss/initialize/variables_docker.yml
- group: "${{ variables['Build.DefinitionName'] }}"
- name: CORPORATE_WIKI_DOC_URL
  value: "TBD"
- name: infrastructureType
  value: ${{parameters.infrastructureType}}
- ${{ if in(variables['Build.SourceBranchName'],'master','main' )}}:
  - name: environment
    value: producao
  - name: publishBranch
    value: true
- ${{ elseif in(variables['Build.SourceBranchName'],'dev','esteira1','esteira2','preprod','prodlike','producao' )}}:
  - name: environment
    value: ${{variables['Build.SourceBranchName']}}
  - name: publishBranch
    value: true
- ${{ else }}:
  - name: environment
    value: ${{parameters.environment}}
  - name: publishBranch
    value: false

stages:
## -> CI

## -> Initialize enviroment
- template: /tech_products/oss/initialize/default_environment.yml

## -> if custArtifactsType is not 'neo4jScripts', 'chetakScripts'
- ${{ if notIn(parameters.custArtifactsType, 'neo4jScripts', 'chetakScripts') }}:

  ## -> Build for CI - Java
  - template: /tech_products/oss/templates/ci/ci_build_java_oss.yml
    parameters:
      environment: ${{variables.environment}}

  ## -> Initialize Gates enviroment
  - template: /tech_products/oss/initialize/gates_environment.yml

  ## -> Quality Gates (SonarQube)
  - template: /tech_products/oss/templates/ci/ci_quality_gate_oss.yml
    parameters:
      environment: ${{variables.environment}}

  ## -> Security Gates (Fortify)
  - template: /tech_products/oss/templates/ci/ci_security_oss.yml
    parameters:
      fortifyExclusionRepository: FortifyExclusion

  ## -> Publish Build for CI - Java
  - ${{ if eq(variables.publishBranch, true) }}:
    - template: /tech_products/oss/templates/ci/ci_publish_java_oss.yml
      parameters:
        infrastructureType: "${{ parameters.infrastructureType }}"

## -> if custArtifactsType is 'neo4jScripts', 'chetakScripts'
- ${{ if in(parameters.custArtifactsType, 'neo4jScripts', 'chetakScripts') }}:

  ## -> Build for CI - Scripts
  - template: /tech_products/oss/templates/ci/ci_build_scripts_oss.yml

  ## -> Publish Build for CI - Scripts
  - ${{ if eq(variables.publishBranch, true) }}:
    - template: /tech_products/oss/templates/ci/ci_publish_scripts_oss.yml

  ## -> CD
- ${{ if and(eq(parameters.skipDeploy, false), eq(variables.publishBranch, true)) }}:
  ## -> DEPLOY 2408
  - template: /tech_products/oss/templates/cd/cd_deploy_bpi_custartifact_oss.yml
    parameters:
      custArtifactsType: ${{parameters.custArtifactsType}}
      infrastructureType: ${{parameters.infrastructureType}}
      environment: ${{variables.environment}}
  ## -> ROLLBACK 2408
  - template: /tech_products/oss/templates/cd/cd_rollback_bpi_custpackage_oss.yml
    parameters:
      custArtifactsType: ${{parameters.custArtifactsType}}
      infrastructureType: ${{parameters.infrastructureType}}
      environment: ${{variables.environment}}
