## -> Parameters:
parameters:
- name: environment
  type: string
  default: ''
- name: skipDeploy
  type: boolean
  default: false
- name: enableRollback
  type: boolean
  default: true
- name: clearCheckSums
  type: boolean
  default: false

## -> Resources:
resources:
  repositories:

  ## -> Fortify
  - repository: FortifyExclusion
    name: DevOps/Vivo.Fortify.Exclusions
    type: git
    ref: refs/heads/master
    endpoint: CorePipelines

  ## -> OSSD Repository
  - repository: OSSDevOpsExclusions
    name: 'OSSD - OSS DEVOPS/exclusions-oss-default'
    type: git
    ref: refs/heads/master
    endpoint: CodePlay

## -> Initialize global variables
variables:
- template: /tech_products/oss/initialize/variables_global.yml
- template: /tech_products/oss/initialize/variables_docker.yml
- template: /tech_products/oss/initialize/variables_java.yml
- template: /tech_products/oss/initialize/variables_gates.yml
- template: /tech_products/oss/initialize/variables_liquibase.yml
  parameters:
    environment: ${{ parameters.environment }}
    skipDeploy: ${{ parameters.skipDeploy }}

## -> Override global variables, with variables set in Library/Variable Groups (Pipelines)
## -> Use this to change the variables on runtime
- group: "${{ variables['Build.Repository.Name'] }}"

stages:

## -> CI

## -> Initialize enviroment
- template: /tech_products/oss/initialize/default_environment.yml

## -> Build for CI - Liquibase
- template: /tech_products/oss/templates/ci/ci_build_liquibase_oss.yml
  parameters:
    enableRollback: ${{ parameters.enableRollback }}
    clearCheckSums: ${{ parameters.clearCheckSums }}

## -> Initialize Gates enviroment
- template: /tech_products/oss/initialize/gates_environment.yml

## -> Quality Gates (Governance App)
- template: /tech_products/oss/templates/ci/ci_gov_app_gate_oss.yml
  parameters:
    environment: ${{ variables.ENVIRONMENT }}

## -> Security Gates (Fortify)
- template: /tech_products/oss/templates/ci/ci_security_oss.yml
  parameters:
    fortifyExclusionRepository: FortifyExclusion

## -> CD
- ${{ if ne(variables.SKIP_DEPLOY, true) }}:

  ## -> Deploy for CD - Liquibase
  - template: /tech_products/oss/templates/cd/cd_deploy_liquibase_oss.yml
    parameters:
      environment: ${{ variables.ENVIRONMENT }}

  ## -> Rollback for CD - Liquibase
  - ${{ if eq(parameters.enableRollback, true) }}:
    - template: /tech_products/oss/templates/cd/cd_rollback_liquibase_oss.yml
      parameters:
        environment: ${{ variables.ENVIRONMENT }}