## -> Parameters:
parameters:
- name: environment
  type: string
  default: ''
- name: infrastructureType
  type: string
  default: 'cloud'
- name: skipComponentTest
  type: boolean
  default: False
- name: skipPackage
  type: boolean
  default: False
- name: skipDeploy
  type: boolean
  default: False
- name: packageVersion
  type: string
  default: ''
- name: legacy
  type: boolean
  default: False
- name: rbqa_jira_id
  type: string
  default: 'none'
- name: rbqa_component_test_id
  type: string
  default: 'none'
- name: rbqa_octane_workspace
  type: string
  default: 'none'
- name: rbqa_docker_image
  type: string
  default: 'selenium'
- name: rbqa_octane_environment
  type: string
  default: 'PROD'  

## -> Resources:
resources:
  repositories:
  
  ## -> Fortify
  - repository: FortifyExclusion
    name: DevOps/Vivo.Fortify.Exclusions
    type: git
    ref: refs/heads/master
    endpoint: CorePipelines
  
  ## -> OSSD Repository
  - repository: OSSDevOpsHelm
    name: 'OSSD - OSS DEVOPS/helm-oss-default'
    type: git
    ref: refs/heads/master
    endpoint: CodePlay
  - repository: OSSDevOpsSettings
    name: 'OSSD - OSS DEVOPS/settings-oss-default'
    type: git
    ref: refs/heads/master
    endpoint: CodePlay
  - repository: OSSDevOpsExclusions
    name: 'OSSD - OSS DEVOPS/exclusions-oss-default'
    type: git
    ref: refs/heads/master
    endpoint: CodePlay

## -> Initialize global variables   
variables:

- template: /tech_products/oss/initialize/variables_global.yml
- template: /tech_products/oss/initialize/variables_nodejs.yml
- template: /tech_products/oss/initialize/variables_gates.yml
- template: /tech_products/oss/initialize/variables_docker.yml
- ${{ if ne(parameters.skipDeploy, True) }}:    
  - template: /tech_products/oss/initialize/variables_helm.yml
  
## -> Override global variables, with variables set in Library/Variable Groups (Pipelines)
## -> Use this to change the variables on runtime
- group: "${{ variables['Build.Repository.Name'] }}"

- name: CORPORATE_WIKI_DOC_URL
  value: "TBD"

## -> Whether branch is dev, esteira1, esteira2, preprod, prodlike or producao, set environment to branch name, 
## -> Otherwise use parameter environment
- ${{ if in(variables['Build.SourceBranchName'],'dev','esteira1','esteira2','preprod','prodlike','producao' )}}:
    - name: environment
      value: ${{variables['Build.SourceBranchName']}}
- ${{ else }}:
    - name: environment
      value: ${{ parameters.environment }}

stages:

## -> Entrypoint
## -> Use CI-CD pipeline if no package version has been provided
## -> Use CD only pipeline if package version has been provided
- ${{ if or(eq(parameters.packageVersion, ''), eq(parameters.packageVersion, 'none')) }}: 
  - template: /tech_products/oss/pipeline_nodejs_oss_ci_cd.yml
    parameters:
      environment: "${{ variables.environment }}"
      infrastructureType: "${{ parameters.infrastructureType }}"
      skipComponentTest: "${{ parameters.skipComponentTest }}"
      skipPackage: "${{ parameters.skipPackage }}"
      skipDeploy: "${{ parameters.skipDeploy }}"
      rbqa_jira_id: "${{ parameters.rbqa_jira_id }}"
      rbqa_component_test_id: "${{ parameters.rbqa_component_test_id }}"
      rbqa_octane_workspace: "${{ parameters.rbqa_octane_workspace }}"
      rbqa_docker_image: "${{ parameters.rbqa_docker_image }}"
      rbqa_octane_environment: "${{ parameters.rbqa_octane_environment }}"      
- ${{ else }}:
  - template: /tech_products/oss/pipeline_nodejs_oss_cd_only.yml
    parameters:
      environment: "${{ parameters.environment }}"
      infrastructureType: "${{ parameters.infrastructureType }}"
      packageVersion: "${{ parameters.packageVersion }}"
      legacy: "${{ parameters.legacy }}"
      rbqa_jira_id: "${{ parameters.rbqa_jira_id }}"
      rbqa_component_test_id: "${{ parameters.rbqa_component_test_id }}"
      rbqa_octane_workspace: "${{ parameters.rbqa_octane_workspace }}"
      rbqa_docker_image: "${{ parameters.rbqa_docker_image }}"
      rbqa_octane_environment: "${{ parameters.rbqa_octane_environment }}"