## -> Parameters:
parameters:
- name: environment
- name: infrastructureType
  type: string
  default: 'cloud'
- name: packageVersion
  type: string
  default: 'latest'
- name: legacy

## -> Parameters RBQA 
- name: rbqa_jira_id
  type: string
  displayName: 'RBQA Jira ID'
  default: ''
- name: rbqa_component_test_id
  type: string
  displayName: 'RBQA Component Test ID'
  default: ''
- name: rbqa_octane_workspace
  type: string
  displayName: 'RBQA Octane Workspace'
  default: ''
- name: rbqa_docker_image
  type: string
  displayName: 'RBQA Docker Image'
  default: ''
- name: rbqa_octane_environment
  type: string
  displayName: 'RBQA Octane Environment'
  default: ''

stages:

## -> CD
## -> Orchestrator Call
- template: /tech_products/oss/templates/cd/cd_deploy_only_orchestrator.yml
  parameters:
    environment: "${{ parameters.environment }}"
    packageVersion: "${{ parameters.packageVersion }}"
    infrastructureType: "${{ parameters.infrastructureType }}"
    legacy: "${{ parameters.legacy }}"
    buildType: 'nodejs'
    
    ## -> Parameters RBQA
    rbqa_jira_id: "${{ parameters.rbqa_jira_id }}"
    rbqa_component_test_id: "${{ parameters.rbqa_component_test_id }}"
    rbqa_octane_workspace: "${{ parameters.rbqa_octane_workspace }}"
    rbqa_docker_image: "${{ parameters.rbqa_docker_image }}"
    rbqa_octane_environment: "${{ parameters.rbqa_octane_environment }}"