parameters:
  workingDirectory:
    type: string
    default: $(Pipeline.Workspace)

steps:
  - task: CmdLine@2
    displayName: "Check catalog-info"
    name: check_catalog_info
    inputs:
      workingDirectory: ${{ parameters.workingDirectory }}
      targetType: inline
      script: |
        if ! [[ -f "catalog-info.yml" || -f "catalog-info.yaml" ]]; then
          echo "##vso[task.logissue type=warning] Unable to find catalog-info file (path=$(pwd))."
        else
          echo "##vso[task.setvariable variable=CATALOG_INFO_FOUND;]true"
          echo "catalog-info file found."
        fi

  - task: YamlParseFromVivo@4
    displayName: 'Load catalog-info'
    name: load_catalog_info
    condition: and(succeeded(), eq(variables['CATALOG_INFO_FOUND'], 'true'))
    inputs:
      type: 'file'
      origin: ${{ parameters.workingDirectory }}/catalog-info.yaml
      jpaths: |
        var GOV_APP_ACRONYM = .metadata.annotations['techarch.governance-app.acronym']
        var APP_SYSTEM = .spec['system']
        var APP_NAME = .metadata['name']
        var APP_DESCRIPTION = .metadata['description']
        var APP_COMPONENT_TYPE = .metadata.annotations['techarch.governance-app.technical_component_type']
        var APP_LANGUAGE = .metadata.annotations['arqtech.telefonica.com.br/language']
        var APP_LANGUAGE_VERSION = .metadata.annotations['arqtech.telefonica.com.br/language-version']
        var SONAR_PROJECT_KEY = .metadata.annotations['sonarqube.org/project-key']
        var K8S_CONFIG = .metadata.annotations['vivo.io/kubernetes-config']
        var HELM_RELEASE = .metadata.annotations['backstage.io/kubernetes-id']
        var K8S_NAMESPACE = .metadata.annotations['backstage.io/kubernetes-namespace']
        var K8S_NAMESPACE_DEV = .metadata.annotations['vivo.io/kubernetes-k8s-namespace-dev']
        var K8S_NAMESPACE_ESTEIRA1 = .metadata.annotations['vivo.io/kubernetes-k8s-namespace-esteira1']
        var K8S_NAMESPACE_ESTEIRA2 = .metadata.annotations['vivo.io/kubernetes-k8s-namespace-esteira2']
        var K8S_NAMESPACE_PREPROD = .metadata.annotations['vivo.io/kubernetes-k8s-namespace-preprod']
        var K8S_NAMESPACE_PRODLIKE = .metadata.annotations['vivo.io/kubernetes-k8s-namespace-prodlike']
        var K8S_NAMESPACE_PRODUCAO = .metadata.annotations['vivo.io/kubernetes-k8s-namespace-producao'] 
 
  - task: CmdLine@2
    displayName: "Set catalog-info Variables"
    condition: and(succeeded(), eq(variables['CATALOG_INFO_FOUND'], 'true'))
    name: catalog_info
    inputs:
      workingDirectory: ${{ parameters.workingDirectory }}
      targetType: inline
      script: |

        catalogInfo=$(find . -type f -name "catalog-info.*" -print -quit)
        CATALOG_INFO_FILE_CONTENT=$(cat $catalogInfo)

        echo "##[group] catalog-info Variables"
        echo "##[debug] GOV_APP_ACRONYM............: ${GOV_APP_ACRONYM}"
        echo "##[debug] APP_SYSTEM.................: ${APP_SYSTEM}"
        echo "##[debug] APP_NAME...................: ${APP_NAME}"
        echo "##[debug] APP_LANGUAGE...............: ${APP_LANGUAGE}"
        echo "##[debug] APP_COMPONENT_TYPE.........: ${APP_COMPONENT_TYPE}"
        echo "##[debug] APP_LANGUAGE_VERSION.......: ${APP_LANGUAGE_VERSION}"
        echo "##[debug] SONAR_PROJECT_KEY..........: ${SONAR_PROJECT_KEY}"
        echo "##[debug] K8S_CONFIG.................: ${K8S_CONFIG}"
        echo "##[debug] HELM_RELEASE...............: ${HELM_RELEASE}"
        echo "##[debug] K8S_NAMESPACE..............: ${K8S_NAMESPACE}"
        echo "##[debug] K8S_NAMESPACE_DEV..........: ${K8S_NAMESPACE_DEV}"
        echo "##[debug] K8S_NAMESPACE_ESTEIRA1.....: ${K8S_NAMESPACE_ESTEIRA1}"
        echo "##[debug] K8S_NAMESPACE_ESTEIRA2.....: ${K8S_NAMESPACE_ESTEIRA2}"
        echo "##[debug] K8S_NAMESPACE_PREPROD......: ${K8S_NAMESPACE_PREPROD}"
        echo "##[debug] K8S_NAMESPACE_PRODLIKE.....: ${K8S_NAMESPACE_PRODLIKE}"
        echo "##[debug] K8S_NAMESPACE_PRODUCAO.....: ${K8S_NAMESPACE_PRODUCAO}"
        echo "##[debug] APP_DESCRIPTION............: ${APP_DESCRIPTION}"
        echo "##[debug] CATALOG_INFO_FILE_CONTENT..: ${CATALOG_INFO_FILE_CONTENT}"

        echo "##vso[task.setvariable variable=GOV_APP_ACRONYM;isOutput=true]${GOV_APP_ACRONYM}"
        echo "##vso[task.setvariable variable=APP_SYSTEM;isOutput=true]${APP_SYSTEM}"
        echo "##vso[task.setvariable variable=APP_NAME;isOutput=true]${APP_NAME}"
        echo "##vso[task.setvariable variable=APP_COMPONENT_TYPE;isOutput=true]${APP_COMPONENT_TYPE}"
        echo "##vso[task.setvariable variable=SONAR_PROJECT_KEY;isOutput=true]${SONAR_PROJECT_KEY}"
        echo "##vso[task.setvariable variable=K8S_CONFIG;isOutput=true]${K8S_CONFIG}"
        echo "##vso[task.setvariable variable=HELM_RELEASE;isOutput=true]${HELM_RELEASE}"
        echo "##vso[task.setvariable variable=K8S_NAMESPACE;isOutput=true]${K8S_NAMESPACE}"
        echo "##vso[task.setvariable variable=K8S_NAMESPACE_DEV;isOutput=true]${K8S_NAMESPACE_DEV}"
        echo "##vso[task.setvariable variable=K8S_NAMESPACE_ESTEIRA1;isOutput=true]${K8S_NAMESPACE_ESTEIRA1}"
        echo "##vso[task.setvariable variable=K8S_NAMESPACE_ESTEIRA2;isOutput=true]${K8S_NAMESPACE_ESTEIRA2}"
        echo "##vso[task.setvariable variable=K8S_NAMESPACE_PREPROD;isOutput=true]${K8S_NAMESPACE_PREPROD}"
        echo "##vso[task.setvariable variable=K8S_NAMESPACE_PRODLIKE;isOutput=true]${K8S_NAMESPACE_PRODLIKE}"
        echo "##vso[task.setvariable variable=K8S_NAMESPACE_PRODUCAO;isOutput=true]${K8S_NAMESPACE_PRODUCAO}"
        echo "##vso[task.setvariable variable=APP_DESCRIPTION;isOutput=true]${APP_DESCRIPTION}"
        echo "##vso[task.setvariable variable=APP_LANGUAGE;isOutput=true]${APP_LANGUAGE}"
        echo "##vso[task.setvariable variable=APP_LANGUAGE_VERSION;isOutput=true]${APP_LANGUAGE_VERSION}"
        echo "##vso[task.setvariable variable=CATALOG_INFO_FILE_CONTENT;isOutput=true]${CATALOG_INFO_FILE_CONTENT}"
        echo "##[endgroup]"
        echo "##[debug] To open and check the information above, click the arrows on the left."
