parameters:
- name: dockerImageName
  type: string
- name: dockerAppVersion
  type: string
- name: imageDigest
  type: string

steps:
- task: AzureKeyVault@2  
  displayName: 'Getting AKV credentials'
  timeoutInMinutes: 1
  retryCountOnTaskFailure: 5  
  inputs:    
    azureSubscription: DevOpsSharedResources    
    KeyVaultName: $(AKV_DEVOPS_NAME)
    SecretsFilter: 'NEXUS-DEFAULT-USR, NEXUS-DEFAULT-PSW'

- script: |
    echo "##[debug] VERSION_CURRENT..........: ${VERSION_CURRENT}"
    echo "##[debug] COMPONENT_IMAGE_NAME.....: ${COMPONENT_IMAGE_NAME}"
    echo "##[debug] IMAGE_DIGEST.............: ${IMAGE_DIGEST}"
    echo "##[debug] GRAFEAS_VERSION..........: ${GRAFEAS_VERSION}"

    curl -s -u ${NEXUS_DEFAULT_USR}:${NEXUS_DEFAULT_PSW} https://nexus.telefonica.com.br/repository/b2b-canaisdigitais-grafeas/io/grafeas/grafeas-project/${GRAFEAS_VERSION}/grafeas-project-${GRAFEAS_VERSION}-jar-with-dependencies.jar -o grafeas-cli.jar
    java -cp grafeas-cli.jar GrafeasListNoteOccurrences -p ${COMPONENT_IMAGE_NAME} -n "sonar-code-coverage" -bpi ${VERSION_CURRENT} -in "${IMAGE_REGISTRY_B2B_CANAISDIGITAIS}/${COMPONENT_IMAGE_NAME}@${IMAGE_DIGEST}"
  displayName: "Validate Grafeas"
  workingDirectory: $(Agent.TempDirectory)
  env:
    NEXUS_DEFAULT_USR: $(NEXUS-DEFAULT-USR)
    NEXUS_DEFAULT_PSW: $(NEXUS-DEFAULT-PSW)
    IMAGE_DIGEST: ${{ parameters.imageDigest }}
    COMPONENT_IMAGE_NAME: ${{ parameters.dockerImageName }}
    VERSION_CURRENT: ${{ parameters.dockerAppVersion }}
    IMAGE_REGISTRY_B2B_CANAISDIGITAIS: b2b-canaisdigitais-docker.nexus.telefonica.com.br
    GRAFEAS_VERSION: $(GRAFEAS_VERSION)