parameters:
  - name: correctionStrategy
    displayName: "Estratégia de correção de vulnerabilidades"
    type: object
    default:
      codeHealer: "SCA"
  - name: maxParallelScans
    type: number
    default: 5
  - name: minNodeVersion
    type: number
    default: 16
  - name: repository
    displayName: "Nome do repositório (ex: 'src-ms-checkout-express'). Se vazio, roda a matriz."
    type: string
    default: ""
  - name: branch
    displayName: "Branch a ser corrigida (ex: 'feat/xpto'). Se informado, commit direto na branch."
    type: string
    default: "master"
  - name: runSync
    displayName: "Executar sincronização de repositórios"
    type: boolean
    default: true
  - name: generateSbom
    displayName: "Gerar SBOM antes de rodar o agente (Single Repo)"
    type: boolean
    default: true
  - name: image
    displayName: "Imagem de container a ser corrigida"
    type: string
    default: ""

variables:
  - template: /tech_products/ecmc/code-healer/variables/load.yml

resources:
  repositories:
    - repository: CorePipelinesScripts
      name: DevOps/Vivo.Core.Pipelines.Scripts
      type: git
      ref: refs/heads/master
      endpoint: CorePipelines

    - repository: CodeHealerSCA
      name: ECMC - Ecomm Cloud B2C/src-agent-ai-code-healer-sca-python
      type: git
      ref: refs/heads/master
      endpoint: CorePipelines

stages:
  ## INIT
  - template: /tech_products/ecmc/core-pipelines/provisioners/app/trunkbased/nodejs/api_default/stages/init.yml

  ## VALIDATE STRATEGY CORRECTION
  - ${{ if eq(parameters.correctionStrategy.codeHealer, 'SCA') }}:
      - template: /tech_products/ecmc/code-healer/provisioners/code-healer-sca.yml
        parameters:
          projectPrefix: "$(System.TeamProject)-"
          maxParallelScans: ${{ parameters.maxParallelScans }}
          minNodeVersion: ${{ parameters.minNodeVersion }}
          repository: ${{ parameters.repository }}
          branch: ${{ parameters.branch }}
          runSync: ${{ parameters.runSync }}
          generateSbom: ${{ parameters.generateSbom }}

  - ${{ if eq(parameters.correctionStrategy.codeHealer, 'CONTAINER') }}:
      - template: /tech_products/ecmc/code-healer/provisioners/code-healer-container.yml
        parameters:
          image: ${{ parameters.image }}
