stages:
- stage: initial_validations
  displayName: "Validations"
  pool: $(PRIVATE_AGENT_DEFAULT)
  jobs:
  - job: validate_pipeline
    displayName: "Validate"
    steps:
    - task: CommitValidationTask@1
      name: "CommitValidationTask"
      displayName: "Commit Message Validation"
      inputs:
        message: $(Build.SourceVersionMessage)