steps:
- task: Bash@3
  displayName: "Defining App Security Asset Version"
  inputs:
    targetType: 'inline'
    script: |

        if [[ "$(Build.Reason)" == "PullRequest" ]]; then
          BRANCH_NAME="${PR_TARGET_BRANCH#refs/heads/}"
        else
          BRANCH_NAME="${SOURCE_BRANCH#refs/heads/}"
        fi

        if [[ "$BRANCH_NAME" =~ ^(master|main)$ ]]; then
          APP_VERSION="${FORTIFY_APP_DEFAULT_VERSION}"
        elif [[ "$BRANCH_NAME" =~ release ]]; then
          APP_VERSION="${FORTIFY_APP_DEFAULT_VERSION}-release"
        else
          APP_VERSION="${FORTIFY_APP_DEFAULT_VERSION}-${BRANCH_NAME}"
        fi

        # Exportando a versão da aplicação
        echo "##vso[task.setvariable variable=FORTIFY_APP_VERSION]$APP_VERSION"
        echo "Exportando a Versão '${APP_VERSION}' da aplicação para variável FORTIFY_APP_VERSION."

  env:
    SOURCE_BRANCH: "$(Build.SourceBranch)"
    PR_TARGET_BRANCH: "$(System.PullRequest.TargetBranch)"
    FORTIFY_APP_DEFAULT_VERSION: "$(FORTIFY_APP_DEFAULT_VERSION)"