parameters:
- name: pythonVersion
  type: string

stages:
- stage: build_test
  displayName: "Build & Test"
  ${{ if eq(variables.flowIsPullRequest, false) }}:
    dependsOn: bump_version
  ${{ else }}:
    dependsOn: pipeline_init
  pool: $(PRIVATE_AGENT_DEFAULT)
  jobs:
  - job: build_app
    displayName: Build & Test & Coverage
    steps:
    - template: /tech_products/srus/tasks/bash/welcome.yml

    - template: /tech_products/srus/tasks/databricks/lint_with_docker.yml
      parameters:
        pythonVersion: ${{ parameters.pythonVersion }}
        excludePaths: $(LINT_EXCLUDE_PATHS)
    - template: /tech_products/srus/task_groups/build/python_build_test.yml
      parameters:
        pythonVersion: ${{ parameters.pythonVersion }}
    - template: /tech_products/srus/task_groups/tests/publish_tests_reports.yml
      parameters:
        testResultsFilesPattern: "**/test-*.xml"
        codeCoverageTool: "Cobertura"
        publishCoverTaskVersion: 1

    - template: /tech_products/srus/tasks/telemetry/telemetry.yml
