stages:
- stage: pipeline_init
  displayName: "Pipeline initialization"
  pool: $(PRIVATE_AGENT_DEFAULT)
  jobs:
  - job: prepare_pipeline
    displayName: "Prepare"
    steps:
    - template: /tech_products/srus/tasks/artifacts/publish_catalog_info.yml