parameters:
- name: outputFile
  default: 'outputs.json'
- name: jsonPath

steps:
- script: |
    echo "##[debug] JSON_PATH..................: ${JSON_PATH}"
    echo "##[debug] OUTPUT_FILE................: ${OUTPUT_FILE}"

    echo "##[command] jq -r '${{ parameters.jsonPath }}.value // empty' ${PIPELINE_WORKSPACE}/${OUTPUT_FILE}"
    OUTPUT_VALUE=`jq -r '${{ parameters.jsonPath }}.value // empty' ${PIPELINE_WORKSPACE}/${OUTPUT_FILE}`

    echo "##[command] jq -r '${{ parameters.jsonPath }}.sensitive // empty' ${PIPELINE_WORKSPACE}/${OUTPUT_FILE}"
    IS_SENSITIVE=`jq -r '${{ parameters.jsonPath }}.sensitive // empty' ${PIPELINE_WORKSPACE}/${OUTPUT_FILE}`

    echo "##[debug] IS_SENSITIVE...............: ${IS_SENSITIVE}"

    if [ -z "${OUTPUT_VALUE}" ]; then
        echo "##vso[task.logissue type=error] Valor não encontrado para '${JSON_PATH}' no arquivo output '${OUTPUT_FILE}'."
        exit 1
    fi
    
    echo "##vso[task.setvariable variable=$JSON_PATH;]$OUTPUT_VALUE"
  displayName: Set variable ${{ parameters.jsonPath }}
  workingDirectory: $(Pipeline.Workspace)
  env:
    JSON_PATH: ${{ parameters.jsonPath }}
    OUTPUT_FILE: ${{ parameters.outputFile }}