parameters:
- name: dryRun
  type: boolean
  default: false

- name: versionsToKeep
  default: 0
  
- name: daysFromLastDownload
  default: 0

- name: feedName
  default: $(AZURE_ARTIFACTS_FEED)

- name: projectName
  default: $(AZURE_ARTIFACTS_ORGANIZATION)

variables:
- template: variables/load.yml

stages:
- template: stages/init.yml

- template: stages/select_purge_packages.yml
  parameters:
    versionsToKeep: ${{ parameters.versionsToKeep }}
    daysFromLastDownload: ${{ parameters.daysFromLastDownload }}
    dryRun: ${{ parameters.dryRun }}
    feedName: ${{ parameters.feedName }}
    projectName: ${{ parameters.projectName }}
