parameters:
- name: components_to_install
- name: qa_environment
- name: currentDate
- name: MAIN_SERVERS
- name: COMMONS_SERVERS
- name: MODELS_SERVERS
- name: USER


steps:
  - ${{ if or(or(contains(parameters.qa_environment, 'esteira1'), contains(parameters.qa_environment, 'esteira2')), or (contains(parameters.qa_environment, 'prodlike'), contains(parameters.qa_environment, 'preprod'))) }}:
      - ${{ each service_connection in split(parameters.MAIN_SERVERS,',') }}:
        - task: SSH@0
          displayName: "Stopping Smart History - MAIN ${{ split(service_connection, '|')[1] }} - ${{ split(service_connection, '|')[0] }}"
          inputs:
            sshEndpoint: ${{ split(service_connection, '|')[0] }}
            runOptions: inline
            failOnStdErr: false
            inline: |
              sudo su - $(user) <<EOF
                sh /opt/eisa/devops_smarthistory/stop_smart_history_application.sh ${{ parameters.qa_environment }}
              EOF
  - ${{ else }}:
      - ${{ each service_connection in split(parameters.MAIN_SERVERS,',') }}:
        - task: SSH@0
          displayName: "Stopping Smart History - MAIN ${{ split(service_connection, '|')[1] }} - ${{ split(service_connection, '|')[0] }}"
          inputs:
            sshEndpoint: ${{ split(service_connection, '|')[0] }}
            runOptions: inline
            failOnStdErr: false
            inline: |
                sh /opt/eisa/devops_smarthistory/stop_smart_history_application.sh ${{ parameters.qa_environment }}
