parameters:
  - name: packageName
  - name: packageVersion
  - name: infrastructureType

stages:
  - stage: ci_publish_package
    displayName: "CI - Publish"
    pool:
      name: $(AGENT_POOL_CI)
    dependsOn:
      - ci_security
      - ci_rename_package
    condition: succeeded()

    ## -> Loads variables from other stages.
    variables:
    - name: NEXUS_DEPS_USR
      value: $[ stageDependencies.environment_init.environment.outputs['credentials.NEXUS_DEPS_USR'] ]
    - name: NEXUS_DEPS_PSW
      value: $[ stageDependencies.environment_init.environment.outputs['credentials.NEXUS_DEPS_PSW'] ]
    - name: NEXUS_DEFAULT_USR
      value: $[ stageDependencies.environment_init.environment.outputs['credentials.NEXUS_DEFAULT_USR'] ]
    - name: NEXUS_DEFAULT_PSW
      value: $[ stageDependencies.environment_init.environment.outputs['credentials.NEXUS_DEFAULT_PSW'] ]
    - name: NEW_VERSION
      value: $[ stageDependencies.ci_build.build.outputs['new_version.NEW_VERSION'] ]
    - name: LEGACY_MODE
      value: $[ stageDependencies.ci_build.build.outputs['java_version.LEGACY_MODE'] ]
    - name: GROUP_ID
      value: $[ stageDependencies.ci_build.build.outputs['source_data.GROUP_ID'] ]
    - name: ARTIFACT_ID
      value: $[ stageDependencies.ci_build.build.outputs['source_data.ARTIFACT_ID'] ]
    - name: ARTIFACT_PATH
      value: $[ stageDependencies.ci_build.build.outputs['artifact_name.ARTIFACT_PATH'] ]
    - name: ARTIFACT_FILE
      value: $[ stageDependencies.ci_build.build.outputs['artifact_name.ARTIFACT_FILE'] ]
    - name: ARTIFACT_NAME
      value: $[ stageDependencies.ci_build.build.outputs['artifact_name.ARTIFACT_NAME'] ]
    - name: ARTIFACT_MODULES
      value: $[ stageDependencies.ci_build.build.outputs['artifact_name.ARTIFACT_MODULES'] ]
    - name: APP_COMPONENT_TYPE
      value: $[ stageDependencies.environment_init.environment.outputs['catalog_info.APP_COMPONENT_TYPE'] ]
    - name: KEBAB_CASE_PACKAGE_NAME
      value: $[ stageDependencies.ci_rename_package.rename_package.outputs['packages.KEBAB_CASE_PACKAGE_NAME'] ]
    - name: KEBAB_CASE_PACKAGE_VERSION
      value: $[ stageDependencies.ci_rename_package.rename_package.outputs['packages.KEBAB_CASE_PACKAGE_VERSION'] ]

    jobs:
      - job: publish
        displayName: "Publish"
        steps:
          ## -> Download Artifacts
          - download: none

          - task: DownloadPipelineArtifact@1
            displayName: Download Artifact
            inputs:
              buildType: "current"
              downloadPath: "$(Build.ArtifactStagingDirectory)"

          - task: UniversalPackages@0
            displayName: Publish a Universal Package
            inputs:
              command: publish
              publishDirectory: "$(Build.ArtifactStagingDirectory)"
              feedsToUsePublish: "internal"
              vstsFeedPublish: "3d53bc62-8749-4931-ae46-a443b73bc87a"
              vstsFeedPackagePublish: "$(KEBAB_CASE_PACKAGE_NAME)"
              packagePublishDescription: ""
              versionOption: "custom"
              versionPublish: "1.0.0-$(KEBAB_CASE_PACKAGE_VERSION)"
