parameters:
  - name: packageName
  - name: packageVersion

stages:
  - stage: ci_rename_package
    displayName: "CI - Rename Package"
    dependsOn:
      - default_initializer
    condition: succeeded()

    jobs:
      - job: rename_package
        displayName: "Rename Package"
        condition: succeeded()
        steps:
          - task: Bash@3
            displayName: 'Rename Package Name and Package Version'
            name: packages
            condition: succeeded()
            inputs:
              targetType: 'inline'
              script: |
                to_kebab_case() {
                    echo "$1" | sed -r 's/([a-z])([A-Z])/\1-\L\2/g' | tr '[:upper:]' '[:lower:]' | tr '_' '-'
                }

                package_name="${{ parameters.packageName }}"
                package_version="${{ parameters.packageVersion }}"

                kebab_package_name=$(to_kebab_case "$package_name")
                kebab_package_version=$(to_kebab_case "$package_version")

                echo "##vso[task.setvariable variable=ORIGINAL_PACKAGE_NAME;isOutput=true]$package_name"
                echo "##vso[task.setvariable variable=ORIGINAL_PACKAGE_VERSION;isOutput=true]$package_version"
                echo "##vso[task.setvariable variable=KEBAB_CASE_PACKAGE_NAME;isOutput=true]$kebab_package_name"
                echo "##vso[task.setvariable variable=KEBAB_CASE_PACKAGE_VERSION;isOutput=true]$kebab_package_version"

                echo "Package name: $package_name"
                echo "Package version: $package_version"
                echo "Package name (kebab case): $kebab_package_name"
                echo "Package version (kebab case): $kebab_package_version"
