parameters:
- name: 'envs'
  type: object
  default: {}
variables:
# MLFLOW TOOLS REPO
- name: MLFLOW_TOOLS_REPO
  value: 'git.telefonicabigdata.com/mlops/mlflow_admin_tools'

# PROJECT NAME
- name: PROJECT_NAME
  value: ${{ variables['Build.Repository.Name'] }}

# SHOULD NOT EXECUTE TRANSITION MODEL
- name: SHOULD_NOT_EXECUTE_TRANSITION_MODEL
  value: ${{ coalesce(parameters.envs.SHOULD_NOT_EXECUTE_TRANSITION_MODEL, 'false') }}
- name: 