parameters:
- name: playbookLocation
  default: $(ansiblePlaybookLocation)

- name: servicepricipal
  default: $(sp-tech-infra-db-brsouth)

steps:
- task: AnsibleFromVivo@1
  inputs:
    playbookPathOnAgentMachine: ${{ parameters.playbookLocation }}
    failOnStdErr: false
  displayName: Ansible Playbook POSTGRESQL
  env:
    ANSIBLE_VERBOSITY: $(ANSIBLE_VERBOSITY)
    CLIENT_SECRET: ${{ parameters.servicepricipal }}
