parameters:
- name: playbookLocation
  default: $(ansiblePlaybookLocation)

- name: servicepricipal
  default: $(sp-tech-infra-db-brsouth)

steps:
- script: |
    python -m pip install --upgrade pip
    pip install pyodbc
    ansible-galaxy collection install azure.azcollection
  displayName: 'Instalar dependências para SQL Server'


- task: AnsibleFromVivo@1
  inputs:
    playbookPathOnAgentMachine: ${{ parameters.playbookLocation }}
    failOnStdErr: false
  displayName: Ansible Playbook SQL
  env:
    ANSIBLE_VERBOSITY: $(ANSIBLE_VERBOSITY)
    CLIENT_SECRET: ${{ parameters.servicepricipal }}
