stages:
- stage: extract_version
  displayName: Extract Lib Version
  dependsOn: pipeline_init
  pool: $(PRIVATE_AGENT_DEFAULT)
  jobs:
  - job: get_version
    displayName: Get Version
    steps:
    - template: /tasks/git/checkout_last_commit.yml
      parameters:
        branchName: "$(Build.SourceBranchName)"
    - template: /tasks/python/extract_lib_version.yml
      parameters:
        currentVersionVariableOut: LIB_VERSION
