parameters:
- name: pythonVersion
  type: string

stages:
- stage: gate
  displayName: "Quality Gates"
  dependsOn: 
  - build_test
  pool: GeneralPurposeLinuxAgentsCI
  jobs:
  - job: sonarqube
    condition: and(succeeded(), ne(variables.skip_sonarqube, true), eq(variables.flowIsTagging, false))
    displayName: Code Analysis
    steps:
    - template: /tasks/bash/welcome.yml
    - ${{ if in(variables['Build.SourceBranch'], 'refs/heads/master', 'refs/heads/main', 'refs/heads/release', 'refs/heads/develop') }}:
      - template: /tasks/catalog_info/extract_variables.yml
        parameters:
          workingDirectory: $(Build.SourcesDirectory)
          skipDownload: true
      - template: /task_groups/gates/run_sonarqube_scan.yml
        parameters:
          stack: "PYTHON"
          pythonVersion: "${{parameters.pythonVersion}}"
          projectKey: "$(SONAR_PROJECT_KEY)"