parameters:
- name: pythonVersion
  type: string
- name: incrementLevel
  default: patch

stages:
- stage: package
  dependsOn:
  - extract_version
  - build_test
  displayName: "Package & Publish"
  pool: $(PRIVATE_AGENT_DEFAULT)
  jobs:
    - job: bump_version
      displayName: Bumping Library Version
      condition: eq(variables.BUMP_VERSION_ENABLED, true)
      variables:
        LIB_CURRENT_VERSION: $[ stageDependencies.extract_version.get_version.outputs['export_current_version.LIB_VERSION'] ]
      steps:
      - template: /tasks/bash/welcome.yml
      - template: /tasks/versioning/bump_version.yml
        parameters:
          currentVersion: $(LIB_CURRENT_VERSION)
          newVersionVariableOut: LIB_NEW_VERSION
          incrementLevel: ${{ parameters.incrementLevel }}
      - template: /tasks/telemetry/telemetry.yml

    - job: package
      displayName: "Package"
      dependsOn: bump_version
      variables:
        LIB_CURRENT_VERSION: $[ stageDependencies.extract_version.get_version.outputs['export_current_version.LIB_VERSION'] ]
        LIB_NEW_VERSION: $[ dependencies.bump_version.outputs['component_bump_version.LIB_NEW_VERSION'] ]
      condition: and(always(), eq(variables.flowIsTagging, false), eq(variables.flowIsMain, true))
      steps:
      - template: /tasks/bash/welcome.yml
      - template: /task_groups/package/python_lib_package.yml
        parameters:
          pythonVersion: ${{parameters.pythonVersion}}
          currentVersion: $(LIB_CURRENT_VERSION)
          newVersion: $(LIB_NEW_VERSION)
          incrementLevel: ${{ parameters.incrementLevel }}
