steps:
- script: |
    echo "##[debug] GIT_USER.............: ${GIT_USER}"
    echo "##[debug] GIT_ASKPASS..........: ${GIT_ASKPASS}"

    echo "exec echo \"$GIT_PASS\"" >> "${GIT_ASKPASS}"
    chmod 777 "${GIT_ASKPASS}"

    echo "##vso[task.setvariable variable=GIT_ASKPASS]$GIT_ASKPASS"
  displayName: Configure Git HTTPS
  workingDirectory: $(Agent.TempDirectory)
  env:
    GIT_PASS : "$(TF_GIT_PASS_MODULE)"
    GIT_USER : "$(TF_GIT_USER_MODULE)"
    GIT_ASKPASS: "$(Agent.TempDirectory)/git_env_password.sh"