parameters:
  - name: environment
  - name: helm_chart_version
  - name: k8s_service_connection
  - name: k8s_resource_group 
  - name: app_name
  - name: namespace
  - name: helm_chart_name
  - name: app_version  


variables:
- template: variables/pipeline.yaml
  parameters:
    environment: ${{ parameters.environment }}
    helm_chart_name: ${{ parameters.helm_chart_name }}
    helm_chart_version: ${{ parameters.helm_chart_version }}
    k8s_service_connection: ${{ parameters.K8S_SERVICE_CONNECTION }}
    k8s_resource_group: ${{ parameters.K8S_RESOURCE_GROUP }}
    app_name: ${{ parameters.app_name }}
    app_version: ${{ parameters.app_version }}

stages:
  - template: templates/cd/deploy.yaml
    parameters:
      environment: ${{ parameters.environment }}

 