parameters:
  environment: ''
  chg_number: ''

jobs:
- job: preparation
  pool: GeneralPurposeLinuxAgentsCD
  steps:
  - ${{ if eq( parameters.environment, 'prod') }}:
    - template: /tech_products/azr4/templates/steps/validate_chg.yaml
      parameters:
        chg_number: ${{ parameters.chg_number }}
