jobs:
  - job: Build
    displayName: 'Build Job'
    pool:
      vmImage: 'ubuntu-latest'
    variables:
      MAVEN_OPTS: '-Xmx3072m'
      MAVEN_CACHE_FOLDER: $(Pipeline.Workspace)/.m2/repository
    steps:  
      - task: JavaToolInstaller@0
        displayName: 'Use Java 8'
        inputs:
          versionSpec: 8
          jdkArchitectureOption: x64
          jdkSourceOption: 'PreInstalled'

      - task: Maven@3
        inputs:
          mavenPomFile: 'pom.xml'
          mavenOptions: '-Xmx3072m'
          options: '-B -e -X'
          goals: 'clean install'

      - script: |
          echo "Build directory: $(Build.SourcesDirectory)"
          echo "Staging directory: $(Build.ArtifactStagingDirectory)"
          echo "Copying JARs and POMs from Maven local repository to staging directory..."
          mkdir -p $(Build.ArtifactStagingDirectory)
          cp -r ~/.m2/repository/br/com/eisa/* $(Build.ArtifactStagingDirectory)/
          ls -la $(Build.ArtifactStagingDirectory)
        displayName: 'Copy Maven Local Repository to Staging Directory'

      - task: PublishBuildArtifacts@1
        displayName: Publish Build Artifacts
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: eisa
          StoreAsTar: false
