## -> Parameters:
parameters:
- name: qa_environment
  type: string
- name: components_to_install
  type: string
- name: skip_deploy
  type: boolean
  default: false

## -> Resources:
resources:
  repositories:
  - repository: FortifyExclusion
    name: DevOps/Vivo.Fortify.Exclusions
    type: git
    ref: refs/heads/master
    endpoint: CodePlay
  - repository: CorePipelines
    name: DevOps/Vivo.Core.Pipelines
    type: git
    ref: refs/tags/latest
    endpoint: CorePipelines

## -> Initialize global variables   
variables:

- template: /tech_products/ngin/initialize/variables_global.yml
- template: /tech_products/ngin/initialize/variables_weblogic_osgi.yml
- template: /.azuredevops/config/${{ parameters.qa_environment }}/environments_variables.yml@self

## -> Override global variables, with variables set in Library/Variable Groups (Pipelines)
## -> Use this to change the variables on runtime
- group: "${{ variables['Build.DefinitionName'] }}"

stages:

## -> Initialize pipeline 
- template: /tech_products/ngin/initialize/pipeline_init_weblogic_osgi.yml

## -> Build for CI - Weblogic
- template: /tech_products/ngin/templates/ci/ci_build_weblogic_osgi.yml

## -> Gates for CI - Weblogic
- template: /tech_products/ngin/templates/ci/ci_gates_weblogic_osgi.yml
  parameters:
    qa_environment: ${{ parameters.qa_environment }}
    
## -> Security for CI - Weblogic
- template: /tech_products/ngin/templates/ci/ci_security_weblogic_osgi.yml
  parameters:
    fortifyExclusionRepository: FortifyExclusion

## -> Package for CI - Weblogic
- template: /tech_products/ngin/templates/ci/ci_package_weblogic_osgi.yml

## -> Deploy for CD - Weblogic
- template: /tech_products/ngin/templates/cd/cd_deploy_weblogic_osgi.yml
  parameters:
    components_to_install: ${{ parameters.components_to_install }}
    qa_environment: ${{ parameters.qa_environment }}
    skip_deploy: ${{ parameters.skip_deploy }}
    weblogic_servers: ${{ variables.WEBLOGIC_SERVERS }}