parameters:
  - name: jdkVersion
    type: string
    default: '17'
  - name: mavenVersion
    type: string
    default: '3.8.1'

jobs:
  - job: Build
    displayName: 'Build Job'
    pool:
      vmImage: 'ubuntu-latest'
    variables:
      MAVEN_OPTS: '-Xmx3072m'
      MAVEN_CACHE_FOLDER: $(Pipeline.Workspace)/.m2/repository
    steps:
      - task: JavaToolInstaller@0
        displayName: 'Use Java 17'
        inputs:
          versionSpec: 17
          jdkArchitectureOption: x64
          jdkSourceOption: 'PreInstalled'

      - task: DownloadPipelineArtifact@2
        displayName: 'Download Artifacts from Previous Build'
        inputs:
          buildType: 'specific'
          project: 'SMRC - SMART CGW'
          pipeline: 'alarm-monitor-libs'
          runVersion: 'latest'
          artifact: 'eisa'
          targetPath: '$(Pipeline.Workspace)/maven-repo'

      - script: |
          echo "Using downloaded artifacts..."
          mkdir -p ~/.m2/repository/br/com/eisa
          cp -r $(Pipeline.Workspace)/maven-repo/* ~/.m2/repository/br/com/eisa/
          echo "Contents of ~/.m2/repository/br:"
          ls -laR ~/.m2/repository/br
        displayName: 'Copy Artifacts to Local Maven Repository'

      - task: Maven@3
        inputs:
          mavenPomFile: 'pom.xml'
          mavenOptions: '-Xmx3072m'
          options: '-B -e -X -DskipTests'
          goals: 'clean install'

      - script: |
          echo "Build directory: $(Build.SourcesDirectory)"
          echo "Staging directory: $(Build.ArtifactStagingDirectory)"
          echo "Copying JARs and POMs from Maven local repository to staging directory..."
          mkdir -p $(Build.ArtifactStagingDirectory)
          cp -r ~/.m2/repository/br/com/eisa/smarts/* $(Build.ArtifactStagingDirectory)/
          ls -la $(Build.ArtifactStagingDirectory)
        displayName: 'Copy Maven Local Repository to Staging Directory'    

      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'maven-artifact'

  - job: Deploy
    displayName: 'Deploy Job'
    dependsOn: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - task: DownloadPipelineArtifact@2
        inputs:
          buildType: 'current'
          artifactName: 'maven-artifact'
          targetPath: '$(Pipeline.Workspace)/maven-artifact'

      - task: CopyFilesOverSSH@0
        inputs:
          sshEndpoint: 'scgwQA41'  # Nome do service connection configurado
          sourceFolder: '$(Pipeline.Workspace)/maven-artifact/scgw/package/scgw-app-rpm/1.2.9-SNAPSHOT/'
          contents: 'scgw-app-rpm-1.2.9-SNAPSHOT-rpm.rpm'
          targetFolder: '/tmp/oms'
          cleanTargetFolder: false
          overwrite: true

      - task: SSH@0
        inputs:
          sshEndpoint: 'scgwQA41'  # Nome do service connection configurado
          runOptions: 'commands'
          commands: |
            chmod +x /tmp/oms/configure.sh
            /tmp/oms/configure.sh
          timeoutInMinutes: 10
          failOnStdErr: false
