parameters:
- name: taskName
  default: get_new_api
- name: continueOnError
  default: false
- name: name
- name: apiVersion

steps:
- script: |
    echo "##[debug] API_MANAGER_BASE_URL.....: ${API_MANAGER_BASE_URL}"
    echo "##[debug] FRONTEND_NAME_PARAM......: ${FRONTEND_NAME_PARAM}"
    echo "##[debug] API_VERSION..............: ${API_VERSION}"

    curl -s -k --fail --get \
    --data-urlencode "field=name" \
    --data-urlencode "op=eq" \
    --data-urlencode "value=${FRONTEND_NAME_PARAM}" \
    --user "${ADMIN_USERNAME}:${ADMIN_PASSWORD}" \
    "${API_MANAGER_BASE_URL}/proxies" > $(Agent.TempDirectory)/api_manager_frontend_new_response.json

    FRONTEND_NEW_API_NAME="$(jq -r '. | sort_by(.createdOn) | reverse | .[0].name // empty' $(Agent.TempDirectory)/api_manager_frontend_new_response.json)"
    FRONTEND_NEW_API_ID="$(jq -r '. | sort_by(.createdOn) | reverse | .[0].id // empty' $(Agent.TempDirectory)/api_manager_frontend_new_response.json)"
    FRONTEND_NEW_API_STATE="$(jq -r '. | sort_by(.createdOn) | reverse | .[0].state // empty' $(Agent.TempDirectory)/api_manager_frontend_new_response.json)"
    FRONTEND_NEW_API_VERSION="$(jq -r '. | sort_by(.createdOn) | reverse | .[0].version // empty' $(Agent.TempDirectory)/api_manager_frontend_new_response.json)"
    BACKEND_NEW_API_ID="$(jq -r '. | sort_by(.createdOn) | reverse | .[0].apiId // empty' $(Agent.TempDirectory)/api_manager_frontend_new_response.json)"

    if [ -z "${FRONTEND_NEW_API_ID}" ] || [ "${FRONTEND_NEW_API_VERSION}" != "${API_VERSION}" ]; then
      if [ -z "${FRONTEND_NEW_API_VERSION}" ]; then
        echo "##vso[task.logissue type=warning] New Frontend API was found but version is empty."
        echo "##vso[task.complete result=SucceededWithIssues;]"
      else
        echo "##vso[task.logissue type=error] New Frontend API '${FRONTEND_NAME_PARAM}' not found in environment for version '${API_VERSION}'."
        echo "##vso[task.complete result=Failed;]"
        exit
      fi
    fi

    echo "##[debug] FRONTEND_NEW_API_NAME....: ${FRONTEND_NEW_API_NAME}"

    echo "##[debug] FRONTEND_NEW_API_ID......: ${FRONTEND_NEW_API_ID}"
    echo "##vso[task.setvariable variable=FRONTEND_NEW_API_ID;isOutput=true]${FRONTEND_NEW_API_ID}"

    echo "##[debug] FRONTEND_NEW_API_STATE...: ${FRONTEND_NEW_API_STATE}"
    echo "##vso[task.setvariable variable=FRONTEND_NEW_API_STATE;isOutput=true]${FRONTEND_NEW_API_STATE}"

    echo "##[debug] FRONTEND_NEW_API_VERSION.: ${FRONTEND_NEW_API_VERSION}"
    echo "##vso[task.setvariable variable=FRONTEND_NEW_API_VERSION;isOutput=true]${FRONTEND_NEW_API_VERSION}"

    echo "##[debug] BACKEND_NEW_API_ID.......: ${BACKEND_NEW_API_ID}"
    echo "##vso[task.setvariable variable=BACKEND_NEW_API_ID;isOutput=true]${BACKEND_NEW_API_ID}"
  displayName: Get new API
  name: ${{ parameters.taskName }}
  continueOnError: ${{ parameters.continueOnError }}
  env:
    API_MANAGER_BASE_URL: $(API_MANAGER_BASE_URL)
    ADMIN_USERNAME: $(ADMIN_USERNAME)
    ADMIN_PASSWORD: $(ADMIN_PASSWORD)
    FRONTEND_NAME_PARAM: ${{ parameters.name }}
    API_VERSION: ${{ parameters.apiVersion }}