parameters:
- name: checkmarxThresholdArgsOut
  default: 'CHECKMARX_THRESHOLD_ARGS'
- name: skipSecurityGate
  default: false
- name: threshold
  type: object
  default:
    sast:
      high: '1'
      medium: ''
      low: ''
    sca:
      high: '1'
      medium: ''
      low: ''
    iac:
      high: '1'
      medium: ''
      low: ''
    api:
      high: '1'
      medium: ''
      low: ''

steps:
- bash: |
      if [[ "${SKIP_SECURITY_GATE}" == "True" ]]; then
        echo "##[warning]O Security Gate está Desligado, a avaliação não será executada."
        exit -1
      fi
      echo "##[debug]O Security Gate está Ligado."
  displayName: Setup Gate Condition
  continueOnError: true
  env:
    SKIP_SECURITY_GATE: ${{ parameters.skipSecurityGate }}

- bash: |
      getGate () {
        ENGINE=$1
        GATE_SEVERITY=$2
        RET=$([[ -n ${GATE_SEVERITY} ]] && echo -n "${ENGINE}=${GATE_SEVERITY};" || echo -n "")
        echo $RET
      }

      SAST="$(getGate sast-high ${SAST_HIGH})$(getGate sast-medium ${SAST_MEDIUM})$(getGate sast-low ${SAST_LOW})"
      IAC="$(getGate iac-security-high ${IAC_HIGH})$(getGate iac-security-medium ${IAC_MEDIUM})$(getGate iac-security-low ${IAC_LOW})"
      SCA="$(getGate sca-high ${SCA_HIGH})$(getGate sca-medium ${SCA_MEDIUM})$(getGate sca-low ${SCA_LOW})"
      API="$(getGate api-security-high ${API_HIGH})$(getGate api-security-medium ${API_MEDIUM})$(getGate api-security-low ${API_LOW})"

      if [[ -n "${SAST}" || -n "${IAC}" || -n "${SCA}" || -n "${API}" ]]; then
        CHECKMARX_THRESHOLD_ARGS="--threshold \"${SAST}${IAC}${SCA}${API}\""
      fi

      echo "##vso[task.setvariable variable=${CHECKMARX_THRESHOLD_ARGS_OUT};]$CHECKMARX_THRESHOLD_ARGS"
      echo "${CHECKMARX_THRESHOLD_ARGS_OUT}: ${CHECKMARX_THRESHOLD_ARGS}"
  displayName: "Prepare Gates"
  env:
    CHECKMARX_THRESHOLD_ARGS_OUT: ${{ parameters.checkmarxThresholdArgsOut }}
    SAST_HIGH: ${{ parameters.threshold.sast.high }}
    SAST_MEDIUM: ${{ parameters.threshold.sast.medium }}
    SAST_LOW: ${{ parameters.threshold.sast.low }}
    IAC_HIGH: ${{ parameters.threshold.iac.high }}
    IAC_MEDIUM: ${{ parameters.threshold.iac.medium }}
    IAC_LOW: ${{ parameters.threshold.iac.low }}
    SCA_HIGH: ${{ parameters.threshold.sca.high }}
    SCA_MEDIUM: ${{ parameters.threshold.sca.medium }}
    SCA_LOW: ${{ parameters.threshold.sca.low }}
    API_HIGH: ${{ parameters.threshold.api.high }}
    API_MEDIUM: ${{ parameters.threshold.api.medium }}
    API_LOW: ${{ parameters.threshold.api.low }}