variables:
- ${{ if not(variables.MULTI_CONTAINERAPP) }}:
  - name: MULTI_CONTAINERAPP
    value: false
- name: AZURE_CLIENT_ID
  value: $(PRODLIKE_AZURE_CLIENT_ID)
- name: AZURE_CLIENT_SECRET
  value: $(PRODLIKE_AZURE_CLIENT_SECRET)
- name: AZURE_SUBSCRIPTION
  value: $(PRODLIKE_AZURE_SUBSCRIPTION)
- name: CONTAINER_APP_NAME
  value: ${{ coalesce(parameters.envs.PRODLIKE_CONTAINER_APP_NAME, 'azure/prodlike.yaml') }}