parameters:
- name: applicationID

steps:
- script: |
    echo "##[debug] API_MANAGER_BASE_URL.....: ${API_MANAGER_BASE_URL}"
    echo "##[debug] APPLICATION_ID...........: ${APPLICATION_ID}"

    echo "##[command] GET /applications/${APPLICATION_ID}/apikeys"
    API_KEYS=$(curl -s -k --fail --get \
    --user "${ADMIN_USERNAME}:${ADMIN_PASSWORD}" \
    "${API_MANAGER_BASE_URL}/applications/${APPLICATION_ID}/apikeys" | jq -r '. | map(.id) | join(",") // empty')

    echo "##[debug] API_KEYS.................: ${API_KEYS}"

    echo "##vso[task.setvariable variable=APPLICATION_API_KEYS]${API_KEYS}"
  displayName: Get API Keys
  env:
    API_MANAGER_BASE_URL: $(API_MANAGER_BASE_URL)
    ADMIN_USERNAME: $(ADMIN_USERNAME)
    ADMIN_PASSWORD: $(ADMIN_PASSWORD)
    APPLICATION_ID: ${{ parameters.applicationID }}