parameters:
- name: search
  type: string
- name: replace
  type: string
  default: "[component_name]"
- name: path
  type: object

steps:
- script: |
    #!/bin/bash
    SEARCH_STRING="${{ parameters.search }}"
    REPLACE_STRING="${{ parameters.replace }}"
    IFS=$'\n' read -d '' -ra FILES <<< "$(find ${{ toJson(parameters.path) }} -type f)"

    for file in "${FILES[@]}"; do
        if grep -q "$SEARCH_STRING" "$file"; then
            sed -i "s/$SEARCH_STRING/$REPLACE_STRING/g" "$file"
        fi
    done
  displayName: 'Substituir Conteúdo nos Arquivos'
