variables:
- name: SKIP_TESTS
  value: false
- name: MULE_SETTINGS_FILE
  value: "settings-mule.xml"
- name: MULE_GET_TOKEN_HEALTH_ENDPOINT_BASE_URL
  value: https://autenticainthml.redecorp.br/ms_oauth/oauth2/endpoints/vivooauthservice/tokens
- name: isBumpingVersion
  value: $[ or(in(variables['Build.SourceBranch'], 'refs/heads/dev', 'refs/heads/master'), startsWith(variables['Build.SourceBranch'], 'refs/heads/release/')) ]
- name: isEnvBranch
  value: $[ in(variables['Build.SourceBranch'], 'refs/heads/dev', 'refs/heads/esteira01', 'refs/heads/esteira02', 'refs/heads/preprod', 'refs/heads/prodlike', 'refs/heads/master') ]
- name: MASTER_ADDITIONAL_DEPLOY_ENV_NAME
  value: prodlike