parameters:
- name: incrementLevel
  default: patch

stages:
- stage: build_test
  displayName: "Build & Test"
  pool: $(PRIVATE_AGENT_DEFAULT)
  dependsOn:
    - pipeline_init
  jobs:
    - job: bump_version
      displayName: Bumping Version
      steps:
      - template: /tasks/maven/extract_api_version.yml
        parameters:
          currentVersionVariableOut: DB_CURRENT_VERSION
      - template: /tasks/versioning/bump_version.yml
        parameters:
          currentVersion: $(export_current_version.DB_CURRENT_VERSION)
          newVersionVariableOut: DB_NEW_VERSION
          incrementLevel: ${{ parameters.incrementLevel }}

    - job: build_db
      displayName: Build & Test
      dependsOn:
        - bump_version
      variables:
      - name: DB_NEW_VERSION 
        value: $[ dependencies.bump_version.outputs['component_bump_version.DB_NEW_VERSION'] ]
      steps:
      - template: /tasks/bash/welcome.yml
        parameters:
          message: $(DB_BUILD_WELCOME_MSG)

      - template: /tasks/maven/update_build_version.yml
        parameters:
          newVersion: $(DB_NEW_VERSION)
          
      - template: /task_groups/build/liquibase_build_test.yml
