stages:
- stage: deploy
  condition: succeeded()
  dependsOn:
    - build_test
    - validation
  pool: $(PRIVATE_AGENT_DEFAULT)
  displayName: "Deploy ${{parameters.environment}}"
  variables:
    - name: DB_NEW_VERSION
      value: $[ stageDependencies.build_test.bump_version.outputs['component_bump_version.DB_NEW_VERSION'] ]
    - name: DB_CURRENT_VERSION
      value: $[ stageDependencies.build_test.bump_version.outputs['export_current_version.DB_CURRENT_VERSION'] ]
  jobs:
    - deployment: "deploy_${{parameters.environment}}"
      workspace:
        clean: all
      displayName: Deploy
      environment: "deploy-db-${{parameters.environment}}"
      strategy:
        runOnce:
          deploy:
            steps:
              - download: none
              - template: /task_groups/deploy/liquibase_run_deploy.yml
          on:
            success:
              steps:
                - template: /task_groups/deploy/liquibase_run_pos_deploy_success.yml
                  parameters:
                    environment: ${{parameters.environment}}
            failure:
              steps:
              - template: /task_groups/deploy/liquibase_run_pos_deploy_failure.yml
