stages:
- stage: gate
  displayName: "Quality Gates"
  variables:
  - name: APP_VERSION
    value: $[ stageDependencies.build_test.bump_version.outputs['component_bump_version.DB_NEW_VERSION'] ]
  dependsOn: build_test
  pool: $(PRIVATE_AGENT_DEFAULT)
  jobs:
  - job: sonarqube
    condition: and(succeeded(), eq(variables.flowIsTagging, false), ne(variables.skip_sonarqube, true), eq(variables.flowIsMain, true))
    displayName: Code Analysis
    steps:
    - template: /tasks/bash/welcome.yml
    - template: /tasks/catalog_info/extract_variables.yml
      parameters:
        skipDownload: true
        workingDirectory: $(Build.SourcesDirectory)
    - template: /task_groups/gates/run_sonarqube_scan.yml
      parameters:
        stack: "JAVA"
        artifactName: "db"
        projectKey: "$(SONAR_PROJECT_KEY)"
