parameters:
- name: branchName
  type: string

steps:
  - checkout: self
    persistCredentials: "true"
    clean: true
    
  - bash: |
      echo "##[info] Checkout last commit from '${BRANCH_NAME}'"

      git config pull.rebase true
      git fetch -f --depth 1 origin ${BRANCH_NAME}:${BRANCH_NAME}
      git checkout -f ${BRANCH_NAME}

      echo "##[command]Git command result code: '${?}'"

    displayName: Checkout last commit
    name: checkout_last_commit
    env:
      BRANCH_NAME: ${{ parameters.branchName }}