parameters:
- name: private_agent_pool
- name: environment
- name: kubeconfig
- name: dependsOn
- name: azureServiceConnectionEnabled
  default: false
- name: kubernetesServiceConnectionEnabled
  default: false

stages:
- stage: rollback
  dependsOn:
    - ${{ parameters.dependsOn }}
  pool: ${{ parameters.private_agent_pool }}
  displayName: "Rollback ${{ parameters.environment }}"
  jobs:
  - deployment: ${{ parameters.environment }}
    displayName: "Rollback"
    environment: "deploy-${{ parameters.environment }}-rollback"
    strategy:
      runOnce:
        deploy:
          steps:
          - download: none
          - checkout: self
          - template: /task_groups/deploy/run_argorollouts_rollback.yml
            parameters:
              environment: ${{ parameters.environment }}
              kubeconfig: ${{ parameters.kubeconfig }}
              azureServiceConnectionEnabled: ${{ parameters.azureServiceConnectionEnabled }}
              kubernetesServiceConnectionEnabled: ${{ parameters.kubernetesServiceConnectionEnabled }}
