## -> Parameters:
parameters:

- name: bump_version
- name: bump_message
- name: use_flutter_version_latest
  default: true

## -> Resources:
resources:
  repositories:
  - repository: FortifyExclusion
    name: DevOps/Vivo.Fortify.Exclusions
    type: git
    ref: refs/heads/master
    endpoint: CorePipelines  

## -> Initialize global variables   
variables:

- template: /tech_products/appv/flutter/initialize/variables_global.yml
- template: /tech_products/appv/flutter/initialize/variables_flutter_web.yml

## -> Override global variables, with variables set in Library/Variable Groups (Pipelines)
## -> Use this to change the variables on runtime
- group: "${{ variables['Build.DefinitionName'] }}"

stages:

## -> Initialize pipeline 
- template: /tech_products/appv/flutter/initialize/pipeline_init_flutter_web.yml

## -> Build for CI - Flutter
- template: /tech_products/appv/flutter/templates/ci/ci_build_flutter_web.yml
  parameters:
    use_flutter_version_latest: ${{ parameters.use_flutter_version_latest }}

## -> Gates for CI - Gates
- template: /tech_products/appv/flutter/templates/ci/ci_gates_flutter_web.yml

## -> Security for CI - Gates
- template: /tech_products/appv/flutter/templates/ci/ci_security_flutter_web.yml
  parameters:
    fortifyExclusionRepository: FortifyExclusion

## -> Package for CI - Flutter
- template: /tech_products/appv/flutter/templates/ci/ci_package_flutter_web.yml
  parameters:
    use_flutter_version_latest: ${{ parameters.use_flutter_version_latest }}

## -> Publish for CI - Flutter
- template: /tech_products/appv/flutter/templates/ci/ci_publish_flutter_web.yml

## -> TAG for CI - Flutter
- template: /tech_products/appv/flutter/templates/ci/ci_tag_flutter_web.yml
  parameters:
    bump_version: ${{ parameters.bump_version }}
    bump_message: ${{ parameters.bump_message }}

