## -> Parameters:
parameters:
  - name: environment
    displayName: "Escolha o ambiente para publicar"
    type: string
    default: preprod
    values:
      - preprod
      - producao
  - name: deliveryModel
    displayName: Modelo de entrega
    type: string
    default: publishOnly
    values:
    - publishOnly
    - deployOnly
  - name: packageName
    type: string
    default: ""
  - name: packageVersion
    type: string
    default: ""
  - name: infrastructureType
    type: string
    default: "weblogic"
    values:
      - weblogic


variables:
  ## -> Override global variables, with variables set in Library/Variable Groups (Pipelines)
  ## -> Use this to change the variables on runtime
  - group: "${{ variables['Build.Repository.Name'] }}"
  - template: /tech_products/cnte/externals-packages/initializers/global_initializer.yml

stages:
  ## -> Entrypoint
  - ${{ if eq(parameters.deliveryModel, 'publishOnly') }}:
      - template: /tech_products/cnte/externals-packages/pipeline_dvps_external_package_ci_v1.yaml
        parameters:
          environment: "${{parameters.environment}}"
          packageName: "${{parameters.packageName}}"
          packageVersion: "${{parameters.packageVersion}}"
          infrastructureType: "${{ parameters.infrastructureType }}"

  - ${{ else }}:
      - template: /tech_products/cnte/externals-packages/pipeline_dvps_external_package_cd_v1.yaml
        parameters:
          environment: "${{parameters.environment}}"
          deliveryModel: "${{parameters.deliveryModel}}"
          packageName: "${{parameters.packageName}}"
          packageVersion: "${{parameters.packageVersion}}"
          infrastructureType: "${{ parameters.infrastructureType }}"
