parameters:
- name: 'envs'
  type: object
  default: {}
- name: 'recipe'
  type: string
  default: ''

variables:
- ${{ if eq(parameters.envs.PRODLIKE_USE_VARS_FROM_HML, 'true') }}:
  - template: /tech_products/azr4/recipes/deploy/${{ parameters.recipe }}/variables/hml.yaml
    parameters:
      envs: ${{ parameters.envs }}
- ${{ else }}:
  - template: /tech_products/azr4/recipes/deploy/${{ parameters.recipe }}/variables/prodlike.yaml
    parameters:
      envs: ${{ parameters.envs }}