[global]
timeout = 60
index = http://nexus.telefonica.com.br/repository/devops-quickstart-pypi-all/pypi
index-url = http://nexus.telefonica.com.br/repository/devops-quickstart-pypi-all/simple
trusted-host = nexus.telefonica.com.br