parameters:
  - name: artifactDir
    type: string
    default: "$(System.ArtifactsDirectory)/extracted_tars/app"
  - name: mavenSettingsLocation
    type: string
    default: $(DEFAULT_MAVEN_SETTINGS)
  - name: azureArtifactsFeed
    type: string
    default: "$(AZURE_ARTIFACTS_FEED)"
  - name: azureArtifactsOrganization
    type: string
    default: "$(AZURE_ARTIFACTS_ORGANIZATION)"
  - name: azureArtifactsMavenFeedURL
    type: string
    default: "$(AZURE_ARTIFACTS_MAVEN_FEED_URL)"
  - name: publishCondition
    type: object

steps:
- task: AzureKeyVault@2  
  displayName: 'Getting AKV credentials'
  timeoutInMinutes: 1
  retryCountOnTaskFailure: 5
  condition: ${{ parameters.publishCondition }}
  inputs:    
    azureSubscription: DevOpsSharedResources    
    KeyVaultName: $(AKV_DEVOPS_NAME)
    SecretsFilter: 'NEXUS-DEPS-USR, NEXUS-DEPS-PSW'

- bash: |
    echo "##[debug]Publishing to Azure Artifacts' feed: ${AZURE_ARTIFACTS_FEED}"
    echo "##[debug]Maven settings.....: ${{ parameters.mavenSettingsLocation }}"

    mvn -version
    java -version

    mvn deploy \
    -s ${{ parameters.mavenSettingsLocation }} \
    -DaltDeploymentRepository="${AZURE_ARTIFACTS_ORGANIZATION}::default::${AZURE_ARTIFACTS_MAVEN_FEED_URL}" \
    -Dmaven.repo.local=$(MAVEN_CACHE_FOLDER) \
    -Dmaven.process-resources.skip=true \
    -Dmaven.install.skip=true \
    -Dmaven.compile.skip=true \
    -Dmaven.package.skip=true \
    -Dmaven.process-test-resources.skip=true \
    -Dmaven.test-compile.skip=true \
    -Dmaven.test.skip=true \
    -Dmaven.gitcommitid.skip=true \
    -Dskip.installnodenpm=true \
    -Dskip.npm=true \
    -DskipTests

  displayName: "Publish to Azure Artifacts"
  workingDirectory: "${{ parameters.artifactDir }}"
  env:
    AZURE_ARTIFACTS_FEED: ${{ parameters.azureArtifactsFeed }}
    AZURE_ARTIFACTS_ORGANIZATION: ${{ parameters.azureArtifactsOrganization }}
    AZURE_ARTIFACTS_MAVEN_FEED_URL: ${{ parameters.azureArtifactsMavenFeedURL }}
    SYSTEM_ACCESSTOKEN: $(System.AccessToken)
    NEXUS_DEPS_USR: $(NEXUS-DEPS-USR)
    NEXUS_DEPS_PSW: $(NEXUS-DEPS-PSW)
    ASDF_JAVA_VERSION: $(JAVA_VERSION_PUBLISH_MVN)
  condition: ${{ parameters.publishCondition }}