parameters:
  environment: ''
  chg_number: ''

jobs:
- job: preparation
  pool: GeneralPurposeLinuxAgentsCD
  steps:
  - ${{ if eq( parameters.environment, 'prod') }}:
    - script: echo "##[warning] a validação de CHG está desabilitada"
      displayName: 'CHG Validation Warning'




