parameters:
- name: 'envs'
  type: object
  default: {}


variables:
- ${{ if eq(parameters.envs.DEV_GCP_CRED_FILE_B64, 'POC_GCP_CRED_FILE_B64') }}:
  - name: DEV_GCP_CRED_FILE_B64
    value:  $(POC_GCP_CRED_FILE_B64)
- ${{ if eq(parameters.envs.DEV_GCP_CRED_FILE_B64, 'DEV_MLOPS_GCP_CRED_FILE_B64') }}:
  - name: DEV_GCP_CRED_FILE_B64
    value:  $(DEV_MLOPS_GCP_CRED_FILE_B64)
- name: GCP_CRED_FILE_B64
  value: $(DEV_GCP_CRED_FILE_B64)
- name: IMAGE_REGISTRY
  value: ${{ coalesce(parameters.envs.DEV_IMAGE_REGISTRY, variables['DEV_IMAGE_REGISTRY']) }}
- name: GCP_PROJECT_NAME
  value: ${{ coalesce(parameters.envs.DEV_GCP_PROJECT_NAME, variables['DEV_GCP_PROJECT_NAME']) }}
- name: ENVIRONMENT
  value: dev
- name: IMAGE_NAME
  value: ${{ coalesce(parameters.envs.DEV_IMAGE_NAME, variables['Build.Repository.Name']) }}
- name: DEFAULT_CLOUDRUN_JOB_FILE_PATH
  value: gcp/$(ENVIRONMENT)-job.yaml
- name: DEPLOY_AND_EXECUTE_JOB
  value: ${{ coalesce( parameters.envs.DEPLOY_AND_EXECUTE_JOB, 'false') }}
- name: CLOUDRUN_JOB_FILE_PATH
  value:  ${{ coalesce( parameters.envs.DEV_CLOUDRUN_JOB_FILE_PATH, variables['DEFAULT_CLOUDRUN_JOB_FILE_PATH']) }}
- name: DEFAULT_CLOUDRUN_CLI_FILE_PATH
  value: gcp/$(ENVIRONMENT)-cli.yaml
- name: CLOUDRUN_CLI_FILE_PATH
  value:  ${{ coalesce( parameters.envs.DEV_CLOUDRUN_CLI_FILE_PATH, variables['DEFAULT_CLOUDRUN_CLI_FILE_PATH']) }}
- name: DEPLOY_SERVICE
  value: ${{ coalesce( parameters.envs.DEPLOY_SERVICE, 'true') }}
- name: DEFAULT_CLOUDRUN_FILE_PATH
  value: gcp/$(ENVIRONMENT).yaml
- name: CLOUDRUN_FILE_PATH
  value:  ${{ coalesce( parameters.envs.DEV_CLOUDRUN_FILE_PATH, variables['DEFAULT_CLOUDRUN_FILE_PATH']) }}
# - name: USE_YAML_TO_DEPLOY
#   value: $(USE_YAML_TO_DEPLOY)
# - name: DEPLOY_AND_EXECUTE_JOB
#   value: $(DEPLOY_AND_EXECUTE_JOB)
# - name: CLOUD_RUN_JOB_NAME
#   value: $(DEV_CLOUD_RUN_JOB_NAME)
# - name: DEPLOY_CLI_SERVICE
#   value: $(DEPLOY_CLI_SERVICE)
