stages:

- stage: ci_build_native
  displayName: "CI - Build Native"
  pool:
    name: GeneralPurposeLinuxAgentsCI
  dependsOn:
  - environment_init

  ## -> Loads variables from other stages.
  variables:
  - name: MAVEN_SETTINGS_LOCATION
    value: $[ stageDependencies.environment_init.environment.outputs['settings_variables.MAVEN_SETTINGS_LOCATION'] ]
  - name: MAVEN_CUSTOM_SETTINGS_CONTENT
    value: $[ stageDependencies.environment_init.environment.outputs['custom_settings.MAVEN_CUSTOM_SETTINGS_CONTENT'] ]
  - name: NEXUS_DEPS_USR
    value: $[ stageDependencies.environment_init.environment.outputs['credentials.NEXUS_DEPS_USR'] ]    
  - name: NEXUS_DEPS_PSW
    value: $[ stageDependencies.environment_init.environment.outputs['credentials.NEXUS_DEPS_PSW'] ]
  
  jobs:      
  - job: build
    displayName: Build    
    steps:

    ## -> Clean the pipeline workspace and checkout the code.
    ## -> 6d15af64-176c-496d-b583-fd2ae21d4df4 is the decorator for checkout.
    - task: 6d15af64-176c-496d-b583-fd2ae21d4df4@1
      displayName: Checkout Code
      name: checkout_code 
      inputs:
        repository: self
        persistCredentials: "true"
        clean: true

    ## -> Checkout the last commit that was pushed to the repository. 
    ## -> Set last commit HASH to a variable. 
    - task: Bash@3
      displayName: Checkout Last Commit
      name: checkout_last_commit     
      condition: succeeded()
      continueOnError: false
      inputs:
        targetType: inline
        script: |
          echo "##[debug] Checkout last commit from '$(Build.SourceBranchName)'"

          git config pull.rebase true
          git fetch -f --depth 1 origin $(Build.SourceBranchName):$(Build.SourceBranchName)
          git checkout -f $(Build.SourceBranchName)
          lastCommitHash=$(git rev-parse --short=6 HEAD)

          echo "##[debug] Last commit short hash '$lastCommitHash'"          
          echo "##vso[task.setvariable variable=SHORT_HASH]$lastCommitHash"

    ## -> Load Custom Settings
    - task: Bash@3
      displayName: 'Load Custom Settings'
      name: load_custom_settings
      condition: and(
        succeeded(),
        ne(variables['MAVEN_CUSTOM_SETTINGS_CONTENT'], ''))
      continueOnError: true
      inputs:
        targetType: inline
        script: |
          echo "##[debug] Loading custom settings: $(MAVEN_CUSTOM_SETTINGS_CONTENT)"
          echo "##[debug] Location: $(MAVEN_SETTINGS_LOCATION)"
          base64 -d <<< "$(MAVEN_CUSTOM_SETTINGS_CONTENT)" > $(MAVEN_SETTINGS_LOCATION)

    # ==================================================================
    # [Compliance] Verifica se o repositório está em conformidade com as políticas de configuração
    # ==================================================================
    - task: VivoDevOpsConfigCompliance@1
      displayName: 'Check DevOps Config Compliance'
      inputs:
        policySets: |
          image-definition-files

    ## -> Build application and generate artifact.
    - task: Bash@3
      displayName: Build Version
      name: build_version
      condition: succeeded()
      continueOnError: false
      inputs:
        targetType: inline
        script: >
          BUILDER_IMAGE_NAME="builder/java"

          echo "##[debug] DOCKER_CMD_USERNAME: $(DOCKER_CMD_USERNAME)"
          echo "##[debug] DOCKER_CMD_GROUP: $(DOCKER_CMD_GROUP)"

          docker build -t $BUILDER_IMAGE_NAME -f .azuredevops/builder.Dockerfile .

          run_docker() {
            DOCKER_CMD_USERNAME=$(id -u)
            DOCKER_CMD_GROUP=$(id -g)

            docker run --rm \
              -v $HOME/.m2:/.m2 \
              "$BUILDER_IMAGE_NAME" sh -c "chown -R $DOCKER_CMD_USERNAME:$DOCKER_CMD_GROUP /.m2/repository"

            docker run --rm \
              --user="$(DOCKER_CMD_USERNAME):$(DOCKER_CMD_GROUP)" \
              --network host \
              --log-driver none \
              -e JAVA_OPTS_MEMORY_MAX="$(DEFAULT_MAX_MEMORY_BUILD)" \
              -e TZ="America/Sao_Paulo" \
              -e SYSTEM_ACCESSTOKEN="$(System.AccessToken)" \
              -e NEXUS_DEPS_USR="$(NEXUS_DEPS_USR)" \
              -e NEXUS_DEPS_PSW="$(NEXUS_DEPS_PSW)" \
              -v $(pwd):/app \
              -v $HOME/.m2:/.m2 \
              -v $(MAVEN_SETTINGS_LOCATION):/.m2/settings.xml \
              -w $(DOCKER_WORKDIR) \
              "$BUILDER_IMAGE_NAME" sh -c "$1"
          }

          run_docker "mvn --version"

          echo "##[debug] mvn command: $(JAVA_CMD_BUILD_NATIVE)"

          run_docker "mvn $(JAVA_CMD_BUILD_NATIVE) -Dmaven.test.failure.ignore=false -s /.m2/settings.xml -Dmaven.repo.local=/.m2/repository"
          
    ## -> Copy files for staging area
    - task: CopyFiles@2
      name: t_copy_file
      displayName: 'Copy to Staging Directory'
      condition: succeeded()
      continueOnError: false
      inputs:
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
        OverWrite: true
        CleanTargetFolder: true
        Contents: >
          **/*

          !.git/**/*

          !?/**/*

          !**/*.log

    ## -> Set artifact information to variables. This allows it to be used in other stages, jobs or tasks. 
    - task: CmdLine@2
      name: artifact_name   
      displayName: 'Get Artifact Name'       
      condition: succeeded()
      continueOnError: false
      inputs:
        targetType: inline
        script: |
          setVariables(){
            eval result=$2
            echo "##vso[task.setvariable variable=$1;isOutput=true]$result"
          }

          targetDirectory=$(echo "$(Build.ArtifactStagingDirectory)/target")
          echo "##[debug] Target Directory '$targetDirectory'"
          artifactFile=$(ls "$targetDirectory" | grep -E "${IMAGE_NAME}" | head -n 1)

          artifactName=$(basename $artifactFile | sed 's/\.[^.]*$//')-native
          echo "##[debug] Artifact Name '$artifactName'"

          setVariables "ARTIFACT_FILE" $artifactFile
          setVariables "ARTIFACT_NAME" $artifactName

    ## -> Compress artifacts into tar. This allows to use less space and to be used in other stages, jobs or tasks.           
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact'
      condition: succeeded()
      continueOnError: false
      inputs:
        ArtifactName: app
        StoreAsTar: true
