# This YAML file defines a pipeline task for pushing changes to a Git repository in Azure Repos.

parameters:
  - name: repository # The name of the repository to push changes to.
  - name: repositoryLocalPath # The local path of the repository on the agent machine.
  - name: commitMessage # The commit message for the changes.
  - name: isEmptyCommit # Flag indicating whether the commit is empty or not. Default value is false.
    default: false
  - name: isOnlyFilesChanged # Flag indicating whether to push only if files have changed.
    default: true

steps:
  - task: CmdLine@2
    ${{ if eq(parameters.isEmptyCommit, 'false') }}:
      displayName: "Commit ${{ parameters.repository }} in Azure Repos"
    ${{ else }}:
      displayName: "Empty Commit ${{ parameters.repository }} in Azure Repos"
    retryCountOnTaskFailure: 3
    inputs:
      workingDirectory: ${{ parameters.repositoryLocalPath }}
      script: |
        # Print debug information
        echo "##[debug] REPOSITORY_LOCAL_PATH ............................: ${REPOSITORY_LOCAL_PATH}"
        echo "##[debug] IS_EMPTY_COMMIT ..................................: ${IS_EMPTY_COMMIT}"
        echo "##[debug] COMMIT_MESSAGE ...................................: ${COMMIT_MESSAGE}"
        echo "##[debug] REPOSITORY .......................................: ${REPOSITORY}"
        echo "##[debug] BRANCH ...........................................: ${BRANCH}"
        echo "##[debug] IS_ONLY_FILES_CHANGED ............................: ${IS_ONLY_FILES_CHANGED}"
        echo ""

        echo "##[group]Files in ${REPOSITORY_LOCAL_PATH}"
        echo "##[command]git status --porcelain"
        git status --porcelain
        echo "##[endgroup]"
        echo ""

        # Check if the commit is empty
        if [ ${IS_EMPTY_COMMIT} == 'true' ]; then
          echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>:<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<"
          echo ">>>>>>>>>>>>>>>>>>>>>>> EMPTY COMMIT <<<<<<<<<<<<<<<<<<<<<<<<"
          echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>:<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<"
        fi

        echo "##[group]Git Configuration"

        # Configure git user email
        echo "##[command]git config --local user.email "fnix.devops@telefonicati.onmicrosoft.com""
        git config --local user.email "fnix.devops@telefonicati.onmicrosoft.com"

        # Configure git user name
        echo "##[command]git config --local user.name "Azure Pipeline Fênix""
        git config --local user.name "Azure Pipeline Fênix"

        # Add changes to the staging area if the commit is not empty
        if [ ${IS_EMPTY_COMMIT} == 'false' ]; then
          if [ ${IS_ONLY_FILES_CHANGED} == 'true' ]; then
            echo "##[command]git add -u ."
            git add -u .
          else
            echo "##[command]git add -- . ':!.artifactignore'"
            git add -- . ':!.artifactignore'
          fi

        fi

        echo "##[command]git status"
        git status

        # Commit the changes
        echo "##[command]git commit --allow-empty -m "${COMMIT_MESSAGE}""
        git commit --allow-empty -m "${COMMIT_MESSAGE}"

        # Pull the latest changes from the remote repository
        echo "##[command]git pull --rebase --autostash origin ${BRANCH}"
        git pull --rebase --autostash origin ${BRANCH}

        echo "##[endgroup]"

        echo ""

        # Push the changes to the remote repository
        echo "##[command]git push origin HEAD:${BRANCH}"
        git push origin HEAD:${BRANCH}
    env:
      AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)
      REPOSITORY_LOCAL_PATH: ${{ parameters.repositoryLocalPath }}
      IS_EMPTY_COMMIT: ${{ parameters.isEmptyCommit }}
      COMMIT_MESSAGE: ${{ parameters.commitMessage }}
      REPOSITORY: ${{ parameters.repository }}
      BRANCH: $(Build.SourceBranchName)
      IS_ONLY_FILES_CHANGED: ${{ parameters.isOnlyFilesChanged }}
