steps:
- script: |
    echo "##[debug] API_MANAGER_BASE_URL.....: ${API_MANAGER_BASE_URL}"

    echo "##[command] GET /currentuser"
    CURRENT_USER_ID=$(curl -s -k --fail --get \
    --user "${ADMIN_USERNAME}:${ADMIN_PASSWORD}" \
    "${API_MANAGER_BASE_URL}/currentuser" | jq -r '.id // empty')

    if [ -z "${CURRENT_USER_ID}" ]; then
      echo "##vso[task.logissue type=error] Current user not found in API Manager."
      echo "##vso[task.complete result=Failed;]"
      exit
    fi

    echo "##[debug] CURRENT_USER_ID..........: ${CURRENT_USER_ID}"

    echo "##vso[task.setvariable variable=CURRENT_USER_ID]${CURRENT_USER_ID}"
  displayName: Get Current User
  env:
    API_MANAGER_BASE_URL: $(API_MANAGER_BASE_URL)
    ADMIN_USERNAME: $(ADMIN_USERNAME)
    ADMIN_PASSWORD: $(ADMIN_PASSWORD)