parameters:
- name: zippedFilesfolderPath

steps: 
- task: CmdLine@2
  displayName: "Unzip Files"
  inputs:
    script: |
      echo "##[debug] ZIPPED FILES FOLDER PATH ........................................: ${{ parameters.zippedFilesfolderPath }}"

      compressed_files () {
        printf "\n>>>>> Checking if there are compressed files in the [$1] folder\n"

        # Find all .zip files in the specified folder.
        ALL_ZIP_FILES=$(find $1 \( -name "*.zip" -o -name "*.zip&patch_password=*" \) 2>/dev/null)
        
        if [ "${#ALL_ZIP_FILES}" -gt 0 ]; then
            printf "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ .zip Files: @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@\n $ALL_ZIP_FILES\n"
            printf "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@\n\n"
            
            COUNT_ZIP_FILES=0
            while IFS= read -r zip_file || [[ -n "$zip_file" ]]; do
                ((COUNT_ZIP_FILES++))
                COMPRESSED_FILE=${zip_file##*/}
                echo ">>>>>>>>>>>>>>> ($COUNT_ZIP_FILES) $COMPRESSED_FILE <<<<<<<<<<<<<<<"

                FOLDER=$(IFS='.' read -ra comp_file2 <<< $COMPRESSED_FILE && echo "${comp_file2[0]}")

                printf ">>>>>>>>>>>>>>>>>>>>>>>>> Unzipping the file\n"

                # Unzip the .zip file and recursively check for compressed files in the extracted folder.
                unzip $zip_file -d $1/$FOLDER

                compressed_files $1/$FOLDER

                echo "============================== : =============================="
            done <<< "$(echo "$ALL_ZIP_FILES")"
        else
            echo "There is no .zip file in the folder."
        fi
      }

      # Call the compressed_files function to check for compressed files in the image_zip folder.
      compressed_files ${{ parameters.zippedFilesfolderPath }}