parameters:
- name: environment
- name: workDir
- name: k8sKubeconfig
- name: helmRepoUrl
- name: helmRepoName
- name: helmRepoUsername
- name: helmRepoPassword

steps:
- bash: |
    source ~/.bashrc
    helm repo add --force-update ${{parameters.helmRepoName}} ${{parameters.helmRepoUrl}} \
      --insecure-skip-tls-verify \
      --username ${{parameters.helmRepoUsername}} \
      --password ${{parameters.helmRepoPassword}} \
      --kubeconfig ${{parameters.k8sKubeconfig}}
      
    helm repo update --kubeconfig ${{parameters.k8sKubeconfig}}
  displayName: "Add default helm repo"
  condition: and( succeeded(), not(eq(variables['HELM_REGISTRY_ACR_ENABLED'], 'true')))