parameters:
- name: components_to_install
- name: qa_environment
- name: currentDate
- name: ENGINE_SERVERS
- name: deploy_command

steps:
  - ${{ each service_connection in split(parameters.ENGINE_SERVERS,',') }}:
    - task: SSH@0
      displayName: "Deploy to JBOSS ${{ split(service_connection, '|')[1] }} - ${{ split(service_connection, '|')[0] }}"
      inputs:
        sshEndpoint: ${{ split(service_connection, '|')[0] }}
        runOptions: inline
        failOnStdErr: true
        inline: |
          echo "executing deploy"
          ${{ parameters.deploy_command }}