jobs:
- job: post_deployment
  pool: GeneralPurposeLinuxAgentsCD
  condition: true
  steps:
  - task: Bash@3
    name: post_deployment
    continueOnError: false
    env:
      NEW_VERSION: $(get_version.VERSION)
      CLIENT_ID: $(AZURE_CLIENT_ID)
      CLIENT_SECRET: $(AZURE_CLIENT_SECRET)
      TENANT_ID: $(AZURE_TENANT_ID)
      MULTI_CONTAINERAPP: $(MULTI_CONTAINERAPP)
      SUBSCRIPTION: $(AZURE_SUBSCRIPTION)
      BRANCH_NAME: $(Build.SourceBranchName)
      CONTAINER_APP_NAME: $(CONTAINER_APP_NAME)
      ENVIRONMENT: ${{ parameters.environment }}
    inputs:
      targetType: inline
      script: |
        #!/bin/bash

        get_logs() {
          if [ -z "$1" ]; then
            echo "##[error] Error: no containerapp path provided"
            exit 1
          fi
          local CONTAINERAPP_PATH="$1"
          local CONTAINER_ID=$(yq e '.id' "$CONTAINERAPP_PATH")
          local SUBSCRIPTION_ID=$(echo $CONTAINER_ID | cut -d'/' -f3)
          local RESOURCE_GROUP=$(echo $CONTAINER_ID | cut -d'/' -f5)
          local CONTAINER_NAME=$(echo $CONTAINER_ID | cut -d'/' -f9)

          echo "##[debug] Getting logs for containerapp: $CONTAINER_NAME in resource group: $RESOURCE_GROUP"
          az containerapp revision list --name ${CONTAINER_NAME} --resource-group ${RESOURCE_GROUP} \
            --subscription ${SUBSCRIPTION_ID} | jq -r '.[] | .name' | while read revision; do
              echo "##[debug] Getting logs for revision: $revision"
              az containerapp logs show --name ${CONTAINER_NAME} \
                --resource-group ${RESOURCE_GROUP} \
                --revision $revision \
                --subscription ${SUBSCRIPTION_ID}
            done
        }
        echo "##[debug] Login to azure"
        az login --service-principal --username ${CLIENT_ID} \
          --password ${CLIENT_SECRET} --tenant ${TENANT_ID} &> /dev/null
        az account set --subscription "${SUBSCRIPTION}" &> /dev/null
        echo "##[debug] List Revisions and getting logs"

        AZURE_FOLDER="azure/${ENVIRONMENT}"

        if [ "$MULTI_CONTAINERAPP" == "true" ]; then
            CONTAINERAPP_LIST=($(ls "$AZURE_FOLDER" | sed -e 's/\.[^.]*$//'))
            echo "##[debug] Containerapp list: ${CONTAINERAPP_LIST[@]}"
        else
          CONTAINERAPP_LIST="${CONTAINER_APP_NAME}"
        fi
        for CONTAINERAPP in "${CONTAINERAPP_LIST[@]}"; do
          if [ "$MULTI_CONTAINERAPP" == "true" ]; then
            CONTAINERAPP_PATH="${AZURE_FOLDER}/${CONTAINERAPP}.yaml"
          else
            CONTAINERAPP_PATH="${AZURE_FOLDER}.yaml"
          fi
          echo "##[debug] Getting logs for ${CONTAINERAPP_PATH}"
          get_logs "${CONTAINERAPP_PATH}"
        done
        echo "##[debug] End of post deployment"
