trigger:
  - develop
  - release/* 
  - master

resources:
  repositories:
    - repository: CorePipelines
      name: DevOps/Vivo.Core.Pipelines
      type: git
      ref: refs/tags/v1

extends:
  template: /provisioners/entrypoint.yml@CorePipelines
  parameters:
    config:
      pipelineType: saas
      technology: aem
      modelName: default
      branchingStrategy: aemflow
      params:
        adobeRemoteUrl: $(adobe_remote_url)
