steps:
- script: |
    terraform --version -json

    echo "##[command] terraform output -json > ${OUTPUT_FILE}"
    terraform output -json > ${OUTPUT_FILE}

    jq 'if . == {} then error("") else . end | {"outputs": "exported"}' ${OUTPUT_FILE}
    retVal=$?

    if [ $retVal -ne 0 ]; then
      echo "##[debug] File '${OUTPUT_FILE}' is empty, removing it from artifact staging directory."
      rm ${OUTPUT_FILE}
    fi
  displayName: 'Terraform OUTPUT .json'
  workingDirectory: $(Build.SourcesDirectory)
  env:
    OUTPUT_FILE: $(Build.ArtifactStagingDirectory)/outputs.json