parameters:
  - name: ociVersion
  - name: ociCliFolderPath
  - name: ociCliKeyFile
  - name: ociCliConfigFile
  - name: condition
    default: succeeded()

steps:
  - task: CmdLine@2
    displayName: "Configure OCI CLI"
    condition: ${{ parameters.condition }}
    inputs:
      script: |
        echo "##[debug] OCI VERSION .......................................................: ${{ parameters.ociVersion }}"
        echo "##[debug] OCI CLI FOLDER PATH ...............................................: ${{ parameters.ociCliFolderPath }}"
        echo "##[debug] OCI CLI KEY FILE ..................................................: ${{ parameters.ociCliKeyFile }}"
        echo "##[debug] OCI CLI CONFIG FILE ...............................................: ${{ parameters.ociCliConfigFile }}"
        echo "##[debug] CONDITION .........................................................: ${{ parameters.condition }}"
        echo ""

        echo "🔧 Configuration OCI CLI ..."

        echo "    📁 Create .oci folder ..."
        echo "##[command]        mkdir -p ${{ parameters.ociCliFolderPath }}"
        mkdir -p ${{ parameters.ociCliFolderPath }}

        echo "    📦➡️ Move api key ..."
        echo "##[command]          mv "$(oci_api_key_secure_file.secureFilePath)" ${{ parameters.ociCliKeyFile }}"
        mv "$(oci_api_key_secure_file.secureFilePath)" "${{ parameters.ociCliKeyFile }}"

        echo "    📝 Adjusting key file path in config file ..."
        echo "##[command]          "sed -i "s|^key_file=.*|key_file="${{ parameters.ociCliKeyFile }}"|" "$(oci_config_secure_file.secureFilePath)"""
        sed -i "s|^key_file=.*|key_file=${{ parameters.ociCliKeyFile }}|" "$(oci_config_secure_file.secureFilePath)"

        echo "    📦➡️ Move config file ..."
        echo "##[command]          mv "$(oci_config_secure_file.secureFilePath)" ${{ parameters.ociCliConfigFile }}"
        mv "$(oci_config_secure_file.secureFilePath)" "${{ parameters.ociCliConfigFile }}"

        echo "    📦➡️ Adjusting OCI CLI Version in config file ..."
        echo "##[command]          sed -i '/^version=/d' ${{ parameters.ociCliConfigFile }}"
        sed -i '/^version=/d' ${{ parameters.ociCliConfigFile }}
        echo "##[command]          echo "" >> ${{ parameters.ociCliConfigFile }}"
        echo "" >> ${{ parameters.ociCliConfigFile }}
        echo "##[command]          echo "version=${{ parameters.ociVersion }}" >> ${{ parameters.ociCliConfigFile }}"
        echo "version=${{ parameters.ociVersion }}" >> ${{ parameters.ociCliConfigFile }}

        echo "    🔒 Permissions adjust  ..."
        echo "##[command]          oci setup repair-file-permissions --file ${{ parameters.ociCliConfigFile }}"
        oci setup repair-file-permissions --file ${{ parameters.ociCliConfigFile }}
        echo "##[command]          oci setup repair-file-permissions --file ${{ parameters.ociCliKeyFile }}"
        oci setup repair-file-permissions --file ${{ parameters.ociCliKeyFile }}

        echo "    🔍 View Files ..."
        echo "##[command]          ls -l ${{ parameters.ociCliFolderPath }}"
        echo "          Files:"
        ls -l ${{ parameters.ociCliFolderPath }} | awk '{print "          " $9}'
