parameters:
  - name: condition
    default: succeeded()
  - name: environment
  - name: dbSystemDisplayName
  - name: compartmentId

steps:
  - task: CmdLine@2
    name: get_db_system
    displayName: "Get ${{ parameters.environment }} DB System [${{ parameters.dbSystemDisplayName }}]"
    condition: ${{ parameters.condition }}
    inputs:
      script: |
        echo "##[debug] ENVIRONMENT ...............................................: ${{ parameters.environment }}"
        echo "##[debug] DB SYSTEM DISPLAY NAME ....................................: ${{ parameters.dbSystemDisplayName }}"
        echo "##[debug] COMPARTMENT ID ............................................: ${{ parameters.compartmentId }}"
        echo "##[debug] CONDITION .................................................: ${{ parameters.condition }}"
        echo ""

        DB_SYSTEM_DISPLAY_NAME_UPPER=$(echo "${{ parameters.dbSystemDisplayName }}" | tr '[:lower:]' '[:upper:]')
        
        echo "##[group]>>>>> Get "$(echo ${{ parameters.environment }} | tr '[:lower:]' '[:upper:]')" DB System ..."
        echo "##[command]oci db system list --compartment-id ${{ parameters.compartmentId }} | jq -r --arg name \"$DB_SYSTEM_DISPLAY_NAME_UPPER\" '.data[] | select((.\"display-name\" | ascii_upcase) == $name)'"
        DB_SYSTEM=$(oci db system list --compartment-id ${{ parameters.compartmentId }} | jq -r --arg name "$DB_SYSTEM_DISPLAY_NAME_UPPER" '.data[] | select((."display-name" | ascii_upcase) == $name)')

        echo "$DB_SYSTEM | jq ."
        echo "##[endgroup]"

        DB_SYSTEM_ID=$(echo $DB_SYSTEM | jq -r '.id')
        DB_SYSTEM_NAME=$(echo $DB_SYSTEM | jq -r '.["display-name"]')
        DB_SYSTEM_STATE=$(echo $DB_SYSTEM | jq -r '.["lifecycle-state"]')
        DB_SYSTEM_NODE_COUNT=$(echo $DB_SYSTEM | jq -r '.["node-count"]')

        if [ -z "$DB_SYSTEM_ID" ] || [ -z "$DB_SYSTEM_NAME" ] || [ -z "$DB_SYSTEM_STATE" ]; then
          echo "##[error]Failed to extract DB System details for environment ${{ parameters.environment }}"
          exit 1
        fi

        echo ""
        echo ">> DB System Name: $DB_SYSTEM_NAME"
        echo ">> DB System ID: $DB_SYSTEM_ID"
        echo ">> DB System State: $DB_SYSTEM_STATE"
        echo ">> DB System Node Count: $DB_SYSTEM_NODE_COUNT"

        echo "##vso[task.setvariable variable=DB_SYSTEM;isoutput=true]"$DB_SYSTEM""
        echo "##vso[task.setvariable variable=DB_SYSTEM_ID;isoutput=true]$DB_SYSTEM_ID"
        echo "##vso[task.setvariable variable=DB_SYSTEM_NAME;isoutput=true]$DB_SYSTEM_NAME"
        echo "##vso[task.setvariable variable=DB_SYSTEM_STATE;isoutput=true]$DB_SYSTEM_STATE"
        echo "##vso[task.setvariable variable=DB_SYSTEM_NODE_COUNT;isoutput=true]$DB_SYSTEM_NODE_COUNT"