parameters:
  - name: condition
    default: succeeded()
  - name: environment
  - name: compartmentId
  - name: cluster

steps:
  - task: CmdLine@2
    name: get_node_pool
    displayName: "Get ${{ parameters.environment }} Node Pool"
    condition: ${{ parameters.condition }}
    inputs:
      script: |
        CLUSTER_JSON=$(echo '${{ parameters.cluster }}' | jq '.')

        CLUSTER_ID=$(echo $CLUSTER_JSON | jq -r '.id')
        CLUSTER_NAME=$(echo $CLUSTER_JSON | jq -r '.name')
        CLUSTER_STATE=$(echo $CLUSTER_JSON | jq -r '.["lifecycle-state"]')

        echo "##[debug] CONDITION .................................................: ${{ parameters.condition }}"
        echo "##[debug] ENVIRONMENT ...............................................: ${{ parameters.environment }}"
        echo "##[debug] COMPARTMENT ID ............................................: ${{ parameters.compartmentId }}"
        echo "##[debug] CLUSTER ...................................................: ${{ parameters.cluster }}"
        echo "##[debug] CLUSTER ID ................................................: $CLUSTER_ID"
        echo "##[debug] CLUSTER NAME ..............................................: $CLUSTER_NAME"
        echo "##[debug] CLUSTER STATE .............................................: $CLUSTER_STATE"
        echo ""

        echo ">>>>> Get "$(echo ${{ parameters.environment }} | tr '[:lower:]' '[:upper:]')" Node Pool ..."
        echo "##[group]node pool details"
        echo "##[command]oci ce node-pool list --compartment-id ${{ parameters.compartmentId }} --cluster-id $CLUSTER_ID | jq '.data[]'"
        NODE_POOL=$(oci ce node-pool list --compartment-id ${{ parameters.compartmentId }} --cluster-id $CLUSTER_ID | jq '.data[]')

        echo "$NODE_POOL | jq ."
        echo "##[endgroup]"

        NODE_POOL_ID=$(echo $NODE_POOL | jq -r '.id')
        NODE_POOL_NAME=$(echo $NODE_POOL | jq -r '.name')
        NODE_POOL_STATE=$(echo $NODE_POOL | jq -r '.["lifecycle-state"]')

        if [ -z "$NODE_POOL_ID" ] || [ -z "$NODE_POOL_NAME" ] || [ -z "$NODE_POOL_STATE" ]; then
          echo "##[error]Failed to extract node pool details for environment ${{ parameters.environment }}"
          exit 1
        fi

        echo ""
        echo ">> Node Pool Name: $NODE_POOL_NAME"
        echo ">> Node Pool ID: $NODE_POOL_ID"
        echo ">> Node Pool State: $NODE_POOL_STATE"

        echo "##vso[task.setvariable variable=NODE_POOL;isoutput=true]"$NODE_POOL""
        echo "##vso[task.setvariable variable=NODE_POOL_ID;isoutput=true]$NODE_POOL_ID"
        echo "##vso[task.setvariable variable=NODE_POOL_NAME;isoutput=true]$NODE_POOL_NAME"
        echo "##vso[task.setvariable variable=NODE_POOL_STATE;isoutput=true]$NODE_POOL_STATE"
