parameters:
  - name: condition
    default: succeeded()
  - name: environment
  - name: databaseName
  - name: databaseId

steps:
  - task: CmdLine@2
    name: get_pluggable_databases
    displayName: "Get  Pluggable Databases"
    condition: ${{ parameters.condition }}
    inputs:
      script: |
        PLUGGABLE_DATABASES=""

        echo "##[debug] ENVIRONMENT ...............................................: ${{ parameters.environment }}"
        echo "##[debug] DATABASE NAME .............................................: ${{ parameters.databaseName }}"
        echo "##[debug] DATABASE ID ...............................................: ${{ parameters.databaseId }}"
        echo "##[debug] CONDITION .................................................: ${{ parameters.condition }}"
        echo ""

        echo "##[group]>>>>> Get ${{ parameters.databaseName }} Pluggable Databases ..."
        echo "##[command]oci db pluggable-database list --database-id ${{ parameters.databaseId }}"
        PD=$(oci db pluggable-database list --database-id ${{ parameters.databaseId }} \
             --query "data[].{name:\"pdb-name\",id:id}")

        RETURNED_PD=$(echo "$PD" | jq '. | length')
        echo "$PD | jq ."
        echo "##[endgroup]"

        echo ""
        echo "##[debug] PLUGGABLE DATABASE COUNT ..............................................: $RETURNED_PD"

        if [ "$RETURNED_PD" -eq 0 ]; then
          echo "##[warning]No pluggable databases found for ${{ parameters.databaseName }}"
        fi

        PD_INDEX=0
        MAX_ITERATIONS=$((RETURNED_PD - 1))

        for i in $(seq 0 $MAX_ITERATIONS); do
          PD_INDEX=$((PD_INDEX + 1))

          PD_NAME=$(echo $PD | jq -r ".[$i].name")
          PD_ID=$(echo $PD | jq -r ".[$i].id")
          
          echo ""
          echo ">>>>> Pluggable Database $PD_INDEX:"
          echo ">> Name: $PD_NAME"
          echo ">> Id: $PD_ID"
          
          if [ -z "$PLUGGABLE_DATABASES" ]; then
            PLUGGABLE_DATABASES="$PD_NAME,$PD_ID"
          else
            PLUGGABLE_DATABASES="$PLUGGABLE_DATABASES;$PD_NAME,$PD_ID"
          fi
        done

        echo ""
        echo "##[section]Pluggable Databases selected for action: $PLUGGABLE_DATABASES"

        echo "##vso[task.setvariable variable=PLUGGABLE_DATABASES;isOutput=true]$PLUGGABLE_DATABASES"