parameters:
  - name: resource # POD or NODES
  - name: sshEndpoint

steps:
  - task: SSH@0
    name: get_${{ parameters.resource }}_status
    displayName: "Get ${{ parameters.resource }} Status"
    inputs:
      sshEndpoint: ${{ parameters.sshEndpoint }}
      runOptions: "inline"
      inline: |
        RESOURCE_LC=$(echo "${{ parameters.resource }}" | tr '[:lower:]' '[:upper:]')_STATUS

        echo "##[debug] RESOURCE .................................: ${{ parameters.resource }}"
        echo "##[debug] SSH Endpoint .............................: ${{ parameters.sshEndpoint }}"
        echo "##[debug] OUTPUT VARIABLE ..........................: $RESOURCE_LC"
        echo ""

        echo "##[command]kubectl get ${{ parameters.resource }} |& tee ${{ parameters.resource }}_status.txt"
        kubectl get ${{ parameters.resource }} |& tee ${{ parameters.resource }}_status.txt

        STATUS=""
        while IFS= read -r line || [[ -n "$line" ]]; do
          if [ "${#STATUS}" -gt 0 ]; then
            STATUS+=";$line"
          else
            STATUS+="$line"
          fi
        done < ${{ parameters.resource }}_status.txt

        echo "##vso[task.setvariable variable=$RESOURCE_LC;]$STATUS"
      readyTimeout: "20000"
      failOnStdErr: false
