parameters:
- name: sshEndpoint
- name: applicationPod

steps: 
- task: SSH@0
  name: get_environment_versions
  displayName: "Get Environment Versions"
  continueOnError: true
  inputs:
    sshEndpoint: ${{ parameters.sshEndpoint }}
    runOptions: 'inline'
    inline: |
      echo "##[debug] sshEndpoint .......................................................: ${{ parameters.sshEndpoint }}"
      echo "##[debug] applicationPod ....................................................: ${{ parameters.applicationPod }}"
      
      RUNNING_VERSIONS="!"

      echo "##[group]kubectl get pods --all-namespaces -o jsonpath=\"{range .items[*]}{.metadata.name},{.spec.containers[*].image}{'\n'}{end}\""
      while IFS= read -r line3 || [[ -n "$line3" ]]; do
        podName=$(echo "$line3" | cut -d',' -f1)
        allImages=$(echo "$line3" | cut -d',' -f2)
        if [[ "${podName}" =~ "domain-admin-server" || "${podName}" =~ "domain-managed-server" ]]; then
          image=$(echo "$allImages" | cut -d' ' -f2)
        else
          image=$(echo "$allImages" | cut -d' ' -f1)
        fi
        imageVersion=$(echo "$image" | cut -d':' -f2)

        if [[ "${podName}" == *"${{ parameters.applicationPod }}"* ]]; then
          echo "********** ${podName} *******************************************************************************************"
          echo "##[debug] Application Pod Image Name ................................: ${image}"
          echo "##[debug] Application Pod Image Version .............................: ${imageVersion}"

          RUNNING_VERSIONS="${podName};${image};${imageVersion}"
        else
          echo "========== ${podName} ==========================================================================================="
          echo "##[debug] Application Pod Image Name ................................: ${image}"
          echo "##[debug] Application Pod Image Version .............................: ${imageVersion}"
        fi
      done < <(kubectl get pods --all-namespaces -o jsonpath="{range .items[*]}{.metadata.name},{.spec.containers[*].image}{'\n'}{end}")
      echo "##[endgroup]"

      if [[ "$RUNNING_VERSIONS" == "!" ]]; then
        echo "##[error] Pod not found: ${{ parameters.applicationPod }}"
      else
        echo "********** ${{ parameters.applicationPod }} Pod Details ***************************************************************************************"
        echo "##[section]Application Pod ...................................................................: $(echo "$RUNNING_VERSIONS" | cut -d';' -f1)"
        echo "##[section]Application Pod Image .............................................................: $(echo "$RUNNING_VERSIONS" | cut -d';' -f2)"
        echo "##[section]Application Pod Version ...........................................................: $(echo "$RUNNING_VERSIONS" | cut -d';' -f3)"
      fi
      
      echo "##vso[task.setvariable variable=RUNNING_VERSIONS;]$RUNNING_VERSIONS"
    readyTimeout: '20000'
    failOnStdErr: false