parameters:
- name: frontendApiID
- name: continueOnError
  default: true

steps:
- script: |
    echo "##[debug] API_MANAGER_BASE_URL.....: ${API_MANAGER_BASE_URL}"
    echo "##[debug] FRONTEND_API_ID..........: ${FRONTEND_API_ID}"

    if [ -z "${FRONTEND_API_ID}" ]; then
      echo "##[warning] Unable to unpublish & delete empty Frontend API ID."
      exit
    fi

    echo "##[command] Unpublish Frontend API. POST /proxies/${FRONTEND_API_ID}/unpublish"
    curl -s -I -k --fail -X POST "${API_MANAGER_BASE_URL}/proxies/${FRONTEND_API_ID}/unpublish" \
    --user "${ADMIN_USERNAME}:${ADMIN_PASSWORD}"

    echo "##[command] Delete Frontend API. DELETE /proxies/${FRONTEND_API_ID}"
    curl -s -I -k --fail -X DELETE "${API_MANAGER_BASE_URL}/proxies/${FRONTEND_API_ID}" \
    --user "${ADMIN_USERNAME}:${ADMIN_PASSWORD}"
  displayName: Unpublish & Delete Frontend API
  continueOnError: ${{ parameters.continueOnError }}
  env:
    API_MANAGER_BASE_URL: $(API_MANAGER_BASE_URL)
    ADMIN_USERNAME: $(ADMIN_USERNAME)
    ADMIN_PASSWORD: $(ADMIN_PASSWORD)
    FRONTEND_API_ID: ${{ parameters.frontendApiID }}