parameters:
- name: frontendApiName
- name: frontendApiID

steps:
- script: |
    echo "##[debug] API_MANAGER_BASE_URL.....: ${API_MANAGER_BASE_URL}"
    echo "##[debug] FRONTEND_API_NAME........: ${FRONTEND_API_NAME}"
    echo "##[debug] FRONTEND_API_ID..........: ${FRONTEND_API_ID}"

    curl -s -i -k --fail --request POST "${API_MANAGER_BASE_URL}/proxies/${FRONTEND_API_ID}/publish" \
    --user "${ADMIN_USERNAME}:${ADMIN_PASSWORD}" \
    --data-urlencode "name=${FRONTEND_API_NAME}"
  displayName: Publish Frontend API
  continueOnError: false
  env:
    API_MANAGER_BASE_URL: $(API_MANAGER_BASE_URL)
    ADMIN_USERNAME: $(ADMIN_USERNAME)
    ADMIN_PASSWORD: $(ADMIN_PASSWORD)
    FRONTEND_API_NAME: ${{ parameters.frontendApiName }}
    FRONTEND_API_ID: ${{ parameters.frontendApiID }}