parameters:
- name: frontendOldApiID
- name: frontendNewApiID

steps:
- script: |
    CURRENT_DATETIME=$(date +"%Y-%m-%dT%TZ")

    echo "##[debug] API_MANAGER_BASE_URL.....: ${API_MANAGER_BASE_URL}"
    echo "##[debug] FRONTEND_OLD_API_ID......: ${FRONTEND_OLD_API_ID}"
    echo "##[debug] FRONTEND_NEW_API_ID......: ${FRONTEND_NEW_API_ID}"
    echo "##[debug] CURRENT_DATETIME.........: ${CURRENT_DATETIME}"

    if [ -z "${FRONTEND_OLD_API_ID}" ]; then
      echo "##[warning] Old API is empty. Unable to upgrade."
      exit
    fi

    curl -s -i -k --fail --request POST "${API_MANAGER_BASE_URL}/proxies/upgrade/${FRONTEND_OLD_API_ID}" \
    --user "${ADMIN_USERNAME}:${ADMIN_PASSWORD}" \
    --data-urlencode "upgradeApiId=${FRONTEND_NEW_API_ID}" \
    --data-urlencode "deprecate=true" \
    --data-urlencode "retire=true" \
    --data-urlencode "retirementDate=${CURRENT_DATETIME}"
  displayName: Upgrade Frontend API
  continueOnError: false
  env:
    API_MANAGER_BASE_URL: $(API_MANAGER_BASE_URL)
    ADMIN_USERNAME: $(ADMIN_USERNAME)
    ADMIN_PASSWORD: $(ADMIN_PASSWORD)
    FRONTEND_OLD_API_ID: ${{ parameters.frontendOldApiID }} 
    FRONTEND_NEW_API_ID: ${{ parameters.frontendNewApiID }}