parameters:
- name: downloadPath
  default: '$(System.ArtifactsDirectory)'

steps:
- task: DownloadBuildArtifacts@1
  displayName: 'Download Build docker'
  inputs:
    artifactName: docker
    parallelizationLimit: 20
    extractTars: false
    downloadPath: ${{ parameters.downloadPath }}