parameters:
- name: downloadPath
  default: '$(System.ArtifactsDirectory)'
- name: parallelizationLimit
  default: 8
- name: cleanDestinationFolder
  default: false
- name: artifactName
  default: app
- name: filesToCopy
  type: string
  default: ''
- name: workingDirectory
  type: string
  default: '$(Build.SourcesDirectory)'

steps:
- task: DownloadBuildArtifacts@1
  displayName: 'Download Build Artifacts'
  inputs:
    artifactName: ${{ parameters.artifactName }}
    cleanDestinationFolder: ${{ parameters.cleanDestinationFolder }}
    extractTars: true
    parallelizationLimit: ${{ parameters.parallelizationLimit }}
    downloadPath: ${{ parameters.downloadPath }}

- ${{ if ne(parameters.filesToCopy, '') }}:
  - bash: |
      SRC_BASE_DIR="$(DEFAULT_WORKDIR_ARTIFACTS)"

      for FILE_TO_COPY in ${FILES_TO_COPY}; do
        SRC_PATH="${SRC_BASE_DIR}/${FILE_TO_COPY}"
        if [ -e "$SRC_PATH" ]; then
          cp -af "$SRC_PATH" "${BASE_DIRECTORY}"
        fi
      done
    displayName: "Copy files to build sources directory"
    workingDirectory: ${{ parameters.workingDirectory }}
    env:
      FILES_TO_COPY: ${{ parameters.filesToCopy }}
      BASE_DIRECTORY: ${{ parameters.workingDirectory }}
