parameters:
- name: artifactPublishName
  type: string
  default: app
- name: pathtoPublish
  type: string
  default: $(Build.ArtifactStagingDirectory)

steps:
- template: copy_to_staging_rsync.yml
  
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    ArtifactName: ${{ parameters.artifactPublishName }}
    StoreAsTar: true
    PathtoPublish: ${{ parameters.pathtoPublish }}