parameters:
- name: environment
- name: argocd_enabled
  type: boolean
  default: true
- name: dev_namespace_to_deploy
  type: string
  default: ''
- name: private_agent_pool
  type: string
- name: kubeconfig
  type: string
- name: git_tag
  type: boolean
  default: true
- name: helm_release_name_prefix
  type: string
- name: useExternalEnv
  type: boolean
  default: false
- name: azureServiceConnectionEnabled
  type: boolean
  default: false
- name: kubernetesServiceConnectionEnabled
  type: boolean
  default: false

# Chama diretamente o template do NodeJS com todos os parâmetros necessários
stages:
- template: /tech_products/ecmc/core-pipelines/provisioners/app/trunkbased/nodejs/api_default/stages/deploy.yml
  parameters:
    environment: ${{ parameters.environment }}
    argocd_enabled: ${{ parameters.argocd_enabled }}
    dev_namespace_to_deploy: ${{ parameters.dev_namespace_to_deploy }}
    private_agent_pool: ${{ parameters.private_agent_pool }}
    kubeconfig: ${{ parameters.kubeconfig }}
    git_tag: ${{ parameters.git_tag }}
    helm_release_name_prefix: ${{ parameters.helm_release_name_prefix }}
    useExternalEnv: ${{ parameters.useExternalEnv }}
    azureServiceConnectionEnabled: ${{ parameters.azureServiceConnectionEnabled }}
    kubernetesServiceConnectionEnabled: ${{ parameters.kubernetesServiceConnectionEnabled }}
