parameters:
- name: environment
  type: string
- name: fortifyExclusionRepository
  type: string
  default: ''

# Chama diretamente o template do NodeJS
stages:
- template: /tech_products/ecmc/core-pipelines/provisioners/app/trunkbased/nodejs/api_default/stages/security_sast_dev.yml
  parameters:
    fortifyExclusionRepository: ${{ parameters.fortifyExclusionRepository }}
