parameters:
- name: environment
- name: applicationName
- name: apiName
- name: overrideQuota
- name: methodQuota
- name: typeQuota
- name: valueQuota
- name: everyQuota
- name: periodQuota

stages:
- stage: stage_subscription_${{ parameters.environment }}
  pool: $(PRIVATE_AGENT_DEFAULT)
  displayName: '${{ parameters.environment }} - API Subscription'
  variables:
    API_MANAGER_BASE_URL: $(API_MANAGER_BASE_URL_${{ upper(parameters.environment) }})
    ADMIN_USERNAME: $[ coalesce(variables.API_MANAGER_ADMIN_USERNAME_${{ upper(parameters.environment) }}, variables.API_MANAGER_ADMIN_USERNAME) ]
    ADMIN_PASSWORD: $[ coalesce(variables.API_MANAGER_ADMIN_PASSWORD_${{ upper(parameters.environment) }}, variables.API_MANAGER_ADMIN_PASSWORD) ]
    SHARED_ORGANIZATIONS: $[ stageDependencies.stage_catalog.job_catalog.outputs['api_subscription_catalog.SHARED_ORGANIZATIONS'] ]
  dependsOn:
  - stage_catalog
  jobs:
  - deployment: api_subscription
    displayName: API Subscription - ${{ parameters.environment }}
    environment: deploy-${{ parameters.environment }}
    strategy:
      runOnce:
        deploy:
          steps:
          - template: /tasks/axway/applications/get_id.yml
            parameters:
              applicationName: ${{ parameters.applicationName }}
          - template: /tasks/axway/frontend_api/get_id.yml
            parameters:
              apiName: ${{ parameters.apiName }}
          - template: /tasks/axway/organizations/get_shared_organizations_id.yml
            parameters:
              sharedOrganizations: $(SHARED_ORGANIZATIONS)
          - template: /tasks/axway/frontend_api/grantaccess.yml
            parameters:
              frontendApiID: $(FRONTEND_API_ID)
              sharedOrganizationsID: $(SHARED_ORGANIZATIONS_ID)
          - template: /tasks/axway/applications/api_subscribe.yml
            parameters:
              applicationID: $(APPLICATION_ID)
              apiID: $(FRONTEND_API_ID)
          - template: /tasks/axway/frontend_api/get_method_operation.yml
            parameters:
              frontendApiID: $(FRONTEND_API_ID)
              methodName: ${{ parameters.methodQuota }}
          - ${{ if eq(parameters.overrideQuota, true) }}:
            - template: /tasks/axway/applications/override_quota.yml
              parameters:
                applicationID: $(APPLICATION_ID)
                apiID: $(FRONTEND_API_ID)
                apiName: ${{ parameters.apiName }}
                method: $(FRONTEND_OPERATION_ID)
                type: ${{ parameters.typeQuota }}
                value: ${{ parameters.valueQuota }}
                every: ${{ parameters.everyQuota }}
                period: ${{ parameters.periodQuota }}
          - ${{ else }}:
            - template: /tasks/axway/applications/delete_quota_restriction.yml
              parameters:
                applicationID: $(APPLICATION_ID)
                method: $(FRONTEND_OPERATION_ID)