parameters:
- name: repository
- name: localFileLocation
- name: remoteFileLocation
- name: condition
  default: succeeded()
- name: credentialsEnabled
  default: true
- name: continueOnError
  default: false
- name: displayName
  default: "Upload file to Nexus"

steps:
- ${{ if eq(parameters.credentialsEnabled, true) }}:
  - task: AzureKeyVault@2
    displayName: Get Nexus credentials
    inputs:
      azureSubscription: DevOpsSharedResources
      KeyVaultName: $(AKV_DEVOPS_NAME)
      SecretsFilter: 'NEXUS-DEFAULT-USR, NEXUS-DEFAULT-PSW'

- script: |
    echo "##[debug] URL......................: ${URL}"
    echo "##[debug] REPOSITORY...............: ${REPOSITORY}"
    echo "##[debug] LOCAL_FILE_LOCATION......: ${LOCAL_FILE_LOCATION}"
    echo "##[debug] REMOTE_FILE_LOCATION.....: ${REMOTE_FILE_LOCATION}"

    if [ ! -f "${LOCAL_FILE_LOCATION}" ]; then
      echo "##vso[task.logissue type=error;] File '${LOCAL_FILE_LOCATION}' not found."
      echo "##vso[task.complete result=Failed;]"
    fi

    echo "##[command] curl upload file"
    curl -s -i --fail -u ${USERNAME}:${PASSWORD} --upload-file "${LOCAL_FILE_LOCATION}" "${URL}/${REPOSITORY}/${REMOTE_FILE_LOCATION}"
  displayName: ${{ parameters.displayName }}
  condition: ${{ parameters.condition }}
  continueOnError: ${{ parameters.continueOnError }}
  env:
    URL: $(NEXUS_REPOSITORY_URL)
    REPOSITORY: ${{ parameters.repository }}
    LOCAL_FILE_LOCATION: ${{ parameters.localFileLocation }}
    REMOTE_FILE_LOCATION: ${{ parameters.remoteFileLocation }}
    USERNAME: $(NEXUS-DEFAULT-USR)
    PASSWORD: $(NEXUS-DEFAULT-PSW)
