parameters:
  - name: environment
  - name: packageName
  - name: packageVersion
  - name: dry_run
  - name: CHG

stages:
  - stage: DryRun
    displayName: "Dry Run - on ${{ parameters.environment }}"
    pool: GeneralPurposeLinuxAgentsCD
    jobs:
      - job: Permissions
        displayName: Deploy Package on ${{ parameters.environment }}
        condition: eq('${{ parameters.dry_run }}', 'True')        
        steps:
          - checkout: none
          - task: SSH@0
            displayName: LS -l $HOME or /opt
            inputs:
              sshEndpoint: ${{ parameters.packageName }}-${{ parameters.environment }}
              runOptions: inline
              inline: |
                if [[ "${{ parameters.environment }}" == "qa1" || "${{ parameters.environment }}" == "qa2" || "${{ parameters.environment }}" == "qa3" ]]; then
                  PATH=$HOME
                else
                  PATH=/opt  
                fi
                PERM=$(ls -l $PATH | grep ${{ parameters.CHG }} | awk '{print $3}')
                echo "##vso[task.setvariable variable=Permissions;isOutput=true]$PERM"
                PACKAGES=$(find $PATH -name "*.whl")
                echo "##vso[task.setvariable variable=Packages;isOutput=true]$PACKAGES"
              continueOnError: true
          - script: |
              echo "Permissions: $(Permissions.Permissions)"
              echo "Packages: $(Permissions.Packages)"
            displayName: 'Show Permissions and Packages'