parameters:
- name: host
  type: string

stages:
- stage: active
  displayName: "Active WF, RS e Task"
  dependsOn: 
  - adm
  - import_files
  pool: GeneralPurposeLinuxAgentsCD
  jobs:
  - job: wf_activate
    displayName: "Ativações WF"
    condition: eq(stageDependencies.import_files.import_files.outputs['checkWorkflowFiles.wfo_found'], 'true')
    steps:
      - checkout: none 

      - task: SSH@0
        condition: true
        displayName: 'Active WF'
        inputs:
          sshEndpoint: 'BRTLVBGB0055CO'
          runOptions: 'commands'
          commands: |
            ssh -o StrictHostKeyChecking=no -i "$(SIEBEL_PRIVATE_KEY)"  ${{parameters.host}} /opt/web/siebel/siebelfs/scripts/active_wf.sh
            exit
          readyTimeout: '20000'
        env:
          HTTPS_PROXY: $(PROXY_NSKP_HTTPS)
          HTTP_PROXY: $(PROXY_NSKP_HTTP)
          NO_PROXY: $(PROXY_NSKP_NO_PROXY)

  - job: put_files
    displayName: "Ativações Objetos App"
    condition: eq(stageDependencies.import_files.import_files.outputs['checkOnrFiles.onr_found'], 'true')
    steps:
      - checkout: none 

      - task: SSH@0
        condition: true
        continueOnError: true
        displayName: 'Active ruleset'
        inputs:
          sshEndpoint: 'BRTLVBGB0055CO'
          runOptions: 'commands'
          commands: |
            ssh -o StrictHostKeyChecking=no -i "$(SIEBEL_PRIVATE_KEY)"  ${{parameters.host}} /opt/web/siebel/siebelfs/scripts/active_ruleset.sh
            exit
          readyTimeout: '20000'
        env:
          HTTPS_PROXY: $(PROXY_NSKP_HTTPS)
          HTTP_PROXY: $(PROXY_NSKP_HTTP)
          NO_PROXY: $(PROXY_NSKP_NO_PROXY)

      - task: SSH@0
        condition: true
        continueOnError: true
        displayName: 'Active task'
        inputs:
          sshEndpoint: 'BRTLVBGB0055CO'
          runOptions: 'commands'
          commands: |
            ssh -o StrictHostKeyChecking=no -i "$(SIEBEL_PRIVATE_KEY)"  ${{parameters.host}} /opt/web/siebel/siebelfs/scripts/active_task.sh
            exit
          readyTimeout: '20000'
        env:
          HTTPS_PROXY: $(PROXY_NSKP_HTTPS)
          HTTP_PROXY: $(PROXY_NSKP_HTTP)
          NO_PROXY: $(PROXY_NSKP_NO_PROXY)
  - job: SkipActive
    condition: and(ne(stageDependencies.import_files.import_files.outputs['checkOnrFiles.onr_found'], 'true'), ne(stageDependencies.import_files.import_files.outputs['checkWorkflowFiles.wfo_found'], 'true'))
    displayName: "Skip Active WF, RS e Task"
    steps:
    - checkout: none
    - task: CmdLine@2
      displayName: "Skip Active WF, RS e Task"
      inputs:
        script: |
          echo No ONR files found. Skipping compilation.
          echo No ONR files found. Skipping compilation. > C:\Siebel_Devops\log\Compile_$(environmentNameUpperCase)_Skip.log