steps:
- script: |
    IFS=',' read -ra ADDB <<< "$(echo "$(ADDITIONAL_BRANCHES)" | sed 's/^ *//;s/ *$//;s/ *, */,/g')"",master,main"
    IS_ALLOWED_BRANCH="false"
    echo "##[debug] Conviso Enabled Branches: ${ADDB[@]}"
    for i in "${ADDB[@]}"; do
      regex=$(echo "$i" | sed -e 's/\*/.*/g' -e 's/^/^refs\/heads\//' -e 's/$/$/')
      if [[ "${SOURCE_BRANCH}" =~ $regex ]] || [[ "${PR_TARGET_BRANCH}" =~ $regex ]]; then
        IS_ALLOWED_BRANCH="true"
        break
      fi
    done
    echo "##[debug] IS_ALLOWED_BRANCH: $IS_ALLOWED_BRANCH"
    echo "##vso[task.setvariable variable=CONVISO_ENABLED_BRANCH;isOutput=true;]$IS_ALLOWED_BRANCH"
  env:
    SOURCE_BRANCH: $(Build.SourceBranch)
    PR_TARGET_BRANCH: $(System.PullRequest.TargetBranch)
  name: evaluate_flags
  displayName: 'Evaluate Conviso flags'