parameters:
  - name: ACRAsDefaultHelmRegistry
    type: boolean
    default: false
  - name: forceDockerK8sSecretCreation
    type: boolean
    default: False

variables:
 - template: /tech_products/ecmc/core-pipelines/global/variables/pipeline.yml
  parameters:
    ACRAsDefaultHelmRegistry: ${{ parameters.ACRAsDefaultHelmRegistry }}
    forceDockerK8sSecretCreation: ${{ parameters.forceDockerK8sSecretCreation }}

- name: PRIVATE_AGENT_POOL
  value: GeneralPurposeLinuxAgentsCI

- name: HELM_VERSION
  value: latest

- name: CORPORATE_WIKI_DOC_URL
  value: "https://wikicorp.telefonica.com.br/display/AC/Modelo+Helm"

- name: DEFAULT_WORKDIR_ARTIFACTS
  value: $(Build.SourcesDirectory)

- name: DEFAULT_WORKDIR_DOCKER_ARTIFACTS
  value: "$(System.ArtifactsDirectory)/docker"