parameters:
  - name: EXTENSION_NAME
  - name: EXTENSION_ID
  - name: SKIP_TESTS
  - name: TAG

stages:  
  - stage: publishProd
    displayName: 'Publish prod'
    jobs:
    - deployment:
      environment: 'deploy-preprod'
      strategy:
        runOnce:
          deploy:
            steps:
            - checkout: self
              clean: true

            - bash: |
                VERSION=''
                if [ -f "package/vss-extension.json" ]; then
                    VERSION=$(cat package/vss-extension.json | grep "\"version\":" | cut -d '"' -f4)
                elif [ -f "vss-extension.json" ]; then
                    VERSION=$(cat vss-extension.json | grep "\"version\":" | cut -d '"' -f4)
                else
                    echo "Arquivo vss-extension.json não foi encontrado. Não foi possível determinar a versão."
                    exit 1
                fi
                echo "##vso[task.setvariable variable=VERSION;isOutput=true]$VERSION"
              name: packageInfo

            - task: PackageAzureDevOpsExtension@5
              name: 'packageProd'
              displayName: 'Package the prod extension'
              inputs:
                rootFolder: '$(packageInfo.EXTENSION_ROOT_FOLDER)'
                outputPath: '$(Build.ArtifactStagingDirectory)/telefonica-vivo-devops-brasil.$(EXTENSION_ID).vsix'
                publisherId: 'telefonica-vivo-devops-brasil'
                extensionName: '$(EXTENSION_NAME) Tasks'
                extensionId: '$(EXTENSION_ID)'
                extensionVersion: '$(packageInfo.VERSION)'
                updateTasksVersion: true
                updateTasksVersionType: 'patch'              
                extensionVisibility: 'private'

            - publish: $(Build.ArtifactStagingDirectory)
              artifact: vsix
              displayName: 'Publish vsix as pipeline artifact'
              condition: succeededOrFailed()