parameters:
  - name: EXTENSION_NAME
  - name: EXTENSION_ID
  - name: SKIP_TESTS
  - name: TAG

stages:  
  - stage: publishProd
    displayName: Publish prod
    jobs:
    - deployment:
      environment: 'teste-share'
      strategy:
        runOnce:
          deploy:
            steps:
            - checkout: self
              clean: true

            - task: TfxInstaller@4
              displayName: 'Use Node CLI for Azure DevOps'
              inputs:
                version: '0.9.x'
                checkLatest: true

            - task: IsAzureDevOpsExtensionValid@5
              displayName: 'Validate the private extension on the marketplace'
              inputs:
                connectTo: "VsTeam"
                connectedServiceName: "Visual Studio Marketplace (DevOps)" 
                publisherId: 'telefonica-vivo-devops-brasil'
                extensionId: '${{ parameters.EXTENSION_ID }}'

            - task: ms-devlabs.vsts-developer-tools-build-tasks.share-extension-build-task.ShareAzureDevOpsExtension@5
              displayName: 'Share Extension'
              inputs:
                connectTo: VsTeam
                connectedServiceName: 'share-extensions-marketplace'
                publisherId: 'telefonica-vivo-devops-brasil'
                extensionId: '${{ parameters.EXTENSION_ID }}'
                accounts: 'telefonica-vivo-brasil'