parameters:
- name: dependsOn
  type: object
  default: [security]
- name: scaFailedCondition
  type: string
  default: "failed('security')"

stages:
- stage: sca_violation
  displayName: "Sca Violations"
  dependsOn: "${{ parameters.dependsOn }}"
  condition: "${{ parameters.scaFailedCondition }}"
  isSkippable: true
  pool: $(PRIVATE_AGENT_DEFAULT)

  jobs:
  - job: check_vulnerabilities_sap_comm
    displayName: "Vulnerabilitites check Sap Comm"
    steps:
    - checkout: CorePipelinesScripts
      persistCredentials: true
      fetchDepth: 1
    - bash: |
        echo "##[debug] Checking Sap Commerce"
        cd $(Build.SourcesDirectory)
        ls -la
        python src/_sap_commerce/sca_script.py
        if [[ $? != 0 ]]; then
          exit 1
        fi
        cd src/_sap_commerce

        if [ -f sap_found_libraries.txt ] && [ -s sap_found_libraries.txt ]; then
          echo "##[section]Arquivo sap_found_libraries.txt encontrado com conteúdo"

          FILE_CONTENT=$(echo $(cat sap_found_libraries.txt))

          MESSAGE_CONTENT="{\"content\": \"$FILE_CONTENT\", \"chatId\": \"$SCA_VIOLATION_CHAT_ID\", \"source\": \"Sap Cloud\"}"

          curl -X POST --location "${CHATOPS_NOTIFICATION_URL}" \
              --header 'Content-Type: application/json' \
              --data-raw "${MESSAGE_CONTENT}"
        fi

        if [ -f sap_support_tickets.txt ] && [ -s sap_support_tickets.txt ]; then
          echo "##[section]Arquivo sap_support_tickets.txt encontrado com conteúdo"

          FILE_CONTENT=$(echo $(cat sap_support_tickets.txt))

          MESSAGE_CONTENT="{\"content\": \"$FILE_CONTENT\", \"chatId\": \"$SCA_VIOLATION_CHAT_ID\", \"source\": \"Sap Cloud\"}"

          curl -X POST --location "${CHATOPS_NOTIFICATION_URL}" \
              --header 'Content-Type: application/json' \
              --data-raw "${MESSAGE_CONTENT}"
        fi

      env:
        PR_LINK : $(System.TeamFoundationCollectionUri)$(System.TeamProject)/_git/$(Build.Repository.Name)/pullrequest/$(System.PullRequest.PullRequestId)
        PIPE_LINK: $(System.TeamFoundationCollectionUri)$(System.TeamProject)/_build/results?buildId=$(Build.BuildId)&_a=summary
        ENVIRONMENT_NAME: $(ENVIRONMENT_NAME)
        TARGET_BRANCH: $(System.PullRequest.TargetBranchName)
        URL_CONVISO: $(URL_CONVISO)
        URL_GET_CXCOMM_VERSION: $(URL_GET_CXCOMM_VERSION)
        URL_PORTAL_SAP: $(URL_PORTAL_SAP)
        API_KEY_CONVISO: $(API_KEY_CONVISO)
        COMPANY_ID: $(COMPANY_ID)
        SCA_VIOLATION_CHAT_ID: $(SCA_VIOLATION_CHAT_ID)
        CHATOPS_NOTIFICATION_URL: $(CHATOPS_NOTIFICATION_URL)
      displayName: "Validate vulnerabilities Sap Comm"
