steps:
- bash: |
    RED='\033[0;31m'
    GREEN='\033[0;32m'
    BLUE='\033[0;34m'
    YELLOW='\033[1;33m'
    BG_GREEN='\033[42;1;37m'

    printf "
    ${YELLOW}=================================================================================================================================
    ${YELLOW}                                                            DEPLOY APPLICATION
    ${YELLOW}=================================================================================================================================
    Estamos quase lá <<--->> Nessa etapa do pipeline vamos implantar a sua aplicação no ambiente de runtime de acordo com as configurações da sua 
    aplicação. Caso ocorra um erro durante a implatação da sua aplicação, não se preocupe, essa fase do pipeline tem auto-remediação, quer dizer que
    se sua aplicação falhar a última versão estava da aplicação será restaurada.

    Abaixo uma breve descrição dos steps dessa fase do pipeline:
    $(ALERT_MESSAGE_ARROW) DOWNLOAD BUILD ARTIFACTS - Realiza o download dos arquivos gerados durante o processo de build,gates e package. ${RED} [FAILED]
    $(ALERT_MESSAGE_ARROW) DOWNLOAD KUBECONFIG - Realiza o download o arquivo kubeconfig previamente cadastrado no seu library. ${RED} [FAILED]
    $(ALERT_MESSAGE_ARROW) SET OUTPUT VARIABLE - Set output variables. ${RED} [FAILED]
    $(ALERT_MESSAGE_ARROW) LOGIN HELM REGISTRY - Setup login registry no cluster que recebera a aplicação. ${RED} [FAILED]
    $(ALERT_MESSAGE_ARROW) HELM REPO - Setup do repo do helm utilizado para buscar os charts corporativos ${RED} [FAILED]
    $(ALERT_MESSAGE_ARROW) REPLACE - Realiza o replace do valores dos arquivos secrets.yml presentes na pasta config da sua aplicação. ${RED} [FAILED]
    $(ALERT_MESSAGE_ARROW) HELM UPGRADE - Realiza o upgrade da sua aplicação cluster de destino. ${RED} [FAILED]
    $(ALERT_MESSAGE_ARROW) TELEMETRY - Realiza o envio de informações para datalake interno. ${GREEN} [CONTINUE ON ERROR]

    ${RED} [FAILED] $(ALERT_MESSAGE_ARROW) Os steps com essa legenda caso acorra um erro na execução o pipeline é interrompido.
    ${GREEN} [CONTINUE ON ERROR] $(ALERT_MESSAGE_ARROW) Os steps com essa legenda caso acorra um erro na execução o pipeline não é interrompido.

    Vamos guia-lo durante todas as fases do pipeline.
    Caso tenha dúvidas sobre essa fase do pipeline acesse a nossa documentação: $(CORPORATE_WIKI_DOC_URL)
    ${YELLOW}=================================================================================================================================
    "
  displayName: About Stage

- template: /task_groups/deploy/run_deploy.yml
  parameters:
    environment: ${{parameters.environment}}
    kubeconfig: ${{parameters.kubeconfig}}
    helmReleaseNamePrefix: ${{parameters.helm_release_name_prefix}}