parameters:
- name: workingDirectory
  default: $(Build.SourcesDirectory)
- name: organizationName
- name: applicationName
- name: email
- name: phone
- name: description
- name: failApplicationNotFound
  default: false

steps:
- task: PythonScript@0
  displayName: 'Add Application in Catalog'
  inputs:
    scriptSource: inline
    script: |
      import json
      import os
      
      catalog_file_name = os.getenv('CATALOG_FILE_NAME')
      organization_name = os.getenv('ORGANIZATION_NAME')
      application_name = os.getenv('APPLICATION_NAME')
      email = os.getenv('EMAIL')
      phone = os.getenv('PHONE')
      description = os.getenv('DESCRIPTION')
      failApplicationNotFound = os.getenv('FAIL_APPLICATION_NOT_FOUND')

      print('##[debug] CATALOG_FILE_NAME...................: ', catalog_file_name)
      print('##[debug] ORGANIZATION_NAME...................: ', organization_name)
      print('##[debug] APPLICATION_NAME....................: ', application_name)
      print('##[debug] EMAIL...............................: ', email)
      print('##[debug] PHONE...............................: ', phone)
      print('##[debug] DESCRIPTION.........................: ', description)
      print('##[debug] FAIL_APPLICATION_NOT_FOUND..........: ', failApplicationNotFound)
      
      with open(catalog_file_name, 'r', encoding='utf8') as catalog_file:
        catalog = json.loads(catalog_file.read())
      
      organization_list = catalog['topology']['workflow']['organizations']

      for organization in organization_list:
        for application in organization['applications']:
          if application['name'] == application_name:
            print("##vso[task.logissue type=warning;] Application '{}' already exists in Catalog".format(application_name))
            print("##vso[task.complete result=Succeeded;]")
            exit()
      
      if failApplicationNotFound == 'True':
        print("##vso[task.logissue type=error;] Application '{}' not found in Catalog".format(application_name))
        print("##vso[task.complete result=Failed;]")
        exit()

      for organization in organization_list:
        if organization['name'] == organization_name:
            print('##[debug] Organization found. Append application list...')
            organization['applications'].append({
                "name": application_name,
                "email": email,
                "phone": phone,
                "description": description,
                "apis": []
            })
            json_app_list = json.dumps(organization['applications'], indent=2, ensure_ascii=False)
            print(json_app_list)

      with open(catalog_file_name, 'w', encoding='utf8') as catalog_file:
        catalog_file.write(json.dumps(catalog, indent=2, ensure_ascii=False))
        
      print("##vso[task.setvariable variable=updateCatalog]Yes")
    workingDirectory: ${{ parameters.workingDirectory }}
  env:
    CATALOG_FILE_NAME: $(CATALOG_FILE_NAME)
    ORGANIZATION_NAME: ${{ parameters.organizationName }}
    APPLICATION_NAME: ${{ parameters.applicationName }}
    EMAIL: ${{ parameters.email }}
    PHONE: ${{ parameters.phone }}
    DESCRIPTION: ${{ parameters.description }}
    FAIL_APPLICATION_NOT_FOUND: ${{ parameters.failApplicationNotFound }}

- template: /tasks/axway/catalog/push_changes.yml
  parameters:
    commitMessage: "feat: Add application '${{ parameters.applicationName }}' for organization '${{ parameters.organizationName }}' [skip ci]"