stages:
- stage: gate
  displayName: "Quality Gates"
  dependsOn: 
  - build_test
  pool: $(PRIVATE_AGENT_DEFAULT)
  jobs:
  - job: gates_development_flow
    displayName: "Check development flow"
    condition: and(
                eq(variables.DEVELOPMENT_ENVIRONMENT_FLOW, true),
                notIn(
                  variables['Build.SourceBranch'], 'refs/heads/main', 'refs/heads/master'
                )
            )
    steps:
    - bash: echo "##[warning] Pulando validações de quality gates devido ser um fluxo de desenvolvimento"
      displayName: "About stage"
  
  - job: sonarqube
    condition: and(
                  succeeded(),
                  eq(variables.flowIsTagging, false),
                  ne(variables.skip_sonarqube, true),
                  ne(variables.DEVELOPMENT_ENVIRONMENT_FLOW, true)
              ) 

    displayName: Code Analysis
    variables:
      - name: APP_VERSION
        value: $[ stageDependencies.build_test.bump_version.outputs['component_bump_version.NEW_VERSION'] ]
    steps:
      - ${{ if or(in(variables['Build.SourceBranch'], 'refs/heads/main', 'refs/heads/master'), and(ne(variables.DEVELOPMENT_ENVIRONMENT_FLOW, true), startsWith(variables['Build.SourceBranch'], 'refs/pull/'))) }}:
        - template: /tasks/catalog_info/extract_variables.yml
          parameters:
            skipDownload: true
            workingDirectory: $(Build.SourcesDirectory)
        - template: /task_groups/gates/run_sonarqube_scan.yml
          parameters:
            stack: "NODE"
            projectKey: "$(SONAR_PROJECT_KEY)"
        - template: /tasks/telemetry/telemetry.yml

  - job: governance
    condition: and(
                succeeded(),
                and( 
                  eq(variables.flowIsPullRequest, false),
                  not(startsWith(variables['Build.SourceBranch'], 'refs/tags/'))
                ),
                eq(lower(variables.GOVAPP_INTEGRATION_ENABLED), 'true')
              )
    displayName: Governance Policies Check
    steps:
      - template: /task_groups/governance/check_govapp_policies.yml
        parameters:
          govAppBreakglass: false
          govAppOperation: "validate"
          continueOnError: false
          environment: ${{ parameters.environment }}
          stack: "NODEJS"