parameters:
- name: run_component_test
  type: boolean
- name: dev_namespace_to_deploy
  type: string
  default: ''
- name: environment
- name: enabledCanaryReleaseWithArgoCD
  type: boolean
  default: False
  
stages:
- stage: package
  dependsOn:
  - security
  - gate
  - build_test
  - ${{ if eq(parameters.run_component_test, True)}}:
    - component_test
  displayName: "Package & Publish"
  pool: $(PRIVATE_AGENT_DEFAULT)
  jobs:
  - job: "Package"
    condition: or(
                and(
                  always(),
                  eq(variables.flowIsTagging, false),
                  eq(variables.flowIsMain, true)
                ),
                or(
                  eq(variables['Build.SourceBranch'], 'refs/heads/main'),
                  eq(variables['Build.SourceBranch'], 'refs/heads/master'),
                  eq(variables['Build.Reason'], 'PullRequest'), 
                  and(
                    startsWith(variables['Build.SourceBranch'], 'refs/heads/'), 
                    ${{ ne(parameters.dev_namespace_to_deploy, '') }}
                  )
                )
            )
    displayName: "Package"
    variables:
      - name: APP_VERSION
        value: $[ stageDependencies.build_test.bump_version.outputs['component_bump_version.NEW_VERSION'] ]
      - name: USE_DT_DOCKER
        value: $[ stageDependencies.security.app_config_keys.outputs['evaluate_flags.USE_DT_DOCKER'] ]
      - name: USE_CONVISO
        value: $[ stageDependencies.security.app_config_keys.outputs['evaluate_flags.USE_CONVISO'] ]
      - name: SKIP_SECURITY_GATE_SCA
        value: $[ stageDependencies.security.app_config_keys.outputs['evaluate_flags.SKIP_SECURITY_GATE_SCA'] ]
    steps:
    - template: /tasks/catalog_info/extract_variables.yml
      parameters:
        workingDirectory: $(Build.SourcesDirectory)
    - template: /task_groups/package/docker_package.yml
      parameters:
        environment: ${{ parameters.environment }}
    - ${{ if ne(variables['Build.Reason'], 'PullRequest') }}:
      
      - template: /tasks/nodejs/update_repo_version.yml
        parameters:
          newVersion: "$(APP_VERSION)"
          condition: eq(variables.BUMP_VERSION_ENABLED, true)
          ${{ if eq(parameters.enabledCanaryReleaseWithArgoCD, true) }}:
            enabledCanaryReleaseWithArgoCD: true