parameters:
- name: recipe
  type: string
  values:
  - nodejs_docker
  - sbt_data
  - maven_docker
  - maven_docker_v2
  - docker
  - maven_libs
  - maven_libs_v2
  - example
  - python_docker
  - python_docker_uv
  - php_docker
  - golang-binary
  - mlops_v1
  - mlops_v2
  - gradle_docker
  - nodejs_libs
  - aura_library
  - aura_cognitive_nlpdata
- name: branching_strategy
  type: string
  values:
  - gitlabflow
  - releaseflow
  - stb
  - gitlabflow-semantic
  default: stb
- name: envs
  type: object
  default: {}
- name: additionalStages
  type: object
  default: []
- name: agent_pool
  type: object
  default: null
- name: useMysql
  type: boolean
  default: false
- name: enableFortifyExclusions
  type: boolean
  default: false

stages:
#### PREPARATION #############################
  - stage: preparation
    displayName: Preparation - ${{ parameters.recipe }} recipe
    jobs:
    - template: /tech_products/azr4/recipes/build/${{ parameters.recipe }}/prep.yaml
    variables:
      - group: '4p-core-default-variables'
      - template: /tech_products/azr4/recipes/build/${{ parameters.recipe }}/variables.yaml
        parameters:
          envs: ${{ parameters.envs }}
      - name: RECIPE
        value: ${{ parameters.recipe }}
      - name: BRANCHING_STRATEGY
        value: ${{ parameters.branching_strategy }}
      - ${{ if and(eq( parameters.branching_strategy, 'gitlabflow'), ne(variables['Build.SourceBranchName'], '')) }}:
        - template: /tech_products/azr4/recipes/build/${{ parameters.recipe }}/variables/${{ variables['Build.SourceBranchName'] }}.yaml
          parameters:
            envs: ${{ parameters.envs }}

### BUILD #############################
  - stage: build
    displayName: Build - ${{ parameters.recipe }} recipe
    condition: succeeded()
    dependsOn:
    - preparation
    jobs:
    - template: /tech_products/azr4/recipes/build/${{ parameters.recipe }}/build.yaml
      parameters:
        envs: ${{ parameters.envs }}
    variables:
      - group: '4p-core-default-variables'
      - template: /tech_products/azr4/recipes/build/${{ parameters.recipe }}/variables.yaml
        parameters:
          envs: ${{ parameters.envs }}
      - name: RECIPE
        value: ${{ parameters.recipe }}
      - name: BRANCHING_STRATEGY
        value: ${{ parameters.branching_strategy }}
      - ${{ if and(eq( parameters.branching_strategy, 'gitlabflow'), ne(variables['Build.SourceBranchName'], '')) }}:
        - template: /tech_products/azr4/recipes/build/${{ parameters.recipe }}/variables/${{ variables['Build.SourceBranchName'] }}.yaml  
          parameters:
            envs: ${{ parameters.envs }}

### Security #############################
  - stage: security
    displayName: Security Analysis
    condition: succeeded()
    dependsOn:
    - build # MUDANÇA AQUI: Garante que a segurança espera o Build terminar!
    jobs:
    - template: /tech_products/azr4/recipes/build/commons/fortify.yaml
      parameters:
        enableFortifyExclusions: ${{ parameters.enableFortifyExclusions }}
    - template: /tech_products/azr4/recipes/build/commons/sca.yaml
    variables:
      - group: '4p-core-default-variables'
      - template: /tech_products/azr4/recipes/build/${{ parameters.recipe }}/variables.yaml
        parameters:
          envs: ${{ parameters.envs }}
      - name: RECIPE
        value: ${{ parameters.recipe }}
      - name: BRANCHING_STRATEGY
        value: ${{ parameters.branching_strategy }}
      - ${{ if and(eq( parameters.branching_strategy, 'gitlabflow'), ne(variables['Build.SourceBranchName'], '')) }}:
        - template: /tech_products/azr4/recipes/build/${{ parameters.recipe }}/variables/${{ variables['Build.SourceBranchName'] }}.yaml  
          parameters:
            envs: ${{ parameters.envs }}

### TESTS #############################
  - stage: tests
    displayName: Tests & Code Analysis - ${{ parameters.recipe }} recipe
    condition: succeeded()
    dependsOn:
    - build
    jobs:
    - template: /tech_products/azr4/recipes/build/${{ parameters.recipe }}/tests.yaml
      parameters:
        envs: ${{ parameters.envs }}
        ${{ if parameters.agent_pool }}:
          agent_pool: ${{ parameters.agent_pool }}
        ${{ if parameters.useMysql }}:
          useMysql: ${{ parameters.useMysql }}
    variables:
      - group: '4p-core-default-variables'
      - template: /tech_products/azr4/recipes/build/${{ parameters.recipe }}/variables.yaml
        parameters:
          envs: ${{ parameters.envs }}
      - name: RECIPE
        value: ${{ parameters.recipe }}
      - name: BRANCHING_STRATEGY
        value: ${{ parameters.branching_strategy }}
      - ${{ if and(eq( parameters.branching_strategy, 'gitlabflow'), ne(variables['Build.SourceBranchName'], '')) }}:
        - template: /tech_products/azr4/recipes/build/${{ parameters.recipe }}/variables/${{ variables['Build.SourceBranchName'] }}.yaml  
          parameters:
            envs: ${{ parameters.envs }}

### SONAR #############################
  - stage: sonar
    displayName: Sonar Analysis
    condition: succeeded()
    dependsOn:
    - tests
    jobs:
    - template: /tech_products/azr4/recipes/build/commons/sonar.yaml
      parameters:
        recipe: ${{ parameters.recipe }}
    variables:
      - group: '4p-core-default-variables'
      - template: /tech_products/azr4/recipes/build/${{ parameters.recipe }}/variables.yaml
        parameters:
          envs: ${{ parameters.envs }}
      - name: RECIPE
        value: ${{ parameters.recipe }}
      - name: BRANCHING_STRATEGY
        value: ${{ parameters.branching_strategy }}
      - ${{ if and(eq( parameters.branching_strategy, 'gitlabflow'), ne(variables['Build.SourceBranchName'], '')) }}:
        - template: /tech_products/azr4/recipes/build/${{ parameters.recipe }}/variables/${{ variables['Build.SourceBranchName'] }}.yaml  
          parameters:
            envs: ${{ parameters.envs }}

### Gates #############################
  - stage: gates
    displayName: Security and Quality Gates
    condition: succeeded()
    dependsOn:
    - security
    - sonar
    jobs:
    - template: /tech_products/azr4/recipes/build/commons/gates.yaml
    variables:
      - group: '4p-core-default-variables'
      - template: /tech_products/azr4/recipes/build/${{ parameters.recipe }}/variables.yaml
        parameters:
          envs: ${{ parameters.envs }}
      - name: RECIPE
        value: ${{ parameters.recipe }}
      - name: BRANCHING_STRATEGY
        value: ${{ parameters.branching_strategy }}
      - ${{ if and(eq( parameters.branching_strategy, 'gitlabflow'), ne(variables['Build.SourceBranchName'], '')) }}:
        - template: /tech_products/azr4/recipes/build/${{ parameters.recipe }}/variables/${{ variables['Build.SourceBranchName'] }}.yaml  
          parameters:
            envs: ${{ parameters.envs }}

### PACKAGE AND PUBLISH #############################
  - stage: publish
    displayName: Package and Publish - ${{ parameters.recipe }} recipe
    condition: succeeded()
    dependsOn:
    - gates
    jobs:
    - template: /tech_products/azr4/recipes/build/${{ parameters.recipe }}/publish.yaml
      parameters:
        branching_strategy: ${{ parameters.branching_strategy }}
        envs: ${{ parameters.envs }}
    variables:
      - group: '4p-core-default-variables'
      - template: /tech_products/azr4/recipes/build/${{ parameters.recipe }}/variables.yaml
        parameters:
          envs: ${{ parameters.envs }}
      - name: RECIPE
        value: ${{ parameters.recipe }}
      - name: BRANCHING_STRATEGY
        value: ${{ parameters.branching_strategy }}
      - ${{ if and(eq( parameters.branching_strategy, 'gitlabflow'), ne(variables['Build.SourceBranchName'], '')) }}:
        - template: /tech_products/azr4/recipes/build/${{ parameters.recipe }}/variables/${{ variables['Build.SourceBranchName'] }}.yaml  
          parameters:
            envs: ${{ parameters.envs }}
      # MUDANÇA AQUI: O Alias que resolve o erro de Service Connection no CodePlay
      - name: DOCKER_SERVICE_CONNECTION
        value: $(IMAGE_REGISTRY_CONNECTION)

### COMMIT VERSION #############################
  - stage: commit_version
    displayName: Commit Version
    condition: and(succeeded(), ne('${{ parameters.recipe }}', 'aura_cognitive_nlpdata'))
    dependsOn:
    - publish
    jobs:
    - template: /tech_products/azr4/recipes/build/commons/commit_version.yaml
      ${{ if contains( parameters.recipe, 'maven') }}:
        parameters:
          downloadSettings: true
    variables:
      - group: '4p-core-default-variables'
      - template: /tech_products/azr4/recipes/build/${{ parameters.recipe }}/variables.yaml
        parameters:
          envs: ${{ parameters.envs }}
      - name: RECIPE
        value: ${{ parameters.recipe }}
      - name: BRANCHING_STRATEGY
        value: ${{ parameters.branching_strategy }}
      - ${{ if and(eq( parameters.branching_strategy, 'gitlabflow'), ne(variables['Build.SourceBranchName'], '')) }}:
        - template: /tech_products/azr4/recipes/build/${{ parameters.recipe }}/variables/${{ variables['Build.SourceBranchName'] }}.yaml
          parameters:
            envs: ${{ parameters.envs }}

### ADDITIONAL STAGES #############################
  - ${{ each stage in parameters.additionalStages }}:
      - ${{ stage }}