parameters:
- name: environment
  type: string
- name: variableGroupName
  type: string
- name: runTests
  type: boolean
  default: true
- name: runTrain
  type: boolean
- name: runEvaluate
  type: boolean
- name: runPredict
  type: boolean
- name: repoName
  type: string
- name: repoUrl
  type: string
- name: repoPathDatabricks
  type: string
- name: pythonVersion
  type: string

stages:
- stage: ValidateConfig
  displayName: "CI - Validate Config Files"
  jobs:
    - template: templates/ci/ci_validate_config.yml

- stage: Tests
  displayName: "CI - Run Tests"
  dependsOn: ValidateConfig
  condition: ${{ parameters.runTests }}
  jobs:
    - template: templates/ci/ci_tests.yml
      parameters:
        pythonVersion: ${{ parameters.pythonVersion }}

- stage: Deploy
  displayName: "CD - Deploy Databricks"
  dependsOn:
    - ValidateConfig
    - Tests
  condition: |
    and(
      succeeded('ValidateConfig'),
      not(failed('Tests'))
    )
  jobs:
    - template: templates/cd/cd_databricks_deploy.yml
      parameters:
        environmentName: ${{ parameters.environment }}
        variableGroupName: ${{ parameters.variableGroupName }}
        runTrain: ${{ parameters.runTrain }}
        runEvaluate: ${{ parameters.runEvaluate }}
        runPredict: ${{ parameters.runPredict }}
        repoName: ${{ parameters.repoName }}
        repoUrl: ${{ parameters.repoUrl }}
        repoPathDatabricks: ${{ parameters.repoPathDatabricks }}

