parameters:
- name: environmentCode
  type: string
  default: ''
- name: dependsOn
  type: string
  default: "deploy"
stages:
  - stage: run_stress_test
    dependsOn:
    - ${{ parameters.dependsOn }}
    displayName: "Run stress test"
    pool:
      name: $(PRIVATE_AGENT_DEFAULT)
    condition: and(succeeded(), eq(variables['STRESS_TEST_ENABLED'], 'true'))
    jobs:
    - template: /tech_products/ecmc/sap-commerce/jobs_groups/tests/validate-run-stress-test.yaml
      parameters:
        environmentCode: ${{ parameters.environmentCode }}
    - template: /tech_products/ecmc/sap-commerce/jobs_groups/tests/start-run-stress-test.yaml
      parameters:
          environmentCode: ${{ parameters.environmentCode }}

