parameters:
- name: dev_namespace_to_deploy
  type: string
  default: ''
- name: project_name
  type: string
- name: environment_code
  type: string
- name: database_update_mode
  type: string
- name: deploy_strategy
  type: string
- name: branch_backend
  type: string
  default: ''
- name: branch_frontend
  type: string
  default: ''
- name: pipeline_status
  type: string
  default: ''
- name: work_item_title_prefix
  type: string
  default: ''

stages:
  - stage: work_itens_deploys_${{ parameters.pipeline_status }}
    dependsOn:
      - pipeline_init
      - ${{ if eq(parameters.pipeline_status, 'DEPLOYED') }}:
        - build
        - deploy
    displayName: 'Send Messages - ${{ parameters.pipeline_status }}'
    pool:
      name: $(PRIVATE_AGENT_DEFAULT)
    jobs:
      - job: 'work_itens'
        displayName: 'Send message to Teams chat'
        steps:
        - checkout: none

        - template: /tech_products/ecmc/sap-commerce/tasks/messages/send_message_to_chat.yaml
          parameters:
            project_name: ${{ parameters.project_name }}
            environment_code: ${{ parameters.environment_code }}
            database_update_mode: ${{ parameters.database_update_mode }}
            deploy_strategy: ${{ parameters.deploy_strategy }}
            branch_frontend: ${{ parameters.branch_frontend }}
            branch_backend: ${{ parameters.branch_backend }}
            pipeline_status: ${{ parameters.pipeline_status }}
            message_title: '${{ parameters.work_item_title_prefix }} Sap Commerce cloud - ${{ parameters.pipeline_status }} - E-commerce B2C'
