parameters:
- name: incrementLevel
  default: patch
- name: enableDevflowValidations
  type: boolean
  default: False

resources:
  repositories:
    - repository: FortifyExclusion
      name: DevOps/Vivo.Fortify.Exclusions
      type: git
      ref: refs/heads/master
      endpoint: CorePipelines
    - repository: CorePipelines
      name: DevOps/Vivo.Core.Pipelines
      type: git
      ref: refs/tags/v1
      endpoint: CorePipelines
    - repository: CorePipelinesScripts
      name: DevOps/Vivo.Core.Pipelines.Scripts
      type: git
      ref: refs/heads/master
      endpoint: CorePipelines

variables:
  - template: /tech_products/ecmc/core-pipelines/provisioners/app/trunkbased/nodejs/lib_default/variables/load.yml

stages:
## INIT
- template: /tech_products/ecmc/core-pipelines/provisioners/app/trunkbased/nodejs/lib_default/stages/init.yml

- ${{ if eq(parameters.enableDevflowValidations, True) }}:
    ## VALIDATE PREDEFINED STANDARDS (COMMIT MESSAGES, BRANCH NAME ETC)
    - template: /tech_products/ecmc/core-pipelines/provisioners/app/trunkbased/nodejs/api_default/stages/validate_standards_dev_flow.yml

## BUILD & TEST
- template: /tech_products/ecmc/core-pipelines/provisioners/app/trunkbased/nodejs/lib_default/stages/build_test.yml
  parameters:
    incrementLevel: ${{ parameters.incrementLevel }}
    enableDevflowValidations: ${{ parameters.enableDevflowValidations }}


## GATES
- template: /tech_products/ecmc/core-pipelines/provisioners/app/trunkbased/nodejs/lib_default/stages/gates.yml

## SECURITY
- template: /tech_products/ecmc/core-pipelines/provisioners/app/trunkbased/nodejs/lib_default/stages/security_sast_sca.yml
  parameters:
    fortifyExclusionRepository: FortifyExclusion

## CODE-HEALER SCA
- template: /tech_products/ecmc/core-pipelines/provisioners/app/trunkbased/nodejs/api_default/stages/code_healer_sca.yml
  parameters:
    repositoryName: $(Build.Repository.Name)
    branchName: $(System.PullRequest.SourceBranch)
    codeHealerPipelineName: $(CODE_HEALER_SCA_PIPELINE_NAME)
    codeHealerPipelineBranch: $(CODE_HEALER_SCA_PIPELINE_BRANCH)
    codeHealerProject: $(System.TeamProject)
    scaFailedCondition: "and(eq(variables.RUN_CODE_HEALER_SCA, 'true'), eq(dependencies.security.outputs['sca_scan.sca_status.SCA_FAILED'], 'true'))"
    minNodeVersion: $(CODE_HEALER_SCA_MIN_NODE_VERSION)
    dependsOn: security