stages:

- stage: Deploy
  displayName: '🚀 Deploy $(Build.SourceBranchName)'
  condition: succeeded('Validate')
  pool: GeneralPurposeLinuxAgentsCD
  jobs:
  - job: Deploy
    displayName: '🚚 Deploy'
    steps:
    - checkout: self
      displayName: '🔄 Checkout code'
      fetchDepth: 0
    - task: CopyFilesOverSSH@0
      displayName: '📤 Transfer config via SSH'
      inputs:
        sshEndpoint: 'SSH_MOVEL_$(Build.SourceBranchName)'
        sourceFolder: '$(Build.SourcesDirectory)'
        contents: '$(ARQUIVO)'
        targetFolder: '$(TRANSACTION_FILE_DIR)'
        readyTimeout: '20000' # string. Required. SSH handshake timeout. Default: 20000.