steps:
- script: |
    echo "##[command] tfsec --var-file ${TFVARS_LOCATION} --exclude-path examples --exclude-downloaded-modules --format junit --soft-fail --verbose --out ${SYSTEM_DEFAULTWORKINGDIRECTORY}/TEST-tfsec.xml"
    tfsec \
      --var-file ${TFVARS_LOCATION} \
      --exclude-path examples \
      --exclude-downloaded-modules \
      --format junit \
      --soft-fail \
      --verbose \
      --out ${SYSTEM_DEFAULTWORKINGDIRECTORY}/TEST-tfsec.xml
  name: step_tfsec
  displayName: Run tfsec
  condition: and(succeeded(), eq(variables.tfsecEnabled, true))
  workingDirectory: $(Build.SourcesDirectory)
  env:
    TFVARS_LOCATION: $(tfvarsLocation)