parameters:
- name: enable_devflow_validations
  type: boolean

stages:
- stage: build_test
  displayName: "Build & Test"
  pool:
    name: $(PRIVATE_AGENT_DEFAULT)
    # demands: Agent.Version -gtVersion 2.210.1
  dependsOn:
    - pipeline_init
    - ${{ if eq(parameters.enable_devflow_validations, True) }}:
      - repo_validations
  jobs:
    - job: "start_build"
      displayName: "About Build and Test"
      steps:
        - checkout: none
        - bash: |
            echo "##[section]Stage para execução de build e testes"
          displayName: "Job information"

    - job: "build"
      displayName: "Build"
      steps:
      - bash: |
          cd $(Build.SourcesDirectory)/$(Build.Repository.Name)

          echo "##[command]Validando containers Sap Commerce Core Customize ativos na máquina"
          docker ps --filter ancestor=$(HYBRIS_IMAGE) --format {{.ID}}
          
          echo "##[command]Baixando imagem docker e executando"
          docker pull $(HYBRIS_IMAGE)
          
          echo "##[command]Checando imagem disponível"
          docker images
        displayName: 'Pulling Docker Image'

      - bash: |
          echo "##[section]Usando imagem $(HYBRIS_IMAGE)"
          echo "##[section]Comando de start $(CMD_HYBRIS_INSTALL)"

          TODAY_MONTH=$(date +"%Y%m")
          BRANCH=""
          LOCAL_COMAND=""

          if [[ $(Build.Reason) == "PullRequest" ]]; then
            BRANCH=$(echo "$(System.PullRequest.SourceBranch)" | sed 's/refs\/heads\///g')
            LOCAL_COMMAND="-Dsonar.branch.name=${BRANCH} -Dsonar.newCode.referenceBranch=$(SONAR_REF_BRANCH) -Dsonar.projectVersion=$TODAY_MONTH -Dsonar.login=$(SONARQUBE_TOKEN_SCC)"
          else 
            BRANCH=$(echo "$(Build.SourceBranch)" | sed 's/refs\/heads\///g')
            LOCAL_COMMAND="-Dsonar.branch.name=${BRANCH} -Dsonar.projectVersion=$TODAY_MONTH -Dsonar.login=$(SONARQUBE_TOKEN_SCC)"
          fi

          echo "##[section]Branch de execução da pipeline $BRANCH"
          echo "##[command]Comando na imagem $(CMD_HYBRIS_INSTALL) $LOCAL_COMMAND"
          docker run --rm --entrypoint "/bin/sh" --network host -v $(pwd):$(Build.SourcesDirectory)/$(Build.Repository.Name) -w "$(Build.SourcesDirectory)/$(Build.Repository.Name)" $(HYBRIS_IMAGE) -c "$(CMD_HYBRIS_INSTALL) $LOCAL_COMMAND"
        displayName: "Build Core Customize"