stages:
- stage: repo_validations
  displayName: "Project validations"
  dependsOn:
    - pipeline_init
  pool:
    name: $(PRIVATE_AGENT_DEFAULT)
  jobs:
    - job: "project_validations"
      displayName: "Start validations"
      steps:
        - checkout: CorePipelinesScripts
          persistCredentials: true
          fetchDepth: 1
        - checkout: self
          fetchDepth: 1
        
        - bash: |
            DIR_FOR_FIND_FILES=$(Build.SourcesDirectory)
            cd $DIR_FOR_FIND_FILES
            FIND_PROHIBITED_WORDS_FILES=$(find . -type f -name "*.spec.ts" -exec grep -wEHo "\b$PROHIBITED_WORDS\b" {} \;)
            if [[ $FIND_PROHIBITED_WORDS_FILES == '' ]]; then 
              echo "##[section]Nenhum arquivo com $PROHIBITED_WORDS_TEXT_MSG encontrado. Parabéns ;)..."
            else
              echo "$FIND_PROHIBITED_WORDS_FILES"
                echo "##[error]O tipo de flag $PROHIBITED_WORDS_TEXT_MSG só é permitido durante o tempo de desenvolvimento"
                echo "##[error]Por favor, verifique o(s) arquivo(s) abaixo e remova as flags:"
                echo "##[group] Clique para expandir"
                echo "##[section] $FIND_PROHIBITED_FILES"
                echo "##[endgroup]"
                echo "##[error]Pipeline abortado devido ao uso indevido de $PROHIBITED_WORDS_TEXT_MSG"
            fi
          displayName: "Find Prohibited Words"
          condition: ne(variables.flowIsMain, True)
        - template: /tech_products/ecmc/sap-commerce/tasks/catalog_info/extract_variables.yaml
          parameters:
            workingDirectory: $(Build.SourcesDirectory)/src-sap-commerce-core-customize-java
        - task: PipAuthenticate@1
          displayName: 'Pip Authenticate'
          inputs:
            artifactFeeds: $(AZURE_ARTIFACTS_FEED)
          env:
            http_proxy: $(PROXY_NSKP_HTTP)
            https_proxy: $(PROXY_NSKP_HTTPS)
            no_proxy: $(PROXY_NSKP_NO_PROXY)
          condition: and(
                      succeeded(),
                      or(
                        eq(variables.DEVFLOW_VALIDATE_STANDARDS, true),
                        eq(variables.DEVFLOW_VALIDATE_JIRA_ISSUE, true)
                      ),
                      ne(variables.flowIsMain, True)
                    )
        
        - bash: |
            echo "##[command]Instalando requirements.txt"
            cd $(Build.SourcesDirectory)/Vivo.Core.Pipelines.Scripts
            pip install -r requirements.txt
          condition: and(
                      succeeded(),
                      or(
                        eq(variables.DEVFLOW_VALIDATE_STANDARDS, true),
                        eq(variables.DEVFLOW_VALIDATE_JIRA_ISSUE, true)
                      ),
                      ne(variables.flowIsMain, True)
                    )
          displayName: "Install Python packages"

        - bash: |
            echo "##[command]Skipando validações por ser ambiente de DEV ou a branch é main/master"
            echo "##[command]Variável DEVELOPMENT_ENVIRONMENT_FLOW está com o valor = false"
          condition: or(ne(variables.DEVELOPMENT_ENVIRONMENT_FLOW, true), ne(variables.flowIsMain, True))
          displayName: "Validate Standards Branches and Variables"

        - bash: |
            echo "##[command]Etapa de validação de branch e commits"
            echo "##[command]Essa etapa valida os padrões de commit bem como a nomenclatura de branches"              
          condition: and(
                        eq(variables.DEVFLOW_VALIDATE_STANDARDS, true),
                        or(
                          eq(variables.DEVFLOW_VALIDATE_BRANCH, true),
                          eq(variables.DEVFLOW_VALIDATE_COMMIT, true)
                        ),
                        ne(variables.flowIsMain, True)
                    )
          displayName: "Validate Standards Enabled/Disabled"

        - bash: |
            echo "##[command]Skipando validação de branch e commits"
            echo "##[command]Variáveis DEVFLOW_VALIDATE_STANDARDS, DEVFLOW_VALIDATE_BRANCH ou DEVFLOW_VALIDATE_COMMIT não estão com valor = true ou a branch é main/master"
          condition: or(
                      ne(variables.DEVFLOW_VALIDATE_STANDARDS, true),
                      ne(variables.DEVFLOW_VALIDATE_BRANCH, true), 
                      ne(variables.DEVFLOW_VALIDATE_COMMIT, true),
                      eq(variables.flowIsMain, True)
                    )
          displayName: "Validate Standards Enabled/Disabled"

        - bash: |
            echo "##[command]Validação de branch e commits"
            cd $(Build.SourcesDirectory)/$(Build.Repository.Name)
            python $(Build.SourcesDirectory)/Vivo.Core.Pipelines.Scripts/app.py --branch-commit
          condition: and(
                      succeeded(),
                      eq(variables.DEVFLOW_VALIDATE_STANDARDS, true),
                      ne(variables.flowIsMain, True),
                      or(
                        eq(variables.DEVFLOW_VALIDATE_BRANCH, true),
                        eq(variables.DEVFLOW_VALIDATE_COMMIT, true)
                      )
                    )
          env:
            SYSTEM_ACCESSTOKEN: $(System.AccessToken)
          displayName: "Validate branch/commits"

        - bash: |
            echo "##[command]Etapa de validação de issue no Jira"
            echo "##[command]Essa etapa valida se a issue que foi passada no commit é válida"              
          condition: and(
                      eq(variables.DEVFLOW_VALIDATE_JIRA_ISSUE, true),
                      ne(variables.flowIsMain, True)
                    )
          displayName: "Validate Jira Issue Enabled/Disabled"

        - bash: |
            echo "##[command]Skipando validação de issue no Jira"
            echo "##[command]Variável DEVFLOW_VALIDATE_JIRA_ISSUE não está com valor = true ou a branch é main/master"
          condition: or(ne(variables.DEVFLOW_VALIDATE_JIRA_ISSUE, true), eq(variables.flowIsMain, True))
          displayName: "Validate Jira Issue Enabled/Disabled"        

        - bash: |
            echo "##[command]Validação de Issue no Jira"
            cd $(Build.SourcesDirectory)/$(Build.Repository.Name)
            python $(Build.SourcesDirectory)/Vivo.Core.Pipelines.Scripts/app.py --jira
          condition: and(
                      succeeded(),
                      eq(variables.DEVFLOW_VALIDATE_JIRA_ISSUE, true),
                      ne(variables.flowIsMain, True)
                    )
          env:
            SYSTEM_ACCESSTOKEN: $(System.AccessToken)
            SYSTEM_ACCESSTOKEN_CUSTOM: $(SYSTEM_ACCESSTOKEN_CUSTOM)
            JIRA_TOKEN: $(JIRA_TOKEN))
          displayName: "Validate Issue Jira"
        
        - template: /tech_products/ecmc/sap-commerce/tasks/validations/validate_release_manager.yaml
          parameters:
            condition: and(
                        succeeded(),
                        eq(variables.VALIDATE_RELEASE_MANAGER, 'true'),
                        ne(variables.flowIsMain, True)
                      )
                
        - bash: |
            echo "##[command]Etapa de criação feature flag automática. A task Create/check feature flags tentará criar a feature flag"
          condition: and(
                      eq(variables.DEVFLOW_VALIDATE_STANDARDS, true),
                      eq(variables.DEVFLOW_VALIDATE_FEATURE_FLAGS_SAP_COMMERCE, true),
                      ne(variables.flowIsMain, True),
                      eq(variables.flowIsPullRequest, True)  
                    )
          displayName: "Create Feature Flag automaticaly"
        
        - bash: |
            echo "##[command]Skipando criação feature flag automática"
            echo "##[command]As variáveis DEVFLOW_VALIDATE_STANDARDS ou DEVFLOW_VALIDATE_FEATURE_FLAGS_SAP_COMMERCE estão com o valor false ou a execução atual não está sendo executada a partir de um Pull Request" 
          condition: or(
                      ne(variables.DEVFLOW_VALIDATE_STANDARDS, true),
                      ne(variables.DEVFLOW_VALIDATE_FEATURE_FLAGS_SAP_COMMERCE, true),
                      or(eq(variables.flowIsMain, True), ne(variables.flowIsPullRequest, True))               
                    )
          displayName: "About Feature Flag automaticaly"
        
        - bash: |
            echo "##[command]Criação/verificação de feature flag automática e geração de dados para a Wiki"
            cd $(Build.SourcesDirectory)/$(Build.Repository.Name)
            export WIKI_FILE=wiki-data.html
            
            python $(Build.SourcesDirectory)/Vivo.Core.Pipelines.Scripts/app.py --feature-flags --wiki-data-file "$WIKI_FILE"
            
            if [ ! -f $WIKI_FILE ]; then
              echo "##[error] Não foi possível recuperar a descricão do Pull Request ou algum outro erro na verificação de feature flag ocorreu. "
              exit 1        
            fi
          condition: and(
                      succeeded(),
                      eq(variables.DEVFLOW_VALIDATE_STANDARDS, true),
                      eq(variables.DEVFLOW_PUBLISH_CONFLUENCE, true),
                      ne(variables.flowIsMain, True),
                      eq(variables.flowIsPullRequest, True)
                    )
          env:
            SYSTEM_ACCESSTOKEN: $(System.AccessToken)
            SYSTEM_ACCESSTOKEN_CUSTOM: $(SYSTEM_ACCESSTOKEN_CUSTOM)
          displayName: "Create/check feature flags and data for Wiki"

        - bash: |
            echo "##[command]Etapa de envio dos dados do Pull Request para a api para posterior gravação no Confluence"

            cd $(Build.SourcesDirectory)/$(Build.Repository.Name)
            unset RESPONSE HTTP_STATUS_CODE RESPONSE_BODY
            
            if [ ! -f wiki-data.html ]; then
              echo "##[error] Não foi possível recuperar a descricão do Pull Request ou algum outro erro na verificação de feature flag ocorreu. "
              exit 1        
            fi

            DESCRIPTION=$(cat "wiki-data.html")
            
            BODY=$(jq --null-input \
                        --arg description "$DESCRIPTION" \
                        --argjson  pull_request_id $SYSTEM_PULLREQUEST_PULLREQUESTID \
                        --arg component_name "$APP_NAME" \
                        --arg owner "$SYSTEM_TEAMPROJECT" \
                        '{"description": $description, "merge_request_id": $pull_request_id, "component_name": $component_name, "owner": $owner}')
            RESPONSE=$(curl --max-time $CURL_HTTP_TIMEOUT  -s -w "\n%{http_code}" -X POST -H 'Content-Type: application/json'  "$DEVFLOW_API_PRE_WRITE" --data-raw "$BODY" )
            RESPONSE=(${RESPONSE[@]})
            HTTP_STATUS_CODE=${RESPONSE[-1]}
            RESPONSE_BODY=${RESPONSE[@]::${#RESPONSE[@]}-1}

            if [[ "$HTTP_STATUS_CODE" != "201" ]]; then
              echo "##[error] Não foi possível gravar os dados na api"
              echo "##[error] Código http $HTTP_STATUS_CODE"
              echo "##[error] Abaixo está o retorno da api"
              echo "$RESPONSE_BODY"
              exit 1        
            fi

            echo "##[command]Dados do pull request gravados"
            unset RESPONSE HTTP_STATUS_CODE RESPONSE_BODY

          displayName: "Save pull request data"
          condition: and(
                      succeeded(),
                      eq(variables.DEVFLOW_VALIDATE_STANDARDS, true),
                      eq(variables.DEVFLOW_PUBLISH_CONFLUENCE, true),
                      ne(variables.flowIsMain, True),
                      eq(variables.flowIsPullRequest, True)
                    )
