parameters:
- name: run_component_test
  type: boolean
- name: qa_environment
  type: string
- name: enableDevflowValidations
  type: boolean
  default: False
- name: argocd_enabled
  type: boolean
  default: False

variables:
- template: /tech_products/srus/provisioners/app/trunkbased/python/api_default/variables/load.yml

resources:
  repositories:
    - repository: FortifyExclusion
      name: DevOps/Vivo.Fortify.Exclusions
      type: git
      ref: refs/heads/master
      endpoint: CorePipelines
    - repository: CorePipelinesScripts
      name: DevOps/Vivo.Core.Pipelines.Scripts
      type: git
      ref: refs/heads/master
      endpoint: CorePipelines

stages: 
# CI / CD Flow

  ## INIT
  - template: /tech_products/srus/provisioners/app/trunkbased/python/api_default/stages/init.yml
  
  - ${{ if eq(parameters.enableDevflowValidations, True) }}:
    ## VALIDATE PREDEFINED STANDARDS (COMMIT MESSAGES, BRANCH NAME ETC)
    - template: /tech_products/srus/provisioners/app/trunkbased/python/api_default/stages/validate_standards_dev_flow.yml

  ## BUILD & TEST
  - template: /tech_products/srus/provisioners/app/trunkbased/python/api_default/stages/build_test.yml
    ${{ if eq(parameters.enableDevflowValidations, True) }}:
      parameters:
        enableDevflowValidations: "${{parameters.enableDevflowValidations}}"

  ## GATES
  - template: /tech_products/srus/provisioners/app/trunkbased/python/api_default/stages/gates.yml
    parameters:
      environment: "${{parameters.qa_environment}}"

  ## SECURITY
  - template: /tech_products/srus/provisioners/app/trunkbased/python/api_default/stages/security.yml
    parameters:
      fortifyExclusionRepository: FortifyExclusion

  ## PACKAGE
  - template: /tech_products/srus/provisioners/app/trunkbased/python/api_default/stages/package.yml
    parameters:
      run_component_test: "${{parameters.run_component_test}}"

  ## VALIDATIONS
  - template: /tech_products/srus/provisioners/app/trunkbased/python/api_default/stages/validation.yml

  ## COMPONENT TEST
  - template: /tech_products/srus/provisioners/app/trunkbased/python/api_default/stages/component_test.yml
    parameters:
      run_component_test: "${{parameters.run_component_test}}"