parameters:
- name: environment
  type: string

- name: pipeline_name
  type: string

- name: pipeline_version
  type: string

stages:
- stage: build_test
  displayName: "Build & Package"
  dependsOn:
    - pipeline_init
  pool: $(PRIVATE_AGENT_DEFAULT)
  jobs:
  - job: build
    displayName: Build & Test & Package
    steps:
    - template: /tech_products/digibee/templates/setup_digibee.yml
      parameters:
        environment: "${{ parameters.environment }}"
        pipeline_name: "${{ parameters.pipeline_name }}"
        pipeline_version: "${{ parameters.pipeline_version }}"

    - template: /tech_products/digibee/templates/load_digibee_pipeline.yml
      parameters:
        environment: "${{ parameters.environment }}"
        pipeline_name: "${{ parameters.pipeline_name }}"
        pipeline_version: "${{ parameters.pipeline_version }}"

    - template: /tech_products/digibee/templates/export_digibee_metadata.yml
      parameters:
        environment: "${{ parameters.environment }}"
        pipeline_name: "${{ parameters.pipeline_name }}"
        pipeline_version: "${{ parameters.pipeline_version }}"

    - template: /tech_products/digibee/templates/publish_digibee_artifacts.yml
    