stages:
- stage: pipeline_init
  displayName: "Initialize"
  pool: $(PRIVATE_AGENT_DEFAULT)
  jobs:
  - job: prepare_pipeline
    displayName: "Init Digibee Pipeline"
    steps:
    # - template: /tasks/bash/welcome.yml
    - script: |
        echo "##[debug] Digibee setup debug variables"
      displayName: 'Initialize Digibee'


      
      