parameters:
- name: digibee_project
  type: string
  
- name: pipeline_name
  type: string

stages:
- stage: setup
  displayName: "Setup Digibee"
  dependsOn:
    - pipeline_init
  pool: $(PRIVATE_AGENT_DEFAULT)
  jobs:
  - job: build
    displayName: Setup Pipeline
    steps:
    - template: /tech_products/digibee/templates/setup_digibee.yml

    - template: /tech_products/digibee/templates/create_digibee_project.yml
      parameters:
        digibee_project: "${{ parameters.digibee_project }}"

    - template: /tech_products/digibee/templates/create_digibee_pipeline.yml
      parameters:
        digibee_project: "${{ parameters.digibee_project }}"
        pipeline_name: "${{ parameters.pipeline_name }}"
        

    
    