parameters:
- name: dependsOn
  type: object
  default: []

stages:
- stage: maven_unit_test
  displayName: "Tests - Maven"
  dependsOn: ${{ parameters.dependsOn }}
  pool: $(PRIVATE_AGENT_DEFAULT)
  jobs:
  - job: build_and_test
    displayName: Build, Test & Coverage
    timeoutInMinutes: 120
    condition: and( succeeded(), and( eq(variables.flowIsToReview, true), not(startsWith(variables['Build.SourceBranch'], 'refs/tags/'))))
    workspace:
      clean: outputs
    steps:
      - checkout: self
        clean: false
        persistCredentials: true
        
      - template: /tech_products/ecmc/core-pipelines/tasks/bash/welcome.yml
      
      - template: ../templates/setup-maven.yml
      
      - template: ../templates/build.yml
    
      - template: /tech_products/ecmc/core-pipelines/tasks/artifacts/publish_pipeline.yml
        parameters:
          artifactName: $(AEM_JAVA_BUNDLE_FOLDER_NAME)
          targetPath: $(Build.SourcesDirectory)/$(AEM_JAVA_BUNDLE_FOLDER_NAME)
      
      - template: /tech_products/ecmc/core-pipelines/task_groups/tests/publish_tests_reports.yml
        parameters:
          workdirArtifacts: "$(Build.SourcesDirectory)/$(AEM_JAVA_BUNDLE_FOLDER_NAME)"
          pathToSources: "$(COVERAGE_REPORT_PATH_TO_SOURCE)"
          coverageFilePattern: "$(COVERAGE_REPORT_SUMMARY_FILE_LOCATION)"
          additionalCodeCoverageFiles: "$(COVERAGE_REPORT_ADDITIONAL_FILE)"
      