
parameters:
- name: environment
  displayName: 'Escolha o ambiente para publicar'
  type: string
  default: dev
  values:
  - dev
  - preprod
  - prod

- name: environment_map
  type: object
  default: 
    dev: development
    prod: production
    test: test
    preprod: preproduction
    prodlike: productionlike
    esteira1: esteira1
    esteira2: esteira2
    esteira3: esteira3
- name: pomFile
  default: ./pom.xml
  type: 'string'

variables:
- name: System.debug
  value: "true"

stages:
- stage:
  displayName: 'Liquibase'
  pool: GeneralPurposeLinuxAgentsCI
  jobs:
  - job:
    displayName: 'Validate and Update SQL'
    variables:
    - name: ASDF_JAVA_VERSION
      value: "openjdk-11.0.2"
    steps:
    - checkout: self
      fetchDepth: 1
      persistCredentials: true

    - task: AzureKeyVault@2
      displayName: 'Secrets from AKV'
      inputs:
        RunAsPreJob: true
        azureSubscription: "DevOpsSharedResources"
        KeyVaultName: "kv-azdevops-shared"
        SecretsFilter: >-
          NEXUS-DEPS-USR,
          NEXUS-DEPS-PSW,
          SONARQUBE-TOKEN

    - task: Maven@3
      displayName: 'liquibase:validate'
      continueOnError: False
      env:
        NEXUS_DEPS_USR: $(NEXUS-DEPS-USR)
        NEXUS_DEPS_PSW: $(NEXUS-DEPS-PSW)
        SYSTEM_ACCESSTOKEN: $(System.AccessToken)
      inputs:
        options: >-
          -s /home/svc_devopscorp/.m2/settings.xml
        mavenPomFile: ${{ parameters.pomFile }}
        mavenOptions: "-Xmx3072m"
        javaHomeOption: "JDKVersion"
        publishJUnitResults: false
        goals: "liquibase:validate"

    - task: Maven@3
      displayName: 'liquibase:updateSQL'
      continueOnError: False
      env:
        NEXUS_DEPS_USR: $(NEXUS-DEPS-USR)
        NEXUS_DEPS_PSW: $(NEXUS-DEPS-PSW)
        SYSTEM_ACCESSTOKEN: $(System.AccessToken)
      inputs:
        options: >-
          -s /home/svc_devopscorp/.m2/settings.xml
        mavenPomFile: ${{ parameters.pomFile }}
        mavenOptions: "-Xmx3072m"
        javaHomeOption: "JDKVersion"
        publishJUnitResults: false
        goals: "liquibase:updateSQL"
