steps:
- script: |
    files=$(find $(pwd) -type f -user root)
    if [ -n "$files" ]; then
      echo "##[debug]Arquivos com owner root encontrados:"
      echo "$files"
      echo "##vso[task.logissue type=warning; ]Arquivos com owner root encontrados. Consulte os logs para mais informações."
      echo "##[debug]Ajustando permissões dos arquivos encontrados..."
      sudo find $(pwd) -type f -user root -exec /usr/bin/chown svc_devopscorp:svc_devopscorp {} +
      if [ $? -eq 0 ]; then
        echo "##[debug]OK"
      else
        echo "##vso[task.logissue type=error]Erro ao ajustar ownership dos arquivos do Teste de Componentes."
      fi
    else
      echo "##[debug]Não foram encontrados arquivos com owner root. Nada a ser ajustado."
    fi
  displayName: 'Verify and change root files ownership'
  condition: always()