parameters:
- name: qa_environment
  type: string
  default: ''
- name: run_component_test
  type: boolean
- name: skip_deploy
  type: boolean
  default: False
- name: dev_namespace_to_deploy
  type: string
  default: ''
- name: argocd_enabled
  type: boolean
  default: False
- name: enableDevflowValidations
  type: boolean
  default: False
- name: pipelineName
  type: string
  default: ''

variables:
- template: /tech_products/loja-online/provisioners/api_default/variables/load.yml
  parameters: 
    pipelineName: ${{ parameters.pipelineName }}

resources:
  repositories:
    - repository: FortifyExclusion
      name: DevOps/Vivo.Fortify.Exclusions
      type: git
      ref: refs/heads/master
      endpoint: CorePipelines
    - repository: CorePipelinesScripts
      name: DevOps/Vivo.Core.Pipelines.Scripts
      type: git
      ref: refs/heads/master
      endpoint: CorePipelines

stages:
# CI Flow

## INIT
- template: /tech_products/loja-online/provisioners/api_default/stages/init.yml

- ${{ if or( and( ne(variables['Build.Reason'], 'PullRequest'), in(variables['Build.SourceBranch'], 'refs/heads/main', 'refs/heads/master')), and(startsWith(variables['Build.SourceBranch'], 'refs/heads/'), ne(parameters.dev_namespace_to_deploy, '')) ) }}:
  ## VALIDATE PREDEFINED STANDARDS (COMMIT MESSAGES, BRANCH NAME ETC)
  - ${{ if eq(parameters.enableDevflowValidations, True) }}:
    - template: /tech_products/loja-online/provisioners/api_default/stages/validate_standards_dev_flow.yml
  
  ## BUILD & TEST
  - template: /tech_products/loja-online/provisioners/api_default/stages/build_test.yml
    parameters:
      enableDevflowValidations: ${{ parameters.enableDevflowValidations }}

  ## GATES
  - template: /tech_products/loja-online/provisioners/api_default/stages/gates.yml
    parameters:
      environment: "${{parameters.qa_environment}}"

  ## SECURITY
  - template: /tech_products/loja-online/provisioners/api_default/stages/security.yml
    parameters:
      fortifyExclusionRepository: FortifyExclusion

  ## PACKAGE
  - template: /tech_products/loja-online/provisioners/api_default/stages/package.yml
    parameters:
      run_component_test: "${{parameters.run_component_test}}"
      dev_namespace_to_deploy: ${{ parameters.dev_namespace_to_deploy }}
      environment: "dev"

- ${{ if or( and( ne(variables['Build.Reason'], 'PullRequest'), in(variables['Build.SourceBranch'], 'refs/heads/main', 'refs/heads/master')), and(startsWith(variables['Build.SourceBranch'], 'refs/heads/'), ne(parameters.dev_namespace_to_deploy, '')) ) }}:
  - ${{ if eq(parameters.enableDevflowValidations, True) }}:
  ## FINALIZE PRE VALIDATIONS 
    - template: /tech_products/loja-online/provisioners/api_default/stages/pos_validate_standards_dev_flow.yml

  ## VALIDATIONS
  - template: /tech_products/loja-online/provisioners/api_default/stages/validation.yml

  ## COMPONENT TEST
  - template: /tech_products/loja-online/provisioners/api_default/stages/component_test.yml
    parameters:
      run_component_test: "${{parameters.run_component_test}}"