parameters:
- name: downloadPath
  default: $(DEFAULT_WORKDIR_ARTIFACTS)
- name: artifactFeed
  default: $(AZURE_ARTIFACTS_FEED)
- name: configFile
  default: $(PYPIRC_PATH)
- name: libPathLocation
  type: string
- name: pythonVersion
  type: string

steps:
- task: TwineAuthenticate@1
  displayName: Twine Authenticate
  inputs:
    artifactFeed: ${{ parameters.artifactFeed }}

- bash: |
    echo "##[debug]Criando arquivo de configuração do Twine..."
    cat ${CONFIG_FILE} > twineconfig.cfg

    echo "##[debug]Copiando diretório Library..."
    cp -r ${DOWNLOAD_PATH}/Library .
  displayName: Copy twine configuration and library files
  env:
    CONFIG_FILE: ${{ parameters.configFile }}
    DOWNLOAD_PATH: ${{ parameters.downloadPath }}

- template: /tech_products/srus/tasks/python/run_bash_on_docker.yml
  parameters:
    pythonVersion: "${{ parameters.pythonVersion }}"
    scriptNameOrCmd: |
        echo "##[debug]Criando ambiente virtual python..."
        python -m venv .venv

        echo "##[debug]Ativando ambiente virtual python..."
        source .venv/bin/activate

        echo "##[debug]Instalando biblioteca twine..."
        pip install twine

        echo "##[debug]Publicando library..."
        python -m twine upload -r ${{ parameters.artifactFeed }} --config-file twineconfig.cfg ${{ parameters.libPathLocation }}
    displayName: Publishing Library
