parameters:
- name: newVersion
  type: string
- name: condition
  type: object

steps:
- bash: |
    echo "##[debug]Update Build Version:"
    
    # Atualiza a versão no arquivo VERSION
    echo "${NEW_VERSION}" > VERSION
    
    echo "##[debug]Version updated to ${NEW_VERSION} in VERSION file"
  
  displayName: 'Update VERSION file'
  condition: ${{ parameters.condition }}
  env:
    NEW_VERSION: ${{ parameters.newVersion }}
