parameters:
  - name: deploy_scgw_option
    type: string
  - name: qa_environment
    type: string  
  - name: components_to_install
    type: string
  - name: skip_deploy
    type: boolean
    default: true
  - name: environment
    type: string
  - name: project_version
    type: string
  - name: redis_cluster
    type: string      

variables:
  - template: /tech_products/ocs/initialize/variables_global.yml
  - template: /tech_products/ocs/initialize/variables_weblogic_osgi.yml
  - template: /.azuredevops/config/${{ parameters.qa_environment }}/environments_variables.yml@self
  - group: "${{ variables['Build.DefinitionName'] }}"

resources:
  repositories:
    - repository: FortifyExclusion
      name: DevOps/Vivo.Fortify.Exclusions
      type: git
      ref: refs/heads/master
      endpoint: CodePlay
    - repository: CorePipelines
      name: DevOps/Vivo.Core.Pipelines
      type: git
      ref: refs/tags/latest
      endpoint: CorePipelines     

stages:

## -> Build for SCGW
- template: /tech_products/ocs/templates/ci/ci_build_scgw.yml
 
  # ## -> Gates for CI - Weblogic
- template: /tech_products/ocs/templates/ci/ci_gates_scgw.yml
  parameters:
    qa_environment: ${{ parameters.qa_environment }}

   ## -> Security for CI - Weblogic
- template: /tech_products/ocs/templates/ci/ci_security_weblogic_osgi.yml
  #parameters:
    #fortifyExclusionRepository: FortifyExclusion

## -> Package for CI - Weblogic
- template: /tech_products/ocs/templates/ci/ci_package_scgw.yml    

## -> Deploy for SCGW
- template: /tech_products/ocs/templates/cd/cd_deploy_scgw.yml
  parameters:
    deploy_scgw_option: ${{ parameters.deploy_scgw_option }}
    skip_deploy: ${{ parameters.skip_deploy }}
    environment: ${{ parameters.environment }}
    project_version: ${{ parameters.project_version }}
    redis_cluster: ${{ parameters.redis_cluster }}
