parameters:
- name: enableDevflowValidations
  type: boolean
  default: False

variables:
- template: /tech_products/ecmc/hybris67/provisioners/variables/load.yaml

resources:
  repositories:
    - repository: CorePipelines
      name: DevOps/Vivo.Core.Pipelines
      type: git
      ref: refs/tags/v1
      endpoint: CorePipelines

    - repository: CorePipelinesScripts
      name: DevOps/Vivo.Core.Pipelines.Scripts
      type: git
      ref: refs/heads/master
      endpoint: CorePipelines

    - repository: FortifyExclusion
      name: DevOps/Vivo.Fortify.Exclusions
      type: git
      ref: refs/heads/master
      endpoint: CorePipelines

stages:
# CI / CD Flow

  ## INIT
  - template: /tech_products/ecmc/core-pipelines/provisioners/app/trunkbased/nodejs/api_default/stages/init.yml


  ## VALIDATE PREDEFINED STANDARDS (COMMIT MESSAGES, BRANCH NAME ETC)
  - ${{ if eq(parameters.enableDevflowValidations, True) }}:
    - template: /tech_products/ecmc/core-pipelines/provisioners/app/trunkbased/nodejs/api_default/stages/validate_standards_dev_flow.yml


  ## UPDATE VERSION
  - ${{ if and(ne(variables['Build.Reason'], 'PullRequest'), eq(variables['Build.SourceBranch'], 'refs/heads/master')) }}:
    - template: stages/bump-version.yaml


  ## BUILD
  - ${{ if not(startsWith(variables['Build.SourceBranch'], 'refs/tags/')) }}:
    - template: stages/build.yaml


  ## SECURITY
  - ${{ if not(startsWith(variables['Build.SourceBranch'], 'refs/tags/')) }}:
    - template: stages/security.yaml
      parameters:
        fortifyExclusionRepository: FortifyExclusion