stages:
- stage: ci_package
  displayName: "CI - Package"  
  pool:
    name: GeneralPurposeLinuxAgentsCI
  dependsOn:
  - ci_build
  - ci_publish
  condition: succeeded()

  ## -> Loads variables from other stages.
  variables:
    - name: SONAR_TASK_ID
      value: $[ stageDependencies.gate.sonarqube.outputs['sonar_task_id.SONAR_TASK_ID'] ]
    - name: APP_VERSION
      value: $[ stageDependencies.ci_build.build.outputs['new_version.NEW_VERSION'] ]
    - name: ARTIFACT_NAME
      value: $[ stageDependencies.ci_build.build.outputs['artifact_name.ARTIFACT_NAME'] ]

  jobs:

  - job: "Package"
    condition: and(
              succeeded(), 
              or(
              eq(variables['Build.SourceBranchName'],'master'),
              eq(variables['Build.SourceBranchName'],'main'),
              eq(variables['Build.SourceBranchName'],'prodlike'),
              eq(variables['Build.SourceBranchName'],'preprod'),
              eq(variables['Build.SourceBranchName'],'esteira1'),
              eq(variables['Build.SourceBranchName'],'esteira2'),
              eq(variables['Build.SourceBranchName'],'test_codeplay'),
              eq(variables['Build.SourceBranchName'],'dev')))
    displayName: "Package"    
    steps:
    
    ## -> Download and uncompress the downloaded artifact.         
    - task: DownloadBuildArtifacts@1
      displayName: 'Download Build Artifacts'
      inputs:
        artifactName: $(ARTIFACT_NAME)
        cleanDestinationFolder: false
        extractTars: true
        parallelizationLimit: 8
        downloadPath: $(System.ArtifactsDirectory)
        
    - task: CmdLine@2
      displayName: "Define Variables"
      inputs:
        workingDirectory: '$(DEFAULT_WORKDIR_ARTIFACTS)/$(ARTIFACT_NAME)/'
        script: |
        
          catalogInfo=$(find . -type f -name "catalog-info.*" -print -quit)          

          if [ ! -f $catalogInfo ]; then
            echo "##vso[task.logissue type=error] Unable to find catalog-info file (path=$(pwd))."
            exit 1
          fi

          GOV_APP_ACRONYM="$(yq -r '.metadata.annotations."techarch.governance-app.acronym" | select (.!=null) | downcase' $catalogInfo)"
          APP_SYSTEM="$(yq -r 'select(documentIndex == 0) | .spec.system | select (.!=null)' $catalogInfo)"
          APP_NAME="$(yq -r 'select(documentIndex == 0) | .metadata.name | select (.!=null)' $catalogInfo)"
          APP_DESCRIPTION="$(yq -r 'select(documentIndex == 0) | .metadata.description | select (.!=null)' $catalogInfo)"
          SONAR_PROJECT_KEY="$(yq -r 'select(documentIndex == 0) | .metadata.annotations."sonarqube.org/project-key" | select (.!=null)' $catalogInfo)"
          K8S_CONFIG="$(yq -r '.metadata.annotations."vivo.io/kubernetes-config" | select (.!=null)' $catalogInfo)"
          K8S_NAMESPACE="$(yq -r '.metadata.annotations."vivo.io/kubernetes-namespace" | select (.!=null)' $catalogInfo)"
          HELM_RELEASE="$(yq -r '.metadata.annotations."backstage.io/kubernetes-id" | select (.!=null)' $catalogInfo)"
          K8S_NAMESPACE_DEV="$(yq -r '.metadata.annotations."vivo.io/kubernetes-k8s-namespace-dev" | select (.!=null)' $catalogInfo)"
          K8S_NAMESPACE_ESTEIRA1="$(yq -r '.metadata.annotations."vivo.io/kubernetes-k8s-namespace-esteira1" | select (.!=null)' $catalogInfo)"
          K8S_NAMESPACE_ESTEIRA2="$(yq -r '.metadata.annotations."vivo.io/kubernetes-k8s-namespace-esteira2" | select (.!=null)' $catalogInfo)"
          K8S_NAMESPACE_PREPROD="$(yq -r '.metadata.annotations."vivo.io/kubernetes-k8s-namespace-preprod" | select (.!=null)' $catalogInfo)"
          K8S_NAMESPACE_PRODLIKE="$(yq -r '.metadata.annotations."vivo.io/kubernetes-k8s-namespace-prodlike" | select (.!=null)' $catalogInfo)"
          K8S_NAMESPACE_PRODUCAO="$(yq -r '.metadata.annotations."vivo.io/kubernetes-k8s-namespace-producao" | select (.!=null)' $catalogInfo)"

          echo "##[group] catalog-info Variables"
          echo "##[debug] GOV_APP_ACRONYM............: ${GOV_APP_ACRONYM}"
          echo "##[debug] APP_SYSTEM.................: ${APP_SYSTEM}"
          echo "##[debug] APP_NAME...................: ${APP_NAME}"
          echo "##[debug] SONAR_PROJECT_KEY..........: ${SONAR_PROJECT_KEY}"
          echo "##[debug] K8S_CONFIG.................: ${K8S_CONFIG}"          
          echo "##[debug] K8S_NAMESPACE..............: ${K8S_NAMESPACE}"
          echo "##[debug] HELM_RELEASE...............: ${HELM_RELEASE}"
          echo "##[debug] K8S_NAMESPACE_DEV..........: ${K8S_NAMESPACE_DEV}"
          echo "##[debug] K8S_NAMESPACE_ESTEIRA1.....: ${K8S_NAMESPACE_ESTEIRA1}"
          echo "##[debug] K8S_NAMESPACE_ESTEIRA2.....: ${K8S_NAMESPACE_ESTEIRA2}"
          echo "##[debug] K8S_NAMESPACE_PREPROD......: ${K8S_NAMESPACE_PREPROD}"
          echo "##[debug] K8S_NAMESPACE_PRODLIKE.....: ${K8S_NAMESPACE_PRODLIKE}"
          echo "##[debug] K8S_NAMESPACE_PRODUCAO.....: ${K8S_NAMESPACE_PRODUCAO}"
          echo "##[debug] APP_DESCRIPTION............: ${APP_DESCRIPTION}"
          echo "##vso[task.setvariable variable=GOV_APP_ACRONYM]${GOV_APP_ACRONYM}"
          echo "##vso[task.setvariable variable=APP_SYSTEM]${APP_SYSTEM}"
          echo "##vso[task.setvariable variable=APP_NAME]${APP_NAME}"
          echo "##vso[task.setvariable variable=SONAR_PROJECT_KEY]${SONAR_PROJECT_KEY}"
          echo "##vso[task.setvariable variable=K8S_CONFIG]${K8S_CONFIG}"
          echo "##vso[task.setvariable variable=K8S_NAMESPACE]${K8S_NAMESPACE}"
          echo "##vso[task.setvariable variable=HELM_RELEASE]${HELM_RELEASE}"
          echo "##vso[task.setvariable variable=K8S_NAMESPACE_DEV]${K8S_NAMESPACE_DEV}"
          echo "##vso[task.setvariable variable=K8S_NAMESPACE_ESTEIRA1]${K8S_NAMESPACE_ESTEIRA1}"
          echo "##vso[task.setvariable variable=K8S_NAMESPACE_ESTEIRA2]${K8S_NAMESPACE_ESTEIRA2}"
          echo "##vso[task.setvariable variable=K8S_NAMESPACE_PREPROD]${K8S_NAMESPACE_PREPROD}"
          echo "##vso[task.setvariable variable=K8S_NAMESPACE_PRODLIKE]${K8S_NAMESPACE_PRODLIKE}"
          echo "##vso[task.setvariable variable=K8S_NAMESPACE_PRODUCAO]${K8S_NAMESPACE_PRODUCAO}"
          echo "##vso[task.setvariable variable=APP_DESCRIPTION]${APP_DESCRIPTION}"
          echo "##[endgroup]"
          echo "##[group] Docker Variables"
          echo "##[debug] DOCKER_REGISTRY............: ${DOCKER_REGISTRY}"
          echo "##[debug] DOCKER_SERVICE_CONNECTION..: ${DOCKER_SERVICE_CONNECTION}"   
          echo "##[debug] DOCKER_IMAGE_NAME..........: ${GOV_APP_ACRONYM}${APP_NAME}"   
          echo "##[debug] DOCKER_IMAGE_TAG...........: ${APP_VERSION}"             
          if [ ! -f "runtime.Dockerfile"  ]; then
            DOCKER_FILE=$(DEFAULT_WORKDIR_ARTIFACTS)/$(ARTIFACT_NAME)/.azuredevops/runtime.Dockerfile
          else
            DOCKER_FILE=$(DEFAULT_WORKDIR_ARTIFACTS)/$(ARTIFACT_NAME)/.azuredevops/runtime.Dockerfile
          fi
          echo "##[debug] DOCKER_FILE...........: ${DOCKER_FILE}"
          echo "##vso[task.setvariable variable=DOCKER_FILE]${DOCKER_FILE}"
          echo "##vso[task.setvariable variable=DOCKER_IMAGE_NAME]${GOV_APP_ACRONYM}${APP_NAME}"
          echo "##vso[task.setvariable variable=DOCKER_IMAGE_TAG]${APP_VERSION}"
          echo "##[endgroup]"

    # ==================================================================
    # [Compliance] Verifica se o repositório está em conformidade com as políticas de configuração
    # ==================================================================
    - task: VivoDevOpsConfigCompliance@1
      displayName: 'Check DevOps Config Compliance'
      inputs:
        workDir: $(DEFAULT_WORKDIR_ARTIFACTS)/$(ARTIFACT_NAME)
        policySets: |
          image-definition-files

    - task: Docker@2
      displayName: Docker Build
      condition: succeeded()
      inputs:
        containerRegistry: $(DOCKER_SERVICE_CONNECTION)
        command: build
        repository: $(DOCKER_IMAGE_NAME)
        Dockerfile: $(DOCKER_FILE)
        buildContext: '$(DEFAULT_WORKDIR_ARTIFACTS)/$(ARTIFACT_NAME)/'
        arguments: --no-cache --build-arg APPLICATION_NAME=$(APP_NAME) --build-arg APPLICATION_PATH=target --build-arg APP_VERSION=$(APP_VERSION) --build-arg HTTP_PROXY="$(PROXY_AGENT_HTTP)" --build-arg HTTPS_PROXY="$(PROXY_AGENT_HTTPS)" --build-arg NO_PROXY="$(PROXY_AGENT_NO_PROXY)"
        tags: >
          $(DOCKER_IMAGE_TAG)
          
    - task: Docker@2
      displayName: Docker Push
      name: dockerPushImage
      condition: succeeded()
      inputs:
        containerRegistry: $(DOCKER_SERVICE_CONNECTION)
        command: push
        repository: $(DOCKER_IMAGE_NAME)
        addPipelineData: true
        addBaseImageData: true
        tags: >
          $(DOCKER_IMAGE_TAG)

    - task: CmdLine@2
      displayName: Export Image Digest
      name: docker_digest
      env:
        DOCKER_OUTPUT: $(dockerPushImage.DockerOutput)
      inputs:
        script: |
          echo "##[group] ${DOCKER_OUTPUT}"
          cat ${DOCKER_OUTPUT}
          echo "##[endgroup]"

          DOCKER_DIGEST="$(cat ${DOCKER_OUTPUT} | grep "digest" | awk -F ' ' '{print $3}')"
          echo "##[debug] DOCKER_DIGEST..........: ${DOCKER_DIGEST}"
          echo "##vso[task.setvariable variable=DOCKER_DIGEST;isOutput=true]${DOCKER_DIGEST}"

    - task: CmdLine@2
      displayName: "Generate docker.json metadata"
      env:
        DOCKER_REGISTRY: $(DOCKER_DEFAULT_REGISTRY)
        DOCKER_IMAGE_NAME: $(DOCKER_IMAGE_NAME)
        DOCKER_IMAGE_TAG: $(DOCKER_IMAGE_TAG)
        DOCKER_APP_NAME: $(APP_NAME)
        DOCKER_APP_VERSION: $(APP_VERSION)
        K8S_NAMESPACE: $(K8S_NAMESPACE)
      inputs:
        script: |
          cat <<EOF > docker.json
          {
            "DOCKER_REGISTRY": "${DOCKER_REGISTRY}",
            "DOCKER_IMAGE_NAME": "${DOCKER_IMAGE_NAME}",
            "DOCKER_IMAGE_TAG": "${DOCKER_IMAGE_TAG}",
            "DOCKER_APP": "${DOCKER_APP_NAME}",
            "DOCKER_APP_VERSION": "$(APP_VERSION)",
            "DOCKER_IMAGE_NAME_FULL": "${DOCKER_REGISTRY}/${DOCKER_IMAGE_NAME}",
            "K8S_NAMESPACE": "${K8S_NAMESPACE}",
            "GIT_TAG": "${DOCKER_IMAGE_TAG}"
          }
          EOF

          echo "##[command] cat docker.json"
          cat docker.json

    - task: CopyFiles@2
      displayName: 'Copy to Staging Directory'
      inputs:
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
        OverWrite: true
        CleanTargetFolder: true
        Contents: |
          docker.json

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact Docker'
      inputs:
        ArtifactName: docker
        StoreAsTar: false
