steps:
- task: AzureKeyVault@2  
  displayName: '[Docker ACR] Getting AKV credentials'
  timeoutInMinutes: 1
  retryCountOnTaskFailure: 5  
  inputs:    
    azureSubscription: DevOpsSharedResources    
    KeyVaultName: $(AKV_DEVOPS_NAME)
    SecretsFilter: 'DOCKER-REGISTRY-ACR-USERNAME, DOCKER-REGISTRY-ACR-PASSWORD'
  condition: and(
              eq(variables['isACRRegistry'], true),
              eq(variables['DOCKER-REGISTRY-USERNAME'], ''),
              eq(variables['DOCKER-REGISTRY-PASSWORD'], '')
            )

- task: AzureKeyVault@2  
  displayName: '[Docker Nexus] Getting AKV credentials'
  timeoutInMinutes: 1
  retryCountOnTaskFailure: 5  
  inputs:    
    azureSubscription: DevOpsSharedResources    
    KeyVaultName: $(AKV_DEVOPS_NAME)
    SecretsFilter: 'DOCKER-REGISTRY-USERNAME, DOCKER-REGISTRY-PASSWORD'
  condition: and(
              eq(variables['isNexusRegistry'], true),
              eq(variables['DOCKER-REGISTRY-USERNAME'], ''),
              eq(variables['DOCKER-REGISTRY-PASSWORD'], '')
            )

- bash: |
    echo "##[debug] Setting Docker Registry credentials with ACR credentials. "
    echo "##vso[task.setvariable variable=DOCKER-REGISTRY-USERNAME]${DOCKER_REGISTRY_ACR_USERNAME}"
    echo "##vso[task.setvariable variable=DOCKER-REGISTRY-PASSWORD]${DOCKER_REGISTRY_ACR_PASSWORD}"
    
  displayName: "Setting Docker Credentials with ACR credentials"
  env:
    isACRRegistry: $(isACRRegistry)
    DOCKER_REGISTRY_ACR_USERNAME: $(DOCKER-REGISTRY-ACR-USERNAME)
    DOCKER_REGISTRY_ACR_PASSWORD: $(DOCKER-REGISTRY-ACR-PASSWORD)
  condition: and(
              eq(variables['isACRRegistry'], true),
              eq(variables['DOCKER-REGISTRY-USERNAME'], ''),
              eq(variables['DOCKER-REGISTRY-PASSWORD'], '')
            )