name: "[${{ parameters.environment }}] ${{ parameters.action }} - $(Date:yyyyMMdd).$(Rev:r)"

parameters:
  - name: action
    displayName: Action
    type: string
    default: "-"
    values:
      - "-"
      - "START"
      - "STOP"
  - name: environment
    displayName: Environment
    type: string
    default: "-"
    values:
      - "-"
      - poc
      # - dev
      # - dev02
      # - dev03
      - qa01
      # - qa02
      # - bugfix01
      # - tpm
      # - preprod
      # - prodlike
      # - prod
  - name: numberAffectedNodes
    displayName: Number of Affected Nodes (ALL for all nodes, or specify a number)
    type: string
    default: "ALL"

trigger: none

resources:
  repositories:
    - repository: CodePlayPipelines
      name: DevOps/Vivo.CodePlay.Pipelines
      type: git
      ref: refs/heads/feature/brm/melhorias_102025 # refs/tags/brm/latest
      endpoint: CodePlay

extends:
  template: tech_products/brm-fenix/provisioners/entrypoint.yml@CodePlayPipelines
  parameters:
    config:
      modelName: iac
    iacParameters:
      action: ${{ parameters.action }}
      environment: ${{ parameters.environment }}
      numberAffectedNodes: ${{ parameters.numberAffectedNodes }}
