parameters:
- name: isGitFlow
  type: boolean
  default: false
- name: gateCondition
  type: object
  default: {}
#- name: fortifyExclusionRepository
- name: fortifyAttributesFileName
  default: "fortify-attributes"
- name: skipSecurityGate
  default: false
  type: boolean
- name: azureSubscription
  default: "$(APP_CONFIGURATION_AZURE_SUBSCRIPTION)"
- name: appConfigurationEndpoint
  default: "$(APP_CONFIGURATIN_ENDPOINT)"
- name: appVersion
  type: string
  default: ""
- name: useconviso
  default: "$(USE_CONVISO)"
- name: vivoFlow
  type: string
  default: "none"
#- name: convisoCompany
#  default: 430

stages:
- stage: security
  displayName: "Security Stage"
  dependsOn: 
  - build_test
  condition: succeeded('build_test')
  pool: GeneralPurposeLinuxAgentsCI
  jobs:
  - job: app_config_keys
    displayName: "AppSec Config Keys"
    steps:
      - template: /security/get_appconfig_keys.yml
        parameters:
          appConfigurationEndpoint: ${{ parameters.appConfigurationEndpoint }}

  - job: sca_scan
    displayName: "SCA SCAN"
    dependsOn: app_config_keys
    variables: 
      USE_DEPENDENCY_TRACK: $[ dependencies.app_config_keys.outputs['evaluate_flags.USE_DEPENDENCY_TRACK'] ]
      USE_CONVISO: $[ dependencies.app_config_keys.outputs['evaluate_flags.USE_CONVISO'] ]
      SKIP_SECURITY_GATE_SCA: $[ dependencies.app_config_keys.outputs['evaluate_flags.SKIP_SECURITY_GATE_SCA'] ]
      USE_DT_DOCKER: $[ dependencies.app_config_keys.outputs['evaluate_flags.USE_DT_DOCKER'] ]
    condition: and(succeeded(), eq(variables.flowIsTagging, false))
    steps:
      - template: /security/run_sca_scan.yml
        parameters: 
          skipSecurityGate: ${{ variables['SKIP_SECURITY_GATE_SCA'] }}
          vivoFlow: "master"

  - job: fortify_scan
    displayName: "Fortify SAST"
    dependsOn: app_config_keys
    condition: and(succeeded(), eq(variables.flowIsTagging, false))
    steps:
      - template: /security/run_fortify_scan.yml
        parameters:
          fortifyExclusionRepository: FortifyExclusion