parameters:
- name: 'envs'
  type: object
  default: {}
variables:
- name: PROJECT_NAME
  value: ${{ variables['Build.Repository.Name'] }}
- name: VERSION_FILE_PATH
  value: ${{ coalesce(parameters.envs.VERSION_FILE_PATH, './VERSION') }}
- name: BIN_FILE
  value: './dist/execute_file'
- name: PATH_KEYTAB
  value: ${{ coalesce(parameters.envs.PATH_KEYTAB, '/home/AURA_BRAIN/.jenkins/aura_brain.keytab') }}

# SSH VARS
- name: SSH_SERVER
  value: $(DEV_SSH_SERVER)
- name: SSH_PATH
  value: $(DEV_SSH_PATH)
- name: SSH_CRED_FILE_B64_CONTENT
  value: $(DEV_DEPLOY_SBT_DATA_SSH_CRED_FILE_B64_CONTENT)
- name: SSH_USER
  value: ${{ coalesce(parameters.envs.PROD_SSH_USER, 'aura_brain') }}

# KEYTAB
- name: KEYTAB_USER
  value: ${{ variables['SSH_USER'] }}@REDECORP.BR

# NEXUS VARIABLES
- name: NEXUS_VERSION
  value: ${{ coalesce(parameters.envs.NEXUS_VERSION, 'nexus3') }}
- name: NEXUS_PROTOCOL
  value: ${{ coalesce(parameters.envs.NEXUS_PROTOCOL, 'https') }}
- name: NEXUS_URL
  value: ${{ coalesce(parameters.envs.NEXUS_URL, 'nexus.telefonicabigdata.com') }}
- name: NEXUS_GROUP_ID
  value: ${{ coalesce(parameters.envs.NEXUS_GROUP_ID, 'br.com.vivo.advanced-analytics.models') }}
- name: NEXUS_GROUP_NAME
  value: ${{ parameters.envs.NEXUS_GROUP_NAME }}
- name: NEXUS_CREDENTIALS_ID
  value: ${{ coalesce(parameters.envs.NEXUS_CREDENTIALS_ID, 'NEXUS_CRED') }}
- name: NEXUS_SUB_ARTIFACT_ID
  value: ${{ variables['Build.Repository.Name'] }}
- name: NEXUS_CLASSIFIER
  value: ${{ coalesce(parameters.envs.NEXUS_CLASSIFIER, '') }}
