parameters:
- name: envConfig
  type: string
  
steps:
- checkout: CodePlay
  path: 'codeplay'

- template: /tech_products/mule-fenix/steps/extract_env_config.yml@CodePlay
  parameters:
    envConfigName: ${{ parameters.envConfig }}
    name: env_config
    workingDirectory: '$(Pipeline.Workspace)/codeplay'

- task: DownloadPipelineArtifact@2
  displayName: 'Getting previous stage artifact'
  inputs:
    buildType: current
    artifactName: app
    targetPath: '$(Build.SourcesDirectory)'

- task: DownloadSecureFile@1
  displayName: 'Getting settings file'
  name: muleSettings
  inputs:
    secureFile: $(MULE_SETTINGS_FILE)

- template: /tech_products/mule-fenix/steps/properties/extract_properties.yml
  parameters:
    file: src/main/resources/properties/$(PROPERTIES_FILE_NAME)
    propertiesField: cloudhub
    outputVariable: CLOUD_HUB_PROPS
    workingDirectory: '$(Build.SourcesDirectory)'

- task: Maven@4
  displayName: 'Executing maven deploy on CloudHub'
  inputs:
    mavenPOMFile: '$(Build.SourcesDirectory)/pom.xml'
    goals: 'mule:deploy'
    options: '-s $(muleSettings.secureFilePath)
      -DmuleDeploy
      -Dmule.artifact=$(Build.SourcesDirectory)/target/$(ARTIFACT_ID)-$(NEW_VERSION)-mule-application.jar
      -DskipTests
      -DconnectedAppClientId=$(MULE_APP_CLIENT_ID)
      -DconnectedAppClientSecret=$(MULE_APP_CLIENT_SECRET)
      -Denv.short=$(env_config.ANYPOINT_ENVIRONMENT_IN_APPLICATION_NAME)
      -DbusinessGroupId=$(MULE_BUSINESS_GROUP_ID)
      -Denv=$(env_config.ANYPOINT_ENVIRONMENT)
      -Dsecurity.key=$(MULE_SECURITY_KEY)
      -Danypoint.platform.client_id=$(MULE_ANYPOINT_CLIENT_ID)
      -Danypoint.platform.client_secret=$(MULE_ANYPOINT_CLIENT_SECRET)
      $(CLOUD_HUB_PROPS)'
  env:
    PUB_CREDENTIAL_USR: $(NEXUS-DEFAULT-USR)
    PUB_CREDENTIAL_PSW: $(NEXUS-DEFAULT-PSW)