parameters:
- name: run_component_test
  type: boolean
- name: qa_environment
  type: string

- name: ACRAsDefaultDockerRegistry
  type: boolean
  default: False


variables:
- template: /provisioners/app/trunkbased/nodejs/bff_client_default/variables/load.yml

resources:
  repositories:
    - repository: FortifyExclusion
      name: DevOps/Vivo.Fortify.Exclusions
      type: git
      ref: refs/heads/master
      endpoint: CorePipelines

stages: 
# CI / CD Flow
  ## INIT
  - template: /provisioners/app/trunkbased/nodejs/bff_client_default/stages/init.yml

  ## BUILD & TEST
  - template: /provisioners/app/trunkbased/nodejs/bff_client_default/stages/build_test_bff_and_client.yml
  
  ## COMPONENT TEST
  - template: /provisioners/app/trunkbased/nodejs/bff_client_default/stages/component_test.yml
    parameters:
      run_component_test: "${{parameters.run_component_test}}"
  
  ## GATES 
  - template: /provisioners/app/trunkbased/nodejs/bff_client_default/stages/gates.yml

  ## SECURITY
  - template: /provisioners/app/trunkbased/nodejs/bff_client_default/stages/security.yml
    parameters:
      fortifyExclusionRepository: FortifyExclusion

  ## PACKAGE
  - template: /provisioners/app/trunkbased/nodejs/bff_client_default/stages/package.yml
    parameters:
      run_component_test: "${{parameters.run_component_test}}"

  ## VALIDATIONS
  - template: /provisioners/app/trunkbased/nodejs/bff_client_default/stages/validation.yml