stages:
- stage: ci_environment      
  displayName: "CI - Environment"
  jobs:
  - job: environment
    displayName: "Setting up environment credentials"
    pool:
      name: TestRunnerAgentsWindows
    steps:
    - checkout: self
      displayName: Checkout Code
      name: checkout_code
      submodules: true
      persistCredentials: true
      clean: true

    - checkout: CodePlay
      displayName: Checkout CodePlay
      name: checkout_codeplay
      persistCredentials: true
      clean: true

    #- checkout: Metrics
    #  displayName: Checkout Metrics Framework
    #  name: checkout_metrics_framework
    #  persistCredentials: true
    #  clean: true
    #  condition: ${{ eq(parameters.framework, 'JUnit') }}

    - task: PowerShell@2
      displayName: "DEBUG"
      condition: always()
      inputs:
        targetType: 'inline'
        script: |
          Write-Host "dir Build.SourcesDirectory:" -backgroundcolor green -foregroundcolor red
          dir $(Build.SourcesDirectory)
          Write-Host "dir Agent.BuildDirectory:" -backgroundcolor green -foregroundcolor red
          dir $(Agent.BuildDirectory)

    ## Download NEXUS Credentials
    - task: AzureKeyVault@2
      displayName: 'Getting AKV Credentials'
      timeoutInMinutes: 3
      retryCountOnTaskFailure: 5
      inputs:
        azureSubscription: DevOpsSharedResources
        KeyVaultName: $(AKV_DEVOPS_NAME)
        SecretsFilter: 'NEXUS-DEPS-USR, NEXUS-DEPS-PSW, NEXUS-DEFAULT-USR, NEXUS-DEFAULT-PSW'

    ## -> Set NEXUS credentials to variables. This allows it to used in other stages, jobs or tasks.
    ## -> NEXUS_DEPS_USR and NEXUS_DEPS_PSW, use these to download dependencies. 
    ## -> NEXUS_DEFAULT_USR and NEXUS_DEFAULT_PSW, use these to upload artifacts. 

    - task: PowerShell@2
      displayName: 'Set Credentials Variables'
      name: credentials
      condition: and(
        succeeded(),
        ne(variables['NEXUS-DEPS-USR'], ''), ne(variables['NEXUS-DEPS-PSW'], ''))
      continueOnError: false
      inputs:
        targetType: 'inline'
        script: |          
          Write-Host  "##[group] Variables to DOWNLOAD dependencies from NEXUS"
          Write-Host  "##[debug] NEXUS-DEPS-USR: $(NEXUS-DEPS-USR). Use as >> NEXUS_DEPS_USR."
          Write-Host  "##vso[task.setvariable variable=NEXUS_DEPS_USR;isOutput=true;isSecret=true]$(NEXUS-DEPS-USR)"
          Write-Host  "##[debug] NEXUS-DEPS-PSW: $(NEXUS-DEPS-PSW). Use as >> NEXUS_DEPS_PSW"          
          Write-Host  "##vso[task.setvariable variable=NEXUS_DEPS_PSW;isOutput=true;isSecret=true]$(NEXUS-DEPS-PSW)"
          Write-Host  "##[endgroup]"
        KeyVaultName: kv-azdevops-shared
        SecretsFilter: 'NEXUS-DEPS-USR, NEXUS-DEPS-PSW'

    - task: PowerShell@2
      displayName: 'Debug NEXUS Variables'
      inputs:
        targetType: 'inline'
        script: |
          Write-Host "NEXUS-DEPS-USR: $env:NEXUS-DEPS-USR"
          Write-Host "NEXUS-DEPS-PSW: $env:NEXUS-DEPS-PSW"
          Write-Host "NEXUS_DEPS_USR: $env:NEXUS_DEPS_USR"
          Write-Host "NEXUS_DEPS_PSW: $env:NEXUS_DEPS_PSW"
          Write-Host "NEXUS-DEPS-USR: $env:NEXUS_DEPS_USR"
          Write-Host "NEXUS-DEPS-PSW: $env:NEXUS_DEPS_PSW"
  
    - task: PowerShell@2
      displayName: "DEBUG"
      condition: always()
      inputs:
        targetType: 'inline'
        script: |     
          Write-Host "dir Build.SourcesDirectory:"
          dir $(Build.SourcesDirectory)
          Write-Host "dir Agent.BuildDirectory:"
          dir $(Agent.BuildDirectory)

    - publish: $(Build.SourcesDirectory)
      artifact: checkout_env
      displayName: 'Publish Checkout Environment'
      condition: succeeded()
      continueOnError: false