parameters:
- name: source_branch
  type: string
- name: target_branch
  type: string

stages:
- stage: merge_branches
  displayName: "Merge branches in Repo"
  pool:
    name: $(PRIVATE_AGENT_DEFAULT)
  jobs:
  - job:
    workspace:
      clean: resources
    displayName: "Merging"
    steps:
      - checkout: self
        fetchDepth: 1
        persistCredentials: true
      - bash: |
          cd $(Build.SourcesDirectory)/$(Build.Repository.Name)

          if [[ ${{ parameters.source_branch }} == ${{ parameters.target_branch }} ]]; then
            echo "##[command]Escolha branches diferentes como origem e destino"
            exit 1
          fi

          git config user.email "azure-pipelines@telefonicati.onmicrosoft.com"
          git config user.name "Azure Pipelines"

          echo "##[command]Atualizando todas as branches no contexto"
          git fetch --all

          echo "##[command]Entrando na branch de destino"
          git checkout ${{ parameters.target_branch }}

          set -e

          echo "##[command]Mergeando com a branch de origem"
          git merge origin/${{ parameters.source_branch }}

          echo "##[command]Commit merge"
          git commit -a -m "[ci skip] atualizando commits da branch ${{ parameters.source_branch }}"

          echo "##[command]Validando alterações"
          git log -1

          echo "##[command]Forçando push na branch"
          git push --force origin ${{ parameters.target_branch }}
        displayName: "Merging branches..."
