parameters:
- name: adobeRemoteUrl
  type: string
  default: $(adobe_remote_url)
- name: adobeBranch
  type: string
  default: ''
- name: gitPushParameter
  type: string
  default: ''

variables:
- template: /tech_products/ecmc/adbb-aem/provisioners/aem/b2b/default/variables/load.yml

resources:
  repositories:
    - repository: FortifyExclusion
      name: DevOps/Vivo.Fortify.Exclusions
      type: git
      ref: refs/heads/master
      endpoint: CorePipelines
    - repository: CorePipelines
      name: DevOps/Vivo.Core.Pipelines
      type: git
      ref: refs/tags/v1
      endpoint: CorePipelines

stages:
- ${{ if ne(variables.skip_quality_gates, true) }}:
  - template: /tech_products/ecmc/adbb-aem/provisioners/aem/b2b/default/stages/maven_test.yml

  - template: /tech_products/ecmc/adbb-aem/provisioners/aem/b2b/default/stages/node_test.yml

  - template: /tech_products/ecmc/adbb-aem/provisioners/aem/b2b/default/stages/gates_java.yml

  - template: /tech_products/ecmc/adbb-aem/provisioners/aem/b2b/default/stages/gates_node.yml

- template: /tech_products/ecmc/adbb-aem/provisioners/aem/b2b/default/stages/security.yml
  parameters:
    fortifyExclusionRepository: FortifyExclusion
    ${{ if eq(variables.skip_quality_gates, true) }}:
      dependsOn: []

- template: /tech_products/ecmc/adbb-aem/provisioners/aem/b2b/default/stages/sync.yml
  parameters:
    gitPushParameter: "${{parameters.gitPushParameter}}"
    adobeRemoteUrl: "${{parameters.adobeRemoteUrl}}"
    adobeBranch: "${{parameters.adobeBranch}}"
    ${{ if eq(variables.skip_quality_gates, true) }}:
      dependsOn: [security]