parameters:
- name: environment
- name: helmReleaseNamePrefix
- name: dev_namespace_to_deploy
  default: ''
- name: useExternalEnv
  default: false
- name: azureServiceConnectionEnabled
- name: kubernetesServiceConnectionEnabled

steps:
- template: /tasks/artifacts/download_docker.yml

- template: /tasks/helm/registry_login.yml

- template: /tasks/helm/init.yml
  parameters:
    environment: ${{ parameters.environment }}

- template: /tasks/helm/utils.yml
  parameters:
    environment: ${{ parameters.environment }}
    dev_namespace_to_deploy: ${{ parameters.dev_namespace_to_deploy }}

- ${{ if eq(parameters.useExternalEnv, true) }}:
  - template: /tasks/git/checkout_env_repo.yml

- template: /tasks/helm/replace.yml
  parameters:
    environment: ${{ parameters.environment }}

- template: /tasks/helm/upgrade_with_service_connection.yml
  parameters:
    environment: ${{ parameters.environment }}
    helmReleaseNamePrefix: ${{ parameters.helmReleaseNamePrefix }}
    azureServiceConnectionEnabled: ${{ parameters.azureServiceConnectionEnabled }}
    kubernetesServiceConnectionEnabled: ${{ parameters.kubernetesServiceConnectionEnabled }}